### ISSUE TITLE
Laravel 5.4.*

### ISSUE THREAD

**Issue by gilbert1995** [Webklex/laravel-imap#1]
Hello this plugin work with with Laravel 5.4?

I got this message:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - webklex/laravel-imap 1.0.0 requires laravel/framework ~5.2.0 -> satisfiable by laravel/framework[5.2.x-dev].
    - webklex/laravel-imap 1.0.1 requires laravel/framework ~5.2.0 -> satisfiable by laravel/framework[5.2.x-dev].
    - webklex/laravel-imap 1.0.x-dev requires laravel/framework ~5.2.0 -> satisfiable by laravel/framework[5.2.x-dev].
    - Conclusion: don't install laravel/framework 5.2.x-dev
    - Installation request for webklex/laravel-imap ^1.0 -> satisfiable by webklex/laravel-imap[1.0.0, 1.0.1, 1.0.x-dev].

**Comment by Webklex** [comment]
Hi Gilbert1995,
I just updated the requirements and published a new version. Laravel 5.4x is now supported.
