### ISSUE TITLE
Email bodies not fetching

### ISSUE THREAD

**Issue by lauspadafora** [Webklex/laravel-imap#10]
Everything was working smoothly before the **optional config parameter** was added. Now email bodies won't fetch and all I get is an empty array. Is there anything special that needs to be done with this new changes?

**Comment by Webklex** [comment]
Hi,
please take a look at this issue [https://github.com/Webklex/laravel-imap/issues/8](https://github.com/Webklex/laravel-imap/issues/8) and let me know if adding the config helped. I'll have a closer look at it tomorrow.

**Comment by Webklex** [comment]
Hi lauspadafora,
please update to the latest version: https://github.com/Webklex/laravel-imap/releases/tag/1.0.2.7

**Comment by lauspadafora** [comment]
It's working now @Webklex! Thanks!
