### ISSUE TITLE
With outlook mail servers, the charset shouldn't be send with the imap_search

### ISSUE THREAD

**Issue by tayfunkayahan** [Webklex/laravel-imap#100]
Hi Webklex,

Firstly, thanks for the great package!

I encountered some problems today with the package, which is actually an edge case.. 

With  every mayor mail server besides Microsofts (outlook) imap servers, the charset shouldn't be send with the imap search. For some reason, if we send the default UTF-8 charset with the `imap_search`, every search criteria besides `ALL` doesn't work.. If I leave it blank, every search criteria works :)

For myself I added a check if it is a microsoft account (@outlook.com / @hotmail.com), than the charset shouldn't be given to the `imap_search`, otherwise I am using the `UTF-8` charset. If I didn't do this, I couldn't use search criteria like `UNSEEN`, `SEEN`, etc :) 

For myself I did something like this;

Define somewhere logical (for me I implemented in the Folder class) an `CONST` with common microsoft domains;
```
CONST MICROSOFT_DOMAINS = [
        'outlook.com',
        'hotmail.com'
];

```

In the `searchMessages` function;

I tried it with setting the `$charset = NIL`, but it really shouldn't be passed when doing an `imap_search`.

```
.........
$query = trim($query);

if(in_array(substr(strrchr($this->getClient()->username, "@"), 1), self::MICROSOFT_DOMAINS)) {
    $availableMessages = imap_search($this->getClient()->getConnection(), $query, SE_UID);
} else {
    $availableMessages = imap_search($this->getClient()->getConnection(), $query, SE_UID, $charset);
}

.........
```

I'd like to hear from you, if you approve this approach I'll make a PR for you, otherwise I'd like to hear what your approach would be! 👍  :-)

**Comment by Webklex** [comment]
Hi @tayfunkayahan ,
the default `$charset` value is actually `null` according to the official php [imap_search()](http://php.net/manual/en/function.imap-search.php) documentation.

So setting` $charset` to `NULL` should perfectly work..
```php
Folder::searchMessages(array $where, $fetch_options = null, $fetch_body = true, NULL);
```
I wouldn't like the idea to perform an unnecessary (unless I' using a microsoft domain) array lookup every time I call the search method. I think it's fair to implement the logic outside if necessary :)

Instead I would like to add it to the known issue section and link it to this issue as well as the future wiki.

If I'm wrong and the majority is actually using microsoft related email addresses the `$charset` parameter could also be set to `null` in a breaking version change (2.*). But I honestly doupt that this is the case :)

Best regards

**Comment by Webklex** [comment]
@tayfunkayahan please update to the latest version. You can now set the charset to `null`. If however the charset is `null` it won't be set anymore:

```php
if($this->getCharset() === null){
    $available_messages = imap_search($this->getClient()->getConnection(), $this->getRawQuery(), SE_UID);
}else{
    $available_messages = imap_search($this->getClient()->getConnection(), $this->getRawQuery(), SE_UID, $this->getCharset());
}
```

**Comment by tayfunkayahan** [comment]
@Webklex thnx for the update! should work perfectly now!

**Comment by freescout-helpdesk** [comment]
We are using the following code:
```
$folder = $client->getFolder('INBOX');
$folder->query()->unseen()->leaveUnread()->get();
```
The following error uccurs when trying to fetch messages from **outlook.office365.com** server:
`[BADCHARSET (US-ASCII)] The specified charset is not supported.`

It looks like we need somehow to set charset to `null` when executing the query. Is it possible?

**Comment by freescout-helpdesk** [comment]
Here is the solution: https://github.com/freescout-helpdesk/freescout/issues/176#issuecomment-464188851

**Comment by Webklex** [comment]
Hi @freescout-helpdesk ,
yes it is posiible:
```php
/** @var \Webklex\IMAP\Folder $folder */
/** @var \Webklex\IMAP\Message $message */
$message = $folder->query(null)->get()->first();
```

`Folder::query()` `Folder::search()` `Folder::messages()` can be parsed a desired charset. UTF-8 ist the default. However by setting it to null, the charset wont be set on imap_search() and therefor prevent this error.
