### ISSUE TITLE
Method Client::setFetchOption does not exist.

### ISSUE THREAD

**Issue by gbaumeister** [Webklex/laravel-imap#106]
The docs state a method  `Client::setFetchOption`. This method does not exist and results in a: `Call to undefined method Webklex\IMAP\Client::setFetchOption()`  error.

**Comment by tayfunkayahan** [comment]
the setFetchOption exists in the ```Message``` class. You need to ```setFetchOption``` on a message and not on the client. So you need to each through every message and set the fetch option :) @gbaumeister

**Comment by Webklex** [comment]
Hi @gbaumeister ,
thanks for pointing it out. I'll update the readme asap :)

@tayfunkayahan  you are right - just wanting to mention that depending on your actual setup you could also define the fetch options inside the `config/imap.php`.
