### ISSUE TITLE
Page runs slowly

### ISSUE THREAD

**Issue by mn6893** [Webklex/laravel-imap#108]
When  i try run the sample code the site slow down and taking nearly 1 min to load the data. find the below sample code. please help me to solve.
```
 foreach($aMessage as $oMessage){
		    
		       if($oMessage->hasAttachments()){
		        echo $oMessage->subject.'<br />';
		        //echo 'Attachments: '.$oMessage->getAttachments()->count().'<br />';
		        print_r($oMessage->getAttachments()->count());
		        exit;
		        echo $oMessage->getHTMLBody(true);
		    }
```

**Comment by Webklex** [comment]
Hi @mn6893 ,
so what have you tried? :)

**Comment by mn6893** [comment]
I'm using localhost. I have over 100+ emails in inbox and when tried to fetch the emails, the page nearly taking 1 min to load. I tried the above code sample code.

Regardsm

**Comment by Webklex** [comment]
Hi @mn6893 ,
please take another look at the [readme.md](https://github.com/Webklex/laravel-imap/blob/master/README.md) below

> Fetch messages without body fetching (decrease load):

or the section above [this](https://github.com/Webklex/laravel-imap#documentation).

Hope this helps you getting started :)

Best regards

P.s.: You might want to take a look at the [available config](https://github.com/Webklex/laravel-imap#configuration) as well ;)

**Comment by mn6893** [comment]
In my project i want to fetch only the excel attachment, where the software read the content in excel directly and save it into the database. Is that possible to do with this webklex library?

Best regards,
MN

**Comment by Webklex** [comment]
No this is not possible, since there is no way to search for attachments..
However you could create a cronjob and fetch all mailes every x minutes / hours and check for any excel attachments :)

Best regards
