### ISSUE TITLE
getMessages Error

### ISSUE THREAD

**Issue by MarouaneZizah** [Webklex/laravel-imap#109]
Hi Webklex,

First I would like to thank you for this great package, I found it very helpful!

But today I encountered an issue, when i run :  

```
$compte = Client::account('mail_box');

$compte->connect();

$inbox_folder = $compte->getFolder('INBOX');

$messages = $inbox_folder->getMessages('ALL', null, false, true);

$messages = $inbox_folder->getMessages();
```
everything works fine but once i turn the $fetch_body option :
```
$messages = $inbox_folder->getMessages('ALL', null, true, true);
```
I get this error : 
```
iconv() wrong charset, conversion from ‘ISO-8859-1 CONTENT-TRANSFER-ENCODING’ to ‘UTF-8//IGNORE’ is not allowed
```
![capture d ecran 2018-06-07 a 12 21 04](https://user-images.githubusercontent.com/16108136/41101335-6921f618-6a53-11e8-8608-67c2654024f8.png)

Using : 
```
Laravel : 5.1,
Php : 7.2
Webklex/laravel-imap : 1.1
```

Any help would be appreciated.

**Comment by MarouaneZizah** [comment]
After little research, i found that the imap_fetchstructure() function that exists inside parseBody() method returns the wrong encoding.

```
public function parseBody() 
{
        $structure = imap_fetchstructure($this->client->getConnection(), $this->uid, FT_UID);

        $this->fetchStructure($structure);

        return $this;
}
```

<img width="661" alt="screen shot 2018-06-07 at 3 47 39 pm" src="https://user-images.githubusercontent.com/16108136/41110959-349f9cd0-6a6a-11e8-9fde-e469e9f62825.png">

So I added this quick fix : 
```
public function parseBody() 
{
        $structure = imap_fetchstructure($this->client->getConnection(), $this->uid, FT_UID);

	$parts = $structure->parts;

	foreach ($parts as $part)
	{
		foreach ($part->parameters as $parameter)
		{
			if($parameter->attribute == "charset")
			{
				$encoding = $parameter->value;
				$parameter->value = preg_replace('/Content-Transfer-Encoding/', '', $encoding);
			}
		}
	}

	dd($structure);

        $this->fetchStructure($structure);

        return $this;
 }
```
Now it returns the right encoding

<img width="653" alt="screen shot 2018-06-07 at 3 49 35 pm" src="https://user-images.githubusercontent.com/16108136/41111057-769deaa6-6a6a-11e8-8366-9114907e272c.png">

**Comment by Webklex** [comment]
Hi @MarouaneZizah ,
thanks for your bug report and additional research :)
I'll provide a fix this weekend and keep you updated.

Best regards
