### ISSUE TITLE
getAttachments returns nothing

### ISSUE THREAD

**Issue by kaveczkib** [Webklex/laravel-imap#11]
Hi,

I noticed a bug in the fetchAttachments method in Message class. 
The "filename" attribute sometimes is not lowercase, and you use '==' (case sensitive) comparison in these if statments (line 414, line 423).
You should use strcasecmp() which is a case-insensitive string comparison.

Example:
  if (!strcasecmp($parameter->attribute, "filename"))

**Comment by Webklex** [comment]
Hi kaveczklib,
thanks for your report. I'll take a closer look at it and release a new version asap.

Best regards,
Malte

**Comment by Webklex** [comment]
This bug is solved: please reffer to: [v1.0.2.8](https://github.com/Webklex/laravel-imap/releases/tag/1.0.2.8)
