### ISSUE TITLE
How to maintain two different session timing for mobile and web?

### ISSUE THREAD

**Issue by mn6893** [Webklex/laravel-imap#110]
I want to maintain two different  token session timing for mobile and web. I set in config/jwt.php in ttl => 60. This is take it as default but i want to set dynamically for mobile and web. Like for mobile token session time is 15 mins and for web is 20 mins like this i want to set session timing.

Best Regards,

**Comment by Webklex** [comment]
Hi @mn6893 ,
please repost your question on the jwt issue section or at stackoverflow. If I'm wrong and your question is somehow related to this package, please reopen this issue and add some more detail :)

Best regards
