### ISSUE TITLE
how to get fix limit mails on load( not load all mail at time) using pagination or limit and offset...?

### ISSUE THREAD

**Issue by karan-shah-21** [Webklex/laravel-imap#116]

**Comment by Webklex** [comment]
Hi @karan-shah-21 ,
please take a look at #96 .

Best regards

**Comment by karan-shah-21** [comment]
**(Please release this  pagination code on this github library because if we update composer then  this code remove from our vendor file because you are not add pagination code into this lib)**

**Comment by karan-shah-21** [comment]
@Webklex  #96  code is not working when there is no message available in particular folder it's given timeout error ...
