### ISSUE TITLE
imap_close() error

### ISSUE THREAD

**Issue by samfrjn11** [Webklex/laravel-imap#118]
Recently my script stopped working. It throws following error:
`imap_close() expects parameter 1 to be resource, integer given in /Users/samsmekens/GitHub/tempproject/vendor/webklex/laravel-imap/src/IMAP/Client.php:235
`

This error happened since PHP 7.2. Anyone an idea of why this is happening?
Did tests with PHP7 and PHP 7.1, both give the same issue

**Comment by Webklex** [comment]
Hi @samfrjn11 ,
thanks for your report. I thought checking for a boolean was enought - well guess it wasn't. I just created a patch, which will be rleased within the next release. :)

Best regards
