### ISSUE TITLE
Plain text attachments have a content type of other/plain of text/plain

### ISSUE THREAD

**Issue by PatrickSJ** [Webklex/laravel-imap#119]
If you attach a plain text file with a .txt extension to an email and then look at it's content_type value it will show up as "other/plain" instead of the common "text/plain"

In fact any attachment with a type of text is currently converted to "other" even though it is being detected as text.

**Comment by PatrickSJ** [comment]
Specifically the issue is the findType method on Webklex\IMAP\Attachment.  It doesn't check for cases of TYPE_TEXT nor TYPE_MULTIPART

**Comment by Webklex** [comment]
Hi @PatrickSJ ,
thanks for your report and hint. I'm currently a bit "over booked" but will look at is asap.

Best regards

**Comment by Webklex** [comment]
Just created a patch resolving this issue which will be released within the next release.

Best regards
