### ISSUE TITLE
Error while connecting to Exchange 2010 server

### ISSUE THREAD

**Issue by pieterschreuder** [Webklex/laravel-imap#12]
Making a connection throws this exception: "Kerberos error: No credentials cache file found (try running kinit) (...)"

This can be fixed by adding a sixth parameter to `imap_open()`, `array('DISABLE_AUTHENTICATOR' => 'GSSAPI')`

Source: https://github.com/tedious/Fetch/issues/15

**Comment by Webklex** [comment]
I just added the requested "option" to the [Client](https://github.com/Webklex/laravel-imap/blob/master/src/IMAP/Client.php) class. The option can be set inside the imap [config](https://github.com/Webklex/laravel-imap/blob/master/src/config/imap.php) file. I just can't test it - so please be so kind and give it a try. If it works let me know and I will release a new version asap :)
