### ISSUE TITLE
is there any method to count unread message from particular folder like inbox...?? (getUnseenMessages is not working )

### ISSUE THREAD

**Issue by karan-shah-21** [Webklex/laravel-imap#120]

**Comment by Webklex** [comment]
Hi @karan-shah-21 ,
please try a bit to figure it out before opening an issue ;)

But regarding your question, yes there is a way. 
There is an experimental function which allows you to fetch only one "folder".

```php
$oFolder = $oClient->getFolder('INBOX.name');
```

With `$oFoldet` you can call `getUnseenMessages()` to get all unseen messages of that given folder.

Please take an other look at the readme for even more tips and tricks :)

If however you can't get it working, please provide your actual code, the error message (or / and callstack) 
and tell a bit more about the issue it self. This makes it a lot easier for others to help you getting started.

Best regards

**Comment by karan-shah-21** [comment]
As per your suggestion i have again tried with this function but it still not work.
**Note :: I have added pagination code into my vendor folder according commit file to  issue at #96 .
(Please release pagination code on this github library because if we update composer then  this code remove from our vendor file because you are not add pagination code into this lib)** 
$oFolder = $oClient->getFolder('INBOX');
 $unreadcount = $oFolder->getUnseenMessages('Unseen',null,false,false);
