### ISSUE TITLE
installing laravel-imap on laravel 5.6 and PHP7.2

### ISSUE THREAD

**Issue by FabrizioReitano** [Webklex/laravel-imap#129]
**Cannot install laravel-imap on Lavarel 5.6**
Hi Webklex,
i'm trying to install this package in Laravel 5.6 (PHP 7.2), but i receive this message from composer:

`laravel/framework v5.0.9 requires ext-mcrypt * -> the requested PHP extension mcrypt is missing from your system.`

The mcrypt extension is [deprecated since PHP7.1](http://php.net/manual/en/migration71.deprecated.php)

The error is because of the requirements of this package:
`"require": {
        "php": ">=5.5.9",
        "laravel/framework": ">=5.0.0"
    }`

I solved cloning locally the project and modifing the require key like this:
`"require": {
        "php": ">=7.1.3",
        "laravel/framework": ">=5.6.0"
    }`

Is there an easier solution to install this package in PHP7 without requiring mcrypt? Are you planning a new PHP7 compliant release?

Thanks

**Comment by Webklex** [comment]
Hi @FabrizioReitano ,
thanks for your report. An alternative solution would be to install the missing php extension (mcrypt).
```sh
sudo apt-get install php7.1-mcrypt 
```
I woudn't like to restrict the package to laravel 5.6 since there are still a lot of older laravel versions online :)

Best regards
