### ISSUE TITLE
Undefined Index

### ISSUE THREAD

**Issue by emp-sean** [Webklex/laravel-imap#131]
Getting the following error when attempting to run.

> In Query.php line 189:
Undefined index: fetch_order

**To Reproduce**
Just run, I believe the bug was introduced in version **1.2.4**

**Additional context**
Managed to get around the error by adding the following to the _options_ array in config.php

`'fetch_order' => 'asc'` 

However, when you do this, the same error then appears again but this time with 

> In Query.php line 189:
Undefined index: message_key

Again, adding this to the options array resolves the issue, but it appears it is not pulling the default from the provided options array, so possibly an issue with the merge?

`'message_key' => 'id'` 

Had to pull the values from the _Query.php_ file as the default values are not listed in the documentation, so be good to have those also.

Hopefully this can get resolved, without the need for the work-arounds above.

EDIT:
Also noticed it does the same thing in the imap.php files for _FT_UID_ need to put it in a quote mark to get it working

**Comment by Webklex** [comment]
Hi @empsean ,
thanks for your report. I'll take a closer look at it tonight :)

Best regards
