### ISSUE TITLE
attachment property empty when using query() instead of messages()

### ISSUE THREAD

**Issue by azzagazz** [Webklex/laravel-imap#134]
Hi,

When i try to get messages from a folder like so:

````
$aMessage = $oFolder->messages()->all()->get();
foreach($aMessage as $oMessage){
    dd($oMessage);
}
````

the output will have the attachment property filled correctly.

when i try to get messages via:

````
$oMessage = $oFolder->getMessage($uid = 6, $fetch_attachment = true);
````

or via: 

````
$aMessage = $oFolder->query()->setFetchAttachment(true)->get();
````
the attachment property will be empty.

Maybe i am doing something wrong here but i cannot seem to get it to work.

Thanks!
Daniel

**Comment by Webklex** [comment]
Hi @azzagazz ,
take closer look at the `Folder::getMessage()` method; 
It accepts a fair amount of parameters:
`getMessage($uid, $msglist = null, $fetch_options = null, $fetch_body = false, $fetch_attachment = false, $fetch_flags = true)`. 

In your case the fetch option should probably be null or FT_UID. However if you want to fetch the attachment, please be aware that you have to fetch the body as well.

 ```php
$oMessage = $oFolder->getMessage($uid = 6, null, null, true, true);
```

Depending on your default config (inside [config/imap.php](https://github.com/Webklex/laravel-imap/blob/master/src/config/imap.php)) you might have to extend your call a little bit to something like:
```php
$aMessage = $oFolder->query()->setFetchBody(true)->setFetchAttachment(true)->get();
```
or reduce it to
```php
$aMessage = $oFolder->query()->get();
```

The Query class has also getter methods for any attribute. Check if they return true, true. 
```php
$query = $oFolder->query();
dd($query->getFetchBody(), $query->getFetchAttachment());
```

You could also check if there are any IMAP errors which might cause some hickup by calling:
```php
dd($oClient->getErrors());
```

Best regards

**Comment by azzagazz** [comment]
Hey @Webklex ,

thanks so much for the quick and thorough response.

> please be aware that you have to fetch the body as well

that was it :) after i added the body to the query it worked!

only problem i have now is that the filename on the attachement property is strangely encoded. prepended by `=?utf-8?Q?` and appended by `?=` is this normal for content extracted from emails, i am absolutely not familiar with email stuff ^^

thanks again for your help 👍 
daniel

**Comment by azzagazz** [comment]
You Sir, made my day! :)

simple `composer update` and voila: `  - Updating webklex/laravel-imap (1.2.6 => 1.2.7): Downloading (100%)   ` everything works like a charm :)

thank you!
daniel
