### ISSUE TITLE
I'm getting Call to undefined method `Webklex\IMAP\Folder::query()`

### ISSUE THREAD

**Issue by kaviyarasansadasivam** [Webklex/laravel-imap#135]
I'm getting Call to undefined method `Webklex\IMAP\Folder::query()` while retireiving message

**To Reproduce**
while retrieveing inbox

**Screenshots**
![untitled](https://user-images.githubusercontent.com/29705026/43956315-4ed3e06e-9cc1-11e8-8862-af1e8d41d988.png)

**Desktop / Server (please complete the following information):**
 - OS: homestead(linux)
- PHP: 7.2.5
 - Version:5.6(laravel)

**Additional context**
I'm getting Call to undefined method `Webklex\IMAP\Folder::query()` while retireiving message.Without uey it's working but takes long time to load,any suggestions for this.Please help me.Thanks in Advance.

**Comment by Webklex** [comment]
Hi @kaviyarasansadasivam ,
are you using the latest version?

Best regards

**Comment by kaviyarasansadasivam** [comment]
Sorry I'm updating latest version now only.It's working fine. I have another question retrieving inbox takes more time to load although i use paginate.Any suggestion please.

**Comment by Webklex** [comment]
Please take a look at https://github.com/Webklex/laravel-imap/blob/master/README.md#result-limiting. I think that's what you are looking for :)

Best regards
