### ISSUE TITLE
What is the unique ID for each mail

### ISSUE THREAD

**Issue by kaviyarasansadasivam** [Webklex/laravel-imap#136]
Is there any unique id for particular mail to retrieve that mail  body later. You said  UID is not unique and change.

If MessageId or MessageNo are unique, then how to retrieve the message with that id like uid $oFolder->getMessage($uid = 1)

Please help me, i'm struck here to handle this.

**Comment by Webklex** [comment]
Hi @kaviyarasansadasivam,
there is no real unique id available. But you could create a token based on the uid, date and folder or so. By doing that you could have enough information to search for a message :)

Best regards

**Comment by kaviyarasansadasivam** [comment]
How to create a token based on UID. I need to delete the specific mail.

**Comment by Webklex** [comment]
Hi @kaviyarasansadasivam ,
please provide some code example and further detail.

If you ment my last comment:
> a token based on the uid, date and folder or so

It could look like: 
```php
/** @var \Webklex\IMAP\Folder $folder **/
/** @var \Webklex\IMAP\Message $message **/
$token = $message->getUid().'/'.$folder->name.'/'.$message->getDate()->timestamp;
```
..and the reversed token:
```php
$parts = explode('/', $token);

/** @var \Webklex\IMAP\Folder $folder **/
$folder = $client->getFolder($parts[1]);
/** @var \Webklex\IMAP\Message $message **/
$message = $folder->getMessage($parts[0]);

/** @var boolean $check **/
$check = $message->getDate()->timestamp === $parts[2];
```

Best regards
