### ISSUE TITLE
option to get the mail with timestamp

### ISSUE THREAD

**Issue by kaviyarasansadasivam** [Webklex/laravel-imap#138]
Please be aware that these issues will be closed if inactive for more then 14 days :)
Is there any option to get the mail with timestamp.

Since takes only date not time.

I need to retrieve the mail after some timestamp.

Any help would be appreciative.

**Comment by Webklex** [comment]
Hi @kaviyarasansadasivam ,
please take closer look at the search section: https://github.com/Webklex/laravel-imap/blob/master/README.md#search-for-messages

As you can see, you can also provide a Carbon object as search value. You can create a new Carbon object from a timestamp - this way you can search for timestamps. But note that it isn't possible to search for hours/mins/seconds.. only "real" dates are supported by RFC1176 (
https://tools.ietf.org/html/rfc1176).

Best regards

**Comment by Webklex** [comment]
Here is an example if your mail server is supporting datetime:

``` php
$timestamp = strtotime('17.08.2018 10:30');

/** @var \Webklex\IMAP\Folder $oFolder */
$oFolder = $oClient->getFolder('INBOX');
$date = Carbon::createFromTimestamp($timestamp);

/** @var \Webklex\IMAP\Support\MessageCollection $aMessage */
$aMessage = $oFolder->search()->where([
    ['SINCE', $date->format('d M y H:i')]
])->get();
```

An overview of all available search citeria can be found here: https://github.com/Webklex/laravel-imap#search-for-messages (scroll down to "Available search criteria").

If your Mailserver isn't supporting datetime, you could also filter the collection and drop all messages which don't match your ciriteria:

``` php
$timestamp = strtotime('17.08.2018 10:30');

/** @var \Webklex\IMAP\Support\MessageCollection $aMessage */
$aMessage = $aMessage->filter(function ($oMessage) use ($timestamp) {
    /** @var \Webklex\IMAP\Message $oMessage */
    if($oMessage->getDate() !== null) {
        return $oMessage->getDate()->timestamp > $timestamp;
    }
        
    return false;
})->values();
```

Best regards
