### ISSUE TITLE
getAttachments() functions given wrong attachments some mail cases

### ISSUE THREAD

**Issue by karan-shah-21** [Webklex/laravel-imap#139]
**Describe the bug**

getAttachments() functions given wrong attachments some mail cases like gmail delivery fail. it give content image and file as attachments. but in actual mail there is not any attachment available

**Below is my attachment get code**

             $result = $attachments = [];
            if($oMessage->hasAttachments()){
                $result['msgid'] = $oMessage->getMessageId();
                $k = 0;
                foreach ($oMessage->getAttachments() as $key => $oAttachment) {
                    $attachments[$k]['getExtension'] = pathinfo($oAttachment->getName(), PATHINFO_EXTENSION); 
                    $attachments[$k]['getName'] = $oAttachment->getName();
                    $dir = storage_path('app/public/attachments/'.$oMessage->getMessageId());
                    if (!is_dir($dir)) {
                        File::makeDirectory($dir, 0777, true);
                    }
                    $filename = str_replace(' ', '', $oAttachment->name);
                    $filepath = 'public/attachments/'.$oMessage->getMessageId().'/'.$filename;
                    $attachments[$k]['getPath'] = $filepath;
                    $pullfile = Storage::put($filepath, $oAttachment->content, 'public');
                    $k++; 
                }
                $result['attachments'] = $attachments;
            }

**Expected behavior**

we need same out for all emails same as it's in original or actual.

**Screenshots**

Please see attachments for this issue
image1 - original email
image2 - get through lib
![image1](https://user-images.githubusercontent.com/40829706/44570573-f0694380-a79b-11e8-8462-ccf99e06334f.png)
![image2](https://user-images.githubusercontent.com/40829706/44570575-f0694380-a79b-11e8-8d96-d460d543a878.png)

**Desktop / Server (please complete the following information):**
 - OS: [ubanthu]
- PHP: [7.2..3]
 - Version [1.2.6]

**Additional context**

**Comment by Webklex** [comment]
Hi @karan-shah-21 ,
thanks for the detailed report.
I noticed you are using an older version. Please update to the latest release and try again :)

Best regards

**Comment by karan-shah-21** [comment]
Hi @Webklex 

I have tired with new lib version:1.2.8 but still it's giving same output as i have mentioned into issue. So please give me solution for same or do needful update into lib for same..

**Comment by Webklex** [comment]
Hi @karan-shah-21 ,
I'm having a hard time to reproduce this behavior. Please provide some of your code so I can adjust my test.

Best regards

**Comment by karan-shah-21** [comment]
Hi @Webklex 

I have alreay provide my code with issue details but still i am providing my entire function to you..

public function getSinglemail(Request $request){
        try{
            if(isset($request->uid))
                $id =$request->uid;
            $oClient = new Client([
                'host'          => $ImapData->imap_host,
                'port'          => 993,
                'encryption'    => 'ssl',
                'validate_cert' => false,
                'username'      => $ImapData->imap_username,
                'password'      => base64_decode($ImapData->imap_password),
            ]);
            $oClient->connect();
            /** @var \Webklex\IMAP\Folder $oFolder */
           
            $oFolder = $oClient->getFolder('INBOX');
            
            /** @var \Webklex\IMAP\Message $oMessage */

            $username = $oFolder->getClient()->username;
            $oMessage = $oFolder->getMessage($id,null,null,true,true,true);
            $result = $attachments = [];
            if($oMessage->hasAttachments()){
                $result['msgid'] = $oMessage->getMessageId();
                $k = 0;
                foreach ($oMessage->getAttachments() as $key => $oAttachment) {

                    $attachments[$k]['getExtension'] = pathinfo($oAttachment->getName(), PATHINFO_EXTENSION); 
                    $attachments[$k]['getName'] = $oAttachment->getName();
                    $dir = storage_path('app/public/attachments/'.$oMessage->getMessageId());
                    if (!is_dir($dir)) {
                        File::makeDirectory($dir, 0777, true);
                    }
                    $filename = str_replace(' ', '', $oAttachment->name);
                    $filepath = 'public/attachments/'.$oMessage->getMessageId().'/'.$filename;
                    $attachments[$k]['getPath'] = $filepath;
                    $pullfile = Storage::put($filepath, $oAttachment->content, 'public');
                    $k++; 
                }
                $result['attachments'] = $attachments;
            }
            $result['emailbody'] = $oMessage->getHTMLBody(true);
            echo json_encode($result); exit;
        }catch(\Exception $ex){
            echo 'false'; exit;
        }
    }

**Comment by Webklex** [comment]
Hi @karan-shah-21 ,
please send them to laravel-imap-test@webklex.com.

Are you aware of the fact that the message id is not unique? I noticed you move them into a folder named by it... Could this be the problem?

Best regards

**Comment by irfan9000** [comment]
@Webklex, Hi sir I am facing an issue to get iPhone(ios) attachments
