### ISSUE TITLE
how to show For Reply , Reply-all showing mail in qouted format and For Forward showing forwared text before sending mail..?

### ISSUE THREAD

**Issue by karan-shah-21** [Webklex/laravel-imap#140]
how to show For Reply , Reply-all showing mail in qouted format and For Forward showing forwared text before sending mail

**Comment by Webklex** [comment]
Hi @karan-shah-21 ,
please take a closer look at the documentation https://github.com/Webklex/laravel-imap#messageclass and try to provide more details and code samples. 
It isn't realy clear what you are asking.

Best regards
