### ISSUE TITLE
Use of undefined constant FT_UID

### ISSUE THREAD

**Issue by Grashee** [Webklex/laravel-imap#141]
**Describe the bug**
When I want to install the package via composer i am facing the following error:

```

post-autoload-dump: Illuminate\Foundation\ComposerScripts::postAutoloadDump
post-autoload-dump: @php artisan package:discover

   ErrorException  : Use of undefined constant FT_UID - assumed 'FT_UID' (this will throw an Error in a future version of PHP)

  at /var/www/html/laravel/vendor/webklex/laravel-imap/src/config/imap.php: 105
  101:     |
  102:     */
  103:     'options' => [
  104:         'delimiter' => '/',
  105:         'fetch' => FT_UID,
  106:         'fetch_body' => true,
  107:         'fetch_attachment' => true,
  108:         'fetch_flags' => true,
  109:         'message_key' => 'id',
  110:         'fetch_order' => 'asc',

  Exception trace:

  1   Illuminate\Foundation\Bootstrap\HandleExceptions::handleError("Use of undefined constant FT_UID - assumed 'FT_UID' (this will throw an Error in a future version of PHP)", "/var/www/html/laravel/vendor/webklex/laravel-imap/src/config/imap.php", ["imap", "/var/www/html/laravel/vendor/webklex/laravel-imap/src/IMAP/Providers/../../config/imap.php"])
      /var/www/html/laravel/vendor/webklex/laravel-imap/src/config/imap.php : 105

  2   require("/var/www/html/laravel/vendor/webklex/laravel-imap/src/config/imap.php")
      /var/www/html/laravel/vendor/webklex/laravel-imap/src/IMAP/Providers/LaravelServiceProvider.php : 66

```

**To Reproduce **
1.  Run "composer require webklex/laravel-imap" on console

**Expected behavior**
I want to install "laravel-imap" into my laravel project and I run the command: "composer require webklex/laravel-imap " in my laravel project. Where it throws me the error which I pasted in my first section of this post.

** Server : **
 - OS: Debian 9
- PHP: 7.0

**Comment by Webklex** [comment]
Hi @Grashee ,
please make sure you've installed all required php extensions:
``` sh
sudo apt-get install php*-imap php*-mbstring php*-mcrypt && sudo apache2ctl graceful
```
..and check #14 and #30 as well. Feel free to reopen this issue if you still encounter the same problem :)

Best regards

**Comment by lomotech** [comment]
i have this issue too with my macOS, php@7.2, valet.
in terminal its ok but in browser have this issue and it says imap_open is not a function.

the solution:

`sudo brew services restart php@7.2`
`sudo brew services restart nginx`

im trying without sudo, nothing changes.

**Comment by mmjjb** [comment]
Maybe better to check if the constant is defined, before calling it? Although it is required anyway php-imap

**Comment by mmjjb** [comment]
This constant is defined by php-imap, php-imap is required as dependency.
However my development environment has no php-imap installed, might be good to build in some check?
