### ISSUE TITLE
Rendering HTML emails

### ISSUE THREAD

**Issue by mallchin** [Webklex/laravel-imap#142]
Hello,

I haven't tried this at all but it looks very promising.  Before I do, I am curious what security measures are required, if any, for rendering HTML emails?

Can someone include rogue javascript or some such in an email that could present a security concern when displaying in-line on a page?

Thanks,

**Comment by Webklex** [comment]
Hi @mallchin ,
a few things you could look at:
- Remove all js components (including inline js)
- Remove all css components (including style attributes
- Strip all html tags
- Don't fetch any attachments

However you will probably end up loosing all styles. Depending on your requirements you could also just use the plain text, but keep in mind that HTML and Text body can contain different texts.

Your question in geberal is very broad. Could you narrow it down some more? :)

Best regards

**Comment by mallchin** [comment]
Thank you, that is most helpful.

I don't have a specific use case or concern other than displaying HTML in an email could potentially throw up security concerns given it is, essentially, external code.

It sounds like simply scrubbing HTML before displaying is that way to go, however, that may render it unreadable.

Displaying the text body is a workaround but as you mentioned, it may differ from the HTML, and it severely limits the usefulness of displaying emails altogether.

So I guess, in short, how to safely display HTML emails in a UI? :)

Sounds like a scrub job!

**Comment by Webklex** [comment]
Guess 'sanboxing' would be the way to go since it does'nt require much work or additional infrastructure :+1:  
Thanks for your research!
