### ISSUE TITLE
How can use pop3 

### ISSUE THREAD

**Issue by rafikmalek68** [Webklex/laravel-imap#143]
I have used imap protocol its working fine
But now i want to be pop3 protocol ,  I checked all documentation but not found anything how to use
Can you please guide me how can i use pop3

**Comment by Webklex** [comment]
Hi @rafikmalek68 ,
please take an other look at the available configuration: https://github.com/Webklex/laravel-imap/blob/master/README.md#configuration

You just have to change the `protocol` option.

Best regards

**Comment by rafikmalek68** [comment]
Thanks for reply.

Please see my code for pop3 

$oClient = new Client([
				'host'          =>'pop.gmail.com',
				'port'          =>'995',
				'encryption'    =>'ssl',
				'validate_cert' =>true ,
				'username'      =>'myUSERNAME',
				'password'      =>'myPASSWORD',
				'protocol'      =>'pop3',
		  ]);
		
		  $oClient->connect();
		  $oFolder  = $oClient->getFolder($folder);	  
		  $mail 	= $oFolder->messages()->all()->get();
		  foreach($mail as $oMessage){
		  
			echo $oMessage->getSubject();
		  }

its return me response only one time second time its return 0 record 
I means one time mail showing me when i second time page refresh its return 0 record

**Comment by Webklex** [comment]
That's right since that's what pop3 does. If you want to keep the mail you either have to save it or use imap instead :)
