### ISSUE TITLE
How to get children folders and display them

### ISSUE THREAD

**Issue by M-Abdullahi** [Webklex/laravel-imap#145]
Please be aware that these issues will be closed if inactive for more then 14 days :)
Hi. I am trying to get and display all the children of the inbox folder but not sure of how to do it. 
 After dumping it like below
```
foreach ($aFolder as $oFolder) {
            dd($oFolder->children);
});
```

I get this the following folder collection of the children:

![screenshot 147](https://user-images.githubusercontent.com/14330689/45263775-bacd8700-b438-11e8-8f2a-5affbcd13fc9.png)

How do i loop through the children collection in blade file and achieve the result below
![screenshot 149](https://user-images.githubusercontent.com/14330689/45263780-ee101600-b438-11e8-834c-a81f4067a4dc.png)

**Comment by Webklex** [comment]
Hi @M-Abdullahi ,
here is an untested view example on how you could build such a list:
```blade
<?php
/**
 * @var \Webklex\IMAP\Support\FolderCollection $paginator
 * @var \Webklex\IMAP\Folder $oFolder
 */
?>
<table>
    <thead>
    <tr>
        <th>Folder</th>
        <th>Unread messages</th>
    </tr>
    </thead>
    <tbody>
    @if($paginator->count() > 0)
        @foreach($paginator as $oFolder)
            <tr>
                <td>{{$oFolder->name}}</td>
                <td>{{$oFolder->search()->unseen()->leaveUnread()->setFetchBody(false)->setFetchAttachment(false)->get()->count()}}</td>
            </tr>
        @endforeach
    @else
        <tr>
            <td colspan="4">No folders found</td>
        </tr>
    @endif
    </tbody>
</table>

{{$paginator->links()}}
```

Best regards

**Comment by M-Abdullahi** [comment]
Hi. Thank you for the feedback. I will take a look at it and respond.

**Comment by hemendra12111** [comment]
How we can get the folder icon. can any one help me ?

**Comment by Webklex** [comment]
Hi @hemendra12111,
the icons arn't stored on the mail server. You'll have to assign/match them yourself.

Best regards
