### ISSUE TITLE
All works except querying for specific message.

### ISSUE THREAD

**Issue by klukiyan** [Webklex/laravel-imap#150]
This works:
```
$aMessage = $oFolder->query()->limit(10, 2)->get();
```
This refuses to work: 
```
$aMessage = $oFolder->query()->text("whatever")->get();
$aMessage = $oFolder->query()->Subject("whatever")->get();
$aMessage = $oFolder->query()->Subject("whatever")->get();
$aMessage = $oFolder->query()->from('example@domain.com')->get();
$aMessage = $oFolder->query()->unseen()->limit(10, 2)->get();
```
all the time getting empty arrays...
Any help please?
I'm using the "facade approach"
```
...
use Webklex\IMAP\Facades\Client;
...
$oClient = Client::account('default');
        $oClient->connect();
...
```

**Comment by Webklex** [comment]
Hi @klukiyan ,
just a basic question before I dive in deepter. Is there an email with the text "whatever" or the subject "whatever" or any unseen emails available? Might sound stupid, but I encountered a simular issue before ;)

Besides that your code looks fine (ecept `WhereQuery::Subject()` - this should be `WhereQuery::subject()`) to me.

Best regards

**Comment by klukiyan** [comment]
@Webklex 
I have it with "Electra" in subject, and yes the folder contains it.
```
$aMessage = $oFolder->query()->subject('Electra')->limit(10, 2)->get();
```
empty array...
the querying simply doesn't seem to work. Maybe I should use some different approach instead of Facade?

**Comment by klukiyan** [comment]
@Webklex , thank you, with `query(null)` it wors.
My last concern is about the speed.

- With above mentioned php code I'm getting the bodies of the 3 searched messages in **2 seconds** (the inbox is really huge, it is on slow distant exchange server).
- When using your package, code is simpler and shorter, but I get the response in **6-8 seconds**.  
I've tried many times, the result is the same. I've tried to make the query as short as possible, it's still considerably slower.
Can you give me a hint what I could optimize to get flawless experience for my users.
This is the shortes option I could get:
```
//this gets me into 6-8 seconds.
$oClient->connect();
$aMessage = $oClient->getFolder('INBOX')->query(null)->text('Electra')->get();
foreach ($aMessage as $oMessage) {
    echo $oMessage->getHtmlBody(true);
}
```

I want to use your package, especially when it comes to working with attachments. But the speed is really a concern. Can you give me a hint how can I make it faster?

**Comment by Webklex** [comment]
If you want to decrease the loading time you could as well fetch bodys and attachments later.
```php
$oFolder->query(null)->setFetchFlags(false) ->setFetchBody(false)->setFetchAttachment(false);
```
Your mentioned plain php code does'nt fetch all attachments, thats probably why its faster. This library also does some encoding etc which might take a few additional ms. However feel free to create a fork and remove everything you don't need - that's probably the best in order to get the most out of it :)

**Comment by klukiyan** [comment]
@Webklex That's a good hint.
Now if I don't fetch the body/flags/attachments and I want to display the body + attachments when I click on the message, how to I query directly that single message please?
_Sorry if this question is too silly._

**Comment by klukiyan** [comment]
Great
Thank you very much, @Webklex

**Comment by dharmendravirasat** [comment]
$oMessage = $oFolder->getMessage($uid = 1); 
can't working please answer

**Comment by Webklex** [comment]
@dharmendravirasat that could be caused by a ton of things. Please provide more information and if it isn't related to this issue, please consider to open a new issue.

Best regards
