### ISSUE TITLE
Replace embedded image with URL

### ISSUE THREAD

**Issue by freescout-helpdesk** [Webklex/laravel-imap#151]
If in the email there is such image:
```
<img src=3D"cid:ii_jmq96j4=y0" alt=3D"test.png" width=3D"562" height=3D"302">
```
it is being converted into:
```
<img src="data:image/png;base64,iVBORw0KGg...
```

Is there any way to replace `data:image...` with the URL of the image on my server?

**Comment by freescout-helpdesk** [comment]
After retrieving a message via IMAP I get attachment using `$message->getAttachments()` and save them to the disk. 

If original message contains:
```
<img src=3D"cid:ii_jmq96j4=y0" alt=3D"test.png" width=3D"562" height=3D"302">
```
`laravel-imap` converts in into `<img src="data:image/png;base64,iVBORw0KGg...`, 

So when I'm retrieving a body of the message `$message->getHTMLBody(true)` I have this `data:image/png;base64,iVBORw0KGg...` in the body. Images can be big (several MBs), I don't need them in the body, as I saved them on the disk before. So now I need to replace all `data:image...` with corresponding attachment URLs.

**Comment by salih0vicX** [comment]
Hi @freescout-helpdesk, please see the `getHTMLBody `method in Message.php. Unless something changed recently the method accepts only one parameter (`$replaceImages = false`). You are calling this method by passing `TRUE `which than results in replacing images with `base64 `data. Try calling method `getHTMLBody(FALSE) `and it should return message body without `src `attribute being replaced with `base64 `image data.

It worked for me.

**Comment by Webklex** [comment]
@salih0vicX , you are right. I totally forgot about that :)
`Message::getHTMLBody($replaceImages = false)` hasn't changed, but If you don't replace the cids with the base64 source, the Attachment class doesn't has to convert the content into a base64 string anyway. 

I thinks adding an option to enable/disable this behavior would be great. It will be part of the next release. Thanks for the hint :+1:

**Comment by Webklex** [comment]
Hi @freescout-helpdesk ,
if you like you could give the current master version a try. It got several new features. You can now create masks which will do exactly what you are looking for :)

I added some examples: 
https://github.com/Webklex/laravel-imap/blob/master/examples/replace_images_with_url.php
https://github.com/Webklex/laravel-imap/blob/master/examples/custom_message_mask.php

If you need any held just let me know.

Best regards
