### ISSUE TITLE
Un-encoded sender name in non-latin emails sent from Gmail

### ISSUE THREAD

**Issue by freescout-helpdesk** [Webklex/laravel-imap#154]
1. Set in your Gmail account long non-latin name and surname (at least 32 symbols total):
First name: Рекламный Вестник
Last name: Туркменистана
2. Send email to some mailbox from this Gmail account.
3. In the email `From` header will look like:
```
From: =?UTF-8?B?0KDQtdC60LvQsNC80L3Ri9C5INCS0LXRgdGC0L3QuNC6INCi0YPRgNC60LzQtdC90LjRgdGC?=
	=?UTF-8?B?0LDQvdCw?= <test@example.com>
```
4. Retrieve email using `laravel-imap` and `$message->getFrom()` will return something like this:
````
stdClass Object
(
    [personal] => =?UTF-8?B?0KDQtdC60LvQsNC80L3Ri9C5INCS0LXRgdGC0L3QuNC6INCi0YPRgNC60LzQtdC90LjRgdGC?= ана
    ....
)
````
I.e. if sender name is split into two parts in incoming headers, `laravel-imap` decodes only the first part.

**Comment by Webklex** [comment]
Hi @freescout-helpdesk ,
thanks for your pull request! :)

A new version will be released within the next few days.

Best regards
