### ISSUE TITLE
getMessage($uid) in other folder than INBOX

### ISSUE THREAD

**Issue by Dreknor** [Webklex/laravel-imap#158]
How can a specific message be retrieved from a folder that is not INBOX?
getMessage($uid) return null

**Comment by 1amdev** [comment]
I'm having the exact same issue. Just posted it a few days ago at https://github.com/Webklex/laravel-imap/issues/157. I hope it gets fixed!

**Comment by dharmendravirasat** [comment]
please try this code..........
  $oFolder = $oClient->getFolder('INBOX');

$aMessage = $oFolder->getMessage($uid,null, null, true, true);
echo $aMessage->getSubject()."</br>";
echo $aMessage->getFrom()[0]->mail."</br>"; 
echo 'Attachments: '.$aMessage->getAttachments()->count().'<br />';
echo $aMessage->getHTMLBody(true);

**Comment by dharmendravirasat** [comment]
> please try this code..........
> $oFolder = $oClient->getFolder('INBOX');
> 
> $aMessage = $oFolder->getMessage($uid,null, null, true, true);
> echo $aMessage->getSubject()."
> ";
> echo $aMessage->getFrom()[0]->mail."
> ";
> echo 'Attachments: '.$aMessage->getAttachments()->count().'
> ';
> echo $aMessage->getHTMLBody(true);

BUT this code using INBOX folder work 
can't working other folder

**Comment by Webklex** [comment]
Please take a look at #157
