### ISSUE TITLE
How to get specific message from other folder rather than Inbox using (WebKlex)

### ISSUE THREAD

**Issue by engrnand** [Webklex/laravel-imap#162]
Please be aware that these issues will be closed if inactive for more then 14 days :)
$oFolder = $oClient->getFolder('INBOX.Drafts');
$oFolder = $oMessage = $oFolder->getMessage($uid = 2);
in this code I able to get only inbox message but it can't get other folders specific message

**Comment by Webklex** [comment]
Please take a look at #157
