### ISSUE TITLE
Long wait time even for few emails

### ISSUE THREAD

**Issue by andreav94** [Webklex/laravel-imap#164]
I think i'm doing something wrong, cause fetching 5 mails for me can take up to 15 seconds, for 30 mail it takes about a minute. Evertything is working as exepected and i correctly read and display the mails, but this loading times are making this great package unusable, so i hope someone can help me with that.

My internet connection is fast and stable and i tried setFetchBody(false) and setFetchAttachment(false) but it seems to speed up the loading time of only a few seconds overall, not making a big difference.

Here is my code. I am only retrieving the gmail folder with his children folders, to speed things up a little bit. I noticed that the connection part takes a "normal"  3-4 seconds. and most of the time is consumed by the query. 

Thanks again to whoever would want to help me, and sorry for bad formatting of code.

ENV FILE:
```
IMAP_HOST=imap.gmail.com
IMAP_PORT=993
IMAP_ENCRYPTION=ssl
IMAP_VALIDATE_CERT=true
IMAP_USERNAME=*********
IMAP_PASSWORD=********
IMAP_DEFAULT_ACCOUNT=default
IMAP_PROTOCOL=imap
```

PHP FILE:
```php
        $oClient = new Client([
            'host'          => 'imap.gmail.com',
            'port'          => 993,
            'encryption'    => 'ssl',
            'validate_cert' => true,
            'username'      => '*******', 
            'password'      => '*******',
            'protocol'      => 'imap',
        ]);
      
//Connect to the IMAP Server
        $oClient->connect();

//Get all Mailboxes
     
        $gmailFolder=$oClient->getFolders(true,'[Gmail]')[0];

//Loop through every folder, only in gmail
//        $gmailFolder=$aFolder[4]->children;
        /** @var \Webklex\IMAP\Folder $oFolder */
        $folders=[];
        foreach($gmailFolder->children as $oFolder){
            //Get all Messages of the current Mailbox $oFolder
    
            $aMessage = $oFolder->query()->since('26.10.2018')->limit(3)->setFetchFlags(false)
               ->setFetchBody(false)
                ->setFetchAttachment(false)->get();

                $mails=[];

            /** @var \Webklex\IMAP\Message $oMessage */
            foreach($aMessage as $oMessage){
                $mail['subject']=$oMessage->getSubject();
                $mail['from']=$oMessage->getFrom();
                $mail['replyTo']=$oMessage->getReplyTo();
      //          $mail['HTMLBody']=$oMessage->getHTMLBody();
                $mail['date']=$oMessage->getDate();
                $mails[]=$mail;
               
            }
            $folders[$oFolder->name]=$mails;
    }
```

**Comment by Webklex** [comment]
Hi @andreav94 ,
how many folders are you actually fetching? 
If you time your code by using something like this:
```php
$start = microtime(true);
$gmailFolder=$oClient->getFolders(true,'[Gmail]')[0];
echo 'folders fetched: '.(microtime(true) - $start);

$_start = microtime(true);
foreach($gmailFolder->children as $oFolder){
     $start = microtime(true);
     $aMessage = $oFolder->query()->since('26.10.2018')->limit(3)->setFetchFlags(false)
               ->setFetchBody(false)
                ->setFetchAttachment(false)->get();
     echo 'messages fetched: '.(microtime(true) - $start);
}
 echo 'all messages fetched: '.(microtime(true) - $_start);
```
..whats the output?

Best regards

**Comment by sigmund-avila** [comment]
@kill300r have you fixed your issue regarding long waiting time? I also experience the same issue.

**Comment by kill300r** [comment]
Hey, yes I have :)
The problem is that the Site has to load too many e-mails at once.
You have to load around 20 Mails per page. Personally i made my own pagination 
because I could’t make Webklexes to work right...
Check this PDF file I hope it helps you!

**Comment by MeSigmund** [comment]
Thanks for your response. Meanwhile i cannot view the pdf that you mentioned. It says Whoops! That unsubscribe link isn't valid for your account.

**Comment by sigmund-avila** [comment]
@kill300r Thanks for your response but I cannot find the PDF that you mentioned.
Another thing, are you saving the email data to the database? If yes, how do you do it? My objective is to fetch the emails of our users then save it to a database.
