### ISSUE TITLE
imap_open(): Couldn't open stream 

### ISSUE THREAD

**Issue by ronlinet** [Webklex/laravel-imap#165]
My imap connection are dying with bellow error :
imap_open(): Couldn't open stream {mail.myhost.com:993/imap/ssl}INBOX  No such host as mail.myhost.com

There is no problem in my settings because the client worked normally for almost two weeks. Then the lockout started randomly showing up but things was getting to order after some delays. Now I am completely blacked out while I can still access my emails with normal  web-based IMAP email clients  such as Round Cube or HORDE. 

My email provider ( godaddy ) is denying any involvement but I believe that  I am being locked out by their system because I am scanning their email server each minute to extract all unread email to my WEB server DB for a real time listing feature. The amount of extracted emails is about 4000 per day. 

At this point I don’t have any other choice than changing the email provider for the beginning I am going for a normal gmail account at the same time but I would welcome any advise about an email provider where I will not run in the same kind of issues as with Godaddy.

**Comment by ronlinet** [comment]
Switched to gmail so far it does much better job for free than Godaddy's payed services.

**Comment by Webklex** [comment]
Sounds like this is solved :)
