### ISSUE TITLE
Message.getSubject is wrong for french emails (UTF8)

### ISSUE THREAD

**Issue by gregoirer** [Webklex/laravel-imap#167]
The subject of my email is : "Votre mise à jour est en ligne", unfortunately when I do getSubject I have : "Votre_mise_à_jour_est_en_ligne". Space has been replaced by underscore.
The function to decode the subject is  currently
```php
$this->subject = mb_decode_mimeheader($header->subject);
```
I suggest to use built-in imap function
```php
$subject = "";
foreach(imap_mime_header_decode($header->subject) as $part){
        $subject.= $part->text;
 }
$this->subject = $subject;
```

**Comment by GeoSot** [comment]
@gregoirer 

Give a try on this [pull request](https://github.com/Webklex/laravel-imap/pull/175)

**Comment by Webklex** [comment]
Hi @gregoirer @GeoSot   ,
please update to [v. 1.3.1](https://github.com/Webklex/laravel-imap/releases/tag/1.3.1) :)
