### ISSUE TITLE
specific sent mail message can't display but inbox folder working 

### ISSUE THREAD

**Issue by dharmendravirasat** [Webklex/laravel-imap#170]
$oClient->connect();
    $oFolder = $oClient->getFolder('[Gmail]/Sent Mail');

/** @var \Webklex\IMAP\Message $oMessage */
$aMessage = $oFolder->getMessage($uid,null, null, true, true);

echo $aMessage->getSubject()."</br>";
echo $aMessage->getFrom()[0]->mail."</br>"; 
echo 'Attachments: '.$aMessage->getAttachments()->count().'<br />';
echo $aMessage->getHTMLBody(true);

**Comment by 1amdev** [comment]
You could've just commented on my issue or referenced it instead of copying and pasting and making the process even more difficult: https://github.com/Webklex/laravel-imap/issues/157

But I'm glad I'm not the only one having this issue.

**Comment by maverickdude** [comment]
@dharmendravirasat 

Always search if any issue exist relating to yours. If there's none, only then you should create a new one.

However please see my solution in this https://github.com/Webklex/laravel-imap/issues/157 to resolve the issue.

**Comment by dharmendravirasat** [comment]
please answer this post

**Comment by Webklex** [comment]
@dharmendravirasat getting a bit rude here ;)

However head over to #157 and just like @maverickdude said, please use the search and don't come back...

**Comment by igmacedo** [comment]
@maverickdude
Its solution is unrelated to the problem, UIDs are incompatible and cannot be searched ​​because they are larger than existing ones. This is a package issue with Gmail.
