### ISSUE TITLE
After moving messages, getFolder->all() retrieve messages that are not there.

### ISSUE THREAD

**Issue by alex-grau** [Webklex/laravel-imap#172]
According to the php_imap docs, after calling imap_mail_move() you should call imap_expunge() (https://secure.php.net/manual/en/function.imap-expunge.php).

**Comment by Webklex** [comment]
Hi @alex-grau ,
you are right. For now you could use something like:
```php
/** @var \Webklex\IMAP\Folder $folder */
/** @var \Webklex\IMAP\Message $message */
$message = $folder->getMessages()->first();
$message->move($folder);
$message->getClient()->expunge();
```
