### ISSUE TITLE
Date filters since, on, before return no messages

### ISSUE THREAD

**Issue by qerim** [Webklex/laravel-imap#174]
**Describe the bug**
None of the date commands (since, on, before) are working.
I've tried formatting the data as a string and Carbon instance.

My inbox folder contains a total of **40 messages**, ranging from 1st Oct 2018 to now.

**To Reproduce**

    $messages = $oFolder->getMessages()->sortByDesc('date');
    dump('Total messages: '. $messages->count());

Returns **40**

    $aMessage = $oFolder->query()->since(\Carbon\Carbon::now()->subDays(10))->get();
    dump('Since command: '.$aMessage->count());

    $aMessage = $oFolder->query()->since('01.10.2018')->get();
    dump('Since: '.$aMessage->count());

    $aMessage = $oFolder->query()->before('29.11.2018')->get();
    dump('Before: '.$aMessage->count());

All Return: **0**

Here is an example of one of the messages:

    $message = $messages->first();
    dd($message->date);

Result:

    Carbon\Carbon @1543474888 {#2200
      date: 2018-11-29 07:01:28.0 +00:00
    }

**System**
 - OS: Ubuntu server
- PHP: 7.1.22
- Laravel: 5.6.39

**Comment by gmauriello** [comment]
Same problem. Nothing returned. (Also with other methods, e.g. text, from, to...)
Works only with:
`$oFolder->messages()->all()->get();`

How to fix this issue and filter the query by date?
