### ISSUE TITLE
Fetch Mail

### ISSUE THREAD

**Issue by aks7665** [Webklex/laravel-imap#177]
I want to fetch all the mails with attachments and all the information from all folders but the issue i am facing is that it takes lot of time in fetching the mail. Sometimes it takes more than 15 minutes to fetch the mails.
Is there any solution for this?
So that i can fetch all the mails of all the folders in less time?

**Comment by Webklex** [comment]
Hi @aks7665 ,
how many messages are you trying to fetch?

You could limit the amount by using something like this:
```php
/** @var \Webklex\IMAP\Folder $folder */
/** @var \Webklex\IMAP\Support\MessageCollection  $messages */
$messages = $folder->query()->limit(10)->get();
```

Best regards
