### ISSUE TITLE
I want to fetch mails after some specific uid.

### ISSUE THREAD

**Issue by aks7665** [Webklex/laravel-imap#178]
I want to fetch all mails after some specific uid.
Is there any way?

**Comment by jonvillegb2ei** [comment]
up

**Comment by Webklex** [comment]
Hi @aks7665 ,
yes there is but please be aware that the UID is not unique and might change over time :)

```php
$uid = 45;
/** @var \Webklex\IMAP\Folder $folder */
/** @var \Webklex\IMAP\Message $message */
$message = $folder->getMessage($uid);
```

Best regards
