### ISSUE TITLE
OAuth

### ISSUE THREAD

**Issue by gareth-ib** [Webklex/laravel-imap#180]
Is there a way or can you add to be able to use OAuth for IMAP instead of user/pass? Like what this Google demo has using old Zend libraries?

https://github.com/google/gmail-oauth2-tools/blob/master/php/oauth2.php

thanks

**Comment by tkrause** [comment]
Bump as Google has announced they're not supporting basic authentication anymore.

https://www.google.com/amp/s/www.androidcentral.com/google-blocking-access-less-secure-apps-protect-g-suite-users%3famp

**Comment by freescout-helpdesk** [comment]
laravel-imap uses PHP IMAP functions (https://www.php.net/manual/en/ref.imap.php), but it does looks like PHP IMAP functions can not be used to authenticate using https://developers.google.com/gmail/imap/xoauth2-protocol

Some workaround is needed.

**Comment by freescout-helpdesk** [comment]
Suggestion for Google: https://github.com/google/gmail-oauth2-tools/issues/18

**Comment by freescout-helpdesk** [comment]
@Webklex do you think it is doable to make this lib compatible with OAuth IMAP or it will just continue to use native PHP `imap_` functions?

**Comment by CW92** [comment]
It looks like Microsoft Office 365 customers are also going to be subject to the same requirements - https://developer.microsoft.com/en-us/office/blogs/end-of-support-for-basic-authentication-access-to-exchange-online-apis-for-office-365-customers/

**Comment by Webklex** [comment]
Solved with v2.0.0: https://github.com/Webklex/laravel-imap#oauth

**Comment by sergiy-petrov** [comment]
> Solved with v2.0.0: https://github.com/Webklex/laravel-imap#oauth

the link is broken

**Comment by freescout-helpdesk** [comment]
PHP IMAP from Webklex: https://github.com/Webklex/php-imap
