### ISSUE TITLE
Bounce processing

### ISSUE THREAD

**Issue by freescout-helpdesk** [Webklex/laravel-imap#182]
In our project we need to process bounces, i.e. extract the following info for bounces: status_code, action, diagnostic_code. To get this info original messages's structure is needed, which is returned by `imap_fetchstructure`.

Is it ok if we add `processBounce` function to Message.php and create a pull request. The function will be based on:
https://github.com/voku/PHPMailer-BMH/blob/b1f7f4f00c137ffa8bed3909a6ec4b2792e61a37/src/BounceMailHandler/BounceMailHandler.php#L702
Function will return array with bounce data (status_code, action, diagnostic_code) or empty array if no nounce detected.

**Comment by freescout-helpdesk** [comment]
Or alternatively is it possible to create a `getStructure()` method which would allow us to get structure?
```
public function getStructure()
{
    return $this->structure;
}
```

**Comment by Webklex** [comment]
Hi @freescout-helpdesk ,
the method Message::getStructure() is now implemented.

Best regards

**Comment by freescout-helpdesk** [comment]
Here is how we ended up doing this: https://github.com/freescout-helpdesk/freescout/blob/2c39ba9d9e7c506b52b5b84284b3bec1d899cb74/app/Console/Commands/FetchEmails.php#L449

**Comment by akash-magar-dev** [comment]
hi @Webklex  @freescout-helpdesk 

for checking the bounced email I followed your logic. I have also added some other ways to find out. 
can you just check at let me know if I am doing anything wrong?

```
public function detectErrorCode(string $error_message)
    {
        // Regular expression pattern to match 4.x.x and 5.x.x error codes
        // $pattern = '/[45]\.\d{1,3}\.\d{1,3}/';

        // regax to match 4xx | 5xx or 4.x.x|5.x.x
        // $pattern = '/\b(?:5\.\d{1,3}\.\d{1,3}|4\.\d{1,3}\.\d{1,3}|5\d{2}|4\d{2})\b/';

        //regax to check Staus: 5.x.x | 4.x.x
        $pattern = '/(?<=status: )(?:5|4)\.\d{1,3}\.\d{1,3}/i';

        if (preg_match_all($pattern, $error_message, $matches)) {
            return $matches[0]; // or we can simply return true
        } else {
            return false;
        }
    }

    public function detectDiagnosticCode(string $body)
    {
        // Regular expression pattern to match Diagnostic-Code
        $pattern = "/Diagnostic-Code:\s(.*\n(?:(?!--).*\n)*)/i";

        if (preg_match_all($pattern, $body, $matches)) {
            return $matches[0]; // or we can simply return true
        } else {
            return false;
        }
    }
```

connect to IMAP client then get all email messages
  ```  
  $aMessage = $folder->messages()->all()->get();

            foreach ($aMessage as $msg) {
                $header = $msg->getHeader();
                $body = $msg->getRawBody();
                $is_bounced = (new BounceChecker())->detectBounceByHeaders($header->raw);
                $error_code = (new BounceChecker())->detectErrorCode($body);
                $diagnosticCode = (new BounceChecker())->detectDiagnosticCode($body);
          }
```

logic : I am checking for Status : 5.x.x | 4.x.x in the email body and next searching for Diagnostic-Code:

so above is the standard DSN I found.
I have tested the above with Gmail and Outlook it's working fine, not sure about other Email Service Providers.

kindly let me know your input.
