### ISSUE TITLE
imap IDLE support for real time notifications

### ISSUE THREAD

**Issue by NikiSchlifke** [Webklex/laravel-imap#185]
**Is your feature request related to a problem? Please describe.**
As it stands now using laravel-imap I am using the laravel scheduler to look for new messages every minute. This works fine, however it requires additional setup and introduces up to 60 seconds extra latency when not really needed.

**Describe the solution you'd like**
Modern mail daemons pretty much all support the IDLE command to let the client leave the TCP connection open and be notified in real time of any new messages.

**Describe alternatives you've considered**
I guess increasing the polling interval into seconds would reduce the latency too, not really practical though.

**Additional context**
https://en.wikipedia.org/wiki/IMAP_IDLE
https://www.limilabs.com/blog/imap-idle
https://tools.ietf.org/html/rfc2177

**Comment by Webklex** [comment]
Solved with v2.0.0: https://github.com/Webklex/laravel-imap#idle
