### ISSUE TITLE
Add Timeout config value so we can reduce or increase the time that the application spends connecting before returning an exception

### ISSUE THREAD

**Issue by BrunMartins** [Webklex/laravel-imap#186]
**Is your feature request related to a problem? Please describe.**
I really require being able to set a timeout and I also really need to use your library.

**Describe the solution you'd like**
Define a CONNECTION_TIMEOUT config value along with all the other values.

**Describe alternatives you've considered**
Have tried to user the php script timeout options but to no avail.

**Additional context**

**Comment by Webklex** [comment]
Hi @BrunMartins  ,
please update to [v. 1.3.1](https://github.com/Webklex/laravel-imap/releases/tag/1.3.1) :)
