### ISSUE TITLE
imap_open(): Couldn't open stream {outlook.office365.com:993/imap/ssl}

### ISSUE THREAD

**Issue by rohit-2018** [Webklex/laravel-imap#187]
ERROR: imap_open(): Couldn't open stream {outlook.office365.com:993/imap/ssl}

Retrying PLAIN authentication after AUTHENTICATE failed.; Retrying PLAIN authentication after AUTHENTICATE failed.; Can not authenticate to IMAP server: AUTHENTICATE failed. {"exception":"[object] (Webklex\\IMAP\\Exceptions\\ConnectionFailedException(code: 0): imap_open(): Couldn't open stream {outlook.office365.com:993/imap/ssl}. Retrying PLAIN authentication after AUTHENTICATE failed.; Retrying PLAIN authentication after AUTHENTICATE failed.; Can not authenticate to IMAP server: AUTHENTICATE failed. at /var/www/html/ats1/api-pms/vendor/webklex/laravel-imap/src/IMAP/Client.php:221

**Comment by jimmY276** [comment]
show me your code i will help you

**Comment by poseidonphp** [comment]
> show me your code i will help you

Any chance you could post the solution?

**Comment by Webklex** [comment]
Hi @rohit-2018 @poseidonphp ,
please take a look at these issues: #153#100 #78.

So far it could be caused by to many things. Please try to provide some more information (code samples, call stacks, etc)  in order to figure things out :)

Best regards

**Comment by yojann96** [comment]
how can i fix: imap_open(): Couldn't open stream {outlook.office365.com:993/imap/ssl}

**Comment by maatinito** [comment]
So far, IF you have a shared mailbox, the parameters for the user name should be something like user@domain.com/sharedmailboxname like john.smith@domain.com\info.
But imap_open failed to authenticate. 
The only solution I've found was to patch the getAddress() function in Client.php
`
        $slash = strpos($this->username,'\\');
        if ($slash > 0) {
            $address .= '/authuser=' . substr($this->username,0,$slash);
            $address .= '/user=' . substr($this->username,$slash+1);
        }
        $address .= '}';
` 
==> address becomes `{outlook.office.com:993/imap/ssl/authuser=john.smith@domain.com/user=info}`
