### ISSUE TITLE
outlook.office365.com different function issue

### ISSUE THREAD

**Issue by venkatesh-php** [Webklex/laravel-imap#189]
outlook.office365.com host not giving proper result while using unseen(), whereSince(), and whereOn() function.Its working all() function only

**Comment by dbronson4672** [comment]
I can confirm that I am having the same issue

**Comment by Webklex** [comment]
Hi @venkatesh-php ,
could you please specify "not giving proper result"? :)

Best regards

**Comment by venkatesh-php** [comment]
Hi @Webklex 
The Query return empty results while using unseen(), whereSince(), and whereOn().

Thank you for your Response.

**Comment by Webklex** [comment]
Hi @venkatesh-php ,
please share some code - specially the part where you build your search query.

Best regards

**Comment by venkatesh-php** [comment]
hi @Webklex 
Here is the sample code 

```
use Webklex\IMAP\Client;
$oClient = new Client([
       'host'          => outlook.office365.com,
         'port'          => 993,
         'encryption'    => 'ssl',
          'validate_cert' => true,
          'username'      => userName,
           'password'      => Password,
           'protocol'      => 'imap'
          ]); 
     
      $oClient->connect();
       $aFolder = $oClient->getFolder('INBOX');
       $aMessage = $aFolder->query()->unseen()->markAsRead()->get();
or
 $aMessage = $aFolder->query()->whereSince()->markAsRead()->get();
or
 $aMessage = $aFolder->query()->whereOn()->markAsRead()->get();
```

$aMessage is giving empty results.

 $aMessage = $oFolder->messages()->all()->get();

working fine.

Thank You

**Comment by Webklex** [comment]
Hi @venkatesh-php ,
what happens if you parse query() a `null`?
```php
$aMessage = $aFolder->query(null)->whereOn()->markAsRead()->get();
```

Best regards

**Comment by venkatesh-php** [comment]
Hi @Webklex 
Thank you so much, its working in above all functions. 
currently i'm using 1.2.9 version. i'll update now.
Thank you.

**Comment by Webklex** [comment]
Hi @venkatesh-php ,
thats great :)

**Comment by udibagas** [comment]
Save my day. Thx a alot! :)
