### ISSUE TITLE
Implode error

### ISSUE THREAD

**Issue by dansleboby** [Webklex/laravel-imap#19]
All details in picture,

![image](https://user-images.githubusercontent.com/4716382/30092464-1d608544-928d-11e7-8af1-23403d4e98ba.png)

**Comment by Webklex** [comment]
Hi,
I just merged your pull request. I'll release a new version in a few hours. Thanks again for your contribution!

**Comment by Webklex** [comment]
Ref. to new version: [1.0.3.2](https://github.com/Webklex/laravel-imap/releases/tag/1.0.3.2)
