### ISSUE TITLE
Hi! Can someone explain to me how to reply to specified email ? Is this feature available ?  

### ISSUE THREAD

**Issue by Djurdjijan** [Webklex/laravel-imap#190]
Please be aware that these issues will be closed if inactive for more then 14 days :)

**Comment by Webklex** [comment]
Hi @Djurdjijan ,
the "reply to" functionality is always provided by the client. This library isn't designed to send mails please head over to https://laravel.com/docs/5.8/mail for more on sending an emails :)

Best regards
