### ISSUE TITLE
Signature parsing

### ISSUE THREAD

**Issue by codematiq** [Webklex/laravel-imap#191]
**Posibility to exclude signature in messages**
Would be a great feature to be able ignore whole signature or attachments in signatures.

Very often signatures contain company logos, award banners etc. That is being included in Attachments. Most of the times i do not want to fetch those. 

So methods to get attachment ->excludeSignature(true/false); would be awesome.

**Comment by Webklex** [comment]
Hi @rodau ,
signature parsing might be possible if everyone would use the correct seperator "---" but that's not the case. However you can already disable the attachment fetching by using something like this:
```php
/** @var \Webklex\IMAP\Folder $folder */
$folder->query()->fetchAttachment(false)->leaveUnread()->get();
```

best regards
