### ISSUE TITLE
Failed to parse time string

### ISSUE THREAD

**Issue by mahoho** [Webklex/laravel-imap#192]
Hello!
I have felt with a crashing on dates:
DateTime::__construct(): Failed to parse time string (Mon, 28 1 14:6:5-0500) at position 5 (2): Unexpected character.

Format is very confusing and I think it will be nice that fetching will simply skip those messages and not crashing whole process.

OS: Windows,
PHP 7.2 x64

**Comment by Webklex** [comment]
Hi @mahoho ,
Im always amazed to see so many possible ways to srew up a date string^^ However I think a date is not trivial and should fail hard if it can't be passed. Hoever I see your point and think the correct way would be to raise a custom exception such as InvalidMessageDateException::class or so. I will incude it within the next release.

**Comment by Webklex** [comment]
Hi @mahoho ,
please update to [v. 1.3.0](https://github.com/Webklex/laravel-imap/releases/tag/1.3.0) :)
