### ISSUE TITLE
Unable to get unseen message

### ISSUE THREAD

**Issue by INattivo** [Webklex/laravel-imap#193]
Dear,
i'm tryng to select all unseen message from a specific folder, but method whereseen and whereunseen not working.

$aMessage = $oClient->getFolder($mailFolder)->query()->whereUnseen()->get();

someone can tell me why of this behavior?
Thanks

**Comment by gotroch** [comment]
I can confirm this. $oFolder->query()->unseen()->get() return nothing.

@INattivo , have you somehow sort it out?

**Comment by Webklex** [comment]
Hi @INattivo,
just to make sure, please verify that there is an actual "unseen" message available on the server. However if there is and you still get this behavior please tell me a bit more about your setup. Such as your config file (without any personal information!) and some sample code :)

Best regards

**Comment by dbronson4672** [comment]
Try 
$oFolder->query(null)->unseen()->get()
