### ISSUE TITLE
get Message Body 

### ISSUE THREAD

**Issue by ColinDT76** [Webklex/laravel-imap#195]
**Describe the bug**
When looping through messages on the server the message body always returns empty string. I am connecting to a POP3 server

**To Reproduce**
Followed example in the REPO:

```php
//Connect to the IMAP Server
$oClient->connect();

//Get all Mailboxes
/** @var \Webklex\IMAP\Support\FolderCollection $aFolder */
$aFolder = $oClient->getFolders();

//Loop through every Mailbox
/** @var \Webklex\IMAP\Folder $oFolder */
foreach($aFolder as $oFolder){

    //Get all Messages of the current Mailbox $oFolder
    /** @var \Webklex\IMAP\Support\MessageCollection $aMessage */
    $aMessage = $oFolder->messages()->all()->get();
    
    /** @var \Webklex\IMAP\Message $oMessage */
    foreach($aMessage as $oMessage){
        echo $oMessage->getSubject().'<br />';
        echo 'Attachments: '.$oMessage->getAttachments()->count().'<br />';
        echo $oMessage->getHTMLBody(true);
        
        //Move the current Message to 'INBOX.read'
        if($oMessage->moveToFolder('INBOX.read') == true){
            echo 'Message has ben moved';
        }else{
            echo 'Message could not be moved';
        }
    }
}
```

Method: getHTMLBody always returns blank
getTextBody returns black

Message data is in the header

Webklex\IMAP\Message Object ( [client:Webklex\IMAP\Message:private] => Webklex\IMAP\Client Object ( [connection] => Resource id #13 [host] => smtp.mailtrap.io [port] => 1100 [protocol] => pop3 [encryption] => [validate_cert] => 1 [username] => xxxxxxxx [password] => xxxxxxxx [read_only:protected] => [activeFolder:protected] => Webklex\IMAP\Folder Object ( [client:protected] => Webklex\IMAP\Client Object *RECURSION* [path] => {smtp.mailtrap.io:1100/pop3}INBOX [name] => INBOX [fullName] => INBOX [children] => Array ( ) [delimiter] => / [no_inferiors] => 1 [no_select] => [marked] => [has_children] => [referal] => ) [connected:protected] => 1 [errors:protected] => Array ( ) [validConfigKeys:protected] => Array ( [0] => host [1] => port [2] => encryption [3] => validate_cert [4] => username [5] => password [6] => protocol ) ) [uid] => 1 [fetch_options] => 1 [fetch_body] => 1 [fetch_attachment] => 1 [fetch_flags] => 1 [msglist] => 0 [msgn] => 1 [header] => Message-ID: Date: Fri, 15 Feb 2019 15:34:22 +0000 Subject: message core test - 15:34:22 From: Example To: test@test.com MIME-Version: 1.0 Content-Type: text/html; charset=utf-8 Content-Transfer-Encoding: quoted-printable =
Body of new Email From System

[header_info] => [raw_body] => [message_id] => d68863922af4af55b9aea0dd9728909b@swift.generated [message_no] => 1 [subject] => message core test - 15:34:22 [references] => [date] => Carbon\Carbon Object ( [date] => 2019-02-15 15:34:22.000000 [timezone_type] => 1 [timezone] => +00:00 )

**Comment by Webklex** [comment]
Hi @ColinDT76 ,
are you fetching an html or text email?
If you are trying to fetch a text mail, please try using `$oMessage->getTextBody()` instead :)

Best regards
