### ISSUE TITLE
How to mark as unread to a message

### ISSUE THREAD

**Issue by jitendrarn86** [Webklex/laravel-imap#196]
Hi,
how to mark as unread to a particular message.

Thanks

**Comment by Webklex** [comment]
Hi @jitendrarn86 ,
here is a small example:

```php
/** @var $oClient \Webklex\IMAP\Client */
$oClient = \Webklex\IMAP\Facades\Client::account('default');
$oClient->connect();

/** @var \Webklex\IMAP\Folder $folder */
$folder = $oClient->getFolder('INBOX');

/** @var \Webklex\IMAP\Message $message */
$message = $folder->getMessages()->first();

/** Add a flag
 *  supported flags: recent, flagged, answered, deleted, seen, draft
 */
$message->setFlag('SEEN');

$oClient->expunge();

/** @var \Webklex\IMAP\Support\FlagCollection $flags */
$flags = $message->getFlags();

/** Remove a flag
 *  supported flags: recent, flagged, answered, deleted, seen, draft
 */
$message->unsetFlag('SEEN');
$oClient->expunge();

$flags = $message->getFlags();
```

Best regards

**Comment by 91Abdullah** [comment]
@Webklex why do you use expunge() since in documentation it is written as "Delete all messages marked for deletion"

**Comment by Webklex** [comment]
Hi @91Abdullah ,
expunge() has to be called in order to perform the action on the mail server side. If you don't call expunge the server wont save any changed flags. The documentation might be incomplete but yes expunge () also "deletes" any message marked/flagged to be deleted :)

**Comment by 91Abdullah** [comment]
@Webklex thanks for the clarification. Kudos to you for such an awesome library! :)

**Comment by eugenevdm** [comment]
My sincere compliments on this package. Combining IMAP with Laravel Collection's makes it super powerful!
