### ISSUE TITLE
Missing argument 2 error

### ISSUE THREAD

**Issue by momoxi** [Webklex/laravel-imap#198]
Hi,

Thank you for this useful library. But I have a error message trying to get the email using the basic example. I received the following error message:

Missing argument 2 for Webklex\IMAP\Query\Query::Webklex\IMAP\Query\{closure}()

It seems to reported in this line:
```php
$aMessage = $oFolder->query()->all()->get();
```

I also tried:
```php
$aMessage = $oFolder->query()
->where([['FROM', 'xxx@xxx.com']])
->get();

```
But neither could work.

I am using Laravel 5.0, php 5.5, laravel-imap: 1.2

Is that because the version is not compatible?

Thank you for your help,
Jessie

**Comment by Webklex** [comment]
Hi @momoxi ,
are you using v1.2.9? 

So far it could be caused by a lot of things. Could you provide some more information such as a bigger code sample and perhaps a stack trace if possible? :)

Best regards

**Comment by momoxi** [comment]
Thank you. Bellow is how I use the Client:

```
<?php

namespace App\Repositories\Imap;

use Webklex\IMAP\Facades\Client;

class ImapGmailRepository
{
    private static $instance;

    public function __construct()
    { }

    public static function getInstance()
    {
        self::$instance = new self();
        return self::$instance;
    }

    public function getEmails()
    {
        $emails = [];

        $oClient = Client::account('default');
        /* Alternative by using the Facade
        $oClient = Webklex\IMAP\Facades\Client::account('default');
        */

        //Connect to the IMAP Server
        $oClient->connect();

        //Get all Mailboxes
        /** @var \Webklex\IMAP\Support\FolderCollection $aFolder */
        $oFolder = $oClient->getFolder('INBOX');
        $oFolder->getMessages()->each(function($oMessage) use ($emails) {
            /** @var \Webklex\IMAP\Message $oMessage */
            $emails[] = [
                'subject' => $oMessage->subject
            ];
        });

        return $emails;
    }
}
```

Stack trace:
Webklex\IMAP\Exceptions\GetMessagesFailedException: Missing argument 2 for Webklex\IMAP\Query\Query::Webklex\IMAP\Query\{closure}() in /innovated/public/service/vendor/webklex/laravel-imap/src/IMAP/Query/Query.php on line 189 Call Stack #TimeMemoryFunctionLocation 10.0054235752{main}( )../index.php:0 20.19731989992Illuminate\Foundation\Http\Kernel->handle( )../index.php:59 30.19731990176Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter( )../Kernel.php:84 41.18056673952Illuminate\Pipeline\Pipeline->then( )../Kernel.php:115 51.18066679632call_user_func ( )../Pipeline.php:101 61.18066679744Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}( )../Pipeline.php:101 71.18986683368Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle( )../Pipeline.php:125 81.19076683504Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}( )../CheckForMaintenanceMode.php:42 91.20426699608Illuminate\Cookie\Middleware\EncryptCookies->handle( )../Pipeline.php:125 101.23766725184Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}( )../EncryptCookies.php:40 111.25126738536Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle( )../Pipeline.php:125 121.25126738616Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}( )../AddQueuedCookiesToResponse.php:36 131.26346763016Illuminate\Session\Middleware\StartSession->handle( )../Pipeline.php:125 141.29716823136Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}( )../StartSession.php:61 151.30046825624Illuminate\View\Middleware\ShareErrorsFromSession->handle( )../Pipeline.php:125 161.30346830248Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}( )../ShareErrorsFromSession.php:55 171.31196837536App\Http\Middleware\VerifyCsrfToken->handle( )../Pipeline.php:125 181.31196838048Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}( )../VerifyCsrfToken.php:23 191.31196838096call_user_func ( )../Pipeline.php:141 201.31196838208Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}( )../Pipeline.php:141 211.31206839128Illuminate\Routing\Router->dispatch( )../Kernel.php:214 221.31206839656Illuminate\Routing\Router->dispatchToRoute( )../Router.php:628 231.35737270080Illuminate\Routing\Router->runRouteWithinStack( )../Router.php:670 241.35907299208Illuminate\Pipeline\Pipeline->then( )../Router.php:703 251.35907300056call_user_func ( )../Pipeline.php:101 261.35907300120Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}( )../Pipeline.php:101 271.35907300168call_user_func ( )../Pipeline.php:141 281.35907300248Illuminate\Routing\Router->Illuminate\Routing\{closure}( )../Pipeline.php:141 291.35907300416Illuminate\Routing\Route->run( )../Router.php:701 301.35917300552Illuminate\Routing\Route->runWithCustomDispatcher( )../Route.php:134 311.36107310048Illuminate\Routing\ControllerDispatcher->dispatch( )../Route.php:204 321.36117312168Illuminate\Routing\ControllerDispatcher->callWithinStack( )../ControllerDispatcher.php:67 331.36117314032Illuminate\Pipeline\Pipeline->then( )../ControllerDispatcher.php:108 341.36127315752call_user_func ( )../Pipeline.php:101 351.36127315864Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}( )../Pipeline.php:101 361.36417320656App\Http\Middleware\LoginMiddleware->handle( )../Pipeline.php:125 371.36417320968Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}( )../LoginMiddleware.php:93 381.36417321016call_user_func ( )../Pipeline.php:141 391.36417321080Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}( )../Pipeline.php:141 401.36417321144Illuminate\Routing\ControllerDispatcher->call( )../ControllerDispatcher.php:107 411.36417321536Illuminate\Routing\Controller->callAction( )../ControllerDispatcher.php:162 421.36417321976call_user_func_array ( )../Controller.php:246 431.36417322216App\Http\Controllers\Datacheck\ExcelController->getImapGmail( )../Controller.php:246 441.36727324920App\Repositories\Imap\ImapGmailRepository->getEmails( )../ExcelController.php:2182 453.40647434560Webklex\IMAP\Folder->getMessages( )../ImapGmailRepository.php:35 464.02817483728Webklex\IMAP\Query\Query->get( )../Folder.php:225

**Comment by Webklex** [comment]
Hi @momoxi ,
please update to the latest release. I could not reproduce this error. However your provided sample does contain one error. You forgot to reference $emails :)

This schould work:
```php
namespace App\Repositories\Imap;

use Webklex\IMAP\Facades\Client;

class ImapGmailRepository {
    private static $instance;

    public function __construct() { }

    public static function getInstance() {
        self::$instance = new self();
        return self::$instance;
    }

    public function getEmails() {
        $emails = [];

        $oClient = Client::account('default');
        /* Alternative by using the Facade
        $oClient = Webklex\IMAP\Facades\Client::account('default');
        */

        //Connect to the IMAP Server
        $oClient->connect();

        //Get all Mailboxes
        /** @var \Webklex\IMAP\Support\FolderCollection $aFolder */
        $oFolder = $oClient->getFolder('INBOX');
        $oFolder->getMessages()->each(function($oMessage) use (&$emails) {
            /** @var \Webklex\IMAP\Message $oMessage */
            $emails[] = [
                'subject' => $oMessage->subject
            ];
        });

        return $emails;
    }
}
```

Best regards
