### ISSUE TITLE
Laravel 5.4 Call to undefined method Webklex\IMAP\Facades\Client::connect()

### ISSUE THREAD

**Issue by gilbert1995** [Webklex/laravel-imap#2]
Call to undefined method Webklex\IMAP\Facades\Client::connect()

in config/app.php I already add 
Webklex\IMAP\Providers\LaravelServiceProvider::class
and
'Client' => Webklex\IMAP\Facades\Client::class

And in my composer.json I have: 
 "webklex/laravel-imap": "^1.0"

Thanks for help

**Comment by Webklex** [comment]
Hi Gilbert1995,
if you are using the Facade you have to select an Account first:
`
$oClient = Webklex\IMAP\Facades\Client::account('default');
`

afterwards you can connect to the IMAP Account:
`
$oClient->connect();
`

..now you can access the account, for example get all the folders:
`
$aMailboxes = $oClient->getFolders();
`

You can define you accounts inside the imap.php config file:
`
'accounts' => [
        'default' => [.. ],
        'gmail' => [.. ],
],
`

I hope I could help. If not let me know.

**Comment by gilbert1995** [comment]
Thanks is working :)

**Comment by zakir7dipu** [comment]
`namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Webklex\IMAP\Facades\Client;


class ReceivedEmailController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function getMail(){
        $user = Auth::user();
        $domainMail = $user->domain_emails()->first();
        $mailId = $domainMail->domain_email;
        $mailPassword = $domainMail->domain_password;

        $oClient = new Client([
            'host'          => 'somehost.com',
            'port'          => 993,
            'encryption'    => 'ssl',
            'validate_cert' => true,
            'username'      => 'username',
            'password'      => 'password',
            'protocol'      => 'imap'
        ]);
        /* Alternative by using the Facade
        $oClient = Webklex\IMAP\Facades\Client::account('default');
        */

//Connect to the IMAP Server
        $oClient->connect();

//Get all Mailboxes
        /** @var \Webklex\IMAP\Support\FolderCollection $aFolder */
        $aFolder = $oClient->getFolders();

        dd($aFolder);
    }
}

I want to use multiple email that what I tried `
use Webklex\IMAP\Client;
but this one is not found
and now showing "Call to undefined method Webklex\IMAP\Facades\Client::connect()"
now what should I do...............?

**Comment by Webklex** [comment]
Hi @zakir7dipu ,
please try the following:
```php
/** @var \Webklex\PHPIMAP\Client $client */

$client = \Webklex\IMAP\Facades\Client::make([
    'host'          => 'somehost.com',
    'port'          => 993,
    'encryption'    => 'ssl',
    'validate_cert' => true,
    'username'      => 'username',
    'password'      => 'password',
    'protocol'      => 'imap'
]);
```

If you are still experience any problems, please go ahead and create a new issue [here](https://github.com/Webklex/laravel-imap/issues/new/choose) or [here](https://github.com/Webklex/php-imap/issues/new/choose) depending on the issue. 

Additional information:
- https://www.php-imap.com/frameworks/laravel/facade
- https://www.php-imap.com/api/client-manager
- https://www.php-imap.com/examples/getting-started

Best regards,
