### ISSUE TITLE
getAttachments() returns 0 all the time

### ISSUE THREAD

**Issue by klukiyan** [Webklex/laravel-imap#200]
**Describe the bug**
Trying to use `getAttachments()` but getting empty array or 0 on `->count()`

**To Reproduce**
```
$aMessage = $oClient->getFolder('INBOX')->query(null)->whereText('Weekly SIT Report TOP BG')->setFetchBody(false)->setFetchAttachment(true)->get();
        
        
        foreach ($aMessage as $oMessage) {
            // echo $oMessage->getHTMLBody(true);
            echo $oMessage->getSubject(true);
            echo 'Attachments: '.$oMessage->getAttachments()->count().'<br />';
            // echo $oMessage->getHtmlBody(true);
        }
        dd($aMessage);
```

**Expected behavior**
Expecting to get attachments. But can't :(

**Desktop / Server (please complete the following information):**
 - OS: windows
- PHP: 5.7
 - Version : 1.4.0

**Comment by Webklex** [comment]
Hi @klukiyan ,
please note that an attachment is sort of part of the mail body - therefore you have to fetch the  body as well :)
```php
$aMessage = $oClient->getFolder('INBOX')->query(null)->whereText('Weekly SIT Report TOP BG')->setFetchBody(true)->setFetchAttachment(true)->get();
```
..or something like this:
```php
$aMessage = $oClient->getFolder('INBOX')->query(null)->text('Weekly SIT Report TOP BG')->get();
```

Best reagrds

**Comment by klukiyan** [comment]
Tried it. but still no results

**Comment by Webklex** [comment]
But you get a Mail right? So `dd($aMessage->first()->subject); ` returns not null and isn't dying, correct? :)

What type of attachment are you expecting? Could it be some sort of "inline" attachment? If so you would probably find them inside the body (html or text).

**Comment by klukiyan** [comment]
Yes, but attachments were empty.
I've tried your second option completely removing these 2 parts: `->setFetchBody(true)->setFetchAttachment(true)` and got the attachments working :)
```
RE: Weekly SIT Report TOP BG Iberia - Week 16Attachments: 20
Weekly SIT Report TOP BG Iberia - Week 11Attachments: 8
```
Don't know what could have been wrong...

**Comment by klukiyan** [comment]
thank you :)

**Comment by thukuwanjiku** [comment]
> Hi @klukiyan ,
> please note that an attachment is sort of part of the mail body - therefore you have to fetch the body as well :)
> 
> ```
> $aMessage = $oClient->getFolder('INBOX')->query(null)->whereText('Weekly SIT Report TOP BG')->setFetchBody(true)->setFetchAttachment(true)->get();
> ```
> 
> ..or something like this:
> 
> ```
> $aMessage = $oClient->getFolder('INBOX')->query(null)->text('Weekly SIT Report TOP BG')->get();
> ```
> 
> Best reagrds

This solution did it for me. Thank you.
