### ISSUE TITLE
Problem with subject =?UTF-8?Q?

### ISSUE THREAD

**Issue by kfijalko** [Webklex/laravel-imap#204]
Hi,
When I get subjects, sometimes I recive somthing like this "=?UTF-8?Q?Odp=3A_Re=3A_Kupi=C5=82e=C5=9B_OPEL_ZAFIRA_B_05-08_Wk=C5=82ad_lusterko_ogrzewany_lewy_=287599940574=29_od_motomatic=5Fpl?=".

Proper subject (element form header):
```
Subject: =?UTF-8?Q?Sprzeda=C5=82e=C5=9B_przedmiot_przez_Kup_Teraz_-_nr:?=
     =?UTF-8?Q?_7685895974_-_OPEL_COMBO_C_03-10_Pr=C3=B3g_prawy?=
```
Wrong subject:
```
Subject: 
     =?UTF-8?Q?Odp=3A_Re=3A_Kupi=C5=82e=C5=9B_OPEL_ZAFIRA_B_05-08_Wk=C5=82ad_lusterko_ogrzewany_lewy_=287599940574=29_od_motomatic=5Fpl?=
```

When subject is wrong decoded, first line in header has only "Subject:\r\n".

Is it bug or I need decode this subejcts by myself?
sorry for my english
Regards
Chris

**Comment by Webklex** [comment]
Hi @kfijalko ,
please provide a save dump of `$header` in Message::parseHeader() L:397.

If $header->subject is properly set it would be possible to implement a certain "filter" for these cases :)

If not there isn't much I could do(?).

Best regards

**Comment by paulocardozo** [comment]
Had any updates about that?  I'm facing this problem..

The getSubject() is returing =?utf-8?Q?Confirmaci=C3=B3n_reserva_Free_Tour_Flo?= =?utf-8?Q?rencia_Esencial_-_Buendiatours.com?=

**Comment by Webklex** [comment]
Hi @paulocardozo ,
please make sure to update to the latest release. If the issue persists, please add `webklex/php-imap` manually to your dependencies and make sure it is at least on v5.4.

If the issue still occurs, please head over to https://github.com/Webklex/php-imap/issues/new?assignees=&labels=&projects=&template=bug_report.md and provide as much information as possible. Every little bit, even if it might seem unrelated could help to solve the mystery :)

Best regards & happy coding,
