### ISSUE TITLE
excuse me  sir.I want to get the  Mail delivery time.What should I do?

### ISSUE THREAD

**Issue by jc91715** [Webklex/laravel-imap#21]

**Comment by Webklex** [comment]
Hi @jc91715 ,
of you are using something simular to my example, just call the following:

`echo $oMessage->date->Format('d.m.Y h:i');`

**Comment by Webklex** [comment]
Hi @jc91715 ,
I added new getter methods to the Message class. You can now call $oMessage->getDate(); in order to get the delivery date.

Ref. [v1.0.3.3](https://github.com/Webklex/laravel-imap/releases/tag/1.0.3.3)
