### ISSUE TITLE
Getting trouble installing it on Laravel 5.8

### ISSUE THREAD

**Issue by ascweb** [Webklex/laravel-imap#211]
I'm using PHP 7.3.1 (on OSX) and Laravel 5.8 and I got the error:

` Problem 1
    - webklex/laravel-imap 1.4.1 requires ext-imap * -> the requested PHP extension imap is missing from your system.
    - webklex/laravel-imap 1.4.0 requires ext-imap * -> the requested PHP extension imap is missing from your system.
    - Installation request for webklex/laravel-imap ^1.4 -> satisfiable by webklex/laravel-imap[1.4.0, 1.4.1].`

In My phpinfo I see IMAP is installed:

> IMAP c-Client Version | 2007f
> SSL Support | enabled
> Kerberos Support | enabled

and in php.ini I have also   extension=imap.so

Can you help me to install it ?

Thanks!

**Comment by Webklex** [comment]
Hi @ascweb ,
I assume your php-cli is missing the extension.

Please check with `php -i | grep imap` if it is acually loaded :)

Best regards

**Comment by ascweb** [comment]
Thanks for quick answer!

I got:

> Protocols => dict, file, ftp, ftps, gopher, http, https, imap, imaps, ldap, ldaps, pop3, pop3s, rtsp, smb, smbs, smtp, smtps, telnet, tftp

end 

php -v return:

> PHP 7.1.23 (cli) (built: Feb 25 2019 09:10:39) ( NTS )
> Copyright (c) 1997-2018 The PHP Group
> Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies

**Comment by ascweb** [comment]
Fixed updating $PATH in .bash_profile:

I have just add the lines:

> export PATH="/usr/local/opt/php@7.1/bin:$PATH"
> export PATH="/usr/local/opt/php@7.1/sbin:$PATH"

and refreshed the .bash_profile by

> source ~/.bash_profile

Thanks For help!  And thanks for your great work!

**Comment by japita-se** [comment]
in Centos 8 does not work
