### ISSUE TITLE
moveToFolder() not moving the message

### ISSUE THREAD

**Issue by MarouaneZizah** [Webklex/laravel-imap#214]
After retrieving the messages and processing them, when I call ```moveToFolder()``` it doesn't move the message to the specified folder, instead I need to call the method twice in order to move the message

```php
$compte = Client::account('test_inbox');

$compte->connect();

$inbox_folder = $compte->getFolder('inbox');

$messages = $inbox_folder->getMessages();

foreach ($messages as $num_message => $message)
{
    //processing the message
    $message->moveToFolder('INBOX.processed');
}
```

I noticed that the first time I call moveToFolder() the flag ```"answered"``` changes to 1, only after the second call is when the message get moved to the new folder.

 - OS X El Capitan 10.11.6
- PHP: 7.1
 - Version 1.4.1

Thanks in advance for your help.

**Comment by DasTobbel** [comment]
Getting the same error in here:
ubuntu 18.04 - lts
php 7.3
version 1.4.1

Currently calling "moveToFolder" twice to workaround that issue.
