### ISSUE TITLE
How to except connection?

### ISSUE THREAD

**Issue by ceo-zenlix** [Webklex/laravel-imap#218]
Hello!
How i can to except connection?
```php
$oClient = Client::account('default');
try {
            $oClient->connect();
        } catch (\Exception $e) {
            // fail
            return '<pre>' . $e . '</pre>';
        }
```
Exception return nothing.

**Comment by Webklex** [comment]
Hi @ceo-zenlix ,
`Client::connect() ` can throw a `ConnectionFailedException` exception. The exception message is identical with the original exception but contains any potential imap errors as well.

```php
$oClient = Client::account('default');
try {
    $oClient->connect();
} catch(ConnectionFailedException $e) {
    dd($e->getMessage());
}
```

Best regards

**Comment by jagoanmamah** [comment]
dosn't work with this code

`$oClient = Client::account('default');
try {
    $oClient->connect();
} catch(ConnectionFailedException $e) {
    dd($e->getMessage());
}`

**Comment by Webklex** [comment]
@jagoanmamah what did you get instead?
