### ISSUE TITLE
Can not authenticate to IMAP server: [CLOSED] IMAP connection broken (authenticate) 

### ISSUE THREAD

**Issue by samfrjn11** [Webklex/laravel-imap#22]
Hi,

I'm running into this issue and I'm not sure what exactly goes wrong.

So I'm using this package to read the inbox of a certain mailbox. My script loops over every message that has been sent to the mailbox and then processes it (delete msg if not recognized or put into database if subject is known and if sender host is known). 

I'm using a cronjob for this together with Laravels scheduler. The cronjob calls `"\Illuminate\Support\Facades\Artisan::call('schedule:run');"` every minute. In the schedule I have `$schedule->command('support:process-inbound-emails')->everyMinute();`

The script works perfect, but sometimes (at random times) I get following error in my errorlogs:

> Couldn't open stream {imap.mailprotect.be:143/imap}. Can not authenticate to IMAP server: [CLOSED] IMAP connection broken (authenticate) 

The script runs 24/7, every minute. So basically 1440 (24*60) times a day. Out of 1440, it fails 'only' 7 to 30 times with the error mentioned above. 

Does anyone know what could be the cause of this error?

**Comment by Webklex** [comment]
Hi @samfrjn11 ,
I guess your mail server is rejecting the given credentials from time to time. Do you have any access to the server side mail log?

**Comment by samfrjn11** [comment]
Hi @Webklex,

Thanks for the quick reply! I'm going to check with my hosting provider (Combell.com).

I'm also having contact with them for over a week to determine where the problem is coming from.

I also believe the problem is on THEIR side, not on this package in paticular, since laravel-imap is basically just a wrapper around php's IMAP functions.

I asked for logs, we'll see.

From previous mailings, my contact found this:
`[Thu Sep 21 09:13:44.223507 2017] [error] [pid 30092] mod_proxy_fcgi.c(745): [client 103.78.227.13:15104] AH01071: Got error 'Primary script unknown\n'
        [Thu Sep 21 09:19:49.970991 2017] [error] [pid 8193] mod_proxy_fcgi.c(851): (103)Software caused connection abort: [client 178.117.87.231:11936] AH01075: Error dispatching request to : (passing brigade to output filters)`

**Comment by Webklex** [comment]
So you are using apache2 in combination with php-fpm?

**Comment by samfrjn11** [comment]
@Webklex going to pass this to my contact. Thank you, i'll keep you updated! :)

**Comment by samfrjn11** [comment]
Contact said the php-fpm was not the problem. They're still searching for solutions

**Comment by samfrjn11** [comment]
Finally they found a solution! Apparently something was wrong on one of the backend nodes on BEM. The problem only occurred to me because I did quite a lot of requests.

**Comment by Hardik0078** [comment]
Hi,
the same issue occurs to me i am using this package to read mail from the mailbox but gives the below error

Webklex\IMAP\Exceptions\MailboxFetchingException: User is authenticated but not connected.

Webklex\IMAP\Exceptions\ConnectionFailedException: imap_open(): Couldn't open stream {smtp.office365.com:993/IMAP/ssl}. Can not authenticate to IMAP server: [CLOSED] IMAP connection broken (authenticate)

**Comment by samfrjn11** [comment]
> Hi, the same issue occurs to me i am using this package to read mail from the mailbox but gives the below error
> 
> Webklex\IMAP\Exceptions\MailboxFetchingException: User is authenticated but not connected.
> 
> Webklex\IMAP\Exceptions\ConnectionFailedException: imap_open(): Couldn't open stream {smtp.office365.com:993/IMAP/ssl}. Can not authenticate to IMAP server: [CLOSED] IMAP connection broken (authenticate)

You need to connect to outlook.office365.com not to smtp.office365.com,
