### ISSUE TITLE
Check Language Folder IMAP

### ISSUE THREAD

**Issue by jagoanmamah** [Webklex/laravel-imap#220]
Each language has a different folder name, how do I check the language used?

**Comment by Webklex** [comment]
Hi @jagoanmamah ,
could you explain your question / problem a bit further? 

If available, please add some code samples as well :)

Best regards

**Comment by jagoanmamah** [comment]
when i connect IMAP with english language settings i get a folder containing email, but when i change the language settings to another language i get an empty folder

**Comment by Webklex** [comment]
@jagoanmamah just a few questions:
- Where and how do you change the language? 
- Does the folder name changes, if you change your language? 
  - If so, does your mailprovider account for that? 
- Did you verify you are fetching an existing mailbox/folder? 
- Can you provide an example?

Best regards
