### ISSUE TITLE
One.com webmail fetching the folders throw new MailboxFetchingException($this->getLastError()) exception

### ISSUE THREAD

**Issue by assadullahchaudhry** [Webklex/laravel-imap#221]
First of all, thanks for this awesome package. I used this package in my Laravel 5.8 project and it's working perfectly fine with Outlook, Gmail and some other famous email services but when I try to use one.com webmail, it throws the following exception.

`throw new MailboxFetchingException($this->getLastError());`

It allows me to log in to my one.com webmail account but throws the specified exception when I try to fetch the mail folders.

**Comment by Webklex** [comment]
Hi @assadullahchaudhry,
please provide the actual error message. MailboxFetchingException just indicates that something went wrong while fetching a Mailbox.

Best regards

**Comment by assadullahchaudhry** [comment]
Here it is.

![image](https://user-images.githubusercontent.com/12120726/61429019-0f397100-a93e-11e9-89f3-393b23e8f7b7.png)

**Comment by assadullahchaudhry** [comment]
I encounter another issue. I used `netcup` and imap and smtp host are mxf960.netcup.net. It works OK but it does not fetch all the mailbox folders. It only fetches inbox and spam but not sent the items and some other folders.

**Comment by Webklex** [comment]
How is the string "Sent Items" escaped? I guess you have to escape the space? Try using something like this "Sent\ Items". I'll hope it helps :)

**Comment by assadullahchaudhry** [comment]
This is how I'm trying to fetch the folders `$aFolder = $oClient->getFolders();`. Do you think I should escape the folder names here? If you think so then how?

**Comment by tchoblond59** [comment]
Hi. I have the same issue with enterprise office365 account.
In the IMAP/Client.php the search of children in getFolders method throw this exception

```
if(is_array($items)){
            foreach ($items as $item) {
                $folder = new Folder($this, $item);

                if ($hierarchical && $folder->hasChildren()) {
                    $pattern = $folder->full_name.$folder->delimiter.'%';

                    $children = $this->getFolders(true, $pattern);
                    $folder->setChildren($children);
                }

                $folders->push($folder);
            }
```
If you comment the children part it's not throwing exception.
Do you think that it's a bug or maybe i did something wrong ?
Thanks.

**Comment by thomeijken** [comment]
Hi,
I'm having the same issue using my office 365 accounts.

```
$mailClient->connect();
var_dump($mailClient->isConnected());
$folders = $mailClient->getFolders();

```
This gives the output below, as you can see the client is connected, but is unable to get the folders.

```
bool(true)

Time: 2.38 seconds, Memory: 18.00 MB

There was 1 error:

1) Tests\Feature\EmailReadWorkerBlockTest::testReadEmail
Webklex\IMAP\Exceptions\MailboxFetchingException: 

/Users/thomeijken/Documents/Development/harmonizer/vendor/webklex/laravel-imap/src/IMAP/Client.php:377
/Users/thomeijken/Documents/Development/harmonizer/vendor/webklex/laravel-imap/src/IMAP/Client.php:368
/Users/thomeijken/Documents/Development/harmonizer/app/Harmonizer/WorkerBlocks/WorkerBlockEmailRead.php:52
/Users/thomeijken/Documents/Development/harmonizer/tests/feature/EmailReadWorkerBlockTest.php:37
```

I'm using the following connection parameters:
```
"protocol" => "imap",
"host" => "outlook.office365.com",
"port" => 993,
"validate_cert" => false,
"username" => "<email address>",
"password" => "<password>",
"encryption" => "ssl"
```

**Comment by nitinaisz** [comment]
I got same problem on Office 365 as well.
Here is how I managed to fix it
```php
$hierarchical = false;
$oClient->getFolders($hierarchical);
```
or
```php
$oClient->getFolders(false);
```
