### ISSUE TITLE
Can't open mailbox {sample.com:995/pop3/ssl}INBOX.name: invalid remote specification

### ISSUE THREAD

**Issue by k3youmin** [Webklex/laravel-imap#222]
Please be aware that these issues will be closed if inactive for more then 14 days :)
IMAP_HOST=sample.com
IMAP_PORT=995
IMAP_ENCRYPTION=ssl
IMAP_VALIDATE_CERT=true
IMAP_USERNAME=mark.valencia@sample.com
IMAP_PASSWORD=
IMAP_DEFAULT_ACCOUNT=default
IMAP_PROTOCOL=pop3

MAIL_DRIVER=smtp
MAIL_HOST=mail.sample.com
MAIL_PORT=26
MAIL_USERNAME=it.helpdesk@sample.com
MAIL_PASSWORD=
MAIL_ENCRYPTION=null

**Comment by Webklex** [comment]
Hi @k3youmin ,
this error indicates that you are giving the server stuff it doesn't understand :)

Perhaps your folder delimiter isn't "." but "/" instead? Or your server doesn't support ssl but tls? 

You can change the default delimiter in config/imap.php L:118. Do you have access to the mailserver logs?

**Comment by k3youmin** [comment]
I don't have access in mailserver logs. what do you mean "Perhaps your folder delimiter isn't "." but "/" instead?"

**Comment by Webklex** [comment]
You used `INBOX.name` as inbox - in this case "." is the delimiter :)

**Comment by k3youmin** [comment]
'options' => [
        'delimiter' => '/',
        'fetch' => \Webklex\IMAP\IMAP::FT_UID,
        'fetch_body' => true,
        'fetch_attachment' => true,
        'fetch_flags' => true,
        'message_key' => 'id',
        'fetch_order' => 'asc',
        'open' => [
            // 'DISABLE_AUTHENTICATOR' => 'GSSAPI'
        ],
        'decoder' => [
            'message' => [
                'subject' => 'utf-8' // mimeheader
            ],
            'attachment' => [
                'name' => 'utf-8' // mimeheader
            ]
        ]
    ],


here's my code

**Comment by Webklex** [comment]
Those are your settings, not the "code" ;)

According to your settings you use "/" as delimiter but in your given error you used "." as delimiter. Please try to use "/" as delimiter instead.

**Comment by k3youmin** [comment]
#errors: array:1 [▼
    0 => "Can't open mailbox {xentromalls.com:995/pop3/ssl}INBOX/name: invalid remote specification"
  ]

same problem

**Comment by k3youmin** [comment]
Thankyou I already solved my problem and thanks in your package.
