### ISSUE TITLE
How can I query all the emails with no RE: or FWD: in subjects

### ISSUE THREAD

**Issue by k3youmin** [Webklex/laravel-imap#223]
Please be aware that these issues will be closed if inactive for more then 14 days :)

**Comment by Webklex** [comment]
If your Mailserver supports "NOT" you can use something like:
```php
$aMessage = $oFolder->query()->notSubject("RE")->get();
```

However if your provider doesn't support it you would have to filter the message collection afterwards.

**Comment by k3youmin** [comment]
what if re and fw?

**Comment by Webklex** [comment]
Exclude RE & FW:
```php
$aMessage = $oFolder->query()->notSubject("RE")->notSubject("FWD")->get();
```
