### ISSUE TITLE
Can't appendMessage to folder with appendMessage() method.

### ISSUE THREAD

**Issue by AdrianKuriata** [Webklex/laravel-imap#224]
Hello there. I have a problem with `appendMessage()` method. After trying add message to my inbox method `imap_append` showing 

```
imap_append(): internal date not correctly formatted
```

But when i copied imap_append and called like that:
```
imap_append($client->getConnection(), $client->getFolderPath(), $message);
```

Message is saved on my inbox. Did someone give me advice? Here is whole code:

```
        $client->connect();
        $folder = $client->getFolder('Sent');
        $message = "From: me@example.com\r\n"
            . "To: you@example.com\r\n"
            . "Subject: test\r\n"
            . "\r\n"
            . "this is a test message, please ignore\r\n";
        imap_append($client->getConnection(), $client->getFolderPath(), $message); // Working
        $folder->appendMessage($message); // Not working, showing error
```

// Edit: Ok, message is saved in inbox with `appendMessage()` - my bad, but error showing up too.

**Comment by Webklex** [comment]
Hi @AdrianKuriata ,
please try to set the date as well:
```php
$date = now()->format(''d-M-Y H:i:s O');
$oFolder->appendMessage($message, null, $date);
```

**Comment by AdrianKuriata** [comment]
Hi @Webklex 
Ok, now it's working properly, but I don't want set date if it is unneccessary. I think you should look at this problem. Thanks for your help!
