### ISSUE TITLE
pagination on emails

### ISSUE THREAD

**Issue by maralbe** [Webklex/laravel-imap#225]
Hi, I want to fetch emails from multiple email server.. and now I'm testing with gmail.
so there are many emails to receive, and I want to store body and attachments of each message..
and as you know it takes so mush time!

I test with your pagination solution to retrieve particular messages in each request.. but I configure that the pagination is on MessageCollection class.. not for emails.. I mean I have to get emails then do pagination on that collection..
I'm writing an API, so every time I have to get all messages, and then paginate on it, to get next part of emails..

its so time consuming! 
I need a solution that can help me with time performance. 
if the pagination wouldn't work here.. so please if you have a solution share it with me!

thanks with regards.

**Comment by Webklex** [comment]
Hi @maralbe ,
you can paginate a query as well :)

Take a look at: https://github.com/Webklex/laravel-imap/blob/master/src/IMAP/Query/Query.php#L236

**Comment by maralbe** [comment]
Hi @Webklex 
thanks for your reply.. I test pagination in my code.. and it returns data just when  I set `$page = 1` in other values it returns an empty object..

this is my sample code:

  ```
$client = $this->getClient();
$folder = $client->getFolder('INBOX');
$messages = $folder->query()->paginate($perPage, $page);
 ```

**Comment by maralbe** [comment]
and also I don't want to get messages from mail server, that I received before.. because I stored them in my service each time that I'm fetching emails..

if there was a solution.. in query.. like `whereNotIn('uid', $uids)` I could handle it.. but now I have no idea how to handle it

**Comment by dragonfire1119** [comment]
> Hi @Webklex
> thanks for your reply.. I test pagination in my code.. and it returns data just when I set `$page = 1` in other values it returns an empty object..
> 
> this is my sample code:
> 
> ```
> $client = $this->getClient();
> $folder = $client->getFolder('INBOX');
> $messages = $folder->query()->paginate($perPage, $page);
> ```

Where you able to resolve this?
