### ISSUE TITLE
I want to show all messages in the output folder

### ISSUE THREAD

**Issue by jacm1993** [Webklex/laravel-imap#228]
I want to show all messages in the output folder. Any example of how?

My code in the controller
 Laravel:
 $ oClient-> connect ();

        $ aFolder = $ oClient-> getFolder ('INBOX.sent');

            foreach ($ aFolder as $ oFolder)
            {
                $ aMessage = $ oFolder-> messages () -> all () -> get ();

            }

        return view ('vendor.adminlte.Mailbox.Buzon', compact ('aMessage'));

**Comment by Webklex** [comment]
Hi @jacm1993,
please take a look at the following example:
[examples/message_table.blade.php](https://github.com/Webklex/laravel-imap/blob/master/examples/message_table.blade.php)

**Comment by jacm1993** [comment]
Ok, I've seen the examples and everything. I get this error.

"Call to a member function messages() on string"

**Comment by Webklex** [comment]
Because you've made a little mistake:
```php
$oClient->connect();
$oFolder = $oClient->getFolder('INBOX.sent');
$aMessage = $oFolder->messages()->all()->get();
return view ('vendor.adminlte.Mailbox.Buzon', ['aMessage' => $aMessage]);
```

Folder::getFolder('INBOX.sent') returns an instance of a Folder and not a folder collection.

**Comment by topcoder20022** [comment]
I couldn't find answers to this problem for a long time.
The reason is why the names of folders were defined in Spanish.
I found a solution and it works now for me.

$oClient->connect();
$oFolder = $oClient->getFolder('Enviados');

Hope it helps!
