### ISSUE TITLE
Date Headers

### ISSUE THREAD

**Issue by brendanProfile** [Webklex/laravel-imap#229]
I am trying to retrieve all emails from an inbox but most of them don't have date headers. Is it possible to still retrieve them? 
Only 2 of 14 emails are coming through and the only difference is the date header.

So I basically need to be able to retrieve all emails regardless or add a date header myself to be able to pull them through.

```
$oClient = Client::account('default');
        $oClient->connect();
        $aFolder = $oClient->getFolders();
        foreach ($aFolder as $oFolder) {
            $aMessage = $oFolder->messages()->all()->get();

            foreach ($aMessage as $oMessage) {
                $address = $oMessage->getSubject(true);
                $str = $oMessage->getTextBody(true);
                echo $address . "<br>";
            }
        }
```

**Comment by Webklex** [comment]
Hi @brendanProfile ,
it doesnt matter if the date header is empty or none existsant. 

Dont forget that not every message has to have a text body. Some might only have an html body instead. How were you validating the fetched amount of messages?

**Comment by brendanProfile** [comment]
Thanks for your reply. I know that they all have a text body because the devices sending the email are incapable of sending anything else.

I am logged into my webmail account and can see there are 14 plaintext emails in the inbox.
This is the output of 
`dd($oFolder->messages()->all()->get());`
`MessageCollection {#400 ▼
  #total: 14
  #items: array:3 [▶]
}`

**Comment by Webklex** [comment]
You could try to change the message_key in your `config/imap.php` file to `number` or `list`. Perhaps they all have the same message id?

**Comment by brendanProfile** [comment]
Yes that's sorted it now thanks.
