### ISSUE TITLE
Cant show Gmail messages

### ISSUE THREAD

**Issue by alexnogueira4** [Webklex/laravel-imap#23]
When i try to use **`$oMailbox->getMessages()`** with a Gmail account on localhost the conection is lost and laravel stop. I have to kill some PHP process to can run **`php artisan serve`** again. Can somebody help?

**Comment by Webklex** [comment]
Hi @alexnogueira4 ,
so it works in your production environment but fails on your local dev setup?
Have you looked at your error log? Please provide some more details and if possible the corresponding error stack.

If you are using a default laravel setup, please take a look at the laravel log file found under storage/logs/laravel.log.

**Comment by alexnogueira4** [comment]
Hi @Webklex ,
I am using on local. Here is what i found on my log file:

`[2017-09-26 20:54:06] local.ERROR: Undefined property: stdClass::$disposition {"userId":1,"email":"alexnogueira4@gmail.com","exception":"[object] (Webklex\\IMAP\\Exceptions\\GetMessagesFailedException(code: 0): Undefined property: stdClass::$disposition at /var/www/html/a3/web/sites/a3/vendor/webklex/laravel-imap/src/IMAP/Client.php:302)
[stacktrace]
#0 /var/www/html/a3/web/sites/a3/vendor/webklex/laravel-imap/src/IMAP/Folder.php(152): Webklex\\IMAP\\Client->getMessages(Object(Webklex\\IMAP\\Folder), 'ALL', NULL)
#1 /var/www/html/a3/web/sites/a3/app/Http/Controllers/Admin/EmailsController.php(61): Webklex\\IMAP\\Folder->getMessages()`

I only have this problem using Gmail. It's like when i try to load messages only of my inbox, the problems appear. But if i delete all my other folders, i can show inbox messages.

Thanks.

**Comment by Webklex** [comment]
It seems like you are having a malformed email in your inbox. If you take a look at the Message class at line 414 and 424 you'll see that the library is trying to fetch the disposition of the given attachment. However your attachment doesn't has a disposition.

Please refer to [https://www.ietf.org/rfc/rfc2183.txt](https://www.ietf.org/rfc/rfc2183.txt) for more information on RFC2183.

A quick and easy fix could be to remove the message manually from your inbox.
