### ISSUE TITLE
timeout with outlook mail server

### ISSUE THREAD

**Issue by maralbe** [Webklex/laravel-imap#230]
Hi,
I'm trying to connect to outlook account to retrieve new emails.. using imap config, but I receive timeout error even when I'm trying to get one email!

my code was OK with gmail mail server, and I could get max 30 emails each time.. but with outlook I don't know what did I miss!

this is part of my code:

````
$client = new Client([
            'host'          => "outlook.office365.com",
            'port'          => 993,
            'encryption'    => "tls",
            'validate_cert' => true,
            'username'      => $username,
            'password'      => $password,
            'protocol'      => "imap"
        ]);

$client->connect();
$folder = $client->getFolder('INBOX');
$messages = $folder->query()->limit(1)->get();
````

**Comment by Webklex** [comment]
Hi @maralbe ,
please ta a look at #100 and #189 .

Additional informtion:
https://docs.microsoft.com/en-us/exchange/troubleshoot/connecting-to-the-service/incorrect-settings

**Comment by maralbe** [comment]
thanks for your reply @Webklex 

my problem solved, but it wasn't because of the `UTF-8` charset, in `imap_search`, actually I was getting the error while connecting to server not searching.. and it solved when I changed `encryption` from `tls` to `ssl`!
and now it works even without setting null for charset in imap_search.

````
$client = new Client([
            'host'          => "outlook.office365.com",
            'port'          => 993,
            'encryption'    => "ssl",
            'validate_cert' => true,
            'username'      => $username,
            'password'      => $password,
            'protocol'      => "imap"
        ]);

$client->connect();
$folder = $client->getFolder('INBOX');
$messages = $folder->query()->limit(1)->get();
````

thanks.
