### ISSUE TITLE
.csv attachement is not processed

### ISSUE THREAD

**Issue by yranazarov** [Webklex/laravel-imap#231]
**Description**
If message has .CSV attachement, method getAttachements() don't return it

**To Reproduce**
Get message with .csv attachement or with multiple attachements, with one .csv and try to get them all.

**Expected behavior**
.csv attachement shold be processed

**Screenshots**
N/A

**Desktop / Server (please complete the following information):**
 - OS: Win 10
- PHP: 7.2

**Comment by clyall** [comment]
We experienced this issue today as well. 

We were able to fix it by changing the if statement in src/IMAP/Message.php (669):

Original:
`if ($structure->subtype == "PLAIN") {`

Fixed:
`if ($structure->subtype == "PLAIN" || $structure->subtype == "CSV") {`
