### ISSUE TITLE
How to differentiate seen and unseen message?

### ISSUE THREAD

**Issue by payalpandav1** [Webklex/laravel-imap#233]
Please be aware that these issues will be closed if inactive for more then 14 days :)

Code : 

 $f = $oClient->getFolder('INBOX');
 $messages = $f->query()->all()->limit(10, 1)->setFetchFlags(true)
                ->setFetchBody(false)
                ->setFetchAttachment(false)->get();
 dd($messages);

I am getting 10 mails from gmail. 1 mail is not read and other 9 is read. Please help me out that how can i recognise unread mail?  there is seen flag is set but i am getting seen = 0 in all 10 mails. Thanks in advance.

**Comment by mr0bles** [comment]
Just read the flag

`$oMessage->getFlags()['seen']`

**Comment by payalpandav1** [comment]
After learning this package, got the below solution ;
            
$f = $oClient->getFolder('INBOX');
$oMessage = $f->getMessages("All", null, false, false, true, 5, 1);
dd($oMessage);

**Comment by mr0bles** [comment]
> After learning this package, got the below solution ;
> 
> $f = $oClient->getFolder('INBOX');
> $oMessage = $f->getMessages("All", null, false, false, true, 5, 1);
> dd($oMessage);

If you need a query, you have a helper (unseen)
`$oMessage = $oFolder->search()->unseen()->get();`

**Comment by payalpandav1** [comment]
> > After learning this package, got the below solution ;
> > $f = $oClient->getFolder('INBOX');
> > $oMessage = $f->getMessages("All", null, false, false, true, 5, 1);
> > dd($oMessage);
> 
> If you need a query, you have a helper (unseen)
> `$oMessage = $oFolder->search()->unseen()->get();`

Yeah. But want both seen and unseen mails. I think this will return only unseen mails.

**Comment by mr0bles** [comment]
> > > After learning this package, got the below solution ;
> > > $f = $oClient->getFolder('INBOX');
> > > $oMessage = $f->getMessages("All", null, false, false, true, 5, 1);
> > > dd($oMessage);
> > 
> > 
> > If you need a query, you have a helper (unseen)
> > `$oMessage = $oFolder->search()->unseen()->get();`
> 
> Yeah. But i want both seen and unseen mails. I think this will return only unseen mails.

OPTION 1: (filter in view)
```
$oMessage = $oFolder->search()->unseen()->get();
 if($oMessage->getFlags()['seen'])
```

OPTION 2: (multiple collections)
```
$oMessageSeen = $oFolder->search()->seen()->get();
$oMessageUnseen = $oFolder->search()->unseen()->get();
```

**Comment by payalpandav1** [comment]
> > > > After learning this package, got the below solution ;
> > > > $f = $oClient->getFolder('INBOX');
> > > > $oMessage = $f->getMessages("All", null, false, false, true, 5, 1);
> > > > dd($oMessage);
> > > 
> > > 
> > > If you need a query, you have a helper (unseen)
> > > `$oMessage = $oFolder->search()->unseen()->get();`
> > 
> > 
> > Yeah. But i want both seen and unseen mails. I think this will return only unseen mails.
> 
> OPTION 1: (filter in view)
> 
> ```
> $oMessage = $oFolder->search()->get();
>  if($oMessage->getFlags()['seen'])
> ```
> 
> OPTION 2: (multiple collections)
> 
> ```
> $oMessageSeen = $oFolder->search()->seen()->get();
> $oMessageUnseen = $oFolder->search()->unseen()->get();
> ```

Yes. That's cool.
