### ISSUE TITLE
How to fix this pagination?

### ISSUE THREAD

**Issue by k3youmin** [Webklex/laravel-imap#236]
![image](https://user-images.githubusercontent.com/15870174/63065577-24072580-bf39-11e9-8260-ccd1a296a85f.png)

![image](https://user-images.githubusercontent.com/15870174/63065567-1ce01780-bf39-11e9-8bba-305423e03397.png)

**Comment by Webklex** [comment]
Hi @k3youmin,
take a look at the generated html (inside your browser). You probably have no style to support the default laravel pagination. At the end you have to style a ul -> li -> a dom tree :)
