### ISSUE TITLE
Subject with quote/special characters

### ISSUE THREAD

**Issue by rad027** [Webklex/laravel-imap#237]
Im having issue selecting specific email message. Im using `$oFolder->query()->subject($subject)->get()`  query, but the problem is, Its not selecting because my Subject string has double quotation `"` . I tried to use `$oFolder->getMessage($id)` but the problem is it doesnt return html body.

Please help me. Thank you :)

**Comment by Webklex** [comment]
Hi @rad027 ,
could you provide some code? :)
