### ISSUE TITLE
imap fetchstructure error

### ISSUE THREAD

**Issue by taradattupreti** [Webklex/laravel-imap#238]
When a email has not content then get method of query in webklex is raising error.
![image001](https://user-images.githubusercontent.com/42542294/63441598-4e804380-c44f-11e9-9d00-fe202ba7a534.png)

**Comment by Webklex** [comment]
Hi @taradattupreti ,
thanks for your report. Please take a look at the provided ["bug report" template](https://github.com/Webklex/laravel-imap/issues/new?template=bug_report.md) and try to update your issue accordingly. 

Kind regards,

**Comment by suraj-enjay** [comment]
i have facing same issue please refer the below error and provide the proper solution:
ErrorException: imap_fetchstructure(): No body information available in vendor/webklex/laravel-imap/src/IMAP/Message.php

 - OS: [e.g. Ubuntu 22.4]
- PHP: [e.g. 8.2.7]
 - webklex/laravel-imap: "^1.4"
 - $oClient = new Client([
                        'host' => $inboundEmailImap['host'],
                        'port' => $inboundEmailImap['port'],
                        'encryption' => 'ssl',
                        'validate_cert' => $validateCertificate,
                        'username' => $inboundEmailImap['username'],
                        'password' => $inboundEmailImap['password'],
                        'protocol' => $inboundEmailImap['protocol'],
                    ]);

                    $oClient->connect();

- I got the erorr on this function :   $oFolder = $oClient->getFolder($mailboxFolder);
