### ISSUE TITLE
IMAP. GMail. SSL. No SNI provided; please fix your client

### ISSUE THREAD

**Issue by IGabor98** [Webklex/laravel-imap#239]
I get this error,

`Certificate failure for imap.gmail.com: self signed certificate: /OU=No SNI provided; please fix your client./CN=invalid2.invalid1PHP`

example of my code
```
$oClient = new \Webklex\IMAP\Client([
            'host'          => 'imap.gmail.com',
            'port'          => 993,
            'encryption'    => 'ssl',
            'validate_cert' => true,
            'username'      => 'mail@gmail.com',
            'password'      => 'password',
            'protocol'      => 'imap'
        ]);

$oClient->connect();
```
I couldn't find a solution in PHP besides ignoring certificate validation.

**Comment by fa2mm** [comment]
IGabor98, I resolved this problem via:
"validate_cert => true" was changed to "validate_cert => false" in the config

`
'gmail' => [ // account identifier
            'host' => 'imap.gmail.com',
            'port' => 993,
            'protocol' => 'imap',
            'encryption' => 'ssl',
            'validate_cert' => true,
            'username' => env('IMAP_GMAIL_USERNAME', 'root@example.com'),
            'password' => env('IMAP_GMAIL_PASSWORD', '')
],`

**Comment by fa2mm** [comment]
https://www.php.net/manual/en/function.imap-open.php
`/novalidate-cert - do not validate certificates from TLS/SSL server, needed if server uses self-signed certificates`
