### ISSUE TITLE
Unable to get folders

### ISSUE THREAD

**Issue by jamipietila** [Webklex/laravel-imap#24]
Hi!

Great library, seems to do what I need very well :)

Just wanted to let you know, that i get error while trying to get all folders from Office 365.

Here's my test code:

```
$oClient = \Webklex\IMAP\Facades\Client::account('default');
$oClient->connect();
$aMailboxes = $oClient->getFolders();
```
Result:

`"Invalid argument supplied for foreach()" in Client.php` (line 232).

I tracked down the "bug" to this recursive function on line 236:
`$children = $this->getFolders(true, $pattern);`

2 of my folders go that part of the scripts what are:

- Conversation History/%
- Yhteystiedot/%

If I skip both of them in items loop, everything works fine. 

Unfortunately I was not able to figure out how to fix it.

**Comment by Jamipietila** [comment]
I just realised that setting $hierarchical to false fixes my issue.

Working code:
```
$oClient = \Webklex\IMAP\Facades\Client::account('default');
$oClient->connect();
$aMailboxes = $oClient->getFolders(false);
```

**Comment by Webklex** [comment]
Hi @Jamipietila ,
thanks for your report. I'm still not shure if this is a bug or not. Also I'm having a hard time to replicate the behavior. 
So if anyone out there could help me / us on this issue or question please comment below :)

Best regards

**Comment by Jamipietila** [comment]
Might not be related at all, but I'm using Homestead and PHP 7.1.2.

**Comment by yangjisen** [comment]
I use the QQ mailbox encountered the same problem, are set to false solution

**Comment by yangjisen** [comment]
vendor\webklex\laravel-imap\src\IMAP\Client.php
```
        $this->checkConnection();
        $folders = [];
 
        if ($hierarchical) {
            $pattern = $parent_folder.'%';
        } else {
            $pattern = $parent_folder.'*';
        }
 
        $items = imap_getmailboxes($this->connection, $this->getAddress(), $pattern);
        foreach ($items as $item) {
            $folder = new Folder($this, $item);
 
            if ($hierarchical && $folder->hasChildren()) {
                $pattern = $folder->fullName.$folder->delimiter.'%';
 
                $children = $this->getFolders(true, $pattern);
                $folder->setChildren($children);
            }
            $folders[] = $folder;
        }
 
        return $folders;
    }
 
    /**
```

```

$aMailboxes = $oClient->getFolders();

$items = imap_getmailboxes($this->connection, $this->getAddress(), $pattern);
dd($items);

array:6 [▼
  0 => {#191 ▼
    +"name": "{imap.qq.com:993/imap/ssl}&UXZO1mWHTvZZOQ-"
    +"attributes": 34
    +"delimiter": "/"
  }
]

 ```

```
$aMailboxes = $oClient->getFolders(false);

$items = imap_getmailboxes($this->connection, $this->getAddress(), $pattern);
dd($items);

array:23 [▼
  0 => {#191 ▼
    +"name": "{imap.qq.com:993/imap/ssl}&UXZO1mWHTvZZOQ-"
    +"attributes": 34
    +"delimiter": "/"
  }
  1 => {#192 ▼
    +"name": "{imap.qq.com:993/imap/ssl}INBOX"
    +"attributes": 64
    +"delimiter": "/"
  }
  2 => {#198 ▼
    +"name": "{imap.qq.com:993/imap/ssl}Sent Messages"
    +"attributes": 64
    +"delimiter": "/"
  }
  3 => {#199 ▼
    +"name": "{imap.qq.com:993/imap/ssl}Drafts"
    +"attributes": 64
    +"delimiter": "/"
  }
  4 => {#200 ▼
    +"name": "{imap.qq.com:993/imap/ssl}Deleted Messages"
    +"attributes": 64
    +"delimiter": "/"
  }
]

```

**Comment by isnipepixels** [comment]
Just so you know the getFolders() does not work for Outlook.

**Comment by salih0vicX** [comment]
@isnipepixels It works for me (imap host: outlook.office365.com).

**Comment by isnipepixels** [comment]
@salih0vicX I will post the errors I keep getting tomorrow, falls under a foreach() in src

**Comment by Webklex** [comment]
@narwy any news? :)

**Comment by jacm1993** [comment]
I want to show all messages in the output folder. Any example of how?

My code in the controller
 Laravel:
 $ oClient-> connect ();

        $ aFolder = $ oClient-> getFolder ('INBOX.sent');

            foreach ($ aFolder as $ oFolder)
            {
                $ aMessage = $ oFolder-> messages () -> all () -> get ();

            }

        return view ('vendor.adminlte.Mailbox.Buzon', compact ('aMessage'));

**Comment by Webklex** [comment]
Hi @jacm1993 ,
please take a look at the issue you've just created: #228
