### ISSUE TITLE
Call to undefined function Webklex\IMAP\Query\camel_case()

### ISSUE THREAD

**Issue by k3youmin** [Webklex/laravel-imap#244]
Please be aware that these issues will be closed if inactive for more then 14 days :)
![image](https://user-images.githubusercontent.com/15870174/64246481-712a5600-cf3f-11e9-90b7-e7cbd8d604df.png)
![image](https://user-images.githubusercontent.com/15870174/64246491-7687a080-cf3f-11e9-8cc8-99a2510a3cb0.png)
![image](https://user-images.githubusercontent.com/15870174/64246514-7f787200-cf3f-11e9-949d-443b0dbf1bec.png)

**Comment by Webklex** [comment]
Hi @k3youmin ,
which laravel version are you using? `camel_case` is a laravel helper function:
```php
if (! function_exists('camel_case')) {
    /**
     * Convert a value to camel case.
     *
     * @param  string  $value
     * @return string
     */
    function camel_case($value)  {
        return Str::camel($value);
    }
}
```

**Comment by k3youmin** [comment]
[image: image.png]
