### ISSUE TITLE
How to query all unread messages?

### ISSUE THREAD

**Issue by k3youmin** [Webklex/laravel-imap#245]
Please be aware that these issues will be closed if inactive for more then 14 days :)

**Comment by Webklex** [comment]
Hi @k3youmin ,
please take a look at the documentation: [search-for-messages](https://github.com/Webklex/laravel-imap#search-for-messages).

One way could be:
```php
//Get all unseen messages containing "hello world"
/** @var \Webklex\IMAP\Support\MessageCollection $aMessage */
$aMessage = $oFolder->query()->unseen()->text('hello world')->get();
```

**Comment by k3youmin** [comment]
Good day Sir,
I want to query all unread messages and all the subject is not RE and FWD?
but the result is empty.
Here's my code
[image: image.png]
Output
[image: image.png]
