### ISSUE TITLE
Call to undefined function Webklex\IMAP\snake_case()

### ISSUE THREAD

**Issue by collaps-modules** [Webklex/laravel-imap#247]
**Describe the bug**
"Call to undefined function Webklex\IMAP\snake_case()"

**To Reproduce**
1. Create connection to IMAP mail server ( validate_cert = false, port = 143, encryption =  TLS )
2. ![image](https://user-images.githubusercontent.com/49482583/64784217-49a44080-d572-11e9-81b8-e9201a9f2fc0.png)
3. See error!

**Screenshots**
![image](https://user-images.githubusercontent.com/49482583/64784484-e6ff7480-d572-11e9-9260-09668114e03e.png)

**Desktop / Server (please complete the following information):**
 - OS: macOS 10.14.6
- PHP: 7.3.9 (cli) (built: Aug 30 2019 01:42:25)
 - Laravel Framework 6.0.0

**Comment by koenhoeijmakers** [comment]
This happens on laravel 6.0 because the helpers have been deprecated, i'll make a PR replacing these helpers.

**Comment by koenhoeijmakers** [comment]
A quick fix for now (until a release is made) would be to require `laravel/helpers` in your project.
