### ISSUE TITLE
How to setFetchBody when searching using 'getMessage' method?

### ISSUE THREAD

**Issue by ianpbh** [Webklex/laravel-imap#252]
getMessage initialize an object of Message class, i can't use setFetchBody since it's a method of Query class. I want to get the attachments of a message but it returns null cause setFetchBody it's false i guess.
`$aFolder = $oClient->getFolder($caixa);
        $oMessage = $aFolder->getMessage($messageId)->setFetchAttachment(true);
        $objetoAttachments = $oMessage->getAttachments();
        foreach($objetoAttachments as $objetoAttachment)
        {
            $dadosMensagem['attachments'][$contadorAttachment] = $objetoAttachment->getName();
            $contadorAttachment++;
        }`

Here's the code, getAttachments() returns null, and this line
`$oMessage = $aFolder->getMessage($messageId)->setFetchAttachment(true);`
returns an error, cause' i can't use this method.

Is there a way to set fetch body and attachment using the message class?

Thanks

**Comment by desenvolvimentotask** [comment]
Hi Ian, to what you wanna do, check the Folder.php in the getMessage method. You can pass the fetch body in the params when calling the method, just like this. 
`$oMessage = $aFolder->getMessage($messageId, null, null, true, true);`
