### ISSUE TITLE
Query::new returns empty

### ISSUE THREAD

**Issue by desenvolvimentotask** [Webklex/laravel-imap#254]
Hi, i'm using the new method, because i want to retrieve the newer messages first, just like an e-mail client does. But the Query::new method returns empty.
![Screenshot_2019-09-25 Screenshot](https://user-images.githubusercontent.com/49455796/65614529-2cb63700-df8e-11e9-9e57-d54eedf1aa80.png)
Here's the code:
![codigonew](https://user-images.githubusercontent.com/49455796/65614802-a0584400-df8e-11e9-9c3c-64fd2f14f987.png)

Here's the stuff i've tried:

1. I've tried using 'new'  method, 'whereNew' 
2. Removing and adding limit to the query
3. Use message, and search instead of 'query' method
4. Setting the fetch body, flags and attachments on and off.
5. Trying to fetch the messages from another inbox folder

Other methods like 'all' and 'limit' works just fine, just new that doesn't.
The imap server is running Dovecot imapd.

I appreciate any help :)

**Comment by Webklex** [comment]
Hi @desenvolvimentotask,
please check if the "new" flag is actually present. Perhaps it doesn't get added or removed by an other client?

You could also try to use `unseen()` instead (to be honest, I don't know if the server handels `unseen` differently..). :)

**Comment by desenvolvimentotask** [comment]
![flags](https://user-images.githubusercontent.com/49455796/65696129-1cb25c00-e04f-11e9-9768-47ea7d893f17.png)
All the messages flags come like this, you're probably right, perhaps there's another client changing the flags of the messages. I tried to use `unseen()` but it really returns only unseen messages, and i need all the new messages.
As an alternative way, i'm searching for all messages in the current date, and using laravel Collector to desc sort by date.

Thank you for your response :)
