### ISSUE TITLE
Not able to install new packages or run dump-autoload

### ISSUE THREAD

**Issue by sheriffmarley** [Webklex/laravel-imap#261]
**Describe the bug**
If I run `composer dumpautoload` or try to install a new package i receive the following error

```
Symfony\Component\Debug\Exception\FatalThrowableError  : Argument 1 passed to Webklex\IMAP\Client::setConfig() must be of the type array, null given, called in C:\Program Files (x86)\EasyPHP-Devserver-17\eds-www\laravel\vendor\webklex\laravel-imap\src\IMAP\Client.php on line 140

  at C:\Program Files (x86)\EasyPHP-Devserver-17\eds-www\laravel\vendor\webklex\laravel-imap\src\IMAP\Client.php:158
    154|      * @param array $config
    155|      *
    156|      * @return self
    157|      */
  > 158|     public function setConfig(array $config) {
    159|         $default_account = config('imap.default');
    160|         $default_config  = config("imap.accounts.$default_account");
    161|
    162|         foreach ($this->valid_config_keys as $key) {

  Exception trace:

  1   Webklex\IMAP\Client::setConfig()
      C:\Program Files (x86)\EasyPHP-Devserver-17\eds-www\laravel\vendor\webklex\laravel-imap\src\IMAP\Client.php:140

  2   Webklex\IMAP\Client::__construct()
      C:\Program Files (x86)\EasyPHP-Devserver-17\eds-www\laravel\vendor\webklex\laravel-imap\src\IMAP\ClientManager.php:76
```

**To Reproduce**
I installed the package

**Expected behavior**
The error should not occur

**Screenshots**

**Desktop / Server (please complete the following information):**
 - OS:  Windows
- PHP:  7.2.16
 - Version laravel 5.8.* 

**Additional context**

**Comment by Webklex** [comment]
Hi,
please provide the full call stack. The above small call stack doesn't provide enough information. Have you tried to remove the vendors folder and install all packages fresh? Please also check if your .env file gets loaded. There is a windows bug in the dotenv library where it sometimes "forgets" all values stored in your .env file.

**Comment by sheriffmarley** [comment]
It was the full stack i received.

Seems to be a windows related issue, since it seems to work on Linux as expected

**Comment by Webklex** [comment]
Hi @sheriffmarley ,
have you set a `default` account inside your `config/imap.php` config file? If not please add one - doesn't has to contain real account information. It just has to be there.. I believe :)

**Comment by Webklex** [comment]
A potential problem could be https://github.com/Webklex/laravel-imap/blob/master/src/IMAP/Providers/LaravelServiceProvider.php#L64
```php
$path = __DIR__.'/../../config/'.$config_key.'.php';
```

..does replacing it with this work?
```php
$path = __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'config'.DIRECTORY_SEPARATOR.$config_key.'.php';
```
