### ISSUE TITLE
How do you do ->whereNot('SUBJECT', 'Automatic Reply') ?

### ISSUE THREAD

**Issue by arctic-ice-cool** [Webklex/laravel-imap#263]
Please be aware that these issues will be closed if inactive for more then 14 days :)
Hi,

How do you do `->whereNot('SUBJECT', 'Automatic Reply')` ?

Basically want to filter out retreived messages based on either subject or body text - like the opposite of 'SUBJECT' and 'TEXT'.

'UNKEYWORD' doesn't work based on the subject as far as my testing has shown me.

**Comment by arctic-ice-cool** [comment]
In fact, UNKEYWORD doesn't seem to be working at all :-( Other filters do :-)

**Comment by Webklex** [comment]
Hi @arctic-ice-cool ,
unfortunately the supported keywords depend on your provider / server setup.

However you can alway perform complex filter function on the fetched message collection. But be aware that this isn't performant so make sure you limit the request to fetch as few messages as possible and as many as required.
