### ISSUE TITLE
Outlook file .msg not displaying after sync.

### ISSUE THREAD

**Issue by spidy10** [Webklex/laravel-imap#264]
Please be aware that these issues will be closed if inactive for more then 14 days :)
Hi,

I use this package to successfully deal with many tens of email on daily basis. I am also using all type of attachment for email. All attachment working very well with email.
But, in case .msg file it is not displaying after sync email from server in E-mail details screen.

Any idea how to fetch .msg file at the time of sync and display it in email and download it ?

**Comment by Webklex** [comment]
Hi @spidy10 ,
I havn't played arround with .msg files. But I could imagine that they get interpreted as part of the "message" and not as attachment !?

If you dump the Message object, does it contain any information which should be present in the .msg attachment and does not belong to the actual message you've just fetched?

**Comment by spidy10** [comment]
Hi @Webklex ,
Thanks for reply,

I have dump the Message object and checked it does not contains any information which is present in .msg file.

**Comment by spidy10** [comment]
Hi @Webklex ,
Can you please check and help me to resolve this issue.
