### ISSUE TITLE
getHTMLBody prevents other columns to save database

### ISSUE THREAD

**Issue by yuzemre** [Webklex/laravel-imap#265]
**Describe the bug**
Looping incoming email if i want to save getHTMLBody column to database other columns insterted null if i remove getHTMLBody every column such as sender inserted as is.

        $oClient->connect();
        $aFolder = $oClient->getFolders();

        foreach($aFolder as $oFolder){
            $aMessage = $oFolder->query()->since(now()->subDays(1))->get();
            foreach($aMessage as $oMessage) {
                $ticket = InsertTicket::firstOrNew(
                    ['subject' => $oMessage->getSubject()],
                    ['body' => $oMessage->getHTMLBody()],
                    ['sender' => $oMessage->getSender()[0]->mail],
                    ['opened_at' => $oMessage->getDate()]);
                $ticket->save();
                //
            }
        } 

**To Reproduce**

**Expected behavior**

**Screenshots**
[https://serving.photos.photobox.com/4297123023bced4ecc849efa896491302add1e5a02da43edfb846462c30f6c328b3ba487.jpg](screenshot)

**Desktop / Server (please complete the following information):**
 - OS: Ubuntu
- PHP: [e.g. 5.5.9]

**Additional context**

**Comment by Webklex** [comment]
Hi @yuzemre ,
what column type have you used for 'body'? Perhaps its to short?

if you dump the `$oMessage` like `dd($oMessage)` and try to perform it manually is it still failing?

This might help you locating the issue.
```php
$data = [
    ['subject' => $oMessage->getSubject()],
    ['body' => $oMessage->getHTMLBody()],
    ['sender' => $oMessage->getSender()[0]->mail],
    ['opened_at' => $oMessage->getDate()]
];

dump($data);

$ticket = InsertTicket::firstOrNew($data);
$ticket->save();

dd($data);
```

**Comment by yuzemre** [comment]
Well it gave an error now. Then i changed mysql table type innodb to myisam.


SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '.`2019 10:00:09 Error Unable to write to configuration backup file`.`<br />26' at line 1 (SQL: select * from `tickets` where (`[Failed]

**Comment by yuzemre** [comment]
![Ekran Alıntısı](https://user-images.githubusercontent.com/17101582/69784769-a5708400-11c7-11ea-8fd3-e6c65f5bf536.PNG)
As you can see on screenshot, there are datas on fields but still inserts all columns empty.

**Comment by yuzemre** [comment]
I found issue,

I remove brackets in $data array send it to eloquent model as 1 array then it inserted all columns.
