### ISSUE TITLE
Laravel Imap connect() slow | reuse?

### ISSUE THREAD

**Issue by SDCRoman** [Webklex/laravel-imap#266]
I noticed that the connect() method is slow, it takes 4-5 sec.:

```
$start = microtime(true);

$oClient = new Client([
    'host'          => env('MAIL_HOST_IN'),
    'port'          => env('MAIL_PORT_IN'),
    'encryption'    => env('MAIL_ENCRYPTION_IN'),
    'validate_cert' => true,
    'username'      => env('MAIL_USERNAME'),
    'password'      => env('MAIL_PASSWORD'),
    'protocol'      => 'imap'
]);

// Connect to the IMAP Server
$oClient->connect(); 

\Log::info('Connect: ' . strval(microtime(true) - $start));
```

Thats it, there is no additional code. I also use getFolders() and loop through them to get messages. I count/get unseen messages and do more operations, but they are all fast.

I am asking this, because if I login into my mailbox through the website, the performance is much better 1-2 sec. And the operation is the same, I get the mailboxes and a count on unseen messages. So why it is slow via script?

In case it simply is like that and I cant change it, what are some possible solutions? The only idea I have right now it to reuse the connection in multple functions, so at least I connect only once, but need also to figure out how to do it.

**Comment by Webklex** [comment]
Hi @SDCRoman ,
I tried to reproduce this behavior but couldn't determine any problems. I ran the following code:
```php
$samples = 100;
$total = 0;
$start = microtime(true);
$oClient = \Webklex\IMAP\Facades\Client::account('default');

for($i = 0; $i <= $samples; $i++) {
    $oClient->connect();

    $folder = $oClient->getFolder('INBOX.test');
    $query = $folder->query()->subject('test');
    $total = $query->count();

    $oClient->disconnect();
}

$duration = (microtime(true) - $start);
dump("--", "Regular connect / disconnect", "Messages: ".$total, "Duration: ".$duration, "AVG: ".($duration / $samples));

for($i = 0; $i <= $samples; $i++) {
    $oClient->connect();

    $folder = $oClient->getFolder('INBOX.test');
    $query = $folder->query()->subject('test');
    $total = $query->count();
}

$duration = (microtime(true) - $start);
dump("--", "Irregular connect", "Messages: ".$total, "Duration: ".$duration, "AVG: ".($duration / $samples));

for($i = 0; $i <= $samples; $i++) {
    $folder = $oClient->getFolder('INBOX.test');
    $query = $folder->query()->subject('test');
    $total = $query->count();
}

$duration = (microtime(true) - $start);
dd("--", "Continuous connection", "Messages: ".$total, "Duration: ".$duration, "AVG: ".($duration / $samples));
```
Output:
>"Regular connect / disconnect"
>"Messages: 4"
>"Duration: 47.338393211365"
>"AVG: 0.47338393211365"

>"Irregular connect"
>"Messages: 4"
>"Duration: 94.146285057068"
>"AVG: 0.94146285057068"

>"Continuous connection"
>"Messages: 4"
>"Duration: 97.467885017395"
>"AVG: 0.97467885017395"

Best regards

**Comment by SDCRoman** [comment]
Hello @Webklex .

Thank you for taking the time to look into the issue. 

I can confirm now that there is no issue with the code/package.

It seems that something on my local machine was responsible for the slow connect time. 
I dont know exactly what it was, maybe a broken firewall.

**I uploaded the code to my server. The performance was much better, it connected immediately.**
