### ISSUE TITLE
How to figure wich reply belongs which mail?

### ISSUE THREAD

**Issue by yuzemre** [Webklex/laravel-imap#267]
Please be aware that these issues will be closed if inactive for more then 14 days :)

![mail](https://user-images.githubusercontent.com/17101582/69877508-76473900-12d3-11ea-9b4f-3cbeb050c313.PNG)

First of all i didn't find any tuts to get replies or i don't even know is there any thing like that. As you can see on ss UID 949 is new mail and on bottom UID 950 is reply of 949. I used getInReplyTo but in first mail its empty so again i couldn't related them.

So how can i match them or is there any way to find out replies.

**Comment by Webklex** [comment]
Hi @yuzemre ,
well there isn't really a way to perform a regex-like search. However you could fetch every 5 minutes all emails which were received within the last 5 minutes (or 6 minutes to be sure). However due tom missconfired emailclients you can also receive messages "in the past". Those could not be discovered using this method...

Once you've fetched your messages you could check if they contain "Re", "Ynt", "Ant", etc. If so remove that part and query your database with the remaining string.

Best regards

**Comment by umutpamuk** [comment]
How can I turn the emails I have transferred to the database into a queue with their answers? Could you do it? @yuzemre
