### ISSUE TITLE
How do you filter for message ID?

### ISSUE THREAD

**Issue by buenyamin-olgun** [Webklex/laravel-imap#268]
Hello,
we are building up a web project based on laravel-imap and tried to filter for the messageID which should be unique along a user's mailbox so that a user can select some messages and request to delete them.

I've tried several ways but can't figure out how to filter for the messageId in the Query::class.

My code so far:
```
[...]

        $messageID = '4aac05f4.1c59fb81.22652.cb54@mx.google.com'

        $oClient = new Client([
            'username'      => $current_mailaddress->username . '@turnierplanung.com',
            'password'      => $current_mailaddress->securetoken
        ]);
        $oClient->connect();

        $folders = $oClient->getFolders();

        $mails = [];

        foreach ($folders as $folder) {
                //$mails[] = $folder->query()->whereMessageId($messageID)->get(); --> this throws an InvalidWhereQueryCriteriaException
                $mails[] = $folder->query("Message-ID <". $messageID . ">")->get();
        }
```

The current version shows all available messages without filtering them for the messageId.

I've looked this up @ https://github.com/Webklex/laravel-imap/blob/master/src/IMAP/Query/WhereQuery.php

There's a `public function whereMessageId($msg_id)` which does not work.
But `public function whereUnseen()` works fine - why?

How can I filter all messages for a given message id without gathering them all and filter them with my own logic?

Thanks in advance & Kind Regards

**Comment by Webklex** [comment]
Hi @buenyamin-olgun ,
the available search criteria depends on your mail provider. Owever if you take alook at your raw mail is there a line containing the string `Message-ID <fooBar>`? If it isn't present but lets say "MESSAGE-ID" you could use something like `->where("MESSAGE-ID <fooBar>")` and use a custom search parameter. 

I hope this helps a little bit :)

**Comment by buenyamin-olgun** [comment]
Hi @Webklex,
thank you for your answer.

There's the following line in every mail on my mail server:
```
Message-ID: <5ddb03f4.1c69fb81.22752.cb54@mx.google.com>
```
But if I try to filter for this with ```$folder->query("Message-ID: <". $messageID . ">")->get();```
there are 2 messages even though the message ID is completely different.

Could you help me with this?

Kind Regards

**Comment by Webklex** [comment]
Oh, well let me do some quick tests :)

**Comment by Webklex** [comment]
Alright, I'm out of luck. My mailserver doesn't understand the Message-ID command.

**Comment by yuan8** [comment]
$oFolder->messages()->text('Message-ID: <CA+=9s-NmW8JnZ7UWSY9y15EV_Chob6WLAJsbN8g-Pg3FFwQR=Q@mail.gmail.com>')->get()

try this

for select mail when contain text [ Message-ID: <id> ]

**Comment by MouMoutMan** [comment]
Or the WhereQuery whereMessageId :
` $folder->query()->whereMessageId( "4aac05f4.1c59fb81.22652.cb54@mx.google.com" )->get();`

**Comment by MouMoutMan** [comment]
Hi Webklex !
Ok ! Thx for  that clarification 😃
