### ISSUE TITLE
iconv(): Wrong charset, conversion from `UTF7-IMAP' to `UTF-8//IGNORE' is not allowed

### ISSUE THREAD

**Issue by demeus** [Webklex/laravel-imap#273]
**Describe the bug**
when calling getMessages()
I get this error
    -  ErrorException  : iconv(): Wrong charset, conversion from `UTF7-IMAP' to `UTF-8//IGNORE' is not allowed

**PHP**
 7.2.25

**OS**
centos-release-7-7.1908.0.el7.centos.x86_64

**Comment by Webklex** [comment]
Hi @demeus ,
plase try to install the php extension `mbstring` and try again :)

**Comment by demeus** [comment]
hi @Webklex ,
it works, thank you so much

**Comment by lomotech** [comment]
hi, i have some sort of same problem with some of the email.

error: iconv(): Wrong charset, conversion from `default' to `UTF-8//IGNORE' is not allowed

PHP 7.4.12 (mbstring and xml is installed and actived)
OS CentOS Linux release 8.2.2004
Laravel 5.7
