### ISSUE TITLE
imap_open(): Couldn't open stream

### ISSUE THREAD

**Issue by yojann96** [Webklex/laravel-imap#275]
Error login con IMAP

Al intentar conectarme, me genera el siguiente error:

Mensaje: imap_open(): Couldn't open stream {outlook.office365.com:993/imap/ssl}. [CLOSED] IMAP connection broken (server response)

Excepción: Webklex\IMAP\Exceptions\ConnectionFailedException

**Comment by Webklex** [comment]
Hi @yojann96 ,
please take a look at these issues: #153 #100 #78.

So far it could be caused by to many things. Please try to provide some more information (code samples, call stacks, etc) in order to figure things out :)

Best regards

**Comment by yojann96** [comment]
Thanks for the reply. Reviewing the links (# 153, # 100, # 78) do not apply in my case with the error.

 In my case, when I try to establish a connection with the server I get the error

[cid:99067e95-502e-426a-be33-9f68d8333e80]

I appreciate your help
________________________________
De: Webklex <notifications@github.com>
Enviado: lunes, 13 de enero de 2020 2:56 p. m.
Para: Webklex/laravel-imap <laravel-imap@noreply.github.com>
Cc: yojann96 <yojann96@hotmail.com>; Mention <mention@noreply.github.com>
Asunto: Re: [Webklex/laravel-imap] imap_open(): Couldn't open stream (#275)


Hi @yojann96<https://github.com/yojann96> ,
please take a look at these issues: #153<https://github.com/Webklex/laravel-imap/issues/153> #100<https://github.com/Webklex/laravel-imap/issues/100> #78<https://github.com/Webklex/laravel-imap/issues/78>.

So far it could be caused by to many things. Please try to provide some more information (code samples, call stacks, etc) in order to figure things out :)

Best regards

**Comment by yojann96** [comment]
![Error conexión IMAO](https://user-images.githubusercontent.com/10881885/72348894-6760ee00-36a9-11ea-96a3-71e01f24f753.PNG)

Error: [CLOSED] IMAP connection broken (server response)
ConnectionFailedException
