### ISSUE TITLE
Appending Sent messages show header not body nor attachments. kindly help

### ISSUE THREAD

**Issue by flowser** [Webklex/laravel-imap#278]
I have appended the message as shown below, 
``~~~
$oClient = new Client([
            'host'          => $host,
            'port'          => $port,
            'encryption'    => $encryption,
            'validate_cert' => true,
            'username'      => $username,
            'password'      => $password,
            'protocol'      => $protocol
        ]);
        $oClient->connect();
            //update
            $oFolder = $oClient->getFolder('INBOX.Sent');
            $oMessage = $oFolder->appendMessage($message);
            $oClient->expunge();
            
        $oClient->disconnect();
~~~
``
![image](https://user-images.githubusercontent.com/30996737/72737748-3acd3a80-3bb1-11ea-9c6f-fa6f01c505f4.png)

**Comment by psizer10** [comment]
I've encountered a similar issue - using this as a temporary work around

`imap_append($oClient->getConnection(), $oFolder->name, $email);`

**Comment by flowser** [comment]
Still same issue, nothing new, i mnot getting attahments, and message on sent folder, only headers

**Comment by Webklex** [comment]
Hi @flowser ,
please try to call `Message::parseBody()` afterwards:
```php
$oFolder = $oClient->getFolder('INBOX.Sent');
$oMessage = $oFolder->appendMessage($message);
$oMessage->parseBody();
```

Kind Regards
