### ISSUE TITLE
Body Content half empty when I get the mail

### ISSUE THREAD

**Issue by pappleweb** [Webklex/laravel-imap#280]
Hi,

I use your code since 1 year. It's working great. Thanks you.
But I have a problem when I want to read a specific message.
I have created a ticketing email on LARAVEL 5.4.36.
I have updated laravel-imap to 1.2 -> 1.4.5.

This is the problem : 

1. My customer send me an email with his iPhone.
2. With your script, I connect on the mailbox and I read the mail.
3. The script only displays the signature : "Envoyé de mon iPhone". 
4. I check the mail in my GMAIL INBOX and i see that there is another text before the signature : 

![1 message-1](https://user-images.githubusercontent.com/15815767/73124037-c6bada00-3f96-11ea-9762-72e7faa42419.JPG)

5. So I display the original message and this is the code generated by the iPhone : 

`Delivered-To: destinataire@example.com
Received: by 2002:a4a:dbd0:0:0:0:0:0 with SMTP id t16csp597905oou;
        Thu, 23 Jan 2020 03:11:14 -0800 (PST)
X-Google-Smtp-Source: APXvYqzq/bRCcSIZLtBx4f6AwobgOg5GnC5FCbk3uiqOuWjrGLy9dNs+s5jFokn2Lvf/0H2F/Og3
X-Received: by 2002:adf:f70b:: with SMTP id r11mr15421890wrp.388.1579777873895;
        Thu, 23 Jan 2020 03:11:13 -0800 (PST)
ARC-Seal: i=1; a=rsa-sha256; t=1579777873; cv=none;
        d=google.com; s=arc-20160816;
        b=jxcfJk3wj9ZoGOscYPlFTy0TxBN2MSqJVT8ULzIu1XlaTwL5zR93wF96gazYw/GoIn
         VIGlb3U4qCpnvYMZ/5EzLJjz5MDymAgTAshILmWHKZ3mTT3BO5UH4vqdH6XNzDyLfl9a
         Ru1r02AID5IroQmQFr4f4wHDF8FGtAHWxCwCLBP/9Veny5Ot945eKyQD/E6ebx3WWX41
         RCdRoSj1SAhChcMaHZN5AeXsDtzvrcf8FX+m95R6xWq3lxqx6UD1c6jB78uG/bjPW+mx
         qNNovMHGBO9v/grZkYx8SsLY8NsiDwPF/+LFTwHIC+rqpGWATS+ZJVuiPOtgZBr6wz8z
         gGsw==
ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=google.com; s=arc-20160816;
        h=to:subject:mime-version:from:date:message-id:secumail-id;
        bh=GCDW3gN9tAW61BFPKVT/VzUSDbLmaRoNUim0opvDkoc=;
        b=N7lnK3Cfx2LzFhSUTgPUsf3zkThSvzhf6CzDD1lqeWoFbnOlsrZbPdEr5MHwwdUO7h
         xPwVWZAy3GZqRtKWt577tBfCJabTflv1JCqwjCiF0U4ypMQXs62mFPuKyC4jO8rFAqH4
         hwnfOEHPNxjpbdLfxZ4YU2dWg7Yd+b+wNUzVdpvQAxZhqufWppZGaIp8efKKwMJiNF7y
         DCqDF28Zkr+2qKVgr196a69GJPPA6FRkgXXh4/TOwxIptaVGD8YKwHy50frNk7i2o1co
         99YlcygWR/9mkUxUh2iT3WZlRXL29bLsE7nuKfpOxUjgnnwZ/6T68NiG05aPUABNdrWs
         rE2w==
ARC-Authentication-Results: i=1; mx.google.com;
       spf=pass (google.com: domain of expediteur@customer.com designates 85.31.212.145 as permitted sender) smtp.mailfrom=expediteur@customer.com
Return-Path: <expediteur@customer.com>
Received: from fx405.security-mail.net (smtpout140.security-mail.net. [85.31.212.145])
        by mx.google.com with ESMTPS id v16si1614975wrm.476.2020.01.23.03.11.13
        for <destinataire@example.com>
        (version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
        Thu, 23 Jan 2020 03:11:13 -0800 (PST)
Received-SPF: pass (google.com: domain of expediteur@customer.com designates 85.31.212.145 as permitted sender) client-ip=85.31.212.145;
Authentication-Results: mx.google.com;
       spf=pass (google.com: domain of expediteur@customer.com designates 85.31.212.145 as permitted sender) smtp.mailfrom=expediteur@customer.com
Received: from localhost (localhost [127.0.0.1]) by fx405.security-mail.net (Postfix) with SMTP id 24605647DA for <destinataire@example.com>; Thu, 23 Jan 2020 12:11:11 +0100 (CET)
Received: from fx405 (localhost [127.0.0.1]) by fx405.security-mail.net (Postfix) with ESMTP id 1861B647D9 for <destinataire@example.com>; Thu, 23 Jan 2020 12:11:11 +0100 (CET)
X-Virus-Scanned: E-securemail
Secumail-id: <f448.5e297f4b.2bb4b.0>
Received: from xxxxReplacexxxxhub01 (unknown [195.6.198.249]) by fx405.security-mail.net (Postfix) with ESMTP id 8EF2564761 for <destinataire@example.com>; Thu, 23 Jan 2020 12:11:07 +0100 (CET)
Message-ID: <OF0BBA9A2D.5A5D6A12-ONC12584F8.003D7017-1579777863513@galec.fr>
Date: Thu, 23 Jan 2020 12:11:04 +0100
From: expediteur@customer.com
MIME-Version: 1.0
Subject: 
To: Destinataire <destinataire@example.com>
X-Mailer: IBM Traveler 9.0.1.21 Build 201803022309_20 on server sig-traveler/sigma on behalf of device with id AV9...RKS, type 460 (ios) and description iPhone 11:Apple-iPhone12C1/1703.54 (OS 13)
X-KeepSent: 0BBA9A2D:5A5D6A12-C12584F8:003D7017; type=4; name=$KeepSent
X-MIMETrack: Itemize by nTRAVELER.EXE on sig-traveler/sigma(Release 9.0.1FP10 HF330|September 27, 2018) at 23/01/2020 12:11:04, Serialize by Router on xxxxReplacexxxx/fr(Release 9.0.1FP10 HF383|November 19, 2018) at 23/01/2020 12:11:08
Content-Type: multipart/mixed; boundary=Apple-Mail-056002AA-9ABC-4900-A57F-A9F53346E2AB
X-Virus-Scanned: by Secumail

--Apple-Mail-056002AA-9ABC-4900-A57F-A9F53346E2AB
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: quoted-printable

LA MEZZANINE=20

venez composer votre salade=20
Plat du jour p=C3=B4le italien =F0=9F=87=AE=F0=9F=87=B9  p=C3=A2te carbonar=
a et disponible d=E2=80=99autres plats du jour =C3=A0 chaque p=C3=B4le=20
Et choisissez votre dessert=20

--Apple-Mail-056002AA-9ABC-4900-A57F-A9F53346E2AB
Content-Type: image/jpeg; name=IMG_6004.jpg; x-apple-part-url=6CC0AA6E-E197-43C0-BB00-FA8BFD9C1797
Content-Disposition: inline; filename=IMG_6004.jpg
Content-Transfer-Encoding: base64

--Apple-Mail-056002AA-9ABC-4900-A57F-A9F53346E2AB
Content-Type: text/plain; charset=us-ascii
Content-Transfer-Encoding: quoted-printable

--Apple-Mail-056002AA-9ABC-4900-A57F-A9F53346E2AB
Content-Type: image/jpeg; name=IMG_6008.jpg; x-apple-part-url=345F0926-7038-495B-9D0F-17EC3CDD995D
Content-Disposition: inline; filename=IMG_6008.jpg
Content-Transfer-Encoding: base64

--Apple-Mail-056002AA-9ABC-4900-A57F-A9F53346E2AB
Content-Type: text/plain; charset=us-ascii
Content-Transfer-Encoding: quoted-printable

--Apple-Mail-056002AA-9ABC-4900-A57F-A9F53346E2AB
Content-Type: image/jpeg; name=IMG_6010.jpg; x-apple-part-url=7BD9E6D6-3143-4C38-BF3D-7B40C7934A9F
Content-Disposition: inline; filename=IMG_6010.jpg
Content-Transfer-Encoding: base64

--Apple-Mail-056002AA-9ABC-4900-A57F-A9F53346E2AB
Content-Type: text/plain; charset=us-ascii
Content-Transfer-Encoding: quoted-printable

--Apple-Mail-056002AA-9ABC-4900-A57F-A9F53346E2AB
Content-Type: image/jpeg; name=IMG_6012.jpg; x-apple-part-url=EF0C9135-75CF-4051-9654-69F56F0310ED
Content-Disposition: inline; filename=IMG_6012.jpg
Content-Transfer-Encoding: base64

--Apple-Mail-056002AA-9ABC-4900-A57F-A9F53346E2AB
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: quoted-printable

Envoy=C3=A9 de mon iPhone

--Apple-Mail-056002AA-9ABC-4900-A57F-A9F53346E2AB--`

6. The Attachements are correctly seen, it's working but I don't have 100% of content body. When I use $oMessage->getRawBody(); I see the message but it's unreadable : 

` --Apple-Mail-056002AA-9ABC-4900-A57F-A9F53346E2AB Content-Type: text/plain; charset=utf-8 Content-Transfer-Encoding: quoted-printable LA MEZZANINE=20 venez composer votre salade=20 Plat du jour p=C3=B4le italien =F0=9F=87=AE=F0=9F=87=B9 p=C3=A2te carbonar= a et disponible d=E2=80=99autres plats du jour =C3=A0 chaque p=C3=B4le=20 Et choisissez votre dessert=20`

My code is :
`$oClient = ClientIMAP::account('default');`
`$oClient->connect();`
`$oFolder = $oClient->getFolder('INBOX');`
`$aMessage = $oFolder->messages()->all()->get();`
`foreach($aMessage as $oMessage){
                     if($oMessage->hasHTMLBody()){
                     	$message = $oMessage->getHTMLBody(true);
                     	echo $message."<br />";
                     }
}`

Can you help me please ??? 

Best regards

**Comment by Webklex** [comment]
Hi @pappleweb ,
please give `Message::getTextBody()` a try :)

```php
class CustomMessageMask extends \Webklex\IMAP\Support\Masks\MessageMask {

    /**
     * New custom method which can be called through a mask
     * @return string
     */
    public function getBody(){
        $body = "";

        if($this->hasHTMLBody()){
            $body .= $this->getHTMLBody(true);
        }
        if($this->hasTextBody()){
            $body .= nl2br($this->getTextBody(true));
        }

        return $body;
    }
}

$oClient = ClientIMAP::account('default');
$oClient->setDefaultMessageMask(CustomMessageMask::class);
$oClient->connect();

$oFolder = $oClient->getFolder('INBOX');
$aMessage = $oFolder->messages()->all()->get();

foreach($aMessage as $oMessage){
    echo $oMessage->mask()->getBody();
}
```

**Comment by pappleweb** [comment]
Hi,

Thanks you for your prompt response. 
But I have already test with `Message::getTextBody()` and it's not working :(.

I use your code and I have created the class CustomMessageMask.
The result is the same...

Another idea for this problem ?

**Comment by pappleweb** [comment]
Un another element can help you. 

1. When I read the mail, I have only the signature.
2. But if I forward the mail (for example with GMAIL), the new mail is successfully read at 100%...

So, Is the problem not related to encoding ?
Should I re-encode the mail ? Or convert it ?

**Comment by pappleweb** [comment]
Hi Webklex (or another), can you help me for this problem ?

**Comment by gerardojbaez** [comment]
I was having this same issue with an email coming from Gmail. Other emails were being parsed correctly and displayed as expected. The issue (at least in my case) was caused by `iconv` used in `Message::convertEncoding` ([line 897](https://github.com/Webklex/laravel-imap/blob/master/src/IMAP/Message.php#L897)). The string was being converted from `ISO-8859-1` to `UTF-8`.

This is the exception that was being thrown and suppressed by the `@` symbol:

```
"iconv(): Wrong charset, conversion from `ISO-8859-1' to `UTF-8//IGNORE' is not allowed"
```

In the end, the problem was on Alpine Linux. Installing `gnu-libiconv`, and adding `ENV LD_PRELOAD /usr/lib/preloadable_libiconv.so php` to my Docker file fixed the issue. More information can be found here: https://github.com/docker-library/php/issues/240

--

On a side note, the suppression symbol should be removed; it causes `iconv` to return `false` whenever there's an issue, something that's undesirable and hard to debug in some cases (this one included). IMO, the best approach would be to just `try` and `catch`, and return the original string whenever there's an exception; this way, we have a clear backtrace and an error message. I can submit a PR if needed.

Thanks for the library! ✌️

**Comment by Webklex** [comment]
Hi @pappleweb @gerardojbaez,
please update to the [latest version](https://github.com/Webklex/laravel-imap/releases) and give it another try :)

Best regards,
