### ISSUE TITLE
please help me solve this problem

### ISSUE THREAD

**Issue by nancysavchenko** [Webklex/laravel-imap#281]
Fatal error: Uncaught ReflectionException: Class config does not exist in D:\XAMPP\htdocs\ls\en\vendor\laravel\framework\src\Illuminate\Container\Container.php:752 Stack trace: #0 D:\XAMPP\htdocs\ls\en\vendor\laravel\framework\src\Illuminate\Container\Container.php(752): ReflectionClass->__construct('config') #1 D:\XAMPP\htdocs\ls\en\vendor\laravel\framework\src\Illuminate\Container\Container.php(631): Illuminate\Container\Container->build('config') #2 D:\XAMPP\htdocs\ls\en\vendor\laravel\framework\src\Illuminate\Container\Container.php(586): Illuminate\Container\Container->resolve('config', Array) #3 D:\XAMPP\htdocs\ls\en\vendor\laravel\framework\src\Illuminate\Foundation\helpers.php(110): Illuminate\Container\Container->make('config', Array) #4 D:\XAMPP\htdocs\ls\en\vendor\laravel\framework\src\Illuminate\Foundation\helpers.php(272): app('config') #5 D:\XAMPP\htdocs\ls\en\vendor\webklex\laravel-imap\src\IMAP\Client.php(159): config('imap.default') #6 D:\XAMPP\htdocs\ls\en\vendor\webklex\laravel-imap\src\IMAP\Client.php( in D:\XAMPP\htdocs\ls\en\vendor\laravel\framework\src\Illuminate\Container\Container.php on line 752

**Comment by Webklex** [comment]
Hi @nancysavchenko ,
please take a look at the issue template: https://github.com/Webklex/laravel-imap/issues/new?template=bug_report.md

So far it could be caused by to many things. Please try to provide some more information (code samples, call stacks, etc) in order to figure things out :)

Best regards
