### ISSUE TITLE
Outlook - Bad message number after changing folders

### ISSUE THREAD

**Issue by sandaru1** [Webklex/laravel-imap#283]
**Describe the bug**
When the imap folders are changed and the messages are queried again, imap_fetchheader() is throwing a "Bad message number" exception.

**To Reproduce**
```
$client = new Client([
        'host' => 'imap-mail.outlook.com',
        'port' => 993,
        'encryption' => 'ssl',
        'validate_cert' => false,
        'protocol' => 'imap',
        'username' => 'username',
        'password' => 'password'
      ]);

$inbox = $client->getFolder("Inbox");
$messages = $inbox->getMessages();
$spam = $client->getFolder("Junk");
$messages = $spam->getMessages();
$inbox = $client->getFolder("Inbox");
$messages = $inbox->getMessages();
```

**Expected behavior**
The list of the messages should be returned.

**Desktop / Server :**
PHP 7.4.2 (cli) (built: Jan 22 2020 06:34:34) ( NTS )
IMAP c-Client Version - 2007f

**Comment by AdolphYu** [comment]
imap.exmail.qq.com

**Comment by Webklex** [comment]
Hi @sandaru1 @AdolphYu ,
please take look at #243 and please make sure Message::parseHeader() has run before.

Best regards,
