### ISSUE TITLE
No attachment is available

### ISSUE THREAD

**Issue by nessor** [Webklex/laravel-imap#284]
**Describe the bug**
We have observed some strange behavior. We receive automatic e-mails to a mailbox, which contain an XML file as attachment. In some e-mails the attachment can be retrieved, in others not. It is noticeable that in the e-mails where retrieval is not possible, the 

Content-Type: text/xml; charset=ISO-8859-1

is. For the mails where the attachment can be retrieved, is the

Content type: multipart/mixed;

Is it possible that attachments are not recognized and therefore not loaded from the server because of these differences?
It is also worth mentioning that the e-mail body is always empty, i.e. there is no further text in the mail. In the issues in the project, there have been some problems with this.
We have also already looked at the code. In the namespace Webklex\imap class message.php the content types are processed. There is no rule for text/xml.

**Comment by Webklex** [comment]
Please update to v2.0.0
