### ISSUE TITLE
Encoding error in the 'from -> personal' field if the username comes in Cyrillic

### ISSUE THREAD

**Issue by Dou-xx** [Webklex/laravel-imap#285]
**Hi, I found a mistake and a way to solve it.**

The error is that when you request a letter in which the sender's name is written in Cyrillic, it is incorrectly encoded. For example, letters from outlook come with the encoding koi8, and the encoding detection function defines this string as utf-8

![Снимок экрана от 2020-02-13 10-39-21](https://user-images.githubusercontent.com/26171810/74416196-6dcfba80-4e4d-11ea-9c28-4d79d52201ea.png)

problem in Webklex\IMAP\Message
line 611, the encoding is incorrectly determined

**To Reproduce**
1. Request a letter in which the sender is indicated in Cyrillic
2. dd($message)
3. See error

**How I solved this problem**
In the class Webklex \ IMAP \ Message on line 612, I added an encoding check that comes in the personal field
```
if($p->charset !== 'default' && $p->charset !== $encoding){
    $encoding = $p->charset;
}
```
![Снимок экрана от 2020-02-13 10-52-38](https://user-images.githubusercontent.com/26171810/74417292-221e1080-4e4f-11ea-81fa-be78019a0870.png)

**And now everything worked as it should**
![Снимок экрана от 2020-02-13 10-53-15](https://user-images.githubusercontent.com/26171810/74417391-4843b080-4e4f-11ea-8375-c475c2040fe3.png)

 - OS: UBUNTU 18.04
- PHP: [7.2]
 - Version laravel-imap 1.4.5

**Comment by bastianjoel** [comment]
I think this is fixed by #286
