### ISSUE TITLE
Pagination emtpy with page 2+

### ISSUE THREAD

**Issue by dragonfire1119** [Webklex/laravel-imap#287]
**Describe the bug**
If I try to paginate($count, $page=1); this will work but if I use paginate($count, $page=2); the collection is empty.

https://github.com/Webklex/laravel-imap/issues/225#issuecomment-514065623 This issue seems to have the same problem

**Tracking Bug**

Looks like this bug started here: https://github.com/Webklex/laravel-imap/blame/d38e0cc80803e6781f8f70fc6a391b74ad92e6cc/src/IMAP/Support/PaginatedCollection.php#L43

Started with this issue: https://github.com/Webklex/laravel-imap/issues/213

Added this line for forPage which returns empty collection: https://github.com/Webklex/laravel-imap/commit/26a503a7a4016984edcc5c5fc7377f6289397c20#diff-3a84d5239272d017767382eaabfd79c3R43

If you change that line to ``$results = $this->all();`` it works.

**Desktop / Server (please complete the following information):**
- PHP: 7.2
 - Version ^1.4

**Comment by koenhoeijmakers** [comment]
Running into the same issue, seems that the paginator is trying to slice a collection that already has been sliced.

Something along the lines of:
```
// returns only 5 items.
->get() 

// slices with an offset of 5 and selects item 6/10, while only 1/5 exists.
->paginate(5, 2)
```

I'm evading this issue by doing:
```->messages()->setPage($page)->setLimit(5)->get();```

**Comment by Webklex** [comment]
Please update to v2.0.0
