### ISSUE TITLE
Parsing calendar invites from email

### ISSUE THREAD

**Issue by edvordo** [Webklex/laravel-imap#289]
**Is your feature request related to a problem? Please describe.**
Somewhat, yes. I have a client which receives google calendar invites to a gmail account. These are however not sent as an attachment, or at least not an attachment recognized by this library.

**Describe the solution you'd like**
I was able to get it as an attachment (recognizable by at least mac calendar app and the google calendar web app) when I added this [here](https://github.com/Webklex/laravel-imap/blob/a7526f89a283b4d11c008aa37e4a7ff6dc7ef470/src/IMAP/Message.php#L666)
```php

            } elseif (strtolower($structure->subtype) == "calendar") {

                $structure->ifdisposition = 1;
                $structure->disposition = 'attachment';
                $param = new \stdClass();
                $param->attribute = 'name';
                $param->value = 'invite.ics';
                $structure->parameters[] = $param;
                if ($this->getFetchAttachmentOption() === true) {
                    $this->fetchAttachment($structure, $partNumber);
                }

            } elseif (strtolower($structure->subtype) == "html") {
```
This provided me with a file `invite.ics` with, as I said, a valid invitation.

---
I know it's not the cleanest solution, but it is a solution.

This is the structure the calendar invite come in
```
 #structure: {#3443
    +"type": 0
    +"encoding": 0
    +"ifsubtype": 1
    +"subtype": "CALENDAR"
    +"ifdescription": 0
    +"ifid": 0
    +"lines": 549
    +"bytes": 27442
    +"ifdisposition": 0
    +"ifdparameters": 0
    +"ifparameters": 1
    +"parameters": array:3 [
      0 => {#3451
        +"attribute": "CHARSET"
        +"value": "utf-8"
      }
      1 => {#3452
        +"attribute": "METHOD"
        +"value": "REQUEST"
      }
    ]
  }
```

One more thing. In case the invite is the only thing in the email, it has no text nor html body. In this case, at least from my limited testing, the email has a header `Content-Type: text/calendar; charset="utf-8"; method=REQUEST`

If anyone has a better solution, I'm open to it. In case this would be okay for you, I can PR it.

**Comment by edvordo** [comment]
Any update on this? @Webklex is this solution okay for you? Should I make a PR?

Not trying to rush anything, just kinda need this.

**Comment by edvordo** [comment]
Any feedback, even a `wontfix` would be appreciated.

**Comment by Stromspielplatz** [comment]
I have the same issue. My workaround it getRawBody() and parse it externally.

**Comment by edvordo** [comment]
Thanks @Stromspielplatz, but seems like google started sending those invites differently semi-recently, since this seems to be working fine now without any change to the code.
