### ISSUE TITLE
getMessages() could be very slow...

### ISSUE THREAD

**Issue by maverickchangithub** [Webklex/laravel-imap#29]
i am using Gmail account to retrieve emails.

getting folders is slow too , but getting messages is unacceptable , and it causes laravel crash....

i have only 200 emails in my folder

**Comment by Webklex** [comment]
Hi @maverickchangithub ,
have you checked which part exactly causes the delay? Also please verify your system load and check if your internet connection is actually working properly. Perhaps you ran into someones traffic limits? If you are using multiple accounts over the same IP and send to many requests to google - they might slow you down as well.

I personally use this library with an old mail account which holds round about 250k mails in several folders. I never had any problems with the actual script speed.

If you can't figure it out please provide any additional laravel error messages so anyone else (including me) can see what has actually happened and might be able to give you further assistance.

**Comment by maverickchangithub** [comment]
@Webklex thanks for the reply.

i am trying gmail for my app.  Maybe my code is not right. And some other email server would shut the link down.
I just wondering if you could give me some samples. 

Now i could display the folders of gmail and speed is OK , but getting the messages is really a problem .
My webmail is working fine , so it should not be a internet issue.

I often got the errors below : 

- The Response content must be a string or object implementing __toString(), "boolean" given. (most of the time)
- Failed to parse time string at position 41 (i): Double timezone specification
- Undefined property: stdClass::$disposition


my code : 
```
$oClient = Client::account('default');
	        $oClient->connect();

	        $mailboxes = $oClient->getFolders();

	        foreach ($mailboxes as $mailbox) {

	        	$messages = $mailbox->getMessages();

	        	return $messages; //this is for test purpose

	        }


```

Thanks for the help!!

**Comment by Webklex** [comment]
Hi @maverickchangithub ,
please update to the latest version. I think most of your problems should be resolved in v. [1.0.3.10](https://github.com/Webklex/laravel-imap/releases/tag/1.0.3.10). Please reopen this issue if you encounter any problems.

Best regards
Malte

**Comment by kill300r** [comment]
Hi I have the same issue...
Maybe my fetching is wrong I don't know,
this is my code and with 400 Mails the site crashes or takes forever to load

``` php

public function index()
    {
        //connect to User imap
        $oClient = connectimap();

        //Get INBOX Folder
        $oFolder = $oClient->getFolder('INBOX');

        //Get all Messages
        $aMessage = $oFolder->messages()->setFetchAttachment(false)->setFetchBody(false)->leaveUnread()->all()->get();

        //Pignate all Messages
        $paginator = $aMessage->sortByDesc('date')->paginate($perPage = 50, $page = null, $pageName = 'INBOX-PAGE');

        return view('Mail/home', compact('paginator'));
    }

```

``` blade
    <table id="mailtable" class="table table-inbox table-hover">
                      <tbody>
                        @if($paginator->count() > 0)
                          @foreach($paginator as $oMessage)
                            <tr class="{{ $oMessage->getFlags()['seen'] ? '' : 'unread' }} ">
                                <td class="inbox-small-cells">
                                  <input type="checkbox" class="mail-checkbox checkbox" name="check[]">
                                </td>
                                <td class="inbox-small-cells"><a href="/compose-mail/star/{{ $oMessage->getMessageId() }}"><i class="fa fa-star {{ $oMessage->getFlags()['flagged']==1 ? 'inbox-started' : ''}} "></i></a></td>
                                {{-- <a href="/viewmail/{{$oMessage->getMessageId()}}"> --}}
                                <td class="view-message dont-show">
                                  <a href="/viewmail/{{$oMessage->getMessageId()}}">
                                    @if (!empty($oMessage->getSender()[0]->personal))
                                      {{$oMessage->getSender()[0]->personal}}
                                    @else
                                      {{$oMessage->getSender()[0]->mail}}
                                    @endif
                                  </a>
                                </td>
                                <td class="view-message view-message">
                                  {{iconv_mime_decode($oMessage->getSubject())}}
                                </a></td>
                                <td class="view-message inbox-small-cells">{!! $oMessage->hasAttachments() ? '<i class="fa fa-paperclip"></i>' : '' !!} </td>
                                <td class="view-message text-right" style="min-width: 100px;">
                                  @if (date('Y-m-d',strtotime($oMessage->getDate()))== date('Y-m-d'))
                                    {{ date('H:i',strtotime($oMessage->getDate())) }}
                                  @elseif (date('Y-m',strtotime($oMessage->getDate()))== date('Y-m'))
                                    {{ date('D',strtotime($oMessage->getDate())) }}
                                  @elseif (date('Y',strtotime($oMessage->getDate())) != date('Y'))
                                    {{ date('d M Y',strtotime($oMessage->getDate())) }}
                                  @endif
                                </td>
                                {{-- </a> --}}
                            </tr>
                          @endforeach
                          {!! paginator->count() > 0 ? '<tr><td colspan="6"><center>'.$paginator->links().'</center></td></tr>'?'<tr><td colspan="6">No messages found</td></tr>'!!}

                      </tbody>
```

is there a way to solve this with queues ?
Thanks for any help!

**Comment by mmjjb** [comment]
@kill300r are you using Gmail, other, or own mail server?

**Comment by kill300r** [comment]
Hi @mmjjb 
No I‘m using the mail from my hosting provider world4you.com
