### ISSUE TITLE
Upgrade to Laravel 7.x

### ISSUE THREAD

**Issue by schmeits** [Webklex/laravel-imap#290]
Hi there,

May I ask when you're planning to upgrade to Laravel 7? I see there will be some errors because of some missing Symfony components (e.g. Symfony\Component\HttpFoundation\File\MimeType\ExtensionGuesser)

**Comment by schmeits** [comment]
Found a quickfix for my project (fetching attachments from a mail in a mailbox)

in file **src/IMAP/Attachment.php** replace line 298:

`return ExtensionGuesser::getInstance()->guess($this->getMimeType());`

by

`return MimeTypes::getDefault()->getExtensions($this->getMimeType())[0] ?? null;`

with the correct uses ofcourse

**Comment by koenhoeijmakers** [comment]
Just ran into this problem too, schmeits his fix works but editing vendor files is not really a way to go on production environments.

**Comment by Shohan494** [comment]
Same issue, 
Error
Class 'Symfony\Component\HttpFoundation\File\MimeType\ExtensionGuesser' not found..

Trying fixing from vendor for now, thanks @schmeits

**Comment by ricus-zero2one** [comment]
Same issue, however since we are using laravel 7, I opted to just replace my extension code with `Str::afterLast($attachment->getName(), ".")`

**Comment by Webklex** [comment]
Thanks for your suggestions. I've added a fix to support all laravel versions including 7.x.

Best regards,
