### ISSUE TITLE
How to fetch only new messages?

### ISSUE THREAD

**Issue by gajosadrian** [Webklex/laravel-imap#292]
**How to fetch only new/last messages?** I know that there's `new` or `unseen` flag or `since()` method in which you can't specify datetime (just date), but it doesn't really help me. I know that it's possible to write query like such: `UID 33:*` in raw query which will fetch all messages, which UID is 33 or higher. I didn't find any solution on how to write it in [the library wrapper](https://github.com/Webklex/laravel-imap). I just find out that in `Message::class` there's `'CUSTOM'` string in `where()`. No idea how to use it, the docs don't help me 😕

https://stackoverflow.com/questions/39402349/php-imap-search-uid-search-returns-false
https://dev.to/kehers/imap-new-messages-since-last-check-44gm

**Comment by jandominik** [comment]
Hi, I have same issue. Currently I'm trying to use `->where(sprintf('CUSTOMUID %d:*', 2))` which where method separate CUSTOM phrase and use just UID 2:*. I can see that method getRawQuery() successfully use my UID parameter but I'm still getting all e-mails (looks like my search parameter is ignored) but I've debugged that it is sent into imap_search() method. Any idea od progress?

**Comment by gajosadrian** [comment]
I believe PHP Api doesn't support "UID query".

**Comment by Webklex** [comment]
Hi @gajosadrian,
the new `Query::idle()` message reflects some of the behavior you are looking for :)

@jandominik take a look at `Client::overview()`. You can pass a sequence such as `2:*` to receive a list of all uids which are above then 2 . 

Best regards,
