### ISSUE TITLE
Invalid message date.

### ISSUE THREAD

**Issue by gajosadrian** [Webklex/laravel-imap#293]
**Describe the bug**
Invalid message date: `\vendor\webklex\laravel-imap\src\IMAP\Query\Query.php:223`

**To Reproduce**
Inside function `private function parseDate($header)`, `$date = $header->date;`, I had:
`$date == "Wed, 20 Mar 2019 11:50:16 +0000 <hidden_chars_C31A56@hidden_6MB5286.eurprd06.prod.outlook.com>"`. 
Carbon wasn't able to parse the date. Idk where's the problem but I believe I can remove the string from the date.

**Hotfix**
`$date = trim(substr($date, 0, strpos($date, '<')));`

**Desktop / Server:**
 - OS: Windows 10
- PHP: 7.3

**Comment by Webklex** [comment]
Hi @gajosadrian,
the Exception is correct. It looks like you've tried to search for emails with an invalid date. Please make sure the date you provide can be parsed by `Carbon::class`.

Best regards,

**Comment by krisnaw** [comment]
A similar issue appears when I try to loop through the messages on a folder and want to print the message subject.
