### ISSUE TITLE
Subject encoding

### ISSUE THREAD

**Issue by Naghal** [Webklex/laravel-imap#295]
**Describe the bug**
When saving subject to database, sometimes the subject output is different for messages with the same subject. (Ex. Two reply to the same message)
Reply A subject: 'Re: Accès SQL Anthony'
Reply B subject: 'Re: Acce`s SQL Anthony'
**To Reproduce**
1. Call `getMessage()` on message A
2. Call `getMessage()` on message B
3. The message A subject is Re: Accès SQL Anthony while message b subject is Re: =?utf-8?Q?Acc=C3=A8s_?=SQL Anthony

**Expected behavior**
Message should be the same for the two messages since the email source has the same subject and encoding information.

**Additionnal information**
To convert Re: =?utf-8?Q?Acc=C3=A8s_?=SQL Anthony to proper UTF8, I use the following function which when saved to database is correctly set to 'Re: Accès SQL Anthony'
```
private function convertSubjectEncoding($subject)
    {
        $encoding = mb_detect_encoding($subject);
        if($encoding != 'UTF-8') {
            return iconv_mime_decode($subject, 0, "UTF-8");
        }
        return $subject;
    }
```
The message which is saved as Re: Acce`s SQL Anthony in the database is already UTF-8 when I call `getSubject()`
I have tried UTF-8, ASCII and nothing as `decoder.message.subject` setting.

**Screenshots**

**Desktop / Server (please complete the following information):**
 - OS: [Linux]
- PHP: [7.4]

**Additional context**
Here is the email source of email a and B (Subject part only)
A: `Subject: Re: =?utf-8?Q?Acc=C3=A8s_?=SQL Anthony`
B: `Subject: =?UTF-8?Q?Re=3A_Acc=C3=A8s_SQL_Anthony?=`

**Comment by OysteinHoiby** [comment]
Hi, 

I had the same issue, and found a workaround. I'm not sure if this is the best approach to this issue, anyway this worked for me:

In Message.php on line 401 change
                `$this->subject = imap_utf8($header->subject);`
to
`  $this->subject = iconv_mime_decode($header->subject);`

**Comment by Naghal** [comment]
Hi, I ended up doing something similar. However, I am also forced to replace accented caracters with normal ones.
I.E: é become e
`normalizeChars(iconv_mime_decode($subject, 2, "UTF-8"));`

The workaround you mentionned can not be used in my case as I need to compare the subjects of multiple messages to group them by conversation. (Looking at references also)
If I did only use `iconv_mime_decode`, message A would have an accent and not the B, so the comparison would fail.

**Comment by Vishrut-1** [comment]
mb_decode_mimeheader($oMessage->getSubject());
Try this it will work.

**Comment by Webklex** [comment]
Please update to the latest version and take a look at the available config option `imap.options.decoder.message.subject`.
If you want to use `mb_decode_mimeheader()` set it to `mimeheader` or to `iconv` if you want to use `iconv_mime_decode()`.

Best regards,

**Comment by sachinaquilmedia** [comment]
when I compare the Marathi language subject with encoded subject  then the data is null .help me .

**Comment by freescout-helpdesk** [comment]
https://github.com/Webklex/php-imap/issues/410

**Comment by Hardik0078** [comment]
**Subject issue**- fetching email from the mail server with this package subject coming in this format =?UTF-8?B?4KSo4KS/4KS14KS/4KSm4KS+IOCkuOCkguCkluCljeCkr+CkviBHRU0vMjAyMy9CLzM0OA==?= =?UTF-8?B?MTcwOCDgpK7gpYfgpIIg4KSr4KS+4KSH4KSo4KWH4KSC4KS44KS/4KSv4KSyIOCksOClh+CknyDgpJU=?= 

how can i fix this?
i used iconv_mime_decode function but it not works

**Comment by freescout-helpdesk** [comment]
Working solution is described here: https://github.com/Webklex/php-imap/issues/410

Here is the result:
![2023-06-08_13-55-01](https://github.com/Webklex/laravel-imap/assets/40499291/da797809-ac6b-408a-a7ff-4c07017253ab)

**Comment by Hardik0078** [comment]
it works,  Thank you so much @freescout-helpdesk  .
