### ISSUE TITLE
error when trying to get count of spam mails

### ISSUE THREAD

**Issue by jitin-joseph** [Webklex/laravel-imap#296]
I'm getting issue while trying to get the count of spam mails.

The code line is

$junk_message_count = $oFolder->query()->whereIsXSpam()->count();

when trying to get it, the message comes like 

InvalidWhereQueryCriteriaException in WhereQuery.php line 106:

![Screenshot 2020-03-30 at 12 35 53 PM](https://user-images.githubusercontent.com/62872551/77884629-0ea1fa00-7283-11ea-8d11-a56d251c86b5.png)

**Comment by Webklex** [comment]
Hi @jitin-joseph ,
thanks for your report. I've just released a fix. Please update to the latest version.

Best regards,
