### ISSUE TITLE
handle error when connect wrong

### ISSUE THREAD

**Issue by iceball1** [Webklex/laravel-imap#297]
Hi.
How can I handle error when connect error (password wrong , username wrong , port wrong ...)
I tried to "try...catch" on $oClient->connect() function but it don't work

**Comment by Webklex** [comment]
Hi @iceball1 ,
you can just catch `Webklex\IMAP\Exceptions\ConnectionFailedException`:
```php
try {
    $oClient->connect();
}catch (\Webklex\IMAP\Exceptions\ConnectionFailedException $e){
    dd("Whoops: ".$e->getMessage());
}
```

Best regards,
