### ISSUE TITLE
Get Attachments

### ISSUE THREAD

**Issue by silwestro** [Webklex/laravel-imap#298]
Please be aware that these issues will be closed if inactive for more then 14 days :)
I need support for get attachments i use getAttachments() method  on single message and return always an empty array. If I count attachments, I got a right number of attachments. Can I have a right step for to get and download the attachments.
Thanks
Sorry for bad English

**Comment by nhathoangfarmtech** [comment]
me too

**Comment by Msrgit** [comment]
Try something like this...
```
$oC=Webklex\IMAP\Facades\Client::account('reception');
$oC->connect();
$oF=$oC->getFolder('INBOX');
$mm=$oF->query()->where("SUBJECT","Code:")->get();
foreach($mm as $m){
    $tb=$m->getTextBody();
    echo $m->from[0]->mail."\n";
    echo $m->subject."\n";
    echo $tb."\n";
    $aa=$m->getAttachments();
    foreach($aa as $a) {
        echo "+++".$a->name."\n";
        $a->save(storage_path('reception'));
    }
    $m->delete();
}
```

**Comment by Vishrut-1** [comment]
u need to do this in foreach loop

            foreach ($oMessage->getAttachments() as $attach) {
                $masked = $attach->setMask(AttachmentMask::class);
                $temp = [];
                $temp['mask'] = $masked->mask();
                $temp['image_url'] = $temp['mask']->getImageSrc();
                $temp['attachment_name'] = $temp['mask']->getName();
                $temp['disposition'] = $temp['mask']->getDisposition();
                $temp['size'] = $temp['mask']->getSize();
               //array_push()
            }
and push this values  in array and return the array
u will get the all ataachments
