### ISSUE TITLE
How to view the selected message

### ISSUE THREAD

**Issue by umutpamuk** [Webklex/laravel-imap#299]
I am doing one web mail application.
I could not find how to open the message on the selected topic.
I think I'd match it with getUid () but I couldn't.

$oClient = Client::account('default');
$oClient->connect();
$aFolder = $oClient->getFolders('INBOX');
foreach($aFolder as $oFolder){
    $aMessage  =  $oFolder -> query () -> whereAll ()
        -> setFetchFlags ( false )
        -> setFetchBody ( false )
        -> setFetchAttachment ( false )
        -> get ();
}

I can read it by saying $ aMessage-> getTextBody (). but the last message in the inbox is coming. The message of the subject I clicked is not coming.

**Comment by achrarajeev** [comment]
you can do by passing message id, see below example. 

//Connect to the IMAP Server
    $oClient->connect();
  //Get all Mailboxes
 /** @var \Webklex\IMAP\Support\FolderCollection $aFolder */
$aFolder = $oClient->getFolder('INBOX');
$oMessageNew = $aFolder->getMessage($id,null,null,null,TRUE);

$oMessageNew->getSubject();
$oMessageNew->getDate();
$oMessageNew->getFrom();
