### ISSUE TITLE
[ErrorException]   Use of undefined constant FT_UID - assumed 'FT_UID'

### ISSUE THREAD

**Issue by Reegan01** [Webklex/laravel-imap#30]
Hi,

I got this error 
`[ErrorException]
  Use of undefined constant FT_UID - assumed 'FT_UID'` when I add your provider and alias into `config\app.php` inside the arrays of `providers` and `aliases` . Your document also wrongly indicate to add the provider and alias inside  `config/imap.php` please check the document and change to `config/app.php`

Thanks for your contribution to the open source world.

**Comment by maverickchangithub** [comment]
i had this before , the doc says , put in the imap.php , not config.php. then everything should work

**Comment by Webklex** [comment]
Hi @Reegan01 ,
thanks for your report. I already updated the README.md. For the otherwise issue please take a look at this older simular issue: [#14](https://github.com/Webklex/laravel-imap/issues/14).

Please let ne know of you are still having this issue. If so please provide the requested informationen from issue #14 .

Best regards

**Comment by Reegan01** [comment]
Thanks for your reply,

So, based on your README.md  I want to add the `provider` to `config/app.php` and `alias` to `config/imap.php` correct?

**Comment by pan-tom** [comment]
I had this error when my hadn't installed php IMAP module in my xammp.

**Comment by Reegan01** [comment]
Now working perfect and fast in my online server.  Thanks @Webklex for your contribution. 

I have a query, Now I can list and view my inbox in my Dashboard. But I also want to compose mail from  dashboard. So what I want to use for compose mail ?  For compose mail If I use Laravel default SMTP mail option, Is that mail will save automatically in my online mail server(send items folder) ?

**Comment by Webklex** [comment]
@Reegan01 yes you are right, for sending mail you should consider to use the "native" laravel Mail class. They have a well documentation: [https://laravel.com/docs/5.5/mail](https://laravel.com/docs/5.5/mail)

**Comment by AndreVME** [comment]
I've been struggling with this error for the past 3 hours. I un-installed and re-installed a number of times. Turns out all I had to do is "valet restart" after following the instructions on here.

**Comment by Reegan01** [comment]
@AndreVME you must add the `provider` and `alias` in config/app.php page. Not in config/imap.php page.

**Comment by allandereal** [comment]
I solved this by installing php-imap module and uncommenting php_imap.dll in php.ini

**Comment by aminefilali1** [comment]
I had the same issue and I resolve it by installing PHP IMAP extension : 
for Linux: **sudo apt-get install phpX.X-imap**

**Comment by SirPoot-** [comment]
@aminefilali1 Thank you. I installed it on development and forgot to in production

**Comment by Loafer19** [comment]
in php.ini must be on imap extension

**Comment by tonitch** [comment]
I'm sorry if I "re-open" a closed issue, I think this is relevent here.

I'm a archlinux user and my distro just stoped supporting php-imap for [security resons](https://archlinux.org/news/php-82-update-and-introduction-of-legacy-branch/) and I know that when arch does something usually after several month, other distro do kinda the same.

So I was wondering... is there an alternative to make this work ? I don't really know the project too much I'm just looking on the internet for a solution since about an hour and kinda figured this out, I hope this is kinda the right place to go. I'm just trying to install freescout tho.

**Comment by Webklex** [comment]
Hi @tonitch ,
it depends on the version you are trying to install. The issue used to occur in v1-v2 and happen if the imap module wasn't installed. Those constants don't get used in newer versions and therefor aren't present anymore.

Best regards,

**Comment by spikerguy** [comment]
I am trying to install freescout to test and using rockylinux9, so there is no php-imap pkg anymore. 

The workaround is not clearly documented. 

Is there any clear documentation I can follow ?

**Comment by tonitch** [comment]
> I am trying to install freescout to test and using rockylinux9, so there is no php-imap pkg anymore. 

Have you tried installing it with PECL ?

https://www.php.net/manual/en/imap.installation.php

> The workaround is not clearly documented. 

php 8.4 dropped 4 days ago, I don't think this is uncommon for
documentation to be a bit behind at this point ^^ 

> Is there any clear documentation I can follow ?

This depend on your linux install, here is the generic php
documentation: https://www.php.net/manual/en/install.pecl.php

cheers,
tonitch

**Comment by spikerguy** [comment]
> I am trying to install freescout to test and using rockylinux9, so there is no php-imap pkg anymore.
> Have you tried installing it with PECL ? https://www.php.net/manual/en/imap.installation.php
> The workaround is not clearly documented.
> php 8.4 dropped 4 days ago, I don't think this is uncommon for documentation to be a bit behind at this point ^^
> Is there any clear documentation I can follow ?
> This depend on your linux install, here is the generic php documentation: https://www.php.net/manual/en/install.pecl.php cheers, tonitch

Thank you for the quick response. 

I have dropped the idea of using imap as it is better for users to just raise ticket from a single point. 

Though I am stuck with another issue where the system does not send out email when agent reply to the ticket. Should I raise a separate issue here or is there any documentation for the same ?

Regards,

**Comment by tonitch** [comment]
Yes you should create a new issue, technically this issue is already
necroposting.
