### ISSUE TITLE
How to get an email by id

### ISSUE THREAD

**Issue by singh304** [Webklex/laravel-imap#302]
I wanted to how I can I get an email by its id

```
$oFolder = $oClient->getFolder('INBOX');
$message = $folder->query()->limit(1)->get()->first();
$aMessage = $oFolder->search()->messageId($id)->get();
```

Tried this but does work

**Comment by ricus-zero2one** [comment]
See [https://github.com/Webklex/laravel-imap#fetch-a-specific-message](url)

**Comment by UmeshKrRana** [comment]
Using this way, I have fetched the specific email by UId 

`$folders = $client->getFolders();

            echo "<pre>";

            foreach($folders as $folder) {
                $email = $folder->getMessage($uid = 4663);
                print_r($email);

            }`

But the main issue is -
 it returns the email in the object format which is difficult to convert it to an array or to print into the view.

**Comment by ricus-zero2one** [comment]
You need to handle that object and display what you need from it. Want to display the subject? Then. just do `->getSubject()` etc
