### ISSUE TITLE
Move email to trash

### ISSUE THREAD

**Issue by umutpamuk** [Webklex/laravel-imap#304]
How do I move my e-mails deleted in the Webklex Laravel imap package to the trash. deletion is running. But I can't move. When I make the folder dd, I only see the INBOX path.

$oMessage->moveToFolder('INBOX.Trash',TRUE);
$oMessage->delete();

**Comment by Vishrut-1** [comment]
u just have to do simple do this
$oMessage = $oFolder->getMessage('uid'); 
$oMessage->moveToFolder('Trash','true');

by doing this message will move to imap trash folder u don't have to use delete.
