### ISSUE TITLE
How to Reply on MessageID to continue an email thread?

### ISSUE THREAD

**Issue by UmeshKrRana** [Webklex/laravel-imap#306]
I have listed out the emails using the Webklex Laravel Imap and got the MessageID with other parameters. Now, my issue is how to reply to the same MessageId in **Reply** and **Reply All** email.

If I will compose an email to Reply Email then it will create a new thread instead of the old one.

So, how to achieve this. Help me out with this issue.

Thank you.

**Comment by umutpamuk** [comment]
You need to add messageID and reference to the header part of the message you reply. Maybe it helps if I used it this way.

`Mail::send([], [], function ($message) use ($aRequest) {
            $references = $aRequest->references . '<' . $aRequest->messageId . '>';
            $message->getHeaders()->addTextHeader('In-Reply-To', $aRequest->messageId);
            $message->getHeaders()->addTextHeader('References', $references);
            $message->from($message->getFrom());
            $message->sender($message->getFrom());
            $message->to($aRequest->to);
            $message->replyTo($message->getFrom());
            $message->subject($aRequest->subject);
            $message->setBody($aRequest->replyMessage);`

**Comment by umarpucitian** [comment]
What did you pass the value for references and to i.e $aRequest->references and  $aRequest->to

**Comment by dev7-abood** [comment]
"What did you pass the value for references and to i.e $aRequest->references and $aRequest->to
Same" 
Same question

**Comment by Webklex** [comment]
Hi @umarpucitian @dev7-abood ,
lets assume these are the headers of a mail you want to replay to:
```
To: Webklex/laravel-imap <laravel-imap@noreply.github.com>
Message-ID: <Webklex/laravel-imap/issues/306/959942153@github.com>
In-Reply-To: <Webklex/laravel-imap/issues/306@github.com>
References: <Webklex/laravel-imap/issues/306@github.com>
Subject: Re: [Webklex/laravel-imap] How to Reply on MessageID to continue an
 email thread? (#306)
```

- If the email has an In-Reply-To header, add it to the list of References
- Use References, if it exists, to match to Message Ids of other emails (in whatever system/code you're working with)

In this case `$aRequest->references ` could be `<Webklex/laravel-imap/issues/306@github.com>` or anything else, if you want to reference it to an other message / topic.
`$aRequest->to` has to be the email address of whoever is supposed to receive the message you are sending.

Additional information: 
- https://cr.yp.to/immhf/thread.html
- https://laravel.com/docs/8.x/mail

Best regards,

**Comment by dev7-abood** [comment]
ok 
assume i use Gmail platform 
$oldMessageId = <old_id>
$ref = <old_id><new_id>

from new_id i use $message->getId()

And I add the 
$message->getHeaders()->addTextHeader('In-Reply-To',  $oldMessageId);
$message->getHeaders()->addTextHeader('References', $ref);

I understand the text pattern but i don't know what is this values

**Comment by Webklex** [comment]
Hi @dev7-abood ,
I'm not sure what your question is. 
- What are you currently trying (code wise)?
- What results are you getting?
- What are you expecting?

Best regards,

**Comment by dev7-abood** [comment]
My issue is i tryed to replay old meassage from Email using laravel  
![aaa](https://user-images.githubusercontent.com/28537192/140194220-b6b7fb2c-8c3a-48fb-95f5-f90dc2bcceb9.PNG)

**Comment by Webklex** [comment]
hmm.. this library `webklex/laravel-imap` is only a wrapper for `webklex/php-imap` made to fetch messages from a server via the imap protocol. If you want to send messages, you should take a look at the official documentation under https://laravel.com/docs/8.x/mail.

The code example from above assumes you've read a message using `webklex/php-imap` and placed part of the header (In-Reply_to, Reference, Subject, etc) in a form and submitted it. At least that is what im reading into it. You usually handle a `$request` or `$aRequest` somewhere within a controller or something.

If you want to have access to the latest request, you'll have to make the request available to your mailable callback.

I Highly recommend you checkout https://laravel.com/docs/8.x/mail. Their documentation is extremely well written and provides lots of examples.

Best regards,

**Comment by dev7-abood** [comment]
Thank You for help me :)
@Webklex

**Comment by s72817** [comment]
Do I have to store the reply mail to the "sent" folder? because I tried "all" things I found on internet like additional headers In-Reply-To or References or Message-ID. But I never see that mail in the thread.
