### ISSUE TITLE
Support StartTLS

### ISSUE THREAD

**Issue by Clausinho** [Webklex/laravel-imap#307]
**Is your feature request related to a problem? Please describe.**
Allow for real STARTTLS Support because apparently just adding the alias does not seem to work
**Describe the solution you'd like**
Working StartTLS support
**Describe alternatives you've considered**
Mail Server could switch to imaps, its a protocol recommended anyways
**Additional context**
I am aware of https://github.com/Webklex/laravel-imap/commit/e84ff4e27a196b41f14df4df740b87bb9fe11075
but I still get the Error "SSL negotation failed" in freescout (see https://github.com/freescout-helpdesk/freescout/issues/627)

**Comment by Webklex** [comment]
Hi @Clausinho ,
please take a look at https://www.php.net/manual/en/function.imap-open.php. `StartTLS` is not directly supported and is aliased with `tls`. I guess there isn't really a way to support startls. 

If I'm wrong please feel free to reopen this issue :)

Best regards,
