### ISSUE TITLE
Is it necessary to connect imap client on every request of email listing?

### ISSUE THREAD

**Issue by UmeshKrRana** [Webklex/laravel-imap#308]
I want to make imap connection one time for the logged-in user by creating a function like this -

`public function connectImap(Request $request) {

 $client         =       new Client([
            'host'                  =>          $request->imap_host,
            'port'                  =>          $request->imap_port,
            'encryption'        =>          $request->imap_encryption,
            'validate_cert'     =>          true,
            'username'          =>         $request->user_name,
            'password'          =>         $request->password,
            'protocol'           =>          'imap'
        ]);  
       $connect_response  =          $client->connect();

       dd($connect_response);
}`

So, I want to know. Is it necessary to connect imap every time before getting emails. Cannot we do by connecting the client one time and next time we will get the email response on the behalf of the previously connected client?

I don't know this will be a good approach but if it is possible then please help me out to achieve this.

**Comment by tetrode** [comment]
Facing the same issue, writing a CLI program that polls for new mails every 5 seconds but no new mails are seen unless a new login is done.

**Comment by icaroscherma** [comment]
I don't think it's a good idea using plain PHP because of the its lifetime being request-oriented, if you use ReactPHP or Swoole for instance, as they are an event-driven enviroment instead of a request-driven it's just setting it as a singleton for the logged-in user. ;)

**Comment by tetrode** [comment]
True, however, when using ReactPHP, how do I know that there is a new message in the IMAP inbox?

**Comment by icaroscherma** [comment]
Since this library is not event-oriented, you can setup a Laravel Artisan (shell) command to check the ID of the latest email and add it to your cron jobs, so each `N` minutes it will run this command and update a flag in your database or emmit a command in your dashboard, it's up to you.

**Comment by Webklex** [comment]
Hi  @UmeshKrRana @tetrode @icaroscherma ,
you are right. I think its not trivial to archive something like this but the feature requests for an "idle" connection already exists. If someone feels like looking into it, please head over to #185 .

If I'm wrong and you've meant something else, please feel free to reopen this issue.

Best regards,
