### ISSUE TITLE
getHtmlBody returns binary string sometimes

### ISSUE THREAD

**Issue by Naghal** [Webklex/laravel-imap#311]
**Describe the bug**
Sometimes, the method `getHtmlBody()` returns a binary string instead of a string. This make it impossible to save it in my database without me calling manually `utf8_encode()` on the binary string. However, calling `utf8_encode` on normal string that was properly encoded result in weird characters in the final string.

**To Reproduce**
I do not know how to reproduce this issue. I only get this strange behaviour from 1 particular sender.
However, here is the details of my own investigations: https://stackoverflow.com/questions/62663514/how-to-convert-binary-string-to-normal-string-in-php

**Expected behavior**
`getHtmlBody()` should always return a string.

**Screenshots**

**Desktop / Server (please complete the following information):**
 - OS: Linux ubuntu 18.04
- PHP: 7.4
 - Package version: 1.4.5

**Additional context**
Details of my own investigations and what I have tried so far: https://stackoverflow.com/questions/62663514/how-to-convert-binary-string-to-normal-string-in-php

**Comment by Webklex** [comment]
Hi @Naghal,
please update to the [latest version](https://github.com/Webklex/laravel-imap/releases) and give it another try.

Best regards,
