### ISSUE TITLE
How to compose - reply - forward email with attachment 

### ISSUE THREAD

**Issue by achrarajeev** [Webklex/laravel-imap#312]
I want to compose the email with an attachment and want to send it. How i can achieve this? 
Also, i didn't get the option reply, reply to, and forward the email.

**Comment by Medboubazine** [comment]
Folwing 👍

**Comment by Webklex** [comment]
Hi @achrarajeev @Medboubazine ,
please take look at https://laravel.com/docs/7.x/mail for sending emails in laravel.

However you could use this library to create new messages inside your mailbox (without sending it) using this library. Take a look at  `Webklex\IMAP\Folder::appendMessage()` if thats your plan :)

Best regards,
