### ISSUE TITLE
Parse addresses in arabic language

### ISSUE THREAD

**Issue by Medboubazine** [Webklex/laravel-imap#314]
Arabic characters in adresses **[ 'from','sender','to','cc',bcc','reply_to']**
### Example
$msg->getFrom() give this array :
`[{"personal":"\u200e\u0627\u0644\u0641\u062a\u0649 \u0627\u0644\u0645\u062c\u0646\u0648\u0646\u200e","mailbox":"notification","host":"facebookmail.com","mail":"notification@facebookmail.com","full":"\u200e\u0627\u0644\u0641\u062a\u0649 \u0627\u0644\u0645\u062c\u0646\u0648\u0646\u200e <notification@facebookmail.com>"}]`
But original is :
`\u200e\u0627\u0644\u0641\u062a\u0649 \u0627\u0644\u0645\u062c\u0646\u0648\u0646\u200e === الفتى المجنون `

### Desktop

 - OS: [WINDOWS 10]
- PHP: [7.4]
- VERSION [1.4.5]

**Comment by Hokan22** [comment]
Hi,
maybe #325 will fix your issue?

**Comment by Webklex** [comment]
Hi @Medboubazine ,
please update to the [latest version](https://github.com/Webklex/laravel-imap/releases) and give it another try :)

Best regards,
