### ISSUE TITLE
why Query where text($searchValue) Does not work? why should i put % before or after the search value or i get null result.

### ISSUE THREAD

**Issue by khaledw62** [Webklex/laravel-imap#315]
**Describe the bug**
the search query seems to has a bug first of all i must pass a null to the query then when i use query()->text($searchValue)->get();
i got null result 

**Expected behavior**
i should use a operator like Larval Query , query()->text($operator,$searchValue)->get();

**Desktop / Server (please complete the following information):**
 - OS: [e.g. MacOs]
- PHP: [e.g. 7.3.8]
 - Laravel [e.g. 5.8.36]

**Comment by Webklex** [comment]
Hi @khaledw62 ,
please be aware that this is a wrapper for IMAP communication which is far away from any database behavior :)

But I was inspired by the eloquent query builder and tried to implement some of it based on the IMAP search rfc standards. However do to the nature of IMAP it has to work a bit different.

For example operators are not implemented / supported by IMAP (There are some odd ones out there but in general it's not supported and usually some sort of modified imap protocol). 

Best regards,
