### ISSUE TITLE
Outlook office 365 queries do not return emails

### ISSUE THREAD

**Issue by alexv96** [Webklex/laravel-imap#316]
I work with outlook office emails. The thing is that I want to bring only the emails from the last 5 days, but I don't get anything back.

If I use this line they bring me the data.

`$aMessage = $aFolder->query()->limit(10)->get();` //return the data

But if I use this query it doesn't bring me anything.

```
$aMessage = $aFolder->query()->since(Carbon::now()->subDays(5))->get(); //This line not return the data 

        foreach ($aMessage as $oMessage) {
            echo 'ID: '. $oMessage->getUid() ."\n";
            echo $oMessage->getSubject() .' | The date of the mail is from : '. $oMessage->getDate() . "\n";
        }
```

**Comment by yusufonur** [comment]
I am using Laravel 7 and I am suffering from this problem too. 
I review a few issue and https://github.com/Webklex/laravel-imap/issues/189 this but not find solution.

**Comment by alexv96** [comment]
> I am using Laravel 7 and I am suffering from this problem too.
> I review a few issue and #189 this but not find solution.

`$aFolder->query(null)->since(Carbon::now()->subDays(30)->format('d-m-Y'))->limit(50)->get();`

**Comment by yusufonur** [comment]
> > I am using Laravel 7 and I am suffering from this problem too.
> > I review a few issue and #189 this but not find solution.
> 
> While it has worked for me by placing a limit on the query to searches by date.
> 
> `$aFolder->query(null)->since(Carbon::now()->subDays(30)->format('d-m-Y'))->limit(50)->get();`

Very interesting. If  we don't add null parameter to the chained method named query, it doesn't work. I gues default value utf-8 causes error
