### ISSUE TITLE
Exception handling not working

### ISSUE THREAD

**Issue by vidhip20** [Webklex/laravel-imap#319]
I want to show user whether the configuration for the credentials is correct or not, and if not then need to show the error messages for that connection.

For that i have used this code in my controller:

try {
	$oClient->connect();
} catch(ConnectionFailedException $e) {
	dd($e->getMessage());
}

But instead of displaying error messge it is displaying
ConnectionFailedException in Client.php line 299:
imap_open(): Couldn't open stream {****}. Retrying PLAIN authentication after AUTHENTICATE failed; Can not authenticate to IMAP server: [CLOSED] IMAP connection broken (authenticate)

Can anyone help me with displaying errors messages to user instead on this exception?

**Comment by Webklex** [comment]
Hi @vidhip20 ,
please provide more details such as php version, laravel-imap lib version, laravel version, os,  etc. I can't replicate your finding.

**Tested with the following:**
```php
try {
    $oClient->connect();
}catch (\Webklex\IMAP\Exceptions\ConnectionFailedException $e){
    dd("Whoops: ".$e->getMessage());
}
```

Best regards,
