### ISSUE TITLE
Get original recipient in case of forwarded mails

### ISSUE THREAD

**Issue by chmoelders** [Webklex/laravel-imap#320]
First of all, thank you for this awesome package. It saves me a lot of work!

With `$message->getFrom()` I'm able to get the senders of an email. In some cases mails are forwarded to my mailbox with the original sender and recipients.
Because my code needs the original recipient, I've written this helper method to receive the original recipient.

Can you please confirm this is the proper way.
```
    /**
     * Get original recipient-address, also if mail is forwarded.
     *
     * @param  Message  $message
     * @return string
     */
    private function getOriginalRecipient(Message $message): string
    {
        $receiver = $message->getTo()[0]->mail;

        if ($receiver === config('imap.accounts.default.username')) {
            return $message->getFrom()[0]->mail;
        }

        return $message->getTo()[0]->mail;
    }
```

**Comment by Webklex** [comment]
Hi @chmoelders ,
you would have to either search through the message content or implement a custom mask-method to such thing for you.
If you forward an email, the client usually writes the information you are looking for into the body and removes them from the header. However every client does this a bit different, therefor I think you'll have a hard time catching all...

Best regards,
