### ISSUE TITLE
New breaking error since 1.5.0 - MessageMovedEvent not enough parameters

### ISSUE THREAD

**Issue by devsi** [Webklex/laravel-imap#322]
**Describe the bug**
On this line since 1.5.0 you added Event:

https://github.com/Webklex/laravel-imap/blob/d56d2cc9ca5e64be951bea2310dfc0b176da6caa/src/IMAP/Message.php#L1004

But the MessageMovedEvent has this signature

https://github.com/Webklex/laravel-imap/blob/d56d2cc9ca5e64be951bea2310dfc0b176da6caa/src/IMAP/Events/MessageMovedEvent.php#L20:

You are missing the second parameter for the event. The result is that `message->moveToFolder` does not work and throws an error:

`Too few arguments to function Webklex\IMAP\Events\MessageMovedEvent::__construct(), 1 passed in /var/www/vendor/webklex/laravel-imap/src/IMAP/Events/Event.php on line 15 and exactly 2 expected`

**Comment by Webklex** [comment]
Hi @devsi ,
thanks for your report. I just tested and released a patch :)

Best regards,

**Comment by devsi** [comment]
Thanks for the quick response. Can I confirm the following (due to confusing name of function)

moveTofolder() fetches the message as here:

https://github.com/Webklex/laravel-imap/blob/d27f53c1ab3a059b5cfb7ed867ab49aae209806a/src/IMAP/Message.php#L1003-L1004

Does this not get a singleMessage object, rather than an array? and if so, does referencing the message as `$messages[0]` remain broken? I haven't tested this, I just ask in theory.

https://github.com/Webklex/laravel-imap/blob/d27f53c1ab3a059b5cfb7ed867ab49aae209806a/src/IMAP/Events/MessageMovedEvent.php#L19-L21

**Comment by Webklex** [comment]
`MessageMovedEvent::dispatch` resolves to:
```php
public static function dispatch() {
    return event(new static(func_get_args()));
}
```
..the two given variables get "cought" by `func_get_args()` which returns an array of the two given variables which then get used to initialize the original event class. In this case an array containing the old and new message :)

If you have php 7.x running you could also do the following and use the variables directly:
```php
public static function dispatch() {
    return event(new static(...func_get_args()));
}
```
..however that's in this case not an option, since laravel 5.0 doesn't require php 7.x.

**Comment by devsi** [comment]
I understand. I didn't see the dispatch() function in the parent class. That makes much more sense.

Thanks for explaining!
