### ISSUE TITLE
Class 'Webklex\IMAP\IMAP' not found

### ISSUE THREAD

**Issue by ibroh24** [Webklex/laravel-imap#323]
**Describe the bug**
Please, help me out!

Ive been able to add Webklex Mail Receiver package to my laravel project, and its been doing fine on localhost, but when uploaded the concern files to cPanel, i got an error that says **Class 'Webklex\IMAP\IMAP' not found**.

All precaution was made (i check the cPanel php.ini for imap, and it was checked by default), but i cant even get to index page for now, i tried to comment out all the dependencies but still cant get in. 

![imap](https://user-images.githubusercontent.com/26309549/91776127-415a7080-ebdc-11ea-9fc3-db9a3021290f.PNG)

**Comment by Webklex** [comment]
Hi @ibroh24 ,
that sounds like a server issue. Perhaps you havn't copied all required files from your dev environment? I would recommended you don't copy any vendor / tmp files from your dev environment onto your server. Try to run composer there instead. If that isn't possible for some reason make sure that the php versions are identical.

Best regards,
