### ISSUE TITLE
MessageCollection items with empty key

### ISSUE THREAD

**Issue by Gmacko** [Webklex/laravel-imap#328]
**Describe the bug**

Hi, I have a little problem when I try to get messages wihout `Message-ID` header.

When I make a query and I apply the get function on mails without `Message-ID` header, the get method returns a collection with an unique result but the total has an another value. 

In the `items` array, I have an empty key.

**To Reproduce**

1. Send emails on a box without `Message-ID` header

```php
$client = new Client([
            'host' => "",
            'port' =>  "",
            'encryption' => "SSL",
            'validate_cert' => true,
            'username' => "",
            'password' => "",
            'protocol' => "imap",
        ]);

$messages = $client->getFolder('INBOX')->from('email@example.com')->get();

dd($messages);

```

**Expected behavior**

If no `Message-ID` is presents in headers add an incremetal key or a random key to preserve this messages.

**Desktop / Server (please complete the following information):**
 - OS: linux
- PHP: v7.0.33
 - Version: 1.6.2

**Comment by Webklex** [comment]
Hi @Gmacko ,
you can change the used key in your `config/imap.php` config file.

Just change `imap.options.message_key` from `id` to `number` or `list` :)

Best regards,

**Comment by Gmacko** [comment]
Thanks for your reply.
