### ISSUE TITLE
Cache problem? Timeout on many mails? Paginate not working?

### ISSUE THREAD

**Issue by MalteKiefer** [Webklex/laravel-imap#329]
Good morning,

I have a little problem, and I hope you can help me.
I tried to open an Office365 Mailbox with more than 1800 Mails in the INBOX folder, like this:

```php
        $client = new Client([
            'host'          => 'outlook.office365.com',
            'port'          => 993,
            'encryption'    => 'ssl',
            'validate_cert' => true,
            'username'      => 'username',
            'password'      => 'password',
            'protocol'      => 'imap'
        ]);

        $client->connect();
        $folder = $client->getFolder('INBOX');
        $messages = $folder->query(null)->limit(10)->get()->paginate($perPage = 2, $page = null);;
```

That works, but this command

```php
{{$mailFolders->links()}}
```

show over 800 pages. I can click on page 832 but then I see "No messages found".

When I tried it like this:

```php
        $folder = $client->getFolder('INBOX');
        $messages = $folder->query(null)->get()->paginate($perPage = 2, $page = null);;
```
my Laravel crashed. I must kill the Laravel process to get it work again. So my question is, is there a problem with mailbox in this size or is there a way to cache and only get the new mails? 
I tried it with a different mailbox too. Same problem.

**Comment by Webklex** [comment]
Please update to v2.0.0 :)
