### ISSUE TITLE
getFolders() works on some IMAP accounts but fails on Exchange Server.

### ISSUE THREAD

**Issue by Stromspielplatz** [Webklex/laravel-imap#330]
I use Webklex\IMAP\Client::getFolders() to get all folders of an IMAP mail account. It works fine on my Gmail and my GMX test account but fails on exchange server.

    $oClient->connect(); //OK
    $aAvailableFolders = $oClient->getFolders()->all(); //FAILS

    Exception trace:
    1   Webklex\IMAP\Client::getFolders("Kontakte/%")
      /var/www/html/jira42/vendor/webklex/laravel-imap/src/IMAP/Client.php:371
    2   Webklex\IMAP\Client::getFolders()
      /var/www/html/jira42/app/Jobs/MailHandler.php:53

**Comment by MalteKiefer** [comment]
Try this:

```php
$aAvailableFolders = $oClient->getFolders(false)->all();
```

**Comment by Webklex** [comment]
Hi @Stromspielplatz ,
please provide the complete error message and corresponding call stack.

Best regards,

**Comment by Stromspielplatz** [comment]
> 
> 
> Try this:
> 
> ```
> $aAvailableFolders = $oClient->getFolders(false)->all();
> ```

This works! Thanks a lot. Can you give me short explanation why to understand what I did wrong?

**Comment by MalteKiefer** [comment]
Yes.
The problem is with exchange that they don't use the UTF-8 encoding.
That is the problem, with `getFolders(false)` you disable the encoding

**Comment by Stromspielplatz** [comment]
OK, THX!

**Comment by MalteKiefer** [comment]
You will need this on ->query() too!
