### ISSUE TITLE
Unseen method doesn't work

### ISSUE THREAD

**Issue by fabyo** [Webklex/laravel-imap#332]
Unseen method doesn't work, what am I doing wrong ?, I've tried everything

$oFolder = $oClient->getFolder('INBOX');
dd($oFolder->query()->all()->count()); **//OK result 1254 mails**

dd($oFolder->query()->unseen()->get()); **// 0 mails**
or
dd($oFolder->query()->where('UNSEEN')->get()); **// 0 mails**
or
dd($oFolder->getUnseenMessages()); **// 0 mails**
or
dd($oFolder->search()->unseen()->get()->count()); **// 0 mails**

OBS: I'm using IMAP office 365

**Comment by Webklex** [comment]
Hi @fabyo ,
how many unseen messages are you expecting to receive? Perhaps they are all "seen" ?

Best regards,

**Comment by fabyo** [comment]
Hi @Webklex 
I'm doing tests and I always leave some unread messages to test and never any method works

**Comment by fabyo** [comment]
Only way it worked, but I think it's wrong to do it like this:

foreach($aMessage as $message) {
	if(! $message->getFlags()['seen']) {
	
	}
}

**Comment by Webklex** [comment]
Hi @fabyo ,
yea that's probably not the fastest way. Have you tested it using a different email provider? The actual available search criteria are defined by the mail server - not all servers support all criteria. Especially office/microsoft solutions seem to do their own little thing..

**Comment by fabyo** [comment]
I tested it using the php imap_ native functions and it worked

**Comment by fabyo** [comment]
thank you very much

**Comment by fabyo** [comment]
vendor\webklex\laravel-imap\src\IMAP\Query\Query.php line 161
does not work:
$ available_messages = \ imap_search ($ this-> getClient()->getConnection(), $this->getRawQuery(), IMAP :: SE_UID);

works ok:
$ available_messages = \ imap_search ($this->getClient()->getConnection());

**Comment by MalteKiefer** [comment]
Can you please use code tags?
Is it a exchange server?

**Comment by Webklex** [comment]
Hi @fabyo ,
please try setting the charset to `null`:
```php
$oFolder->query(null)->unseen()->get();
```

Best regards,

**Comment by Webklex** [comment]
Please update to v2.0.0 :)
