### ISSUE TITLE
How to create a customized method that you look for by uuid?

### ISSUE THREAD

**Issue by alexv96** [Webklex/laravel-imap#333]
I'm trying to search by uuid, I know you can use the ```$oMessage = $oFolder->getMessage($uid = 1);``` but the idea is not to have to enter the message to know the ID, but every time I run it goes directly to search from the last Uuid onwards?

At the moment I took a criteria to do it but it doesn't work.

```
use \webklex\IMAP\Query\WhereQuery;

class FunctionWebklex extends Query{
    
    protected function validate_criteria($criteria) {
        $criteria = strtoupper($criteria);

        if (substr($criteria, 0, 6) === "uuid") {
            return substr($criteria, 6);
        }
        if(in_array($criteria, $this->available_criteria) === false) {
            throw new InvalidWhereQueryCriteriaException();
        }

        return $criteria;
    }

    public function whereUuid($value) {
        return $this->where('UUID', $value);
    }
}
```

Any idea to make it work? or how to do it correctly

**Comment by Webklex** [comment]
Hi @alexv96  ,
please update to the latest release [v2.3.0](https://github.com/Webklex/laravel-imap/releases/tag/2.3.0) and update the config option `options.sequence` inside your `config/imap.php` file to `IMAP::ST_UID`.

You can now use the following to query a message by uid:
```php
/** @var \Webklex\PHPIMAP\Folder $folder */
$message = $folder->query()->getMessage($uid = 1);
```
See: https://www.php-imap.com/api/query

Best regards,

**Comment by alexv96** [comment]
@Webklex I updated the version and changed it but now I get this error.

![image](https://user-images.githubusercontent.com/33232796/102844034-4b9db600-43e9-11eb-81ff-03a9d4cb61b3.png)

**Comment by Webklex** [comment]
Hi @alexv96 ,
this exception indicates that the given id could not be found. Have you changed the `sequence` option to `IMAP::ST_UID` and does your id represent the message uid?

Best regards,

**Comment by alexv96** [comment]
If you change it but do not change the error.

![image](https://user-images.githubusercontent.com/33232796/102846798-b4882c80-43ef-11eb-8cce-4b517d3a94a3.png)

Ans this is my code 

```
$oClient->connect();

            $aFolder = $oClient->getFolders(false);

            $aFolder = $oClient->getFolder('INBOX');
            $aMessage = $aFolder->query()->getMessage(165);
            //$aMessage = $aFolder->query()->getMessage(168)->get();
            //$aMessage = $aFolder->query(null)->since('11.10.2020')->limit(10)->get();

            foreach ($aMessage as $value) {
               
```

**Comment by Webklex** [comment]
That screenshots still says `IMAP::ST_MSGN` and not `IMAP::ST_UID`? I just want to make sure we are talking about the same option :)

Best regards,

**Comment by alexv96** [comment]
Sorry it does not show the error but I do not know if something I'm doing wrong, because it shows me now only the blank page when I indicate the sequence ``` $aMessage = $aFolder->overview($sequence = "168:*"); ```, maybe a method that is occupying wrong, because that overview is sought by uuid right?

**Comment by Webklex** [comment]
Hi @alexv96 ,
it seems like we are a bit lost in translation :)

If you are using the laravel package (https://github.com/Webklex/laravel-imap), please update your config file `config/imap.php` and make sure to set the following options:
```php
return [
    ...
    'options' => [
        'delimiter' => '/',
        'fetch' => \Webklex\PHPIMAP\IMAP::FT_PEEK,
        'sequence' => \Webklex\PHPIMAP\IMAP::ST_UID,
        'fetch_body' => true,
        'fetch_flags' => true,
        'message_key' => 'list',
        'fetch_order' => 'asc',
        'dispositions' => ['attachment', 'inline'],
        'common_folders' => [
            "root" => "INBOX",
            "junk" => "INBOX/Junk",
            "draft" => "INBOX/Drafts",
            "sent" => "INBOX/Sent",
            "trash" => "INBOX/Trash",
        ],
        'open' => [
            // 'DISABLE_AUTHENTICATOR' => 'GSSAPI'
        ],
        'decoder' => [
            'message' => 'utf-8', // mimeheader
            'attachment' => 'utf-8' // mimeheader
        ]
    ],
    ...
];
```
The original file can be found here: https://github.com/Webklex/laravel-imap/blob/master/src/config/imap.php

If you are using the standalone version, please make sure you have copied the config file `vendors/Webklex/php-imap/src/config/imap.php` into your project directory. Lets assume you've placed it under `config/imap.php`. Please go ahead and update the containing array the same way as described above.

Please note that the `sequence` has been updated to `\Webklex\PHPIMAP\IMAP::ST_UID`. This is very important if you want to use uids instead of message numbers.

Checkout https://www.php-imap.com/configuration/configuration if you want to learn more about the available options.

Once you've updated the config, you can now go ahead and actually search / query uids:
```php
$cm = new ClientManager('config/imap.php');
$client = $cm->account('account_identifier');

// or if you are using the laravel wrapper:
$client = \Webklex\IMAP\Facades\Client::account('account_identifier');

$folder = $client->getFolder('INBOX');
$overview = $folder->overview($sequence = "168:*");
$message = $aFolder->query()->getMessage($uid = 165);
```

Best regards,
