### ISSUE TITLE
Fast way to catch messages

### ISSUE THREAD

**Issue by MalteKiefer** [Webklex/laravel-imap#334]
Hi,

I tested some code and I think there is a fast and better way to catch the important information from a mail without taking the whole mail.
So this code:

```php
// page
        $page = 1;
// mails per page
        $mailsperpage = 25;
// open the stream
        $mbox = imap_open($hoststring, $username, $password);
// count all mails
        $count['SELF'] = imap_num_msg($mbox);
// get start point
        $startMail = (($count['SELF'] - ($page * $mailsperpage)) > 0) ? $count['SELF'] - ($page * $mailsperpage) : 1;
// set end point
        $maxMail = $startMail + $mailsperpage;
// get the mail infos
        $messages = imap_fetch_overview($mbox, $startMail . ':' . $maxMail, 0);
```
the infos you get
```php
/*

- subject
- from
- to
- date
- message_id
- references
- in_reply_to
- size
- uid
- msgno
- recent
- flagged
- answered 
- deleted
- seen
- draft
- udate 

*/
```

This is more than enough for an overview and must fast then the current way with your code.
Maybe we can integrate a method like this, @Webklex

**Comment by Webklex** [comment]
Hi @MalteKiefer ,
I guess you are looking for `Client::overview()`, `Client::countMessages()` and `Query::idle()`? :)
https://github.com/Webklex/laravel-imap/blob/5d9610d352dc037fb3e5fccafdfb3260e263ecf0/src/IMAP/Client.php#L609
https://github.com/Webklex/laravel-imap/blob/5d9610d352dc037fb3e5fccafdfb3260e263ecf0/src/IMAP/Client.php#L585
https://github.com/Webklex/laravel-imap/blob/5d9610d352dc037fb3e5fccafdfb3260e263ecf0/src/IMAP/Query/Query.php#L267

Best regards,

**Comment by MalteKiefer** [comment]
Yeah, but I tried countMessages and it was really slow.
Also, the connection was really slow.
Strange thing, with pure PHP it is fast

**Comment by Webklex** [comment]
Well the method `Client::countMessages()` itself is not much more - just an additional check in front to make sure the connection is still alive.
```php
public function countMessages() {
        $this->checkConnection();
        return \imap_num_msg($this->connection);
}
```

Best regards,

**Comment by MalteKiefer** [comment]
Ok I will test it.
I will give you some feedback
