### ISSUE TITLE
Wrong path to config directory in v2 Service Provider

### ISSUE THREAD

**Issue by gerardojbaez** [Webklex/laravel-imap#336]
**Describe the bug**
Wrong path to config directory in v2 Service Provider:

https://github.com/Webklex/laravel-imap/blob/2c906c6f943bd9c28cd177a651c9c38d09fd8b09/src/Providers/LaravelServiceProvider.php#L64

This path is causing `composer require webklex/laravel-imap:^2.0` to fail with: 

```
ErrorException: require(/var/www/html/vendor/webklex/laravel-imap/src/Providers/../../config/imap.php): failed to open stream: No such file or directory
```

The package is trying to access the config path as if it were located in `laravel-imap/`, it is currently located under `laravel-imap/src/`.

**To Reproduce**
1. On a Laravel instance, execute `composer require webklex/laravel-imap:^2.0`
2. See error when install reaches `@php artisan package:discover --ansi` step

**Expected behavior**
The config directory is properly loaded, and the package is successfully installed.

**Screenshots**

![image](https://user-images.githubusercontent.com/11788389/93937399-b1e54080-fcf5-11ea-92cb-18c10f427cfe.png)

**Desktop / Server:**
 - OS: Alpine Linux v3.12.0
- PHP: 7.4.7
 - Version: v2.0.0

**Comment by Webklex** [comment]
Hi @gerardojbaez ,
thanks for your excellent report. 
Please update to [v2.0.1](https://github.com/Webklex/laravel-imap/releases/tag/2.0.1).

Best regards,

**Comment by gerardojbaez** [comment]
That was quick! Thank you for the package! 😊
