### ISSUE TITLE
Undefined index: authentication at php-imap/src/Client.php:155

### ISSUE THREAD

**Issue by gerardojbaez** [Webklex/laravel-imap#337]
**Describe the bug**

The [default account settings](https://github.com/Webklex/laravel-imap/blob/ec463dbd52c63f5fade4c5eb3aca3736a38e891b/src/config/imap.php#L49-L56) doesn't have `authentication` key, causing an error (or sometimes a notice) when Client tries to set default values based on the [valid config keys](https://github.com/Webklex/php-imap/blob/c108cca409ebe194fcc92a27a48e050a5c569a5b/src/Client.php#L111). The error is thrown by php-imap package, in [Client.php L155](https://github.com/Webklex/php-imap/blob/c108cca409ebe194fcc92a27a48e050a5c569a5b/src/Client.php#L155).

**To Reproduce**
1. Run `php artisan tinker`
2. Write into the console `resolve(Webklex\PHPIMAP\Client::class);` and hit Enter
3. In this case a Notice is shown with message `Undefined index: authentication in /var/www/html/vendor/webklex/php-imap/src/Client.php on line 155`

In a regular HTTP request, a 500 error is thrown (but same issue). 

**Expected behavior**
Either Client needs to check whether a valid key is present in the default account settings, or `authentication` key is added to the `default` account settings, fixing the error. 

**Screenshots**

Relevant portion of the error message generated by a regular HTTP request:
![image](https://user-images.githubusercontent.com/11788389/93946389-1ceb4300-fd07-11ea-8a7e-1f41f526abff.png)

Tinker:
![image](https://user-images.githubusercontent.com/11788389/93946317-ef05fe80-fd06-11ea-8c47-2bb213b9ef54.png)

**Woraround/Fix**
Publishing the package's config file (i.e., `php artisan package:publish --provider Webklex\IMAP\Providers\LaravelServiceProvider`) and adding `authentication` key to `accounts.default` resolves the issue.

**Desktop / Server (please complete the following information):**
 - OS: Alpine Linux
- PHP: 7.4.7
 - Version: 2.0.1

**Comment by Webklex** [comment]
Hi @gerardojbaez ,
thanks again :)

Best regards,
