### ISSUE TITLE
I got base64 encoded Subject (title) string, How to resolve this?

### ISSUE THREAD

**Issue by donilearn** [Webklex/laravel-imap#338]
**given string (from sender) :** "Официальное сотрудничество с PPP Global Europe"

**Used:**    $mail["subject"] = mb_convert_encoding(**$message->getSubject(),** 'UTF-8', 'UTF-8');

**Result:** "=?UTF-8?B?RndkOiDQntGE0LjRhtC40LDQu9GM0L3QvtC1INGB0L7RgtGA0YPQtNC90LjRh9C10YHRgg==?= во с PPP Global Europe"

Pls, help. How to fully correctly decode it

**Comment by Webklex** [comment]
Hi @donilearn ,
thanks for your report. Please update your "webklex/php-imap" dependency to the latest version > v2.1.3 and try again :)

Best regards,

**Comment by donilearn** [comment]
I'm sorry, but I mean for this -> Webklex/laravel-imap

**Comment by Webklex** [comment]
Yes I know, but `webklex/laravel-imap` has a dependency to `webklex/php-imap`. Take a look at the [composer.json](https://github.com/Webklex/laravel-imap/blob/master/composer.json#L29). However I was able to reproduce the problem and supplied a fix. In order for you to get the fix, you have to update the dependency. The easiest way is probably to just run `composer update`.
