### ISSUE TITLE
Help when saving attachments with the storage facade

### ISSUE THREAD

**Issue by Black0bsidian** [Webklex/laravel-imap#339]
Hi, I'm trying to save the attachments with the storage facade, this generates the file but I cannot open or view. I've seen the properties of the file and apparently it's of type binary.
I save the attachments as follows:

```php
$client = \Client::connect();
$messages = $folder->messages()->unseen()->subject('[Ticket #]')->get();
$messages = $folder->messages()->subject('[Ticket #]')->get();
foreach ($messages as $msg) {
     echo $msg->getSubject().'<br />';
     echo $msg->getFrom()[0]->mail.'<br />';
     if($msg->getAttachments()) {
          $msg->getAttachments()->each(function ($att) use ($msg){
               $path = '/attachments/'.$msg->getUid().'/';
               Storage::disk('public')->put($path.$att->name,$att->content);
          });
     }
}
```
Any help is appreciated, thanks

**Comment by Webklex** [comment]
Hi @Black0bsidian ,
have you checked the file content of the saved file? Is it empty or not correctly decoded?

Please dump the attachment and look for the `part` attribute and check if the part attribute `header` is fetched correctly. You might also want to update the `webklex/php-imap` dependency to the latest version. I just released a patch to a problem which might correlate with yours.

Best regards,

**Comment by Black0bsidian** [comment]
Hi @Webklex thanks for answered.
Actually I am working with the latest update but do the update again and now it works perfectly.
Lastly, how can I get the text of the message when there is an attachment? I've tried with `getTextBody()` but return `false`

**Comment by Black0bsidian** [comment]
Hi @Webklex thanks for answered.
Actually I am working with the latest update but do the update again and now it works perfectly.
Lastly, how can I get the text of the message when there is an attachment? I've tried with `getTextBody()` but return `false`

**Comment by Webklex** [comment]
You mean you want to get the content of an attachment if no text body is present?

```php
/** @var Message $message */
$message = $messages->first();
$text = $message->getTextBody();

// Check if a text body is available - if not find all text attachments and append them to $text
if ($text === false && $message->getAttachments()->count() > 0) {
    $message->getAttachments()->each(function($attachment) use(&$text) {
        /** @var Attachment $attachment */
       
       // Check if the attachment is from type "text"
        if ($attachment->getType() == "text") {

            // Append attachment content to $text - in case there are more than one possible candidate
            $text .= $attachment->getContent()."\n";
        }
    });
}
echo $text;
```

Best regards,

**Comment by Black0bsidian** [comment]
No, for example this is the email
![Captura de pantalla de 2020-10-01 16-04-02](https://user-images.githubusercontent.com/65327219/94863245-c2856d00-03ff-11eb-93c7-fae3676acf7a.png)
I want to get this "Test" and then save it to a database.
Thanks regards

**Comment by Webklex** [comment]
Hi @Black0bsidian ,
perhaps like this:
```php
/** @var \Webklex\PHPIMAP\Client $client */
/** @var \Webklex\PHPIMAP\Folder $folder */
$folder = $client->getFolder("INBOX");

$folder->query()->all()->get()->each(function($message){
    /** @var \Webklex\PHPIMAP\Message $message */
    $msg_model = MyMessageModel::create([
        "msg_id" => $message->getMessageId(),
    ]);
    $message->getAttachments()->each(function($attachment) use($msg_model) {
        /** @var \Webklex\PHPIMAP\Attachment $attachment */
        $att_model = $msg_model->attachments()->create([
            "name" => $attachment->getName(),
            "mime" => $attachment->getMimeType(),
        ]);
        Storage::disk('local')->put("/attachments/".$msg_model->id."_".$att_model->id, $attachment->getContent());
    });
});
```
Keep in mind that you should check if the email already exists before creating a new one and also keep in mind that not every email has a message id - therefor you might want to create a token based on the message subject, date, uid, id, etc.. 

This is just an example and goes beyond the scope of this library wrapper.  

Best regards,

**Comment by Black0bsidian** [comment]
I think I did not explain it correctly I meant to the word "Test" in the body message.
Thanks anyway

**Comment by rerdogantr** [comment]
> Hi @Black0bsidian ,
> have you checked the file content of the saved file? Is it empty or not correctly decoded?
> 
> Please dump the attachment and look for the `part` attribute and check if the part attribute `header` is fetched correctly. You might also want to update the `webklex/php-imap` dependency to the latest version. I just released a patch to a problem which might correlate with yours.
> 
> Best regards,

hi @Webklex thanks for informing us.
After the latest update, now i m getting the all attachments. 

Best regards,
