### ISSUE TITLE
Can I use this library for Lumen 5.5?

### ISSUE THREAD

**Issue by puneetthakur66** [Webklex/laravel-imap#34]
I am using Lumen 5.5, where I need to use IMAP to load emails from the client.
In  **Composer.json** 

> "require": {
        "php": ">=5.5.9",
        "laravel/framework": ">=5.0.0"
},

 Larvel framework is required, Can I change this to "laravel/lumen" : ">=5.0.0" and will that work ok in the Lumen framework?

**Comment by Webklex** [comment]
Hi @puneetthakur66 ,
I'll run a test tomarrow. If it works with Lumen i'll update the composer file and release a new version. If you don't want to wait, please feel free to test it your self and commit your changes to this project :)

Best regards

**Comment by puneetthakur66** [comment]
This does not seem to be working, as installation requires vendor: publish command which is not available in the Lumen by default.

**Comment by puneetthakur66** [comment]
For Lumen, I  am doing this by using [Barbushin php-imap](https://github.com/barbushin/php-imap), a PHP library which can be installed via Composer and be used directly in the controller.
