### ISSUE TITLE
laravel-imap v2.0 not working for me

### ISSUE THREAD

**Issue by saleoid** [Webklex/laravel-imap#340]
I tried to install laravel-imap in new Laravel 8 setup(even tried in 6) and used first example(fetch emails and make them read) mentioned in doc. It gives me following error. Not sure why?

![image](https://user-images.githubusercontent.com/28570623/94778755-70365300-03e3-11eb-9c7b-58d829176348.png)

**Comment by necorobsd** [comment]
Try this config:
```
        $oClient = new Client([
            'host'          => 'mail.*******.com',
            'port'          => 143,
            'encryption'    => 'starttls',
            'username'      => '*********',
            'password'      => '********',
            'protocol'      => 'imap',
            'masks' => [
                'message' => \Webklex\PHPIMAP\Support\Masks\MessageMask::class,
                'attachment' => \Webklex\PHPIMAP\Support\Masks\AttachmentMask::class
            ]
        ]);
```
Which version of php are you using?

**Comment by saleoid** [comment]
I am using PHP 7.4.3.

**Comment by saleoid** [comment]
Ok it changed the error to:
![image](https://user-images.githubusercontent.com/28570623/94790380-d0cd8c00-03f3-11eb-8665-3cf7c664a29c.png)

**Comment by saleoid** [comment]
I also passed events to it and error changed to: 

![image](https://user-images.githubusercontent.com/28570623/94790565-12f6cd80-03f4-11eb-9ab7-8556629554c1.png)

**Comment by necorobsd** [comment]
> I am using PHP 7.4.3.


I have the same problem with php 7.4. 
Try php 7.3

**Comment by Webklex** [comment]
Hi @saleoid ,
please make sure to publish the package config file [installation step 3.](https://github.com/Webklex/laravel-imap/blob/master/README.md#installation)

The error you are getting indicates that the package could not find any configuration. 

Best regards,

**Comment by david34corbalan** [comment]
hola buenas tardes, tengo el mismo problema, y segui los comentarios anteriores y no funciona

************************************
************************************

Undefined offset: 0

  at vendor/webklex/laravel-imap/src/IMAP/Providers/LaravelServiceProvider.php:130
    126▕                     $base[$key] = $append[$key];
    127▕                     continue;
    128▕                 }
    129▕ 
  ➜ 130▕                 if(is_array($value) or is_array($base[$key])) {
    131▕                     $base[$key] = $this->array_merge_recursive_distinct($base[$key], $append[$key]);
    132▕                 } else if(is_numeric($key)) {
    133▕                     if(!in_array($value, $base)) $base[] = $value;
    134▕                 } else {

      +13 vendor frames 
  14  artisan:37

**Comment by Webklex** [comment]
Hi @david34corbalan ,
this is the exact error I get if I use the old config file. Please update your `imap.php` config file found under `config/imap.php`. 

Best regards,

**Comment by david34corbalan** [comment]
Gracias, funciono tu respuestas...
