### ISSUE TITLE
getSubject returns missing subject

### ISSUE THREAD

**Issue by aradhell** [Webklex/laravel-imap#341]
Example Subject:
Fully Approved - Credit Limit Decision - Your reference: Credit Limit Buyer: 2222222 Buyer Name: XXXXXXX Policy Number: 111111

getSubject returns only "fully approved - credit limit decision - your reference: credit"
and sometimes "fully approved - credit limit decision - your reference: credit limit"

mail contains an attachment but getAttachments - hasAttachments returns null and 0

**Expected behavior**
return full subject

**Desktop / Server (please complete the following information):**
- OS: macOS
- PHP: 7.4.2
- Version 2.0.2

**Additional context**
outlook.office365.com

**Comment by Webklex** [comment]
Hi @aradhell ,
thanks for your report.

I cant replicate the behavior. Please dump the message header like this:
```php
dd($message->getHeader());
```
and look for the attribute `raw`; please provide an anonymized copy of that. This will enable me to accurately reproduce the header and possibly  verify the bug.

Best regards,

**Comment by aradhell** [comment]
hi @Webklex thanks! I sent it to github@webklex.com, I can also provide full mail by exporting it as .msg if it is needed.

**Comment by Webklex** [comment]
It turned out that the subject was broken up into two lines. Each terminated with "\r\n". However the second line did not start as expected with a "\t" but with a " " and contained a ":" which lead to it being interpreted as a separat header entry.

Possible solution: support multiple "continuous indicators" such as " " and "\t".

**Comment by Webklex** [comment]
Hi @aradhell ,
a patch has been released. Please update your `webklex/php-imap` dependency to at least v2.1.11.

Best regards,
