### ISSUE TITLE
Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by david34corbalan** [Webklex/laravel-imap#342]
Invalid argument supplied for foreach ();

hello good, I have an error in version 2.0, sometimes the package gives me a foreach invalid error, in the previous version it did not happen.
![Captura de Pantalla 2020-10-05 a la(s) 14 31 11](https://user-images.githubusercontent.com/43279485/95112846-dc80c180-0717-11eb-8743-b0870ad6ed83.png)

> code->
 $data = [];
        $folder = $client->getFolder('INBOX',false);
        $message = $folder->query()->leaveUnread()->unseen()->since(Carbon::now()->subDays(15))->get();
        $i = 0;
        foreach ($message as $m) {
            $data[$i]['subject'] = $m->getSubject();
            $data[$i]['body'] = $m->getHTMLBody();
            $data[$i]['from'] = $m->getFrom();
            $data[$i]['cc'] = $m->getCc();
            $data[$i]['to'] = $m->getTo();
            $data[$i]['uid'] = $m->getUid();
            if ($m->getAttachments()) {
                $files = $m->getAttachments();
                $x = 0;
                foreach ($files as $f) {
                    $data[$i]['file'][$x]['getName'] = $f->getName();
                    $data[$i]['file'][$x]['getExtension'] = $f->getExtension();
                    $data[$i]['file'][$x]['getId'] = $f->getId();
                    $f->save(File::crearDirectorio());
                    $x++;
                }
            }
            $i++;
        }
        return $data;

any idea why this happens?

**Comment by squal0** [comment]
Having the same problem, the INBOX folder doesn't seem to return a MessageCollection and hence the error **Invalid argument supplied for foreach()**

**Comment by Webklex** [comment]
Hi @david34corbalan @squal0 ,
please update the "webklex/php-imap" dependency to the latest version and give it another try. If it still doesn't work, please head over to the php-imap repository and [create a bug report](https://github.com/Webklex/php-imap/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) there :)

Best regards,
