### ISSUE TITLE
Unknown mask provided

### ISSUE THREAD

**Issue by omarhabeh** [Webklex/laravel-imap#345]
Hello there, i tried this plugin with facade and without it and in both it give me error, i literally followed the instructions that are on the usage and im getting this, when im using facade i get folders but i can't access messages or so.

**Comment by Webklex** [comment]
Hi @omarhabeh ,
thanks for your report. I was able to reproduce the problem and just released a patch. Please update to the latest version, update your `config/imap.php` config file and try again.

Best regards,
