### ISSUE TITLE
Message structure depending on host (?)

### ISSUE THREAD

**Issue by juliakerschbaummayr1** [Webklex/laravel-imap#347]
Hi,

it seems that the structure of the given messages depends on the host where the message was sent from, is this correct?
I am trying to build a CRM-like tool where I display customer mails, which can be sent from any host obviously. 

For example for _gmail.com_ I don´t get a html or text body, they both return null. So I used `getStructure()` and the content in `parts[1]` to display the mail content. Like this:

`$note->text = 'Mail an: ' . $message->toaddress . '<br><br>' .
                            '<strong>' . $message->getSubject() . '</strong><br>' .
                            str_replace(array("=\r\n", "\r\n", "\n\r", "\n", "\r"), "", strstr($message->getStructure()->parts[1]->content, '<d'));`

Then I tested it with a mail sent from _hotmail.com_, here I don´t have a `parts[1]` so the code doesn´t work anymore. However, now the text body returns the mail text.
 
Is there a way to use this package for my use case of getting mails from different hosts and displaying them? Or does it depend on something else than the sending host where the mail text is returned?
I don´t really get why the structure differs so much, so I would be really grateful for some help.

Thanks in advance

**Comment by ricus-zero2one** [comment]
In our system we get mails from pretty much all hosts and `->getHtmlBody()` as well as `->getTextBody()` always seems to work.

Is your `fetch_body` config value set to `true`?

**Comment by juliakerschbaummayr1** [comment]
Yes it is set to true.
Both `->getHtmlBody()` and `->getTextBody()` return `ErrorException  : Trying to get property 'content' of non-object` for mails sent from _gmail.com_
For the mail sent from _hotmail.com_ `->getTextBody()` also returns this error and `->getHtmlBody()` returns `null`. This is really strange too as the `$message` from _hotmail.com_ does have a text body but not a html body:
`+bodies: array:1 [
    "text" => """
      Test \n
      \n
      Von meinem Huawei-Mobiltelefon gesendet
      """
  ]`
and for the other mails both text and html are `null`

**Comment by ricus-zero2one** [comment]
What version are you on @juliakerschbaummayr1 ?

I don't think this is an issue with the package, we process thousands of mails from a whole bunch of different hosts and don't have this issue. Sometimes the text body is empty but that is usually when there just isn't one as not all clients will add the text version.

I think we would need to see some more stacktraces or examples in order to help further with this one, or a way to reproduce would be best.

**Comment by Webklex** [comment]
Hi @juliakerschbaummayr1 ,
please update the "webklex/php-imap" dependency. If the problem persists, please head over to the php-imap repository and [create a new bug report](https://github.com/Webklex/php-imap/issues/new?template=bug_report.md).

Best regards,
