### ISSUE TITLE
Cant get messages on IMAP MS Exchange

### ISSUE THREAD

**Issue by DjeyKey** [Webklex/laravel-imap#348]
Hi everyone, seems i got MS exchange problems here is my basic controller to get messages from a specific folder "Orange".
Count() is OK, but cant get messages, here is the code and the stack trace of from Laravel.

Conf is MS exchange IMAP

`
	$oClient->connect();
	/** @var \Webklex\PHPIMAP\Support\FolderCollection $aFolder */
	$oFolder = $oClient->getFolder('Orange');
	$count = $oFolder->query()->all()->count(); // Works fine
	$messages = $oFolder->messages()->all()->get(); //crash
	echo "$count"; //	
		foreach($messages as $message){
	        echo $message->getSubject().'<br />';
	        
	        
    	}
   `

Thanks for any help, seems that cannot fetch the message list, MS Exchange particularity maybe ?

Stack trace : 
![error](https://user-images.githubusercontent.com/72506002/95337035-b55df780-08b1-11eb-8a7c-77a1c293fbcd.png)

**Comment by ricus-zero2one** [comment]
What is the value of $count? How many messages are you trying to retrieve in one go there?

**Comment by Webklex** [comment]
Hi @DjeyKey  ,
please update the "webklex/php-imap" dependency to the latest version and give it another try. If it still doesn't work, please head over to the php-imap repository and [create a bug report](https://github.com/Webklex/php-imap/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) there :)

Best regards,
