### ISSUE TITLE
Error: Undefined property: stdClass::$disposition

### ISSUE THREAD

**Issue by studiodaniels** [Webklex/laravel-imap#35]
My first try with this (in Laravel 5.4)... 
Names of folders is working so connection is okay.
But if I want to retrieve messages it gives an error:
GetMessagesFailedException in Client.php line 310:
**Undefined property: stdClass::$disposition**

My code:
```
$oClient = Webklex\IMAP\Facades\Client::account('default');
$oClient->connect();

$aMailboxes = $oClient->getFolders();
foreach($aMailboxes as $oMailbox){
echo '<br><br>'.$oMailbox->name.'<br>';
    foreach($oMailbox->getMessages() as $oMessage){
        echo $oMessage->subject.'<br />';
    } 
} 
```

**Comment by studiodaniels** [comment]
Any help?

**Comment by Webklex** [comment]
Hi @studiodaniels ,
I think the problem in a malformed mail in your inbox - anyway please update to the newest version [1.0.3.7](https://github.com/Webklex/laravel-imap/releases/tag/1.0.3.7). This problem shouldn't occur anymore :)
