### ISSUE TITLE
fetch_attachment config option missing in version 2

### ISSUE THREAD

**Issue by ricus-zero2one** [Webklex/laravel-imap#350]
Hi @Webklex 

Looking at https://github.com/Webklex/laravel-imap/blob/master/src/config/imap.php it seems like the config option for fetch_attachments has also been removed, could this maybe be added back?

From previous config file:
```
    |   -Attachment download option
    |       Default TRUE
```

and in `imap.php` config file

```
 'options'     => [
    ...
        'fetch_attachment' => true,
     ...
    ],
```

I realise this options defaults to true, but it would be nice to have the option back to turn it off.

**Comment by Webklex** [comment]
Hi @ricus-zero2one ,
this option is no longer supported. This has to do with the fact how content fetching works. The attachments are actually part of the body - if you fetch the body, you also fetch all attachments. If you fetch the attachments, you also fetch the body :)

If you want to reduce the load, you could disable the body fetching and work with the message headers and perhaps fetch the body later if you actually need it:
```php
$messages = $folder->query()->all()->fetchBody(false)->get();
$messages->each(function($message){
    if ($message->uid == 123) {
        $message->parseBody();
        dump($message->getBodies());
    }
}
```

If this option is added back, it could just prevent the attachment parsing, which might shave off some loading time?

Best regards,

**Comment by ricus-zero2one** [comment]
Thanks @Webklex no worries then, I do have it enabled because I need the attachments.

I've come to realise that attachments are actually in the body, think it's base64 encoded or something like that. I was manually appending mails with attachments to imap folders for clients that don't automatically save a sent copy if sent via smtp, before I came to my senses and just used swiftmailer to build up the mail 😆 

You're welcome to close this one 🙂
