### ISSUE TITLE
Webklex\PHPIMAP\Exceptions\MaskNotFoundException Unknown mask provided:

### ISSUE THREAD

**Issue by KyoRion** [Webklex/laravel-imap#354]
![image](https://user-images.githubusercontent.com/26852023/95974492-3f243c80-0e3f-11eb-8121-a72440afd203.png)
I'm trying connect to my gmail account but It show error like this
![image](https://user-images.githubusercontent.com/26852023/95974554-56632a00-0e3f-11eb-93fa-09b3ed11151e.png)

I need your help!

**Comment by Webklex** [comment]
Hi @KyoRion ,
Please try to use the facade to make sure the config is loaded:
```php
$client = Webklex\IMAP\Facades\Client::make([
    'host'          => 'somehost.com',
    'port'          => 993,
    'encryption'    => 'ssl',
    'validate_cert' => true,
    'username'      => 'username',
    'password'      => 'password',
    'authentication' => "oauth", 
    'protocol'      => 'imap'
]);
```

Best regards,

**Comment by KyoRion** [comment]
> Hi @KyoRion ,
> Please try to use the facade to make sure the config is loaded:
> 
> ```
> $client = Webklex\IMAP\Facades\Client::make([
>     'host'          => 'somehost.com',
>     'port'          => 993,
>     'encryption'    => 'ssl',
>     'validate_cert' => true,
>     'username'      => 'username',
>     'password'      => 'password',
>     'authentication' => "oauth", 
>     'protocol'      => 'imap'
> ]);
> ```
> 
> Best regards,

I got another error with not found class
![image](https://user-images.githubusercontent.com/26852023/95976166-56642980-0e41-11eb-969f-af238463749e.png)

**Comment by Webklex** [comment]
Just add a "\\" :)

```php
$client = \Webklex\IMAP\Facades\Client::make([
    'host'          => 'somehost.com',
    'port'          => 993,
    'encryption'    => 'ssl',
    'validate_cert' => true,
    'username'      => 'username',
    'password'      => 'password',
    'authentication' => "oauth", 
    'protocol'      => 'imap'
]);
```

Best regards,

**Comment by KyoRion** [comment]
> Just add a "\" :)
> 
> ```
> $client = \Webklex\IMAP\Facades\Client::make([
>     'host'          => 'somehost.com',
>     'port'          => 993,
>     'encryption'    => 'ssl',
>     'validate_cert' => true,
>     'username'      => 'username',
>     'password'      => 'password',
>     'authentication' => "oauth", 
>     'protocol'      => 'imap'
> ]);
> ```
> 
> Best regards,

Fixed but 
![image](https://user-images.githubusercontent.com/26852023/95976555-e5714180-0e41-11eb-877b-c5a093ea0eba.png)

**Comment by KyoRion** [comment]
`[Wed Oct 14 17:27:57 2020] got an extra server challenge: eyJzdGF0dXMiOiI0MDAiLCJzY2hlbWVzIjoiQmVhcmVyIiwic2NvcGUiOiJodHRwczovL21haWwuZ29vZ2xlLmNvbS8ifQ==

[Wed Oct 14 17:27:57 2020] got failure response: NO [AUTHENTICATIONFAILED] Invalid credentials (Failure)`

And check it. this showing in my console

**Comment by Webklex** [comment]
Hi @KyoRion ,
If you think its a bug and the provided credentials are definitely correct, please head over to webklex/php-imap and [create a new bug report](https://github.com/Webklex/php-imap/issues/new?template=bug_report.md).

Best regards,
