### ISSUE TITLE
Can't get the SPAM Messages

### ISSUE THREAD

**Issue by usamanoman** [Webklex/laravel-imap#360]
I am unable to get the SPAM Messages. 

I am using simple Google Account (not Gsuite)

```
$folders = $client->getFolders();
        foreach($folders as $folder){
           $junk_message_count = $folder->query()->whereIsXSpam()->count();
           echo $junk_message_count ."</b>";
        }

```
Please let me know what is wrong, or how to get the SPAM emails from Gmail account. I am always getting 0 when getting the count. Although I have marked email as SPAM. 

Thanks.

**Comment by usamanoman** [comment]
Update: Same thing with Yahoo Mail. This function returns 0. Although i marked an email as SPAM.

**Comment by Webklex** [comment]
Hi @usamanoman ,
`WhereQuery::whereIsXSpam()` and `WhereQuery::whereNoXSpam` are custom search methods which have to be supported by the provider. I assume that Google and Yahoo don't support it.

If it is indeed supported by Google / Yahoo feel free to open a bug over at the [webklex/php-imap](https://github.com/Webklex/php-imap/issues/new?template=bug_report.md) repository.

Best regards,
