### ISSUE TITLE
How get headers?

### ISSUE THREAD

**Issue by damian-g** [Webklex/laravel-imap#362]
How get all headers from message?

`$message->getHeader()`

generate error:

```
Error
Object of class Webklex\PHPIMAP\Header could not be converted to string 
```

**Comment by Webklex** [comment]
Hi @damian-g ,
it look like you try to echo an object. `Message::getHeader()` returnes an `Header::class` instance.
```php
/** @var \Webklex\PHPIMAP\Message $message */
/** @var \Webklex\PHPIMAP\Header $header */
$header = $message->getHeader();

dd($header);
```
If you want to access the raw header try to use `Header::$raw` to receive the "unparsed" original header or `Message::getAttributes()` to get an array of all parsed headers.
```php
/** @var \Webklex\PHPIMAP\Message $message */
/** @var string $raw_header */
/** @var array $attributes */
$raw_header = $message->getHeader()->raw;
$attributes = $message->getAttributes();

echo $raw_header;

dd($attributes);
```

Best regards,
