### ISSUE TITLE
How can I recognize autoreplay messages?

### ISSUE THREAD

**Issue by dewelooper** [Webklex/laravel-imap#363]
Hello, 
is this package have implementet some features to recognize autoreplay messages? or if hasnt, which way is the best way to do this? Now Im using this package but I try to check some usual "slogans" in subject and in edge cases try to recognize loops which told me that messages are sending by automatic stript.

Thank you

**Comment by Webklex** [comment]
Hi @dewelooper ,
there is currently no such method or feature available. As you already discovered, there is no such thing as the "auto reply" message. They can look very different. However you might be able to create your own logic by using the `Message::thread()` method and check if they have an response within a given time, which might indicate an "auto response".

Best regards,
