### ISSUE TITLE
Whenever im using pop3 always return 'connection setup failed'

### ISSUE THREAD

**Issue by takuminaoya** [Webklex/laravel-imap#364]
Good afternoon,

Please forgive if this quite simple explanation,
As you can see in the title Whenever im using pop3 always return 'connection setup failed'. im trying using imap and other with dummy value in it like

IMAP_HOST=dummi.com
IMAP_PORT=993
IMAP_ENCRYPTION=ssl
IMAP_VALIDATE_CERT=true
IMAP_USERNAME=user
IMAP_PASSWORD=root
IMAP_PROTOCOL=imap

it simply say 'connection failed' instead 'connection setup failed'.

I Hope i can get a little bit explanation about it

Thanks you & Best Regard

**Comment by Webklex** [comment]
Hi @takuminaoya ,
port `993` is usually used by imap. If you are indeed trying to connect through pop3, please use port `995` for an ssl encrypted connection (unless your server setup differs from the default).

Best regards,

**Comment by takuminaoya** [comment]
Thanks for the reply, im really sorry to bother you.

Im already fix it. the reason is
