### ISSUE TITLE
No folder selected after disconnect

### ISSUE THREAD

**Issue by AntonioDiPassio-AppSys** [Webklex/laravel-imap#368]
Hi there

If you run this code 2x in succession, it won't show messages on 2nd run:

```
$client = Client::account('default');
$client->connect();

//get all messages from inbox
$folder = $client->getFolder('INBOX');
$messages = $folder->messages()->all()->get();

foreach ($messages as $message) {
    echo $message->getSubject();
}

$client->disconnect();
```

The debug log shows the client doesn't select a folder on the 2nd run. This is because the property $active_folder is not set to false when disconnecting.

My solution would be to add `$this->active_folder = false;` to Client.php in function disconnect() before `$this->connection->logout();`

**Comment by Webklex** [comment]
Hi @AntonioDiPassio-AppSys   ,
thanks for your report :+1: 

Please update your `webklex/php-imap` dependency to v2.2.5.

Best regards,
