### ISSUE TITLE
getHTMLBody has invalid string at the end.

### ISSUE THREAD

**Issue by Jedliu** [Webklex/laravel-imap#369]
**Describe the bug**
```php
$message->getHTMLBody()
``` 
result not correct. It contains an additional string at the end
`------=_Part_84962_2141841230.1473470845045  `

**Desktop / Server (please complete the following information):**
- PHP: v7.4.11
 - Version: 2.2

**Additional context**
I tested two mailboxes. The problems are the same.

**Comment by narguelles** [comment]
any update on this issue?

**Comment by Webklex** [comment]
Hi @Jedliu ,
if this issue is not related to https://github.com/Webklex/php-imap/issues/36 please head over to https://github.com/Webklex/php-imap/issues/new?template=bug_report.md to create a new report. Please provide some additional context as well so the issue can be reproduced. 

Best regards,
