### ISSUE TITLE
 Use of undefined constant FT_UID - assumed 'FT_UID'

### ISSUE THREAD

**Issue by kashifumar** [Webklex/laravel-imap#37]
After installing the package, when I run php artisn vendor:publish. I get this error

[ErrorException]
 Use of undefined constant FT_UID - assumed 'FT_UID'

Got Laravel 5.5

**Comment by Webklex** [comment]
Hi @kashifumar ,
please take a look at the reportet problems #30 and #14 .

**Comment by aminefilali1** [comment]
I had the same issue and I resolve it by installing PHP IMAP extension : 
for Linux: **sudo apt-get install phpX.X-imap**
