### ISSUE TITLE
Method getMessageId does not exist

### ISSUE THREAD

**Issue by 1dveeran** [Webklex/laravel-imap#370]
I trying to display the message of a message but, its throwing "Method getMessageId does not exist." error.

I followed the installation method which was given in README. GMAIL Imap configuration is fine and i can able to get subjects, attachments, unseen message counts but i couldn't able to use this method.

`$oClient = Client::account('default');
$oClient->connect();
$oFolder = $oClient->getFolder('INBOX');
$unreadCount = $oFolder->query()->unseen()->count();
$oMessage = $oFolder->query(null)->subject('Purchase Order #')->limit(10, 1)->get();
 /** @var \Webklex\PHPIMAP\Message $message */
dd($oMessage->getMessageId());`

![image](https://user-images.githubusercontent.com/5801197/97709550-8b7aa800-1ae0-11eb-9969-bcaa695f318c.png)

**Comment by Webklex** [comment]
Hi @1dveeran ,
You've missed one step. Try the following:
```php
$oClient = Client::account('default'); 
$oClient->connect(); 
$oFolder = $oClient->getFolder('INBOX'); 
$unreadCount = $oFolder->query()->unseen()->count(); 

$aMessage = $oFolder->query(null)->subject('Purchase Order #')->limit(10, 1)->get(); 

/** @var \Webklex\PHPIMAP\Message $message */ 
$message = $aMessage->first();
dd($message->getMessageId());
```

`Query::get()` returns a collection. With `MessageCollection::first()` you can select the first message. However you can of course use `each()` etc as well.

Best regards,

**Comment by 1dveeran** [comment]
doing `dd($message);` gives the below output.

![image](https://user-images.githubusercontent.com/5801197/97779856-e8d92c80-1ba6-11eb-9cfa-b8959f10a2d5.png)

but `dd($message->getMessageId());` is returning `null`

![image](https://user-images.githubusercontent.com/5801197/97779884-158d4400-1ba7-11eb-870a-6ef647dd942c.png)

**Comment by Webklex** [comment]
Hi @1dveeran ,
please take a look at the raw header:
```php
dd($message->getHeader()->raw);
```
..and look for a row starting with "Message-Id:". If you can find it, please provide the raw header around the message id in order to reproduce this problem. However I', afraid your message has no message id? If that's the case, you won't be able to receive a message id.

Best regards,

**Comment by 1dveeran** [comment]
I can able to see the "Message-Id" using `dd($message->getHeader()->raw);`

![image](https://user-images.githubusercontent.com/5801197/97804326-12608980-1c75-11eb-8439-6bd536d5ae02.png)

**Comment by Webklex** [comment]
Hi @1dveeran ,
many thanks for the followup. Please head over to https://github.com/Webklex/php-imap/issues/60 for future updates.

Best regards,
