### ISSUE TITLE
Some problem with getCc 

### ISSUE THREAD

**Issue by takuminaoya** [Webklex/laravel-imap#371]
**Describe the bug**
Im experience some weird whem im using getCc to get CC information, im notice whenever my CC is more than 1 its always return empty array.

**To Reproduce**
Im just using the basic to test it out.

**Additional context**
Everything is work properly, just this getCc its not working whenerver there more than 1 CC address

** What im already do **
1. Updating the depedency
2. dump-autoload
3. Checkin the source code on vendor in Message.php even there no getCc on there
4. checkin outlook and server the the email had their CC on it. but not on my app

** Screenshot **
-- Code
![image](https://user-images.githubusercontent.com/13032055/97833849-51441d00-1d11-11eb-9787-4599b4fced4a.png)
-- 1 CC
![image](https://user-images.githubusercontent.com/13032055/97833955-97997c00-1d11-11eb-8f3b-aa0c70ac9054.png)
-- More than 1
![image](https://user-images.githubusercontent.com/13032055/97833980-a6802e80-1d11-11eb-8422-66c6915cc81e.png)
-- This in oulook
![image](https://user-images.githubusercontent.com/13032055/97834055-d0395580-1d11-11eb-92eb-dfc6e99f7130.png)

**Comment by Webklex** [comment]
Hi @takuminaoya ,
many thanks for your report. Please follow https://github.com/Webklex/php-imap/issues/60 for any updates.

Feel free to reopen this issue If these two issues are not related.

Best regards,
