### ISSUE TITLE
message move is not working

### ISSUE THREAD

**Issue by demeus** [Webklex/laravel-imap#373]
```
$folder = $client->getFolder('INBOX');


$messages = $folder->messages()->all()->get();

foreach ($messages as $message) {
	$subject = $message->getSubject();
	$uid = $message->getUid();
	$body = $message->getTextBody();
	
	// some actions 
	

            if($message->move('READ') == true){
                $this->line('Message has ben moved');
            }else{
                $this->error('Message could not be moved');
            }
}

```

But o have always message Message could not be moved

![Screenshot 2020-11-03 162314](https://user-images.githubusercontent.com/2157091/98005034-e9fd9a00-1df0-11eb-9950-c9e3d9bb8ee6.png)

How can i move message to folder READ or trash ? 
Thanks

**Comment by jonasschen** [comment]
Same for me...
I'm using the follow command
`$message->move('INBOX.Read', true)`

I have the error :
`Trying to get property 'path' of non-object at /vendor/webklex/php-imap/src/Message.php:763)`

**Comment by jonasschen** [comment]
> Same for me...
> I'm using the follow command
> `$message->move('INBOX.Read', true)`
> 
> I have the error :
> `Trying to get property 'path' of non-object at /vendor/webklex/php-imap/src/Message.php:763)`

I solved my problem changing config/imap.php.
I changed parameter "options->delimiter" from "/" to ".".

Before:
```
    'options' => [
        'delimiter' => '/',
    ]
```

After
```
    'options' => [
        'delimiter' => '.',
    ]
```
