### ISSUE TITLE
Pagination result return empty array

### ISSUE THREAD

**Issue by zu007** [Webklex/laravel-imap#376]
i've already Search in closed issues but not work anyone.
$f->query()->all()->get(); //return MessageCollection
$f->query()->all()->count() // return 30
how to paginate return 10 mail per page

$f->query()->paginate($per_page, $page,$page_name = 'imap_page');
return below result.
`
Illuminate\Pagination\LengthAwarePaginator {#1835
  #total: 0
  #lastPage: 1
  #items: Illuminate\Support\Collection {#1847
    #items: []
  }
  #perPage: 4
  #currentPage: 1
  #path: "http://novidforce.local/api/v1/users/mailbox"
  #query: []
  #fragment: null
  #pageName: "imap_page"
  +onEachSide: 3
  #options: array:2 [
    "path" => "http://novidforce.local/api/v1/users/mailbox"
    "pageName" => "imap_page"
  ]
}
`
as u see items is empty array.
**I want to paginate 10 result per page with desc order.**

**Comment by Webklex** [comment]
Hi @zu007 ,
you are missing one step. You haven't provided any search criteria. Please try the following:
```php
$paginator = $f->query()->all()->paginate();
```
..or:
```php
$paginator = $f->query()->subject("test")->paginate();
```

Best regards,
