### ISSUE TITLE
mails filter by labels

### ISSUE THREAD

**Issue by zu007** [Webklex/laravel-imap#377]
as in Gmail there are many labels e.g. social, primary, promotions etc. ...
How to filter mails by labels .
`$f->query()->all()->paginate(10, $request->page);`

**Comment by Webklex** [comment]
Hi @zu007 ,
please head over to the main repository https://github.com/Webklex/php-imap.

In general: if these flags are accessible depends on the mail provider. I'm not aware that google supports the search for labels. However please prove me wrong :)

Best regards,
