### ISSUE TITLE
Pagination emtpy on page 2+

### ISSUE THREAD

**Issue by zu007** [Webklex/laravel-imap#379]
i've already ready  #287 and #225.
`        $paginator = $f->query()->all()->paginate(10, 1);`
return 10 emails
        `$paginator = $f->query()->all()->paginate(10, 2);`
on page 2 or other page .return 0 email.
only works for page = 1

**Comment by Webklex** [comment]
Hi @zu007 ,
#287 and #225 are not related to v2.x. If you are still using v1.6.x please update to v2. If you are using v2 please updated to the latest release. If you are still facing issues, please head over to https://github.com/Webklex/php-imap and create a new report under https://github.com/Webklex/php-imap/issues/new?template=bug_report.md.

Best regards,
