### ISSUE TITLE
MoveToFolder() in 

### ISSUE THREAD

**Issue by Polfo** [Webklex/laravel-imap#380]
When I use the example in README.md line 141
The following exception is raised.
```
Webklex\PHPIMAP\Exceptions\MethodNotFoundException
Method Webklex\PHPIMAP\Message::moveToFolder() is not supported
```

A similar issue has been solved in (https://github.com/Webklex/php-imap/commit/4b6ca8c37be91f930d61abc3b641a374be7859dc)

**Comment by Webklex** [comment]
Hi @Polfo ,
thanks for the report :+1: 

Best regards,
