### ISSUE TITLE
Couldn't connect to server IMAP , can you show step from beginning?

### ISSUE THREAD

**Issue by imaaronath** [Webklex/laravel-imap#381]

**Comment by Webklex** [comment]
Hi @imaaronath ,
are you looking for anything special or just the "getting started"?

This might help you:
- https://www.php-imap.com/frameworks/laravel/installation
- https://www.php-imap.com/frameworks/laravel/configuration
- https://www.php-imap.com/frameworks/laravel/facade
- https://www.php-imap.com/frameworks/laravel/events
- https://www.php-imap.com/frameworks/laravel/commands
- https://www.php-imap.com/frameworks/laravel/service
- https://www.php-imap.com/examples/getting-started
- https://www.php-imap.com/configuration/configuration
- https://github.com/Webklex/laravel-imap#basic-usage-example

Best regards,

**Comment by imaaronath** [comment]
Thankyou so much 

Sent from Yahoo Mail on Android 
 
  On Wed, Dec 23, 2020 at 15:17, Webklex<notifications@github.com> wrote:   


Hi @imaaronath ,
are you looking for anything special or just the "getting started" part?

This might help you:
   
   - https://www.php-imap.com/frameworks/laravel/installation
   - https://www.php-imap.com/frameworks/laravel/configuration
   - https://www.php-imap.com/frameworks/laravel/facade
   - https://www.php-imap.com/frameworks/laravel/events
   - https://www.php-imap.com/frameworks/laravel/commands
   - https://www.php-imap.com/frameworks/laravel/service
   - https://www.php-imap.com/examples/getting-started
   - https://www.php-imap.com/configuration/configuration
   - https://github.com/Webklex/laravel-imap#basic-usage-example

Best regards,
