### ISSUE TITLE
Empty body

### ISSUE THREAD

**Issue by sudhirsingh4116** [Webklex/laravel-imap#382]
$message->getHTMLBody()  empty if email body containing inline attachments

**Comment by Webklex** [comment]
Hi @sudhirsingh4116 ,
it looks like you've hit the wrong repository. Please head over to https://github.com/Webklex/php-imap/issues/new?template=bug_report.md and try to fill out as many questions / answers as possible.

Please also take a look at these issues before creating a new one: https://github.com/Webklex/php-imap/issues?q=Empty+body

Best regards,
