### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by imaaronath** [Webklex/laravel-imap#384]
**Describe the bug**
Cannot use object of type Webklex\PHPIMAP\Attribute as array

'mailbox_user' =>
                            'mailbox_uid' => $message->getUid(),
                            'mailbox_message_id' => $message->getMessageId(),
                            'mailbox_date' => $message->getDate(),
                            'mailbox_sender_name' => $message->getSender()[0]->personal,
                            'mailbox_sender_mail' => $message->getSender()[0]->mail,
                            'mailbox_subject' => $message->getSubject(),
                            'mailbox_recipient_mail' => $message->getTo()[0]->mail,
**To Reproduce**

**Expected behavior**
getSender and getTo should be return as array , but when I tried return getSender() only return 1 line

**Desktop / Server (please complete the following information):**
 - Windows
 - Version 2.3

**Comment by Webklex** [comment]
HI @imaaronath ,
thanks for your report. Your observation is correct and has been resolved with `webklex/php-imap` v2.4.0.

You can either update / add the dependency `webklex/php-imap:^2.4` or wait a few days until `webklex/laravel-imap` v2.4 is released.

Please note the breaking changes of v2.4: https://github.com/Webklex/php-imap/blob/master/CHANGELOG.md#240---2021-01-03

Best regards,

**Comment by imaaronath** [comment]
What happened if my IMAP downgrade to 2.3? 

Sent from Yahoo Mail on Android 
 
  On Wed, Jan 6, 2021 at 19:36, Webklex<notifications@github.com> wrote:   


HI @imaaronath ,
thanks for your report. Your observation is correct and has been resolved with webklex/php-imap v2.4.0.

You can either update / add the dependency webklex/php-imap:^2.4 or wait a few days until webklex/laravel-imap v2.4 is released.

Please note the breaking changes of v2.4: https://github.com/Webklex/php-imap/blob/master/CHANGELOG.md#240---2021-01-03

Best regards,

**Comment by Webklex** [comment]
Hi @imaaronath ,
please update to v2.4.

If you are still experiencing problems, please report them to the appropriate repository:
- https://github.com/Webklex/php-imap/issues/new?assignees=&labels=&template=bug_report.md

Best regards,
