### ISSUE TITLE
production.ERROR: connection failed 

### ISSUE THREAD

**Issue by umarpucitian** [Webklex/laravel-imap#386]
[2021-01-13 17:47:36] production.ERROR: connection failed {"userId":3,"exception":"[object] (Webklex\\PHPIMAP\\Exceptions\\ConnectionFailedException(code: 0): connection failed at project-dir\\vendor\\webklex\\php-imap\\src\\Connection\\Protocols\\ImapProtocol.php:77)
[stacktrace]

Following is my code, I am unable to connect 
        $client = Clientx::account('default');        
        $client->connect();
        $folders = $client->getFolders();

Although I have added the credentials in .env

IMAP_HOST=mail.overstepgroup.com
IMAP_PORT=993
IMAP_ENCRYPTION=ssl
IMAP_VALIDATE_CERT=true
IMAP_USERNAME=*******
IMAP_PASSWORD=*******
IMAP_DEFAULT_ACCOUNT=default
IMAP_PROTOCOL=imap
MAIL_ENCRYPTION=NULL

**Comment by Webklex** [comment]
Hi @umarpucitian ,
this looks fine besides the `Clientx` but I guess this is just a typo in the report?
Please also double check your host name, port and encryption method. The error indicates that a connection to the provided server could not be established. 
You might also want to check if the newest .env got correctly loaded by dumping a variable:
```php
dump(env("IMAP_HOST"));
dump(Client::account("default"));
```

Best regards,

**Comment by umarpucitian** [comment]
![imap](https://user-images.githubusercontent.com/41008978/104607168-583cc380-56a2-11eb-82f9-a0162b7146ac.PNG)

**Comment by umarpucitian** [comment]
I dumped that already, Its all working fine but still same error which I mentioned above, I am using CPanel Email credentials. I own cPanel account where I deployed my application

**Comment by Webklex** [comment]
Hi @umarpucitian ,
thanks for the followup.

Are you using a self signed certificate? If so try to set `IMAP_VALIDATE_CERT` to `false`.

By the way I tried to connect to your mentioned domain name; `Name or service not known`. Are you sure it is correctly configured and actually reachable by the server?
You can test it yourself by running the following command:
```bash
openssl s_client -crlf -connect mail.overstepgroup.com:993
```

Best regards,

**Comment by webdeal** [comment]
I have the same problem, I'm using the latest version and I get:
production.ERROR: failed to read - connection closed?

It works, but sometimes it throws this error. I have it in 5 minutes scheduler and I get this error about 2-3 times a day (nothing wrong, but in logs it messing).
I've tried change protocol and encryption, change validate cert, change domain to ip, but nothing helped.

**Comment by Webklex** [comment]
Hi @webdeal ,
this can happen if your internet connection isn't stable.

If you don't feel like that's the cause, please head over to https://github.com/Webklex/php-imap/issues/new?assignees=&labels=&template=bug_report.md and create a new issue.

Best regards,
