### ISSUE TITLE
How to get info about read status.

### ISSUE THREAD

**Issue by Jalbf** [Webklex/laravel-imap#387]
Please be aware that these issues will be closed if inactive for more then 14 days :)
Implementing some email client, base on this package. For list of emails (just subjcect, date and from fields) it is good to use folder overview function. But I also need an information if this message is already read. How can I get this information with overview? Because if I get all the messages, it's take to much time for listing to load for example 50 messages

**Comment by Webklex** [comment]
Hi @Jalbf ,
unfortunately you can't right now.

However the next version will contain a new method which will allow you to fetch messages in chunks.
It will look like this:
```php
$folder->query()->setFetchBody(false)->leaveUnread()->all()->chunked(function($messages, $chunk){
    /** @var \Webklex\PHPIMAP\Support\MessageCollection $messages */
    dump("chunk #$chunk");
    $messages->each(function($message){
        /** @var \Webklex\PHPIMAP\Message $message */
        dump($message->flags);
    });
}, $chunk_size = 10, $start_chunk = 1);
```

- https://github.com/Webklex/php-imap/commit/32c2f577fe9e0384c1af8664624c7ed123c77bcf
- https://github.com/Webklex/php-imap/blob/master/CHANGELOG.md
- https://github.com/Webklex/php-imap-documentation/commit/309e201a69a6a94d99c0b3a58767dba28c6ba246

Best regards,

**Comment by Jalbf** [comment]
Ok, Thank you for the informations
