### ISSUE TITLE
Loading attachments / bodies after fetching message without body / attachments

### ISSUE THREAD

**Issue by ricus-zero2one** [Webklex/laravel-imap#388]
Hi @Webklex 

General question here I hope you can assist with.

This question is for version 1.x as I haven't been able to upgrade just yet because of one mailbox, but there is a more pressing issue of bandwidth usage.

On our current setup, we sync emails every 1 or 2 minutes, and every time we sync we get the latest x amount of messages (normally 10), and process them. 

The problem here is that every time we query the emails, we pull down everything (full bodies and attachments), and if no new email has arrived since the last sync, we are essentially just wasting bandwidth as we are pulling down attachments that has already been synced.

This isn't really an issue with gmail and outlook, but some locally hosted mail servers start to charge for overusage, and in one situation we have already done 500GB of traffic for one client for half a month, which isn't ideal.

I'm trying to slim down our bandwidth usage by just pulling the headers, using that to identify if we've synced it already, and only get the full bodies and attachments if we need to. (In hindsight it should have worked like this from the start)

I've noticed that `->setFetchBody(false)` (when querying the folder) can be used on it's own, as you can't get the attachments without getting the body, so setting fetch body to `false` gives me an empty array for the bodies and an empty array for the attachments which seems to be on the right path, setting it to `true` gives the bodies and attachments.

```php
$messages = $inbox->query()
            ->setFetchBody(false) // returns without bodies / attachments as expected
            ->all()
            ->limit(1)->get();
```

Now that you've got the long of it. I'm struggling to get the bodies and attachments after already have retrieved the email without them. Calling `->getAttachments()` on the email returns an empty array, it doesn't seem to check if it needs to retrieve it, just returns what is stored on `Message`

How can I go about getting the full bodies and attachments **after** having retrieved the email without them? Do I need to query the imap folder again from scratch or preferably is there a way I can use the existing `Message` instance I have to just pull these items down?

**Edit**
It seems like calling `parseBody()` on the message loads the full bodies. Is this the way to go about it? Fetch without bodies, when we need to sync it knowing it's new, then call `parseBody()` and continue as normal?

**Comment by Webklex** [comment]
Hi @ricus-zero2one ,
thanks for your question.

V2 is way faster then V1. I highly reccommend to use v2 instead of v1 as soon as possible.

But regarding your question:
- Try to limit the overall amount of messages you are fetching:
```php
$folder->query()->unseen()
$folder->query()->since(Carbon::now()->subDays(1))
```
- You can't fetch the attachment without the body. Attachments are part of the body.
- Yes, you are correct. Only fetching the headers is the best way:
  - Using `Message::parseBody()` is perfectly fine - I do the same :)
  - Checkout `Folder::overview()` and the v2 feature `Folder::idle()`  maybe they'll help you as well

Best regards,

**Comment by ricus-zero2one** [comment]
@Webklex we normally do at most 10 messages each sync, but we do that every minute or so, so it adds up.

Adding `->setFetchBody(false)` to my main query when we sync seems to be working nicely, after I do a duplication check on the message id and some other values in the header, I then only call `$message->parseBody()` to get the full message if it's not a duplicate, and just discard it if it is, without ever getting the full body and attachments. From my tests this seems to work, and I'll likely be deploying that one later today.

I really want to get v2 deployed, it was merged into master and deployed last Saturday, but then ran into those issues I've been creating on the other repo, so had to revert until that has been sorted.

It's basically one box keeping us up now, the one with that weird offset 0 error, we are possibly going to make another plan with that one if it can't be resolved because it's keeping version 2 away from 500+ other mailboxes, and I'm eager to try some of these new things in v2. Especially IDLE, but also need to consider if idle is viable for hundreds of mailboxes (and monitoring to make sure they remain listening?), or to just use it in some cases.

Kind Regards
