### ISSUE TITLE
Wired results from IMAP

### ISSUE THREAD

**Issue by PrzemekTkaczyk** [Webklex/laravel-imap#389]
Hello, 
first, thank you for your great work on the package!

Now, my question ;)
After update from v1 to v2.4.4 I have wired problems when getting emails from IMAP, 
I'm using query like ~ `folder->query->since(now->subMin(10))->get()` and the details of emails is random, I mean for example - I had one email content on few others emails, 
I've changed config - and remove attachments: `'dispositions' => ['inline']` instead of `'dispositions' => ['attachments', 'inline']` but still 
when fetching a lot of emails and for example just dump `uid` & `hasXXXBody` & `hasAttachemnts` 
results are random, the same UID sometimes has true sometimes has false ..

For now, I changed my code, and fetch emails each minute - because if there are fewer emails in the package there were no problems.
If I try to get one email `byUid` - then always has correct content/attachments etc...

Maybe you can help me or give some advice on how to fix this issue?

(I use your package for more than a year probably :) and works perfectly 👍  )

**Comment by Webklex** [comment]
Hi @PrzemekTkaczyk ,
thanks for your report.

Never think you've seen it all - well this one is new to me. I try to make sense of it but I can't imagine a scenario which might cause this.
However to get some clues:
- Please provide the entire used config
- Does updating to v2.5.0 solve this?
- Can you disclose the provider you are using? Is it a Microsoft product?

This should not work:
```php
$folder->query()->since(now()->subMin(10))->get()
```
Please try to use:
```php
$folder->query()->since(now()->subDays(1))->get();
// ..or
$folder->query()->unseen()->get();
```
Here is an other alternative:
```php
$now = now();

$folder->query()->since(now()->subDays(1))->setFetchBody(false)->get()->each(function($message) use($now){
    if ($message->date->toDate()->diffInMinutes($now) <= 5) {
        $message->parseBody();
        var_dump($message);
    }
}
```

Checkout https://www.php-imap.com/api/query for additional methods such as `Query::chunked()`.

Best regards,

**Comment by PrzemekTkaczyk** [comment]
Thank you for your advices 

I update to 2.5
and change to chunked query 
I will check how it will works :)
