### ISSUE TITLE
AUTHENTICATIONFAILED

### ISSUE THREAD

**Issue by EvgenyGulyaev** [Webklex/laravel-imap#390]
I got the following error
Can you help me ?

```
got an extra server challenge: eyJzdGF0dXMiOiI0MDAiLCJzY2hlbWVzIjoiQmVhcmVyIiwic2NvcGUiOiJodHRwczovL21haWwuZ29vZ2xlLmNvbS8ifQ==

got failure response: NO [AUTHENTICATIONFAILED] Invalid credentials (Failure)
```
I change my settings too.(Enable imap and enable security)
I try use OAUTH login and password are correct

**Desktop / Server (please complete the following information):**
- PHP: [e.g. 7.4]

**Comment by Webklex** [comment]
Hi @EvgenyGulyaev ,
thanks for your report.

Please checkout https://www.php-imap.com/examples/oauth

The challenge you've received is base64 encoded and decodes to:
```php
{"status":"400","schemes":"Bearer","scope":"https://mail.google.com/"}
```

It looks like you've forgot to add `https://mail.google.com/` to the scope during your token generation process.

Best regards,

**Comment by EvgenyGulyaev** [comment]
@Webklex  I got this message after the following code 
```
  $this->client = Client::account('gmail');
        $this->client->connect();
```

**Comment by EvgenyGulyaev** [comment]
I'm not sure But I don't have  "App passwords"
![image](https://user-images.githubusercontent.com/18347978/106745757-a0605d80-6632-11eb-89fc-7567bdb48e7b.png)

**Comment by EvgenyGulyaev** [comment]
Ok, I added application password,
But I got the same error

**Comment by EvgenyGulyaev** [comment]
Oh..... It is a magic  =)
I randomly added this => `'authentication' => 'oauth'`, in my config and I got error about  auth
I deleted this row. I solved this problem, thank you for your advice
