### ISSUE TITLE
Bug in message class

### ISSUE THREAD

**Issue by okrulik** [Webklex/laravel-imap#391]
take a look 

` public function parseRawFlags($raw_flags) `
method in Message class

line 
```
   if ( in_array($flag_key, $this->available_flags)  || $this->available_flags === null) {
                $this->flags->put($flag_key, $flag);
            }
```
can potentially throw an exception

correct code is
```
 if ( $this->available_flags === null || in_array($flag_key, $this->available_flags) ) {
                $this->flags->put($flag_key, $flag);
            }
```

**Comment by peanut24** [comment]
@okrulik depending on your error level configured you are correct. If `$this->available_flags` is null, the current if statement will thrown a php warning for `in_array() expects parameter 2 to be array, null given`

The easiest solution is probably to swap them around like you suggested. Have you considered making a PR with this change?

@Webklex would you accept a PR that changes the order to have the null check first?

**Comment by Webklex** [comment]
Hi @okrulik ,
thanks for your report. @peanut24 thanks for your pr.

Please head over to the core repository https://github.com/Webklex/php-imap for any additional problems / questions.

Best regards,
