### ISSUE TITLE
Reply to an email

### ISSUE THREAD

**Issue by umarpucitian** [Webklex/laravel-imap#393]
How can we reply to an email when we get email using webklex.. I want to reply to that emails using Webklex. Any help will be highly appreciated

**Comment by Webklex** [comment]
Hi @umarpucitian ,
thanks for your question.

Please take a look at https://laravel.com/docs/8.x/mail for sending messages in laravel.

@umutpamuk provided an example here: https://github.com/Webklex/laravel-imap/issues/306

Best regards,
