### ISSUE TITLE
Wrong detect attachment name

### ISSUE THREAD

**Issue by martinsojak** [Webklex/laravel-imap#394]
Wrong detect attachment name (return "undefined")

Raw data of attachment:
Content-Type: application/pdf; 
	name="=?UTF-8?Q?Testovacie_meranie_ur=C4=8Den=C3=A1_na_hocijak=C3=A9_=2D_hodnoty_=2D_dokol?=
	=?UTF-8?Q?a=2C_tretier_s_nami=2Epdf?="
Content-Disposition: attachment; 
	filename="=?UTF-8?Q?Testovacie_meranie_ur=C4=8Den=C3=A1_na_hocijak=C3=A9_=2D_hodnoty_=2D_dokol?=
	=?UTF-8?Q?a=2C_tretier_s_nami=2Epdf?="
Content-Transfer-Encoding: base64
Content-ID: <f_klty4q3q0>
X-Attachment-Id: f_klty4q3q0

Attachment->getName() return "undefined" but original name is "Testovacie meranie určená na hocijaké - hodnoty - dokola, tretier s nami.pdf"

**Comment by MouMoutMan** [comment]
You need to sanitize your filename ;) 

For example:
`filename="=?UTF-8?Q?Testovacie_meranie_ur=C4=8Den=C3=A1_na_hocijak=C3=A9_=2D_hodnoty_=2D_dokol?=
=?UTF-8?Q?a=2C_tretier_s_nami=2Epdf?="`
to
`filename="Testovacie_meranie=pdf"`

**Comment by BinPhanH** [comment]
Same problem here
`Content-Type: application/pdf;\r\n
        \tname=________________.pdf;\r\n
        \tx-apple-part-url=D7BA66D5-CDC0-4355-B439-4809C7FAF8F4\r\n
        Content-Disposition: attachment;\r\n
        \tfilename*=utf-8''%E3%82%A6%E3%82%A3%E3%82%B5%E3%82%99%E3%83%BC%E3%80%81%E3%82%A6%E3%82%A3%E3%82%B5%E3%82%99%E3%83%BC%E3%82%B9%E3%82%B1%E3%83%AB%E3%83%88%E3%83%B3.pdf\r\n`
        
 And I cant seem to find a way to decode it

**Comment by vigstudio** [comment]
I am also having the same problem

**Comment by Webklex** [comment]
Hi @martinsojak  @MouMoutMan  @BinPhanH  @vigstudio  many thanks for your reports!

I'm going to merge this issue with [#102](https://github.com/Webklex/php-imap/issues/102). Please feel free to come over and join the discussion :)

Best regards,
