### ISSUE TITLE
Idle on multiple accounts

### ISSUE THREAD

**Issue by dichioniccolo** [Webklex/laravel-imap#395]
Hello,

Is there a way to remain idle (using the idle function on the folder) on multiple accounts?
I have a list of accounts in the DB and I would like to have them all listen to new messages, without me having to fetch them manually.

Currently my code looks like this:
![image](https://user-images.githubusercontent.com/5453226/110040594-5c509d80-7d43-11eb-87b1-5c574f3849af.png)

Is there a way to archieve what I am trying to do?

Thank you in advance.

**Comment by NiccoFuria** [comment]
NO

**Comment by dichioniccolo** [comment]
> Hi, did you find a solution?

No, i did not find a solution, sorry

**Comment by Webklex** [comment]
Hi @dichioniccolo  @burakaktna @NiccoFuria ,
this is kind of tricky since you'll have to manage x async connections. PHP itself isn't really designed to do this, but nothing is impossible :)

You could utilize Laravel Jobs and / or Laravel queue workers to do this, however you'll need some mechanism to monitor and control all running instances and restart them if they failed or died for some reason. So tracking the job system-pids might be required. If you are tracking pids you also need to check them regularly to detect and remove any stale pids and so on.. It also depends on the amount of accounts - if you only want to monitor a hand full, then I wouldn't go as far as implementing any complex job / queue system. Just create 5 different commands :)

**Comment by amiranagram** [comment]
I watched this 2 videos on building an asynchronous chat with React PHP. Check it out it's very useful.

https://www.youtube.com/watch?v=xv1_IhT-kiM
https://www.youtube.com/watch?v=zv4YcIo-lYk

I'm gonna try to use this knowledge to try and build a pool that's gonna listen for new messages on multiple email accounts. Will get back to you with findings.

If anyone tries it out before me and has some success with it, post your findings please. 🙂

**Comment by stevebauman** [comment]
I was able to get this going using [Spatie\Fork](https://github.com/spatie/fork). You can call this library's `$folder->idle()` method in each Spatie `Fork` process which will stay long lived. Though I'm not sure how reliable it will be when running on many mailboxes:

```php
<?php

namespace App\Console\Commands;

use App\Models\Mailbox;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\Log;
use Spatie\Fork\Fork;
use Webklex\IMAP\Facades\Client as ClientFacade;
use Webklex\PHPIMAP\Exceptions\ConnectionFailedException;
use Webklex\PHPIMAP\Exceptions\FolderFetchingException;
use Webklex\PHPIMAP\Folder;
use Webklex\PHPIMAP\Message;

class MailboxWatch extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'app:mailbox:watch';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Watch mailboxes for new messages.';

    /**
     * Execute the console command.
     *
     * @return int
     */
    public function handle()
    {
        $fork = Fork::new();

        $processes = [];

        /** @var \App\Models\Mailbox $mailbox */
        foreach (Mailbox::all() as $mailbox) {
            $processes[] = function () {
                $client = ClientFacade::make(['...']);

                try {
                    $client->connect();
                } catch (ConnectionFailedException $e) {
                    Log::error($e->getMessage());

                    return 1;
                }


                try {
                    /** @var Folder $folder */
                    $folder = $client->getFolder('Inbox');
                } catch (ConnectionFailedException $e) {
                    Log::error($e->getMessage());

                    return 1;
                } catch (FolderFetchingException $e) {
                    Log::error($e->getMessage());

                    return 1;
                }

                try {
                    $folder->idle(function ($message) {
                        $this->onNewMessage($message);
                    });

                } catch (\Exception $e) {
                    Log::error($e->getMessage());

                    return 1;
                }
            };
        }

        $fork->run(...$processes);
    }
}
```
