### ISSUE TITLE
getDate() results in Carbon\Exceptions\InvalidFormatException 

### ISSUE THREAD

**Issue by christophnagl** [Webklex/laravel-imap#396]
Hi,

using $oMessage->getDate() is generating the error
Carbon\Exceptions\InvalidFormatException
The separation symbol could not be found Unexpected data found. Unexpected data found. Unexpected data found. Trailing data

is this releated with the fix in V 2.5.0. in the php-imap repository?

thanks

**Comment by christophnagl** [comment]
has anyone an idea for a workaround?

**Comment by Webklex** [comment]
Hi @christophnagl ,
please take a look at the raw message headers and look for a line which starts with "Date: ". This date is very likely invalid. Please post it here, so another validation rule can be added to the Header class. 

https://github.com/Webklex/php-imap/blob/master/src/Header.php#L692-L715

Best regards,
