### ISSUE TITLE
mb_convert_encoding(): Illegal character encoding specified

### ISSUE THREAD

**Issue by octolit** [Webklex/laravel-imap#40]
When email contains HTML and/or characters such as **ąčęėįšųūž** i get this error.

**Comment by Webklex** [comment]
Hi @octolit ,
I did some research and it seems to be a special case for win encoded emails. I'll guess I have to find the correct encoding method for each email in order to prevent this error.

Any ideas are welcome here :)

Best regards

**Comment by girvydas** [comment]
Some references:
https://github.com/roundcube/roundcubemail/issues/1004
https://github.com/roundcube/roundcubemail/commit/b8e65ce39b5330fb99371c9dc039f8d19f39477d

**Comment by Webklex** [comment]
@girvydas thanks for the references. I'll take a closer look at them and will provide a fix as soon as possible

**Comment by girvydas** [comment]
Fo me hotfix at Webklex\IMAP\Message class works fine:
```
private function convertEncoding($str, $from = "ISO-8859-2", $to = "UTF-8") {
        if (function_exists('iconv') && $from!='UTF-7' && $to!='UTF-7') {
            return iconv($from, $to, $str);
        } else {
            if (! $from) {
                return mb_convert_encoding($str, $to);
            }
            return mb_convert_encoding($str, $to, $from);
        }
    }
```

**Comment by Webklex** [comment]
@girvydas @octolit please ref. to v. [1.0.3.8](https://github.com/Webklex/laravel-imap/releases/tag/1.0.3.8)
