### ISSUE TITLE
replace email inline image url using mask 

### ISSUE THREAD

**Issue by nehemmiah** [Webklex/laravel-imap#400]
hello,
so i've been trying to understand how to use mask since i read the code and it has function to replace the image url inside the mail.
i'm referencing to the getHTMLBodyWithEmbeddedBase64Images()
i'm new to this so the first question is : _what_ is mask? and then the main question, _how_ to use it?

this is the code for my controller
```php
$oClient = Client::account('default');
        $oClient->connect();

        $message_mask = \Webklex\PHPIMAP\Support\Masks\MessageMask::class;
        $oClient->setDefaultMessageMask($message_mask);

        /** @var \Webklex\IMAP\Folder $oFolder */
        $aFolder = $oClient->getFolders('INBOX');

        foreach($aFolder as $oFolder){
            
            /** @var \Webklex\IMAP\Support\MessageCollection $aMessage */
            try {
                $aMessage = $oFolder->query()->getMessageByUid($id);
            } catch (\Throwable $th) {
                return 'error';
            }

        }
        
        $message_mask = $aMessage->mask();
        $mail = $aMessage;
        // $mailbody = $mail->getHtmlBody();
        

        return view("email.show", compact('mail'));
```

and this is on the blades view,
```blade
{!! $mail->getHtmlBody() !!}
```

i tried using 
```blade
{!! $mail->getHTMLBodyWithEmbeddedBase64Images() !!}
or
{!! $mail->getCustomHTMLBody() !!}
```
but it just returned null

i hope i can get some help with this, thank you

**Comment by Webklex** [comment]
Hi @nehemmiah ,
please try to use `$message_mask` instead of `$mail`. In your case the masked instance is stored in  `$message_mask` and not in `$mail`. If you want or have to use `$mail`, try using `$mail->mask()` instead.

Best regards,
