### ISSUE TITLE
Client doesn't connect to POP3 servers

### ISSUE THREAD

**Issue by 91Abdullah** [Webklex/laravel-imap#402]
Client doesn't work with POP3 clients and throws error (probably due to read-only access disabled from mail server). Apart from that client should support POP3 servers. Error is pasted below:

imap_open(): Couldn't open stream {0.0.0.0:110/pop3/novalidate-cert}. Read-only POP3 access not available (0)

**To Reproduce**
```php
$cm = new ClientManager();
        $client = $cm->make([
            'host' => '0.0.0.0',
            'port'          => 110,
            'encryption'    => false,
            'validate_cert' => false,
            'username'      => 'example@example.com',
            'password'      => 'example123',
            'protocol'      => 'pop3',
        ]);
        $client->connect();
        $folders = $client->getFolders();
        $client->disconnect();
        dd($folders);
```

**Expected behavior**
Client should connect to POP3 server.

**Solution**
After changing login function in LegacyProtocol.php (/webklex/php-imap/src/Connection/Protocols/LegacyProtocol.php) client connected successfully with POP3. 

Error was due to passing option parameter in imap_open:
```php
$this->stream = \imap_open(
                $this->getAddress(),
                $user,
                $password,
                ~~IMAP::OP_READONLY~~,
                $attempts = 3,
                ClientManager::get('options.open')
            );
```

The option should be configurable passed in the constructor etc.

**Comment by Webklex** [comment]
Hi @91Abdullah ,
please update your `webklex/php-imap` dependency to the latest release (>2.7.0). 
This will hopefully solve the problem. If not, please head over to the [webklex/php-imap](https://github.com/Webklex/php-imap) repository and create a new issue.

Best regards,
