### ISSUE TITLE
Folder List is empty when connection to Microsoft account

### ISSUE THREAD

**Issue by crisleiria** [Webklex/laravel-imap#405]
**Describe the bug**
I am trying to get all messages from inbox from Microsoft account. It connects successefuly but when I list all folders, list is empty.
This is an brand new Microsoft account with default settings.

Webklex\PHPIMAP\Support\FolderCollection^ {#1133
  #total: null
  #items: []
}

This are my settings:

`IMAP_HOST=outlook.office365.com`
`IMAP_PORT=993`
`IMAP_ENCRYPTION=ssl`
`IMAP_VALIDATE_CERT=true`
`IMAP_USERNAME=email@mydomain.com`
`IMAP_PASSWORD=mypassword`
`IMAP_PROTOCOL=imap`
`IMAP_AUTHENTICATION=xoauth2`

**To Reproduce**

1. Have one laravel app
2. Setting this on .env file with the above settings
3. Connect to Email box with the following code

`$oClient = Client::account('default');`
`$oClient->connect();`
`$aFolder = $oClient->getFolder('INBOX', true);`

**Expected behavior**
Fetch INBOX folder and retreive all emails.

**Screenshots**

**Desktop / Server (please complete the following information):**
 - OS: Ubuntu
- PHP: 7.4.9
 - Version 2.4 (latest) and Laravel version 6.20.27

**Additional context**
It connects OK, but no folders.

**Comment by duykhoa87** [comment]
Anyone can help on this issue. I am facing the same here. Thanks
