### ISSUE TITLE
subject encode error

### ISSUE THREAD

**Issue by vigstudio** [Webklex/laravel-imap#408]
The subject is faulty. I don't understand the reason. Here is a specific example
Re: [Water Care] -Thông báo lịch phỏng vấn ÄeÌÌn uÌÌng vieÌn

**Comment by Webklex** [comment]
Hi @vigstudio ,
many thanks for your report. Please head over to the core repository: https://github.com/Webklex/php-imap

If you haven't updated your `webklex/php-imap` dependency to the latest version, please do so and try again.

Best regards,
