### ISSUE TITLE
Error in the manual  "Disable encryption" must be "notls"

### ISSUE THREAD

**Issue by jazz-max** [Webklex/laravel-imap#409]
When trying to connect without encryption, using the "false" parameter as indicated in the documentation results in an error. Using "notls" solved the problem. 
Please correct manual at  https://www.php-imap.com/configuration/account/account

**To Reproduce**
$clientManager = new ClientManager();
$config = [
'host'=> 'mail.host.com',
'port'=> 110,
'encryption'=>false,
'validate_cert'=>false,
'username'=>'user',
'password'=>'pasword',
'protocol'=>'pop3'
];
 $client = $clientManager->make ( $config );

<warning>PHP Warning:  imap_open(): Couldn't open stream {mail.host.com:110/pop3/novalidate-cert} in /var/www/html/vendor/webklex/php-imap/src/Connection/Protocols/LegacyProtocol.php on line 85</warning>

**Comment by Webklex** [comment]
Hi @jazz-max ,
thanks for your report.

It might be a bit misleading but I don't think its wrong. If you set `encryption` to false - the whole "tag" wont get set. If you set it to `notls` the tag gets set. 

Here is the code reference: https://github.com/Webklex/php-imap/blob/master/src/Connection/Protocols/LegacyProtocol.php#L128-L142

Best regards,
