### ISSUE TITLE
imap_expunge(): supplied resource is not a valid imap resource

### ISSUE THREAD

**Issue by nemiq** [Webklex/laravel-imap#41]
Hi,

message->delete runs imap_expunge which should not run until connection is shut down. See comments from http://php.net/manual/en/function.imap-expunge.php

Message.php:
>/**
     * Delete the current Message
     *
     * @return bool
     */
    public function delete(){
        $status = imap_delete($this->client->connection, $this->uid, $this->fetch_options);
        $this->client->expunge(); <-- Remove
        return $status;
    }

Add new function for Client.php to delete all messages marked for delete (which is done through imap_delete).

>[15-Nov-2017 15:21:21 UTC] PHP Fatal error:  Uncaught ErrorException: imap_expunge(): supplied resource is not a valid imap resource in /www/vendor/webklex/laravel-imap/src/IMAP/Client.php:448
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'imap_expunge():...', '/www...', 448, Array)
#1 /www/vendor/webklex/laravel-imap/src/IMAP/Client.php(448): imap_expunge(Resource id #307)
#2 /www/vendor/webklex/laravel-imap/src/IMAP/Client.php(211): Webklex\IMAP\Client->expunge()
#3 /www/vendor/webklex/laravel-imap/src/IMAP/Client.php(102): Webklex\IMAP\Client->disconnect()
#4 [internal function]: Webklex\IMAP\Client->__destruct()
#5 {main}
  thrown in /www/vendor/webklex/laravel-imap/src/IMAP/Client.php on line 448

**Comment by parshikov** [comment]
To temporary fix this issue, you MUST NOT call `$client->disconnect()`  before destructing the `$client` object

**Comment by nemiq** [comment]
Thanks parshikov,

Noticed I copied wrong fault message, but anyway happened to be the other issue I was facing. I also removed the disconnect() which fixed it.

What about the expunge in the delete function? If I loop two messages from a mail box, run expunge on first message then second message ID wont be correct?

> [16-Nov-2017 17:18:25 UTC] PHP Fatal error:  Uncaught ErrorException: Unknown: IMAP protocol error: Error in IMAP command STORE: Invalid messageset (errflg=2) in Unknown:0
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Unknown: IMAP p...', 'Unknown', 0, NULL)
#1 {main}
  thrown in Unknown on line 0

**Comment by parshikov** [comment]
@nemiq yes. This is another issue. I can not check now, but it looks like if you use `FT_UID` option you should not get this fault message, because deleting of one message from the mailbox does not change the uids of others. Anyway, using `Client::expunge()` in `Message::delete()` makes `Message::restore()` absolutely useless.
