### ISSUE TITLE
Subject encoding is sometime not what's expected

### ISSUE THREAD

**Issue by Naghal** [Webklex/laravel-imap#410]
**Describe the bug**
Sometimes, the subject is not what expected,
As an example, I have an email in gmail web browser with subject `Maj Vidéotron`.
When calling $message->getSubject(), I am getting the subject: `MAJ =?utf-8?b?Vmlkw6lvdHJvbg==?=`.
It is the same subject no matter what decoder option is set in the decode.message.subject config.
(utf-8, iconv and mimeheader)

**To Reproduce**
Connect to a mailbox then:

```php
 $this->client->connect();
 $folder = $this->client->getFolder('INBOX');
$unseenMessages = $folder->query()->unseen()->get();

foreach($unseenEmails as $email) {
    dd($email->getSubject())
}
```

**Expected behavior**
The subject returned by `getSubject()` should be `Maj Vidéotron`.

**Screenshots**
![image](https://user-images.githubusercontent.com/29404633/130810799-589fc4b4-9728-4fef-b3e3-8c8745e50790.png)
raw subject header:
![image](https://user-images.githubusercontent.com/29404633/130810871-52059687-f8a2-454f-8569-4d6438a2f527.png)

**Desktop / Server (please complete the following information):**
 - OS: Ubuntu 20
- PHP: 8.0.6
 - laravel-imap 2.4.0
 - php-imap 2.6.0

**Comment by Webklex** [comment]
Hi @Naghal ,
many thanks for your report. 

Please update your `webklex/php-imap` dependency to the latest release (>2.7.0). 
This will hopefully solve the problem. If not, please head over to the [webklex/php-imap](https://github.com/Webklex/php-imap) repository and create a new issue.

Best regards,
