### ISSUE TITLE
from and subject not correctly documented

### ISSUE THREAD

**Issue by Akantor47** [Webklex/laravel-imap#411]
**Describe the bug**

The Documentation is not up to date. 

Function ´getFrom()` and `getSubject()` do not work as displayed in the documentations.

**To Reproduce**

Connect to an IMAP server and Read messages via the examples/message_table.blade.php.

Line 33 wil throw an error. Correct to `getSubject()->toArray()[0]` for a working example.

Line 34 will throw an error. Correct to  `getFrom()->toArray()[0]->mail` for a working example.

**Expected behavior**

**Screenshots**

**Desktop / Server (please complete the following information):**
 - OS: Ubuntu Server
- PHP: 7.4
 - Version 20.04 LTS

**Additional context**

**Comment by EriBloo** [comment]
You can fix it as well with `getSubject()->first()` and `getFrom()->first()->mail`.
