### ISSUE TITLE
Why $attachment->getAttributes()  always contain "type" => "text"

### ISSUE THREAD

**Issue by jazz-max** [Webklex/laravel-imap#413]
When i get message "jpg" attachments attributes
$attachment->getAttributes()  always contain "type" => "text"

**Comment by Webklex** [comment]
Hi @jazz-max ,
many thanks for your report. Unfortunately this is the wrong repository.

Please head over to https://github.com/Webklex/php-imap/issues/new?assignees=&labels=&template=bug_report.md and try to be as precise as possible. Also consider to add some example date which would be required to replicate the issue.

Best regards,
