### ISSUE TITLE
getSender is null

### ISSUE THREAD

**Issue by vigstudio** [Webklex/laravel-imap#414]
When I use the getSender method the return value is always NULL

**Comment by Webklex** [comment]
Hi @vigstudio ,
many thanks for your report. Unfortunately this is the wrong repository.

Please head over to https://github.com/Webklex/php-imap/issues/new?assignees=&labels=&template=bug_report.md and try to be as precise as possible. Also consider to add some example date which would be required to replicate the issue.

Best regards,
