### ISSUE TITLE
getSender method NULL

### ISSUE THREAD

**Issue by vigstudio** [Webklex/laravel-imap#415]
**Describe the bug**
When I use the getSender method the return value is always NULL

**To Reproduce**
$message->getSender() 

**Expected behavior**
I hope it can work properly again. I used getFrom instead

**Screenshots**

**Desktop / Server (please complete the following information):**
 - OS: Windows 10
- PHP: 8.0.10
 - Version 2.4.0

**Additional context**

**Comment by Webklex** [comment]
Hi @vigstudio ,
many thanks for your report. Unfortunately this is the wrong repository.

Please head over to https://github.com/Webklex/php-imap/issues/new?assignees=&labels=&template=bug_report.md and try to be as precise as possible. Also consider to add some example data which would be required to replicate the issue.

Best regards,
