### ISSUE TITLE
Slow loading on retrieving emails

### ISSUE THREAD

**Issue by Elsingad** [Webklex/laravel-imap#416]
**Describe the bug**
Retrieving e-mails from a g-mail account takes super long (1.5 hours for 600-700 e-mails)

**Expected behavior**
Fast loading (or atleast under 2 minutes)

```
// Select inbox
$inbox = $client->getFolder('INBOX');

// Get mails
 $messages = $inbox->query()->whereOn('15.09.2021')
            ->setFetchFlags(false)
            ->setFetchBody(false)
            ->get();
```

**Desktop / Server (please complete the following information):**
 - OS: Windows & MacOS
- PHP 8.0.7

**Comment by Webklex** [comment]
Hi @Elsingad,
many thanks for your report. Unfortunately this is the wrong repository.

Please head over to https://github.com/Webklex/php-imap/issues/new?assignees=&labels=&template=bug_report.md and try to be as precise as possible. Also consider to add some example date which would be required to replicate the issue.

Best regards,
