### ISSUE TITLE
Failed to fetch messages in Query.php (line 239)

### ISSUE THREAD

**Issue by OctavianPlay** [Webklex/laravel-imap#418]
For a while I get this error made by a received email. When I manually read him the error dissapears and all works fine(it pulls all emails).
The email is looking fine and I cant figure out what is the problem with that email.

I attached the email if can someone figure and help me with a workaround. I receive it every month from the same email address and it's a automatic email.

Sorry for my bad english!

**Comment by OctavianPlay** [comment]
Hi, ok but it's not spam. 
I receive it in inbox(we are pulling only from inbox folder). It is a trusted email from a hospital. It cotains a simple table with a notification of payment.
I only get that error. We are using laravel-imap from first months of 2020 and we didnt had any problems until last month.

**Comment by Webklex** [comment]
Hi @OctavianPlay ,
please head over to the core repository and create a new issue under https://github.com/Webklex/php-imap/issues/new?assignees=&labels=&template=bug_report.md . This library (`Webklex/laravel-imap`) is just a wrapper for `Webklex/php-imap` which holds all core classes such as the `Query::class`.

Please include as much information as possible (errors, callstacks, code snippets, etc).

Best regards,
