### ISSUE TITLE
How to use ->idle() method when trying to check for new messages through ajax request ?

### ISSUE THREAD

**Issue by eXCom** [Webklex/laravel-imap#420]
Im trying to check for new messages using ajax request.
When im just trying to listen to new messages on backend only with php, everything works fine. 

```
public function tracingNewMsg()
    {
        $client = MailIMAP::connection();
        $folder = $client->getFolderByPath('INBOX');
        $client->disconnect();
        $m = $folder->idle(function($message){
           $msg = $message->subject;
            dd($message->subject);
        },$timeout = 1200, $auto_reconnect = true);
    }
```

![scr1](https://user-images.githubusercontent.com/5220521/140330903-99958a47-1446-40fb-9a41-d8b43000c1d9.png)

But if im trying to send ajax request from frontend to backend, my request is pending.
```
public function tracingNewMsg()
    {
        $client = MailIMAP::connection();
        $folder = $client->getFolderByPath('INBOX');
        $client->disconnect();
        $m = $folder->idle(function($message){
           $msg = $message->subject;
            return response()->json($msg);
        },$timeout = 1200, $auto_reconnect = true);
    }
```

![scr2](https://user-images.githubusercontent.com/5220521/140331157-eacda479-019a-433e-badf-b74f93b18faf.png)

I also tried
```
public function tracingNewMsg()
    {
        $client = MailIMAP::connection();
        $folder = $client->getFolderByPath('INBOX');
        $client->disconnect();
        return $folder->idle(function($message){
           $msg = $message->subject;
            return response()->json($msg);
        },$timeout = 1200, $auto_reconnect = true);
    }
```
Its the same, pending...
Looks like ->idle() is just infinitely repeating itself, i would like to check for messages once and get a responce

 Is there any way to achieve what im trying to do ?

**Comment by Webklex** [comment]
Hi @eXCom ,
many thanks for your question. The `Folder::idle()` command is exactly designed to do just this - idle and call the callback as soon as a new message arrives. Its not supposed to ever "finish"..

If you want to fetch new messages, you'll have to use the `Folder::query()` method - or implement a websocket and combine it with the idle method. Take a look at the implemented event / subscriber support https://www.php-imap.com/frameworks/laravel/events - they might help you as well :)

Best regards,

P.s.: if you have any questions regarding the core `webklex/php-imap`, please head over to the core repository https://github.com/Webklex/php-imap and create an new issue there.

**Comment by eXCom** [comment]
Thank you @Webklex very much for such a quick responce, i'll look into it!
