### ISSUE TITLE
Trying to connect to outlook

### ISSUE THREAD

**Issue by jbarretodev** [Webklex/laravel-imap#421]
![image](https://user-images.githubusercontent.com/64809357/141513899-fa891fb3-af8e-4c4b-a93a-5b84912e57c8.png)

i dont know why? but it is throwing that exception....

i am doing this...

![image](https://user-images.githubusercontent.com/64809357/141514021-96003650-d062-4117-9649-40dbd4fa16b6.png)

my config

![image](https://user-images.githubusercontent.com/64809357/141514135-a05a7ef7-541c-465f-84ab-f62ce4d3b67f.png)

my .env

![image](https://user-images.githubusercontent.com/64809357/141514202-0b825187-6f2f-44fb-8e2f-6b834478772c.png)

**Comment by jbarretodev** [comment]
Please... i need some help

**Comment by Webklex** [comment]
Hi @jbarretodev ,
thanks for your question. Can you provide the entire call stack / stack trace? So far it could be anything.
Please check if `outlook.office365.com` is reachable by your host.

A few additional questions:
- Which `webklex/laravel-imap` version are you currently using?
- Which php version are you using?
- Which operating system are you using?

Best regards,

**Comment by jbarretodev** [comment]
i change my .env value SSL or TLS to tls and now show me that!

im using php7.4, nginx, ubuntu 20.04

 "webklex/laravel-imap": "^2.4",
        "webklex/php-imap": "^2.7",

![image](https://user-images.githubusercontent.com/64809357/141515910-98336a8b-3b01-481e-8ca9-67225b164c13.png)

**Comment by jbarretodev** [comment]
![image](https://user-images.githubusercontent.com/64809357/141516716-41e63451-268d-4519-988a-34f78ac9d77d.png)

**Comment by Webklex** [comment]
Hi @jbarretodev ,
many thanks for the followup.

What happens if you change `IMAP_ENCRYPTION` to `ssl` or `tls` (all lowercase) and / or enable `IMAP_VALIDATE_CERT`?

Best regards,

**Comment by jbarretodev** [comment]
COOOL MAN! jajajaa it work now! THANKS! hey just one more question.... with this library  can i download file from emails??

**Comment by Webklex** [comment]
I'm glad I could help :)

Yes you can, check out these links for more information and examples:
- https://www.php-imap.com/examples/getting-started
- https://www.php-imap.com/api/attachment

Best regards,

**Comment by jbarretodev** [comment]
Cool man! Thanks a lot!
