### ISSUE TITLE
Cannot move to sub folder

### ISSUE THREAD

**Issue by larsbo** [Webklex/laravel-imap#423]
After upgrading from 1.6.x to 2.4.x I cant move a message into an existing sub folder.

Running
`$message->move('INBOX.Folder.SubFolder');`
does not throw an exception and the message stays in the current folder.

While
`$message->move('INBOX.Folder');`
works fine.

The reason seems to be that `examineFolder()` inside the move method fails.

- PHP: 7.4.25
 - Version 2.4.0

**Comment by larsbo** [comment]
Update: it works fine with existing folders but not if the sub folder does not exist.

**Comment by Webklex** [comment]
Hi @larsbo ,
many thanks for your report. To be honest, it seem fine to me :) If you like to implement such a feature, feel free to create a pull request here: https://github.com/Webklex/php-imap

Best regards,
