### ISSUE TITLE
getMessageNo() is empty?

### ISSUE THREAD

**Issue by AndyDunn** [Webklex/laravel-imap#43]
When looping through a series of messages in a folder, I can get the UUID, subject, etc. but when I access the 'getMessageNo()' it's empty.

Is there any reason for this or a bug perhaps?

**Comment by Webklex** [comment]
Hi @AndyDunn ,
please provide some more information or perhaps some code samples.

I can't reproduce this behavior.

Best regards

**Comment by AndyDunn** [comment]
Hi @Webklex, this is the code I'm using:

`<?
            $client = new Client([
                'host'          => env('IMAP_HOST'),
                'port'          => 993,
                'encryption'    => 'ssl',
                'validate_cert' => true,
                'username'      => env('IMAP_USERNAME'),
                'password'      => env('IMAP_PASSWORD'),
            ]);

            $client->connect();
            $aMailboxes = $client->getFolders();

            foreach($aMailboxes as $oMailbox) {
                if ($oMailbox->name == env('IMAP_FOLDER')) {
                    foreach($oMailbox->getMessages() as $message) {
                        Log::info("Number: ".$message->getMessageNo());
                    }
                }
            }`

In the log files the number value is empty. Anything else you'd need me to check?

**Comment by VictorOtavio** [comment]
I've the same issue here...

**Comment by Webklex** [comment]
Please update to the latest version [v.1.0.4.0](https://github.com/Webklex/laravel-imap/releases/tag/1.0.4.0).
