### ISSUE TITLE
Trying to access array offset on value of type null

### ISSUE THREAD

**Issue by marcmaalouly** [Webklex/laravel-imap#430]
Hello,
I've been using this package for about a day or so, everything was working until today i've beeng getting the following error each time i try to fetch emails "Trying to access array offset on value of type null"

`$oClient = \Webklex\IMAP\Facades\Client::make([
            'host'          => $host,
            'port'          => $port,
            'encryption'    => 'ssl',
            'validate_cert' => true,
            'username'      => $username,
            'password'      => $password,
            'protocol'      => 'imap'
        ]);`

i connected the user using the following function and then did the following query
`$oFolder = $this->oClient->getFolder('INBOX');
            $messages = $oFolder->query()->unseen()->get();`

The full error is the following
`Webklex\PHPIMAP\Exceptions\GetMessagesFailedException {#933
  #message: "Trying to access array offset on value of type null"
  #code: 0
  #file: "./vendor/webklex/php-imap/src/Query/Query.php"
  #line: 347
  -previous: ErrorException {#974
    #message: "Trying to access array offset on value of type null"
    #code: 0
    #file: "./vendor/webklex/php-imap/src/Header.php"
    #line: 454
    #severity: E_NOTICE
    trace: {
      ./vendor/webklex/php-imap/src/Header.php:454 { …}
      ./vendor/webklex/php-imap/src/Header.php:206 { …}
      ./vendor/webklex/php-imap/src/Header.php:73 { …}
      ./vendor/webklex/php-imap/src/Message.php:420 { …}
      ./vendor/webklex/php-imap/src/Message.php:270 { …}
      ./vendor/webklex/php-imap/src/Query/Query.php:252 { …}
      ./vendor/webklex/php-imap/src/Query/Query.php:321 { …}
      ./vendor/webklex/php-imap/src/Query/Query.php:343 { …}
      ./app/Jobs/FetchSMTPEmails.php:46 {
        App\Jobs\FetchSMTPEmails->handle()
        › $oFolder = $this->oClient->getFolder('INBOX');
        › $messages = $oFolder->query()->unseen()->get();
        › foreach ($messages as $message)
      }
      ./vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:36 { …}
      ./vendor/laravel/framework/src/Illuminate/Container/Util.php:40 { …}
      ./vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:93 { …}
      ./vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:37 { …}
      ./vendor/laravel/framework/src/Illuminate/Container/Container.php:653 { …}
      ./vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php:128 { …}
      ./vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:128 { …}
      ./vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:103 { …}
      ./vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php:132 { …}
      ./vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php:120 { …}
      ./vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:128 { …}
      ./vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:103 { …}
      ./vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php:122 { …}
      ./vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php:70 { …}
      ./vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php:98 { …}
      ./vendor/laravel/framework/src/Illuminate/Queue/Worker.php:428 { …}
      ./vendor/laravel/framework/src/Illuminate/Queue/Worker.php:378 { …}
      ./vendor/laravel/framework/src/Illuminate/Queue/Worker.php:329 { …}
      ./vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php:117 { …}
      ./vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php:101 { …}
      ./vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:36 { …}
      ./vendor/laravel/framework/src/Illuminate/Container/Util.php:40 { …}
      ./vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:93 { …}
      ./vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:37 { …}
      ./vendor/laravel/framework/src/Illuminate/Container/Container.php:653 { …}
      ./vendor/laravel/framework/src/Illuminate/Console/Command.php:136 { …}
      ./vendor/symfony/console/Command/Command.php:298 { …}
      ./vendor/laravel/framework/src/Illuminate/Console/Command.php:121 { …}
      ./vendor/symfony/console/Application.php:1015 { …}
      ./vendor/symfony/console/Application.php:299 { …}
      ./vendor/symfony/console/Application.php:171 { …}
      ./vendor/laravel/framework/src/Illuminate/Console/Application.php:94 { …}
      ./vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:129 { …}
      ./artisan:37 { …}
    }
  }
  trace: {
    ./vendor/webklex/php-imap/src/Query/Query.php:347 { …}
    ./app/Jobs/FetchSMTPEmails.php:46 {
      App\Jobs\FetchSMTPEmails->handle()
      › $oFolder = $this->oClient->getFolder('INBOX');
      › $messages = $oFolder->query()->unseen()->get();
      › foreach ($messages as $message)
    }
    ./vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:36 { …}
    ./vendor/laravel/framework/src/Illuminate/Container/Util.php:40 { …}
    ./vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:93 { …}
    ./vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:37 { …}
    ./vendor/laravel/framework/src/Illuminate/Container/Container.php:653 { …}
    ./vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php:128 { …}
    ./vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:128 { …}
    ./vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:103 { …}
    ./vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php:132 { …}
    ./vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php:120 { …}
    ./vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:128 { …}
    ./vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:103 { …}
    ./vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php:122 { …}
    ./vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php:70 { …}
    ./vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php:98 { …}
    ./vendor/laravel/framework/src/Illuminate/Queue/Worker.php:428 { …}
    ./vendor/laravel/framework/src/Illuminate/Queue/Worker.php:378 { …}
    ./vendor/laravel/framework/src/Illuminate/Queue/Worker.php:329 { …}
    ./vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php:117 { …}
    ./vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php:101 { …}
    ./vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:36 { …}
    ./vendor/laravel/framework/src/Illuminate/Container/Util.php:40 { …}
    ./vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:93 { …}
    ./vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:37 { …}
    ./vendor/laravel/framework/src/Illuminate/Container/Container.php:653 { …}
    ./vendor/laravel/framework/src/Illuminate/Console/Command.php:136 { …}
    ./vendor/symfony/console/Command/Command.php:298 { …}
    ./vendor/laravel/framework/src/Illuminate/Console/Command.php:121 { …}
    ./vendor/symfony/console/Application.php:1015 { …}
    ./vendor/symfony/console/Application.php:299 { …}
    ./vendor/symfony/console/Application.php:171 { …}
    ./vendor/laravel/framework/src/Illuminate/Console/Application.php:94 { …}
    ./vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:129 { …}
    ./artisan:37 { …}
  }
}
`

Hope someone can help me with this and thanks.

**Comment by marcmaalouly** [comment]
To be more specific since i noticed something.
Creating the client and establishing the connection and finally fetching all emails in the same function works fine.
The error is happening when i'm establishing the connection in a function, then returning the client and finally fetching the emails in another function.
Example
`public function connect ($host,$port,$username,$password) {
$oClient = \Webklex\IMAP\Facades\Client::make([
            'host'          => $host,
            'port'          => $port,
            'encryption'    => 'ssl',
            'validate_cert' => true,
            'username'      => $username,
            'password'      => $password,
            'protocol'      => 'imap'
        ]);
        return $oClient->connect();
`
lets say i take this $oClient and i send it as a parameter to the following funciton:
`public function fetch(Client $oClient) {
            if (!$oClient->isConnected()) {
                $oClient = $oClient->connect();
            }
$oFolder = $oClient->getFolder('INBOX');
            $messages = $oFolder->query()->unseen()->get();
`

in this case i'm getting the error

**Comment by Webklex** [comment]
Hi @marcmaalouly ,
can you provide an example, so I can try to replicate this behavior? Im not sure what code you are running :)

Best regards & happy coding,

**Comment by marcmaalouly** [comment]
Hello @Webklex,
I fixed this error by caching the Client object and calling the cache in another function.
This error was caused since i'm calling the connect function and the fetch function on different API instances so the only way to keep the connection of the client opened was to save it in cache
