### ISSUE TITLE
Unable to get message html body in some cases

### ISSUE THREAD

**Issue by AsifMian** [Webklex/laravel-imap#431]
Please be aware that these issues will be closed if inactive for more then 14 days :)
` dd($oMessage->hasHTMLBody(),$oMessage->getHTMLBody());`

result is **false , null**

if message has body with html and inline css it retruns nothing which is annonying.

please tell how to fix, package install version is **2.4**

**Comment by jil1092000** [comment]
try this $oMessage->getRawBody()

**Comment by alphaolomi** [comment]
@jil1092000 still no content in body

Using v4 with gmail

**Comment by jil1092000** [comment]
> 
can you send me your code ?

**Comment by mpryvkin** [comment]
Seems to be related to  [php-imap issue #275 ](https://github.com/Webklex/php-imap/issues/275) and [php-imap PR #233](http://github.com/Webklex/php-imap/pull/233).

**Comment by Webklex** [comment]
Hi @AsifMian @alphaolomi ,
please update to the latest release. 
If the issue persists even after updating to the latest release, please head over to the core library and create a fresh issue here: https://github.com/Webklex/php-imap/issues/new?assignees=&labels=&projects=&template=bug_report.md

If you do, please also include a code and mail sample to replicate the reported behavior.

Best regards & happy coding,
