### ISSUE TITLE
message move is not working

### ISSUE THREAD

**Issue by PARTH-KUNDARIYA** [Webklex/laravel-imap#433]
Move message to another folder was working but since update it is not working.

```
if($message->move('INBOX/test') == true){
    echo 'Message has been moved';
}else{
    echo 'Message could not moved';
}
```

I have check delimiter etc but still not works. I have tried everything still not working. Now in big problem.

**Comment by Webklex** [comment]
Hi @PARTH-KUNDARIYA ,
many thanks for your report. Which versions are you currently using? Especially which version of `webklex/php-imap` and `webklex/laravel-imap`.

Do you get any error messages?

Best regards,
