### ISSUE TITLE
Gmail Authentication failed on live server - Uncaught Webklex\PHPIMAP\Exceptions\AuthFailedException 

### ISSUE THREAD

**Issue by boakyezitek** [Webklex/laravel-imap#434]
Hello, I really need help, Am using windows to test for PHP IMAP testing with Gmail from local and is working perfectly, when I upload them to the production server authentication keeps failing. Am using the ubuntu server. 

Fatal error: Uncaught Webklex\PHPIMAP\Exceptions\AuthFailedException in /home/themisterfridayproject/domains/maget.themisterfridayproject.com/public_html/vendor/webklex/php-imap/src/Client.php:388 Stack trace: #0 /home/themisterfridayproject/domains/maget.themisterfridayproject.com/public_html/vendor/webklex/php-imap/src/Client.php(371): Webklex\PHPIMAP\Client->authenticate() #1 /home/themisterfridayproject/domains/maget.themisterfridayproject.com/public_html/core/Imap/ImapConnection.php(47): Webklex\PHPIMAP\Client->connect() #2 /home/themisterfridayproject/domains/maget.themisterfridayproject.com/public_html/core/Application.php(20): app\core\Imap\ImapConnection->connection() #3 /home/themisterfridayproject/domains/maget.themisterfridayproject.com/public_html/index.php(14): app\core\Application->app() #4 {main} Next Webklex\PHPIMAP\Exceptions\ConnectionFailedException: connection setup failed in /home/themisterfridayproject/domains/maget.themisterfridayproject.com/public_html/vendor/webklex/php-imap/src/Client.php:391 S in /home/themisterfridayproject/domains/maget.themisterfridayproject.com/public_html/vendor/webklex/php-imap/src/Client.php on line 39

**Comment by Webklex** [comment]
Hi @boakyezitek ,
there are many possibilities such as:
- Perhaps the generated token is bound to a specific IP?
- The server config could be different
- The server could be blocked / blacklisted
- The server uses a different library version

Best regards & happy coding,
