### ISSUE TITLE
how do I see my all send mail by laravel project to show in my outlook Sent Items with attachments using IMAP?

### ISSUE THREAD

**Issue by abhishekP-bacany** [Webklex/laravel-imap#435]
On my laravel project, I am using the default sending mail method but now I show all sending mail on Microsoft 365 Sent Items.

**Comment by jil1092000** [comment]
$rootMailBox = "{".$ic->host.":".$ic->port."/".$ic->protocol."/".$ic->encryption."/novalidate-cert}";
            if($ic->host=='imap.gmail.com'){
                $draftsMailBox = $rootMailBox . '[Gmail]/Sent Mail';
            }else{
                $draftsMailBox = $rootMailBox . 'Sent';
            }

            $conn = imap_open ($rootMailBox, $ic->username, $ic->password) or die("can't connect: " . imap_last_error());

            $envelope["to"]  = $data['mail_to'];
            $envelope["from"]  = $data['mail_from'];
            $envelope["bcc"]  = isset($data['bcc'])?$data['bcc']:'';
            $envelope["cc"]  = isset($data['cc'])?$data['cc']:'';
            $envelope["subject"]  = $data['subject'];
            $envelope["date"]  = date('d.m.Y H:i:s');
            $envelope["message_id"] = 'sent'.strtotime(date('d.m.Y.H:i:s')).$envelope["to"];

            $part1["type"] = TYPEMULTIPART;
            $part1["subtype"] = "mixed";
            
            if ($request->hasfile('attachment')) {

                $file = $request->file('attachment');
                $extension = $file->getClientOriginalExtension();
                $originalname = $file->getClientOriginalName();
//                $path = $file->move(public_path('uploads/emails/'), $originalname);
                $filesizes = $path->getSize();
                $mimetype = $file->getClientMimeType();
                $fileopen = fopen($path, "r");
                $filedata =  @fread($fileopen,$filesizes);
//                dd($filedata);
                @fclose($fp); 
                $filedata = chunk_split(base64_encode($filedata));
//                dd($originalname);
                $part2["type"] = TYPEOTHER;//TYPEIMAGE,TYPEOTHER
                if($extension=='jpeg' || $extension=='jpg' || $extension=='png'){
                    $part2["type"]=TYPEIMAGE;
                }else{
                    $part2["type"]=TYPEAPPLICATION;
                }
                $part2["charset"] = $mimetype;
                $part2["subtype"] = $extension;
                $part2["encoding"] = ENCBASE64;
                $part2["contents.data"] = $filedata;
                $part2["disposition"]=$file;
                $part2["disposition.type"]='attachment';
                $part2['type.parameters'] = array('name' => $originalname);
                $part2['disposition'] = array ('filename' => $originalname);
                $part2["encoding"] = ENCBASE64;
            }
$body[1] = $part1;
            if($request->hasfile('attachment') || (isset($data['oldattachment']) && $data['oldattachment']!='') ){
                $body[2] = $part2;
            }
            $body[3] = $part3;

            $msg = imap_mail_compose($envelope, $body);

            if (imap_append($conn, $draftsMailBox, $msg) === false) {
                die( "could not append message: " . imap_last_error() )  ;
            }

**Comment by jil1092000** [comment]
try this after mail send
