### ISSUE TITLE
is there any way to move mail from one account to another account using Message::move() function ?

### ISSUE THREAD

**Issue by jil1092000** [Webklex/laravel-imap#436]
Please be aware that these issues will be closed if inactive for more then 14 days :)

**Comment by jil1092000** [comment]
@Webklex need help !!

**Comment by Webklex** [comment]
Hi @jil1092000 ,
thanks for your question. It is possible, but not so trivial. You could use `Folder::appendMessage()` to "create" a new mail inside the mailbox of the other account.

Here is the method:
https://github.com/Webklex/php-imap/blob/master/src/Folder.php#L279

Best regards & happy coding,
