### ISSUE TITLE
  Use of undefined constant FT_UID - assumed 'FT_UID'

### ISSUE THREAD

**Issue by RhRU** [Webklex/laravel-imap#44]
This occures when trying to publish the service provider:
Changed the imap.php config file to 
'options' => [
        'fetch' => "FT_UID",
        'open' => [
            // 'DISABLE_AUTHENTICATOR' => 'GSSAPI'
        ]
    ]

**Comment by Webklex** [comment]
Hi @RhRU ,
please take a look at #14 and #30 .
