### ISSUE TITLE
performance of version 4.0.0

### ISSUE THREAD

**Issue by vigstudio** [Webklex/laravel-imap#443]
**Describe the bug**
I'm using 2.4.0 which is fine until I get to 4.0.0. The amount of CPU consumed a lot every time I connect to my project, it is always in 100% state
I am using it to download imap emails from 60 emails at the same time

**To Reproduce**
try to compare the connection of CPU consumption between the 2 versions

**Expected behavior**
I hope to improve performance again

**Screenshots**
![image](https://user-images.githubusercontent.com/34742453/186310512-aaf883a4-88cc-4c5a-9c48-82f6a5fd12c0.png)

**Desktop / Server (please complete the following information):**
 - OS: CentOS
- PHP: 8.1
 - Version 4.0.0

**Additional context**
the old methods to getForm() getTo() getCc() don't seem to work anymore

**Comment by Webklex** [comment]
Hi @vigstudio ,
many thanks for the report. Are you sure that it is code from this repository? This repository is just a wrapper for [Webklex/php-imap](https://github.com/Webklex/php-imap). If it is indeed [Webklex/php-imap](https://github.com/Webklex/php-imap), please head over there and create a new issue: https://github.com/Webklex/php-imap/issues/new?assignees=&labels=&template=bug_report.md

Please also keep in mind that the issue has to be reproducible. How can I replicate the result? Which methods / functions are you using? Which method is slowing you down?

`Message::getForm()`,  `Message::getTo()` and `Message::getCc()`are still accessible, do exist and will return the related message header value. What do you mean by "don't seem to work anymore"?

The attached screenshot doesn't seem to fit your description. It doesn't show 100% cpu consumption - it rather looks like max. 24.1% and 47.2% MySQL? [Webklex/php-imap](https://github.com/Webklex/php-imap) doesn't use MySQL which indicates something else is taking up all your cpu time.

Best regards & happy coding,

**Comment by vigstudio** [comment]
![image](https://user-images.githubusercontent.com/34742453/186553871-24de23da-eb2b-402e-bf1f-e45d1bd79e1f.png)
here is my email download job using horizon
