### ISSUE TITLE
Invalid return type in ImapProtocol::search()

### ISSUE THREAD

**Issue by ken717w** [Webklex/laravel-imap#444]
**Describe the bug**
In the class `Webklex\PHPIMAP\Connection\Protocols\ImapProtocol`, the return type of `search()` has been specified to `array`. However, `$response` is being returned if it has a falsy value, while the type of `$response` could be either `array`, `bool` or `null` according to `requestAndResponse()`.

**Screenshots**
![image](https://user-images.githubusercontent.com/6499363/186339449-b3e53475-b77d-47c6-8c57-50d346732a13.png)

**Desktop / Server (please complete the following information):**
- PHP: 7.4.30
- webklex/laravel-imap: 4.0.0

**Comment by Webklex** [comment]
Hi @ken717w ,
many thanks for your report. Unfortunately this is the wrong repository. Please head over to https://github.com/Webklex/php-imap/issues/new?assignees=&labels=&template=bug_report.md

Many thanks & happy coding,
