### ISSUE TITLE
Empty body when using gmail

### ISSUE THREAD

**Issue by alphaolomi** [Webklex/laravel-imap#445]
**Describe the bug**
Empty body when fetching emails

**To Reproduce**
1. Install package on fresh laravel 9
2. Integrate Gmail or other service
3. Use Client facade to fetch emails
4. When displaying the body is empty 

**Expected behavior**
Email body should be present in the body

**Screenshots**
Problem is reproducible without screenshots

**Desktop / Server (please complete the following information):**
 - OS: Macos Monterey 
- PHP: 8.1
- Package Version: ^4.0

**Additional context**
Connection is okay
It fetches folders ok
It fetches emails ok
It failed to load messages body
On the mail servers for this case Gmail it registers emails as read since the it assumes the body is read

**Comment by alphaolomi** [comment]
Great package and kudos to the author(s).

**Comment by alphaolomi** [comment]
How to reproduce 
Ref: https://github.com/Webklex/laravel-imap/issues/431#issuecomment-1236884534

1. Create new project `laravel new imap-demo && cd imap-demo`

2. install the package `composer require webklex/laravel-imap`
Now the `require` of the `composer.json` is 

```json
 "require": {
        "php": "^8.0.2",
        "ddeboer/imap": "^1.14",
        "guzzlehttp/guzzle": "^7.2",
        "laravel/framework": "^9.19",
        "laravel/sanctum": "^3.0",
        "laravel/tinker": "^2.7",
        "php-imap/php-imap": "^5.0",
        "webklex/laravel-imap": "^4.0"
 },
```

3. add the ENV variables
For my case am using Gmail with App password
```

IMAP_HOST="imap.gmail.com"
IMAP_PORT=993
IMAP_ENCRYPTION=ssl
IMAP_VALIDATE_CERT=true
IMAP_USERNAME="XXXXX@gmail.com"
IMAP_PASSWORD="XXXXXX"
IMAP_DEFAULT_ACCOUNT="default"
IMAP_PROTOCOL=imap
```

4. I added a custom Artisan command `php artisan make:command ImapTestCommand`

```
<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Webklex\IMAP\Facades\Client;

class ImapTestCommand extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'imap:test';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Command description';

    /**
     * Execute the console command.
     *
     * @return int
     */
    public function handle()
    {
        $client = Client::account("default");
        $client->connect();

        //Get all Mailboxes
        /** @var \Webklex\PHPIMAP\Support\FolderCollection $folders */
        $folders = $client->getFolders(false);

        //Loop through every Mailbox
        /** @var \Webklex\PHPIMAP\Folder $folder */
        foreach($folders as $folder){
            $this->info("Accessing folder: ".$folder->path);

            $messages = $folder->messages()->all()->limit(3, 0)->get();

            $this->info("Number of messages: ".$messages->count());
            /** @var \Webklex\PHPIMAP\Message $message */
            foreach ($messages as $message) {
                $this->info("\tMessage: ".$message->message_id);
				$this->info("\tBody: ".$message->getHTMLBody());
            }
        }

        return 0;
    }
}
```

**Comment by alphaolomi** [comment]
Sorry guys, It works now

**Comment by vikrantisk** [comment]
Hi @alphaolomi , Can you please tell me how did you resolved this issue?

**Comment by alphaolomi** [comment]
Hello @vikrantisk, I recreated the project from scratch, used a fresh Mailbox for testing with minimal number of email, and my conclusion is issue https://github.com/Webklex/laravel-imap/issues/431 still exists in some cases
