### ISSUE TITLE
Base64 attachments in side content mail 

### ISSUE THREAD

**Issue by matran2210** [Webklex/laravel-imap#448]
I use $message->getHTMLBody() and receive all ( html_body + base64 of the attachment) (illustration)
I use $message->getAttachments() and didn't get anything
![ccc](https://user-images.githubusercontent.com/64309499/189622130-f9d1ed28-193c-4a36-928e-4545f2c2e0ec.png)

I don't know what email structure this is. 
I need to separate html body and attachment
Someone help me please!

**Comment by matran2210** [comment]
@Webklex  can you help me ?

**Comment by Webklex** [comment]
Hi @matran2210 ,
unfortunately this is the wrong repository. Please had over to https://github.com/Webklex/php-imap

If you believe this is a bug, please use this issue template https://github.com/Webklex/php-imap/issues/new?assignees=&labels=&template=bug_report.md and provide as much information as possible. Preferably so the issue can be reproduced.

Best regards & happy coding,
