### ISSUE TITLE
Exception Parse Data

### ISSUE THREAD

**Issue by GuiAndra** [Webklex/laravel-imap#45]
Hello, I'm getting this exception

![error-email-imap](https://user-images.githubusercontent.com/15656816/33278376-88180a66-d382-11e7-96c4-5208e60fb665.png)

I added a try in the parse header function in the message class to pass the error.

private function parseHeader() {
    $header = imap_fetchheader($this->client->connection, $this->uid, $this->fetch_options);
    if ($header) {
        $header = imap_rfc822_parse_headers($header);
    }

    if (property_exists($header, 'subject')) {
        $this->subject = imap_utf8($header->subject);
    }
    if (property_exists($header, 'date')) {
        try{
            $this->date = Carbon::parse($header->date);
        }catch (\Exception $e){
        }
    }
    if (property_exists($header, 'from')) {
        $this->from = $this->parseAddresses($header->from);
    }
    if (property_exists($header, 'to')) {
        $this->to = $this->parseAddresses($header->to);
    }
    if (property_exists($header, 'cc')) {
        $this->cc = $this->parseAddresses($header->cc);
    }
    if (property_exists($header, 'bcc')) {
        $this->bcc = $this->parseAddresses($header->bcc);
    }

    if (property_exists($header, 'reply_to')) {
        $this->reply_to = $this->parseAddresses($header->reply_to);
    }
    if (property_exists($header, 'sender')) {
        $this->sender = $this->parseAddresses($header->sender);
    }

    if (property_exists($header, 'message_id')) {
        $this->message_id = str_replace(['<', '>'], '', $header->message_id);
    }
    if (property_exists($header, 'Msgno')) {
        $this->message_no = ($this->fetch_options == FT_UID) ? trim($header->Msgno) : imap_msgno($this->client->getConnection(), trim($header->Msgno));
    }
}

**Comment by GuiAndra** [comment]
I added a try in the parse header function in the message class.
private function parseHeader() {
        $header = imap_fetchheader($this->client->connection, $this->uid, $this->fetch_options);
        if ($header) {
            $header = imap_rfc822_parse_headers($header);
        }

        if (property_exists($header, 'subject')) {
            $this->subject = imap_utf8($header->subject);
        }
        if (property_exists($header, 'date')) {
            try{
                $this->date = Carbon::parse($header->date);
            }catch (\Exception $e){
            }
        }
        if (property_exists($header, 'from')) {
            $this->from = $this->parseAddresses($header->from);
        }
        if (property_exists($header, 'to')) {
            $this->to = $this->parseAddresses($header->to);
        }
        if (property_exists($header, 'cc')) {
            $this->cc = $this->parseAddresses($header->cc);
        }
        if (property_exists($header, 'bcc')) {
            $this->bcc = $this->parseAddresses($header->bcc);
        }

        if (property_exists($header, 'reply_to')) {
            $this->reply_to = $this->parseAddresses($header->reply_to);
        }
        if (property_exists($header, 'sender')) {
            $this->sender = $this->parseAddresses($header->sender);
        }

        if (property_exists($header, 'message_id')) {
            $this->message_id = str_replace(['<', '>'], '', $header->message_id);
        }
        if (property_exists($header, 'Msgno')) {
            $this->message_no = ($this->fetch_options == FT_UID) ? trim($header->Msgno) : imap_msgno($this->client->getConnection(), trim($header->Msgno));
        }
    }

**Comment by Webklex** [comment]
Hi @GuiAndra ,
thanks for the report. I think I would rather like to validate the given datestring and perhaps "fix it" if it seems to be broken. This way anyone can be sure to always have a valid Carbon object.

Please give me a few days or perhaps the upcomming weekend to comeup with a fix :)

Best regards

**Comment by Webklex** [comment]
Hi @GuiAndra,
 please update to v [1.0.3.9](https://github.com/Webklex/laravel-imap/releases/tag/1.0.3.9) :)

**Comment by GuiAndra** [comment]
Thaanks @Webklex :)

**Comment by RpCoding** [comment]
04 Jan 2018 10:12:47 UT

**Comment by Webklex** [comment]
@RpCoding thanks for your report :) I just released a new version containing the new validation rule.

Ref.: [v. 1.0.5.5](https://github.com/Webklex/laravel-imap/releases/tag/1.0.5.5)

**Comment by brandxtc** [comment]
Got a new invalid timestamp. :) 
Failed to parse time string (22 Jun 18 03:56:36 PM
    -05:00 (GMT -05:00)) at position 35 (-): Double timezone specification

**Comment by tortato** [comment]
I got a new invalid timestamp:
Thu, 8 Nov 2018 08:54:58 -0200 (-02)

**Comment by Webklex** [comment]
@tortato wow you've found a new way to write a date^^ Thanks for the report and a solution. This will be part of the next release :)

Best regards

**Comment by VijayTahkur** [comment]
@Webklex 
I got a new error 
DateTime::__construct(): Failed to parse time string (Sat, 31 Aug 2013 20:08:23 +0580) at position 30 (0): Unexpected character

![image](https://user-images.githubusercontent.com/44797871/50677675-1d1e4900-1021-11e9-96cb-5c28303c3977.png)

**Comment by archond** [comment]
Fri,  1 Feb 2019 01:30:04 +0600 (+06)

**Comment by anibalealvarezs** [comment]
'DateTime::__construct(): Failed to parse time string (Mon,  4 Feb 2019 04:03:49 -0300 (-03)) at position 32 ((): Unexpected character

**Comment by Webklex** [comment]
Hi @tortato @VijayTahkur @archond @anibalealvarezs ,
please update to [v. 1.3.0](https://github.com/Webklex/laravel-imap/releases/tag/1.3.0) :)

**Comment by dmitryplus** [comment]
Hi @Webklex 
I caught an exception 'Invalid message date' for the date
Sun, 6 Apr 2008 21:24:33 UT

v 1.4.1

**Comment by Eldar89** [comment]
I got a new error
Warning: DateTime::modify(): Failed to parse time string (Wed, 11 Sep 2019 15:23:06 +0600 (+06)) at position 32 ((): Unexpected character

v.1.4.2

**Comment by bsralph** [comment]
@Webklex 
I got the following error, could you assist?

`DateTime::__construct(): Failed to parse time string (14 Sep 2019 00:10:08 UT +0200) at position 21 (U): The timezone could not be found in the database`

**Comment by danielkleach** [comment]
@Webklex 

Getting the following error:
`Failed to parse time string (Tue, 08 Nov 2022 18:47:20 +0000 14:03:33 +0000) at position 32 (1): Double time specification`

We are on version 1.6.2. Is this particular date error handled in later versions?

**Comment by rxmgrudy** [comment]
For anyone that comes across this in the future, you can switch over to php-imap with very minor changes to your code and you can pass in a fallback_date to deal with errors related to parsing time strings.

[https://github.com/Webklex/php-imap/blob/master/src/Header.php#L736
](url)

`$clientManager = new ClientManager(['options' => ['fallback_date' => Carbon::now()]]);`
