### ISSUE TITLE
when run thi

### ISSUE THREAD

**Issue by satyajitckt** [Webklex/laravel-imap#456]
Please be aware that these issues will be closed if inactive for more then 14 days :)
Webklex\PHPIMAP\Client::authenticate
D:\taillog-backend\New folder\taillog-backend\vendor\webklex\php-imap\src\Client.php:391

    /**

     * Authenticate the current session

     *

     * @throws ConnectionFailedException

     */

    protected function authenticate() {

        try {

            if ($this->authentication == "oauth") {

                if (!$this->connection->authenticate($this->username, $this->password)) {

                    throw new AuthFailedException();

                }

            } elseif (!$this->connection->login($this->username, $this->password)) {

                throw new AuthFailedException();

            }

        } catch (AuthFailedException $e) {

            throw new ConnectionFailedException("connection setup failed", 0, $e);

        }

    }

**Comment by Webklex** [comment]
Hi @satyajitckt ,
I'm not sure what you are asking or reporting.

If the issue / question you are asking is related to [webklex/php-imap](https://github.com/Webklex/php-imap) please head over there. This repository is just a wrapper for `webklex/php-imap`.

Best regards & happy coding,
