### ISSUE TITLE
How to get raw subject ?

### ISSUE THREAD

**Issue by abcprintf** [Webklex/laravel-imap#458]
Hello, I need get raw subject but I can't find how to get raw subject.

ทดสอบ นำส่งจดหมายผ ????????????????????????????????

![2022-11-18_12-13-07](https://user-images.githubusercontent.com/8300694/202625049-160b7287-5120-4d5d-9e6f-6a7e721261d1.png)

expected :
ทดสอบ นำส่งจดหมายผ่านระบบอีเมล

but if i can retrieve get raw header subject It will work.

simple :

![2022-11-18_12-20-49](https://user-images.githubusercontent.com/8300694/202626646-a563b967-3b18-4710-ab6b-cc737d45d2cf.png)

I'am try:
```sh
$subject_raw = "=?UTF-8?B?4LiX4LiU4Liq4Lit4LiaIOC4meC4s+C4quC5iOC4h+C4iOC4lOC4q+C4oeC4suC4ouC4nA==?=
                =?UTF-8?B?4LmI4Liy4LiZ4Lij4Liw4Lia4Lia4Lit4Li14LmA4Lih4Lil?=";
echo mb_decode_mimeheader($subject_raw);

// output : ทดสอบ นำส่งจดหมายผ่านระบบอีเมล  <-- is work
```

Version:
Laravel 8, php 7.4

**Comment by robis199** [comment]
$message->getSubject()[0];
