### ISSUE TITLE
Is the php extension mcrypt still a requirement?

### ISSUE THREAD

**Issue by larsbo** [Webklex/laravel-imap#459]
It looks as if the requirement for the `mcrypt` extension results from this issue: https://github.com/Webklex/laravel-imap/issues/129. But as mentioned there, this extension was a requirement of [laravel/framework 5.0](https://github.com/laravel/framework/blob/5.0/composer.json#L20) (and not laravel-imap itself) and was removed in [Laravel 5.1](https://github.com/laravel/framework/blob/5.1/composer.json).

Maybe it should be removed from the installation requirement section? The extension seems also a bit [outdated](https://www.php.net/manual/en/migration71.deprecated.php).

**Comment by ricardovanderspoel** [comment]
I am also facing problems with mcrypt in php 8>

**Comment by amitleuva1987** [comment]
@larsbo and @ricardovanderspoel , did you guys get any solution to make it work without `mcrypt` extension?

I tried installing mcrypt in php 8.1 which is not working.

**Comment by larsbo** [comment]
@amitleuva1987 try
`composer […] --ignore-platform-reqs`
as the mcrypt extension is not really necessary.

**Comment by amitleuva1987** [comment]
Thanks @larsbo , It's working

**Comment by Webklex** [comment]
Hi @larsbo ,
many thanks for asking and providing an answer as well. I've just updated the readme and removed the `mcrypt` reference.

Best regards

**Comment by Razoxane** [comment]
Could you please also update the documentation site pages to reflect this dropped requirement?
