### ISSUE TITLE
Getting imap_mail_move() expects parameter 1 to be resource, object given 

### ISSUE THREAD

**Issue by Dhavalptel** [Webklex/laravel-imap#463]
**Describe the bug**
Getting imap_mail_move() expects parameter 1 to be resource, object given 

**To Reproduce**
```
 $client = $cm->make([
                'host' => 'outlook.office365.com',
                'port' => 993,
                'encryption' => 'ssl',
                'validate_cert' => true,
                'username' => IMAP_USERNAME,
                'password' => ACCESS_TOKEN,
                'protocol' => 'imap',
                'authentication' => "oauth",
            ]);

imap_mail_move($client->getConnection(), $range, $processedfolder, 1)
```
@Webklex I'm using this `$client->getConnection()` which returns object, Do we need any other parameter at position 1?

Let me know 
Thanks!

**Comment by inkarnation** [comment]
seems `imap_mail_move` expects an `IMAP\Connection` as first parameter see [https://www.php.net/manual/de/function.imap-mail-move.php](https://www.php.net/manual/de/function.imap-mail-move.php). Alternatively you could use the build in move function: `$cm->moveMessage(...);` see [https://github.com/Webklex/php-imap/blob/master/src/Connection/Protocols/ImapProtocol.php#L976](https://github.com/Webklex/php-imap/blob/master/src/Connection/Protocols/ImapProtocol.php#L976)

**Comment by Dhavalptel** [comment]
@inkarnation Yes, I followed the same and was able to fix it.
