### ISSUE TITLE
markAsRead doesn't work in linux manjaro and php 7.3

### ISSUE THREAD

**Issue by madsalehi** [Webklex/laravel-imap#471]
markAsRead doesn't work properly and it has not any errors.

```php
$query = $inbox->messages()->unseen();
$query->markAsRead();
```

**Desktop / Server :**
 - OS: Manjaro Linux
- PHP: 7.3
- Laravel: 8.83
 - Version 4.1

**Comment by Webklex** [comment]
Hi @madsalehi ,
many thanks for your report. Please update to the latest release and try again - please note that v5 requires php 8.

If the issue persists even after updating, please enable the debug mode inside your config and head over to: https://github.com/Webklex/php-imap/issues/new?assignees=&labels=&template=bug_report.md

Please try to provide as much information as possible.

Best regards & happy coding,
