### ISSUE TITLE
Can't move email from folder

### ISSUE THREAD

**Issue by Gustavo-queirozman** [Webklex/laravel-imap#478]
How to fix following error?
![image](https://github.com/Webklex/laravel-imap/assets/73914910/26777ed9-c4b5-410a-a828-5042b6b19e9d)
Code:
![image](https://github.com/Webklex/laravel-imap/assets/73914910/b55177ef-7037-425c-b847-c2932856f442)

**Comment by Webklex** [comment]
Hi @Gustavo-queirozman ,
please enable the debug mode inside your config and make sure you are using the latest release.

You can enable the debug mode inside your `config/imap.php` file: https://github.com/Webklex/laravel-imap/blob/master/src/config/imap.php#L152

The debug mode will print the entire server communication (outgoing and incoming). This might provide some insight :)

Best regards & happy coding,

**Comment by Gustavo-queirozman** [comment]
This method not exists: 
![image](https://github.com/Webklex/laravel-imap/assets/73914910/0bac33c0-4f83-495a-89b0-11f92a2bed23)
![image](https://github.com/Webklex/laravel-imap/assets/73914910/d15be1cf-3f93-4158-9052-56abf552e56c)

**Comment by Mysterri1** [comment]
Hello @Gustavo-queirozman, [according to the documentation](https://www.php-imap.com/api/message) the method to move a message is "move" :
