### ISSUE TITLE
How can I  specify a single folder? 

### ISSUE THREAD

**Issue by Amos1st** [Webklex/laravel-imap#48]
Hello,
  I can get all folders through `$client->getFolders()` , but if I would like to specify a single one, example `INBOX`, how can I do for it? like this: foreach the mailboxes and then judge the condition `if ($mailbox->name === 'INBOX')` ? pls give me some advise! 

look forward your reply, thanks in advance

**Comment by GuiAndra** [comment]
Hello, I did it that way, maybe it would help you.

        $oClient->connect();

        $folder = new Folder($oClient, (object)['name' => '{vps.minhacartacontemplada.com.br/imap/novalidate-cert/ssl}INBOX', 'attributes' => 32, 'delimiter' => '.']);

        $messages = $oClient->getMessages($folder, 'SINCE '.Carbon::parse(date('Y-m-d'))->subDays(5)->format('Y-m-d'));

**Comment by Webklex** [comment]
Hi @Amos1st ,
I don't think its currently possible but I would like to implement a feature which would allow such a behavior.

Inspired by @GuiAndra it might look like something similar to this:
```
$oClient->connect();
$oFolder = \Webklex\Facade\Folder::get('INBOX.sample');
$aMessage = $oClient->getMessages($folder, ....);
```

Best regards

**Comment by Webklex** [comment]
Hi @Amos1st ,
please update to v. [1.0.3.11](https://github.com/Webklex/laravel-imap/releases/tag/1.0.3.11) and take a look at the new [README.md](https://github.com/Webklex/laravel-imap/blob/master/README.md). I added a new Funktion to the Client class in order to get a folder instance by name.

Short description:
``` php
use Webklex\IMAP\Facades\Client;

/** @var \Webklex\IMAP\Client $oClient */
$oClient = Client::account('default');
$oClient->connect();

/** @var \Webklex\IMAP\Folder $oFolder */
$oFolder = $oClient->getFolder('INBOX.name');

/** @var \Webklex\IMAP\Message $oMessage */
foreach($oFolder->getMessages() as $oMessage){
    echo $oMessage->subject.'<br />';
}
```

Best regards
