### ISSUE TITLE
FT_PEEK not working

### ISSUE THREAD

**Issue by goweri** [Webklex/laravel-imap#49]
Hi,
Thanks for the Package. But when i try to get messages using getMessages() function using ft_peek, because i don't want my messages to be set as read. but i get error while using this. 
Code:
$message=$oClient->getMessages($this->aMailboxes[0],'ALL',FT_PEEK);

(1/1) GetMessagesFailedExceptionimap_fetchheader(): invalid value for the options parameter
--
in Client.php (line 320)
at Client->getMessages(object(Folder), 'ALL', 2)

**Comment by goweri** [comment]
Hello,
  After some research, i found that for imap_fetchheader and imap_fetchstructre does not accept value 2(FT_PEEK).they both accepts 1(FT_UID). But  imap_fetchbody uses 2(FT_PEEK) for not marking it as read while listing them. Any work around? i urgently need it for my project. please help as soon as possible

**Comment by deio89** [comment]
after selected your account, set your client to readonly.
     
$oClient = Client::account('default');
**$oClient->setReadOnly();**
$oClient->connect();

**Comment by goweri** [comment]
hi @deio89, thanks for the code. if i open my client as readonly, then i'm not able to setflag to any of my messges.

**Comment by Webklex** [comment]
Please update to the latest version [v.1.0.4.0](https://github.com/Webklex/laravel-imap/releases/tag/1.0.4.0) and take quick look at the changelog :)
