### ISSUE TITLE
[Help] Saving Attachments

### ISSUE THREAD

**Issue by narwy** [Webklex/laravel-imap#51]
Hi,
Not sure how people have done this basically I want my script to use each attachment and save them and send them to s3 how have people managed to save their attachments and save them in this way?

Any examples would be appreciated, thank you.

```php
$outlook->connect();
$folder = $outlook->getFolder('Inbox');
foreach($folder->getMessages() as $message){
	$subject = $message->subject;
	$attachments = $message->getAttachments();
	dd($attachments);
	foreach($attachments as $attachment){
		$file = header('Content-type: '.$attachment->content_type.'');
		$file .= header('Content-disposition: attachment; filename='.$attachment->name.'');
		print $attachment->content;
		// send it to s3 Storage::disk('s3')->put
	}
	$message->moveToFolder('Success');
}
```

**Comment by kevinp1005** [comment]
@narwy I'm working on this too, found some article on how to use it with imap_fetchstructure() function, but haven't really implement this with laravel-imap. 
[Check this out](
https://www.electrictoolbox.com/extract-attachments-email-php-imap/)

**Comment by Webklex** [comment]
Hi @narwy @kevinp1005 ,
I save attachments using the followoing:

 ```php
/** @var $oClient \Webklex\IMAP\Client */
$oClient = \Client::connect();
$aMailboxes = $oClient->getFolders();

/** @var \Webklex\IMAP\Folder $oMailbox */
foreach($aMailboxes as $oMailbox){

    /** @var \Webklex\IMAP\Message $oMessage */
    foreach($oMailbox->getMessages() as $oMessage) {

        $oMessage->getAttachments()->each(function ($oAttachment) use ($oMessage) {
            file_put_contents(storage_path('attachments/' . $oMessage->getMessageId() . '/' . $oAttachment->name), $oAttachment->content);
        });
    }
}
```
..if this doesn't work please provide some addiotional information so we can find a solution :)

**Comment by narwy** [comment]
Hi @Webklex,

Thanks for that snippet. I will look at it a bit more this weekend :) 👍

**Comment by Webklex** [comment]
@narwy @kevinp1005 I added it to the [usage documentation](https://github.com/Webklex/laravel-imap#usage) :)

Best regards
