### ISSUE TITLE
How know message is flagged

### ISSUE THREAD

**Issue by Drillyus** [Webklex/laravel-imap#53]
HI,

 Actually, we can't find how check if message is flagged.
 How can i do that?

Thanks

**Comment by Webklex** [comment]
Hi @Drillyus ,
it is currently not supported but I'm working on a whole bunch of new methods and working with flags is part of it.

Please wait till sunday or monday (depending on your timezone) :)

Best regards

**Comment by Drillyus** [comment]
HI ,

 OK it's a good news.
 Thanks a lot for this library , it's very useful.

Best regards

**Comment by Webklex** [comment]
Please update to the latest version [v.1.0.4.0](https://github.com/Webklex/laravel-imap/releases/tag/1.0.4.0).

By doing `$oMessage->getHeaderInfo()` you can see which flags are set.

Please use `$oMessage->setFlag(['Seen', 'Spam']) or $oMessage->unsetFlag('Spam')` for setting and unsetting flags.
