### ISSUE TITLE
Message automaticly set to "read"

### ISSUE THREAD

**Issue by Drillyus** [Webklex/laravel-imap#54]
Hi,

Actually i do that 

`public function index()
	{
		$oUnseenMsgs = $this->oClient->getUnseenMessages($this->oClient->getFolder('INBOX'));
		return view('dashboard', compact('oUnseenMsgs'));
	}`

And if i jst refreh my app, my emails status change to "read" automaticly, why?

P.S: i  use OVH smtp

**Comment by Webklex** [comment]
Hi @Drillyus ,
please take a look at the [imap.php](https://github.com/Webklex/laravel-imap/blob/master/src/config/imap.php).

> Fetch option:
         FT_UID  - Message marked as read by fetching the message
         FT_PEEK - Fetch the message without setting the "read" flag

I think changing the fetch option to FT_PEEK will do the trick for you :)

Best regards

**Comment by Drillyus** [comment]
oh, indeed.
 Thanks a lot.

Best Regards

**Comment by atikrahman-ew** [comment]
Changing FT_PEEK Gives imap_fetchheader(): invalid value for the options parameter

**Comment by atikrahman-ew** [comment]
@Webklex  can you help plz ???

**Comment by Webklex** [comment]
Hi @atikrahman-ew ,
please provide some more information such as code samples, complete error messages, call stacks or screenshots if necessary and tell us a bit more on what you've already tryed yourself.

I'm sure we (the community and I) can help you :)

Best regards

**Comment by atikrahman-ew** [comment]
I just changed ft_uid to ft_peek and when i add that error gives.when getting messages.
I also tried sending (all,ft_peek)
.i needed to fetch inbox without setting it as read.
