### ISSUE TITLE
$folder->appendMessage stop request

### ISSUE THREAD

**Issue by Drillyus** [Webklex/laravel-imap#55]
HI,

 I have this : 

```php
$messageStruct = $this->build_mime_msg($recipient,$subject,$content,"global@fallen.fr");
$this->oClientRead->getFolder('INBOX.INBOX.Sent')->appendMessage($messageStruct);
return redirect()->route('webmail.inbox')->with(['email-success' => 'L\'email a bien été envoyé.']);`
```
![screenshot_20180209_115555](https://user-images.githubusercontent.com/1550178/36024517-45313c20-0d90-11e8-875b-4991ac81f2f0.png)

The mail is correctly save on sent folder but my Post request return anything. I don't understand why.

**Comment by Drillyus** [comment]
OK , you need to replace : 
`   public function appendMessage($message, $options = null, $internal_date = null){
        return imap_append($this->client->connection, $this->path, $message, $options, $internal_date);
    }`

by

`   public function appendMessage($message, $options = null, $internal_date = null){
        return @imap_append($this->client->connection, $this->path, $message, $options, $internal_date);
    }`

**Comment by Webklex** [comment]
Hi @Drillyus ,
there should be an error logged somewhere. Please try to locate the actual error message. The "@" would just suppress the error, so it's not realy a fix more like a "cover up".
