### ISSUE TITLE
timeout issue after 60 sec

### ISSUE THREAD

**Issue by tirumodak** [Webklex/laravel-imap#58]
My code is below

// Replace with your Test Function
            $oClient = new Client();
            //Connect to the IMAP Server
            $oClient->connect();

            //Get all Mailboxes
            $aMailboxes = $oClient->getFolders(false,'INBOX');

            //Loop through every Mailbox
            /** @var \Webklex\IMAP\Folder $oMailbox */
            
            foreach($aMailboxes as $oMailbox){
                //Get all Messages of the current Mailbox
                /** @var \Webklex\IMAP\Message $oMessage */
                $count = 0;
                foreach($oMailbox->getMessages() as $oMessage){
                    
                    echo $oMessage->subject.'<br />';
                    echo 'Attachments: '.$oMessage->getAttachments()->count().'<br />';
                    echo $oMessage->getHTMLBody(true);

                   
                if($count==1)
                {
                    break;
                }
                $count++;  
                    
                }
                
            }

I am getting an exception : 

(1/1) FatalErrorExceptionMaximum execution time of 60 seconds exceeded
--
in Message.php (line 452)

I want to fetch only 1st email and show.

how can I do ?

**Comment by Drillyus** [comment]
HI,
 Your imap.config and your .env are correctly configure?

**Comment by Webklex** [comment]
Hi @tirumodak ,
have you checked which part exactly causes the delay? Also please verify your system load and check if your internet connection is actually working properly. Perhaps you ran into someones traffic limit? If you are using multiple accounts over the same IP and send to many requests to google - they might slow you down as well.

I personally use this library with an old mail account which holds round about 250k mails in several folders. I never had any problems with the actual script speed.

If you can't figure it out please provide any additional laravel error messages so anyone else (including me) can see what has actually happened and might be able to give you further assistance.

**Comment by Iftequar14** [comment]
I have also encountered to the same exception
this my imap.php
<?php
/*
* File:     imap.php
* Category: config
* Author:   M. Goldenbaum
* Created:  24.09.16 22:36
* Updated:  -
*
* Description:
*  -
*/

return [

    /*
    |--------------------------------------------------------------------------
    | IMAP Host Address
    |--------------------------------------------------------------------------
    |
    | By default this the imap handler will use this given account.
    |
    */
    'default' => env('IMAP_DEFAULT_ACCOUNT', 'default'),

    /*
    |--------------------------------------------------------------------------
    | Available IMAP accounts
    |--------------------------------------------------------------------------
    |
    | Please list all IMAP accounts which you are planning to use within the
    | array below.
    |
    */
    'accounts' => [

        'default' => [
            'host'  => env('IMAP_HOST', 'imap.gmail.com'),
            'port'  => env('IMAP_PORT', 993),
            'encryption'    => env('IMAP_ENCRYPTION', 'ssl'), // Supported: false, 'ssl', 'tls'
            'validate_cert' => env('IMAP_VALIDATE_CERT', true),
            'username' => env('IMAP_USERNAME', 'my email id'),
            'password' => env('IMAP_PASSWORD', 'my password'),
        ],

        /*
        'gmail' => [
            'host' => 'imap.gmail.com',
            'port' => 993,
            'encryption' => 'ssl', // Supported: false, 'ssl', 'tls'
            'validate_cert' => true,
            'username' => 'example@gmail.com',
            'password' => 'PASSWORD',
        ],

        'another' => [
            'host' => '',
            'port' => 993,
            'encryption' => false, // Supported: false, 'ssl', 'tls'
            'validate_cert' => true,
            'username' => '',
            'password' => '',
        ]
        */
    ],

    /*
    |--------------------------------------------------------------------------
    | Available IMAP options
    |--------------------------------------------------------------------------
    |
    | Available php imap config parameters are listed below
    |   -Delimiter (optional):
    |       This option is only used wehen calling $oClient->
    |       You can use any supported char such as ".", "/", (...)
    |   -Fetch option:
    |       FT_UID  - Message marked as read by fetching the message
    |       FT_PEEK - Fetch the message without setting the "read" flag
    |   -Open IMAP options:
    |       DISABLE_AUTHENTICATOR - Disable authentication properties.
    |                               Use 'GSSAPI' if you encounter the following
    |                               error: "Kerberos error: No credentials cache
    |                               file found (try running kinit) (...)"
    |                               or ['GSSAPI','PLAIN'] if you are using outlook mail
    |
    */
    'options' => [
        'delimiter' => '/',
        'fetch' => FT_UID,
        'open' => [
            // 'DISABLE_AUTHENTICATOR' => 'GSSAPI'
        ]
    ]
];

this is my mail.blade.php


<?php
use Webklex\IMAP\Client;
$oClient = new Client([
    'host'          => 'imap.gmail.com',
    'port'          => 993,
    'encryption'    => 'ssl',
    'validate_cert' => true,
    'username'      => 'my email id',
    'password'      => 'my password',
]);

//Connect to the IMAP Server
$oClient->connect();

//Get all Mailboxes
$aMailboxes = $oClient->getFolders();

//Loop through every Mailbox
/** @var \Webklex\IMAP\Folder $oMailbox */
foreach($aMailboxes as $oMailbox){

    //Get all Messages of the current Mailbox
    /** @var \Webklex\IMAP\Message $oMessage */
    foreach($oMailbox->getMessages() as $oMessage){
        echo $oMessage->subject.'<br />';
        echo 'Attachments: '.$oMessage->getAttachments()->count().'<br />';
        echo $oMessage->getHTMLBody(true);
        
        //Move the current Message to 'INBOX.read'
        if($oMessage->moveToFolder('INBOX.read') == true){
            echo 'Message has ben moved';
        }else{
            echo 'Message could not be moved';
        }
    }
}
?>

**Comment by Webklex** [comment]
Hi @tirumodak @Drillyus @Iftequar14 ,
I just released a new version [v 1.0.5.0](https://github.com/Webklex/laravel-imap/releases/tag/1.0.5.0) which can now pull only the mail headers. 
This might help you if you still encounter heavy loads.

Set the third option `$parse_body` of the `Folder::getMessages()` `Folder::getUnseenMessages()` or the `Folder::searchMessages()` method to `false` in order to prevent the body to be fetched and parsed.

If you updated and set `$parse_body` to false and still have the same problems please reopen this issue.

Best regrds,
Malte
