### ISSUE TITLE
how to open folder INBOX

### ISSUE THREAD

**Issue by hsleewis** [Webklex/laravel-imap#6]
I don't really understand the openFolder part of the documentation.
How do I open a folder with the name INBOX?

**Comment by Webklex** [comment]
Hi hsleewis,
the openFolder method is a reimplementation of the native imap_reopen php function. Please take a look at the official documentation for more information: http://php.net/manual/en/function.imap-reopen.php.

If you want to open a Mailbox such as "INBOX" just use something similar to this:

       /** @var  $oClient \Webklex\IMAP\Facades\Client */
        $oClient = \Client::account('default');
        /** @var $oClient \Webklex\IMAP\Client */
        $oClient->connect();

        /** @var \Webklex\IMAP\Folder $oFolder */
        $oFolder = new Folder($oClient, (object)['name' => '{mx1.server.com:993/imap/novalidate-cert/ssl}INBOX', 'attributes' => 32, 'delimiter' => '.']);
        foreach($oFolder->getMessages() as $oMessage){
            echo $oMessage->subject.'<br />';
            echo $oMessage->getHTMLBody(true);
        }
