### ISSUE TITLE
if an email has attachment , then return Malformed email .

### ISSUE THREAD

**Issue by maverickchangithub** [Webklex/laravel-imap#63]
tested , i am using gmail .

if i add an attachment , then laravel returns 500 server error , with message "Malformed email".

plain email is ok . 

why does this happen ? if anyone encounter the same issue?

**Comment by Webklex** [comment]
Hi @maverickchangithub ,
please provide some addiotional information such as code samples, call stacks or error logs.

**Comment by maverickchangithub** [comment]
@Webklex thanks for your reply. 
I am using the sample code to connect to gmail, nothing special.
I sent 2 emails to my gmail with attachments from hotmail and gmail itself. Then server return 500 error after very long pending. The error message is said that I have malformed email in my inbox.
I am guess you have a very strict rule of reading an email with standard email format. I am not familiar with email format , if you can give me some help.

My dev environment is Mac OS HighSierra apache php 7.2.

**Comment by Webklex** [comment]
Well take a look at either the Laravel log (storage/logs/laravel.log) or the apache log. There has to be a more detailed error message and the correlating call stack :)

**Comment by maverickchangithub** [comment]
i know that ..... anyway , here is my error message of laravel.log

> [2018-03-14 18:59:23] local.ERROR: Malformed UTF-8 characters, possibly incorrectly encoded {"userId":1,"exception":"[object] (InvalidArgumentException(code: 0): Malformed UTF-8 characters, possibly incorrectly encoded at /Library/WebServer/Documents/newapp/vendor/laravel/framework/src/Illuminate/Http/JsonResponse.php:75)

And there is no error log in apache.

I guess it's a parse problem .  Still digging . Thanks for your reply . I really need this .

---

after 5 minutes test , Now i have a theory : getMessages() method will pack attachment with the message body together , if in php , it is ok to parse , but since i using a ajax call , laravel will transform the message to json format , which , cannot hold a very big file ....
