### ISSUE TITLE
Unable to save Email attachments (Outlook .msg files)

### ISSUE THREAD

**Issue by salih0vicX** [Webklex/laravel-imap#64]
Hi,

I use this package to successfully deal with many tens of email on daily basis. So far I was able to extract almost all attachments: pdf files, excel files etc. However, I was never able to extract email attachment (Outlook .msg file) from the message. Almost all users of the app I am building are using Microsoft Outlook desktop application to send their emails and they often attach another email (previously stored) to the message (usually .msg extension).

Any idea how to save such attachment (.msg file) to drive? Thanks.

**Comment by salih0vicX** [comment]
[This](https://github.com/Webklex/laravel-imap/pull/47/commits/fa4c31b0df3ad3b1139b025a3aaff3e831816f4f) is helpful... I was saving attachment's content to a ".msg" file instead of ".eml" so Outlook kept throwing "Invalid file" or similar error message...

**Comment by Webklex** [comment]
Hi @salih0vicX ,
I just merge #47 and created a new release :)
