### ISSUE TITLE
imap_fetch_overview needed

### ISSUE THREAD

**Issue by maverickchangithub** [Webklex/laravel-imap#65]
Actually this is not a issue , more like an request .

Retrieve all the messages in a folder could be slow , is it possible to add a fetch overview method to get all the subjects , date , from , to ,etc ? This could speed up the reading.

also , once click on the message , we need to access the specific mail , how to do it ?

if the emails are like a database model , we could do everything laravel provided , but since it is not .....

THANKS , anyone has good thoughts , please share !

**Comment by salih0vicX** [comment]
@maverickchangithub I wanted to ask for this for a long time but being busy ... Thanks @Webklex, I am super anxious cannot wait for a new release. :)

**Comment by Webklex** [comment]
Hi @maverickchangithub @salih0vicX ,
the new version is now available: [v. 1.0.5.0](https://github.com/Webklex/laravel-imap/releases/tag/1.0.5.0).

Please let me know if you encounter any problems :)

Best regards
Malte
