### ISSUE TITLE
Undefined Variable 

### ISSUE THREAD

**Issue by fernastereo** [Webklex/laravel-imap#68]
Hi, I followed the instructions from readme file, step by step, and I get the following error: **Undefined variable: oMailbox**

I'm using Laravel 5,6

![captura](https://user-images.githubusercontent.com/17733505/37781380-97bfc51c-2dbe-11e8-948f-de23f234cd0c.PNG)

Here's my code:

`public function inbox(){

	    $oClient = new Client([
		    'host'          => 'imap.gmail.com',
		    'port'          => 993,
		    'encryption'    => 'ssl',
		    'validate_cert' => true,
		    'username'      => 'some_email@gmail.com',
		    'password'      => 'mypassword',
		]);

		//Connect to the IMAP Server
		$oClient->connect();

		//Get all Mailboxes
		/** @var \Webklex\IMAP\Support\FolderCollection $aFolder */
		$aFolder = $oClient->getFolders();

		//Loop through every Mailbox
		/** @var \Webklex\IMAP\Folder $oFolder */
		foreach($aFolder as $oFolder){

		    //Get all Messages of the current Mailbox
		    /** @var \Webklex\IMAP\Support\MessageCollection $oMessage */
		    $aMessage = $oMailbox->getMessages();
		    
		    /** @var \Webklex\IMAP\Message $oMessage */
		    foreach($aMessage as $oMessage){
		        echo $oMessage->subject.'<br />';
		        echo 'Attachments: '.$oMessage->getAttachments()->count().'<br />';
		        //echo $oMessage->getHTMLBody(true);
		        
		        //Move the current Message to 'INBOX.read'
		        if($oMessage->moveToFolder('INBOX.read') == true){
		            echo 'Message has ben moved';
		        }else{
		            echo 'Message could not be moved';
		        }
		    }
		}
    }
`

**Comment by Webklex** [comment]
Hi @fernastereo ,
sry my bad. Take another look at the updated Version - I just fixed it. Thanks for telling me :)

Best regards

**Comment by fernastereo** [comment]
Thanks for your help. I updated the code but now I get a timeout error.

![captura](https://user-images.githubusercontent.com/17733505/37803123-2eeecb72-2dfb-11e8-875d-368e02ba053a.PNG)

**Comment by Webklex** [comment]
If your Mailbox is to big or your connection to slow you could either specify your mail fetching query by uing the search method and / or limit your messages to pull only the message headers (set third parameter to `false` [default: `true`]).

```php
/** @var \Webklex\IMAP\Folder $oFolder */

/** @var \Webklex\IMAP\Support\MessageCollection $aMessage */
$aMessage = $oFolder->searchMessages([['TEXT', 'Hello world']], null, false);

/** @var \Webklex\IMAP\Support\MessageCollection $aMessage */
$aMessage = $oFolder->getMessages('ALL', null, false);
```
