### ISSUE TITLE
Cannot fetch Attachment if Attachment does not have file extension

### ISSUE THREAD

**Issue by elysiumtiles** [Webklex/laravel-imap#69]
Hello Webklex,
$oMessage->getAttachments()->count() returns 0 if attachment file has no extension
$oMessage->getAttachments() does not fetch attachment if file does not have a file extension

example:
Attachment file = myTest.txt, this works you can fetch attachemnt
Attachment file = myTest, does not work cannot fetch attachment, no file extension

Attachment file = myPdf.pdf, this works you can fetch attachment
Attachment file = myPdf, does not work cannot fetch attachment, no file extension

Is there a way to detect MIME type and guess at the extension?

Thanks

**Comment by Webklex** [comment]
Hi @elysiumtiles ,
well thats some interesting behavior. They should actually be treated as type `other`..

I think guessing the mime type sounds like a good plan, but that's a different story.

I'll try to take a closer look in the next couple days. If you can't wait that long, feel free do dive in yourself:)

Best regards

**Comment by Webklex** [comment]
Hi @elysiumtiles,
please update to the latest version. Lots of things have changed since march. 

Please reopen this issue if you still encounter the same problem. I just tested it with two files (txt/png) without an extension and had no problem what so ever :)

Best regards
