### ISSUE TITLE
How to get attachments file ?

### ISSUE THREAD

**Issue by mharjo** [Webklex/laravel-imap#7]
how i can get attachment file from mail?

**Comment by Webklex** [comment]
Hi Mhajo,
thanks for the question. There has ben a bug within the fetchStructure() method. How ever I just solved it and published a new version. Just use the new one and you are good to go.

By the way the method for receiving attached files is called: getAttachments() and is implemented inside the Message class. You  might want to take aanother look at the readme.md, I updated the example as well :)

**Comment by mharjo** [comment]
i already update the latest.
But method getAttachments and getHTMLBody or getTextBody
return empty array.

i notice you forgot remove  var_dump($structure); in line 350 Message.php

**Comment by Webklex** [comment]
Hi Mharjo,
yes I noticed this a few minutes later.. 

Are you sure you are on version: 1.0.2.5.1?

If you are on version 1.0.2.5.1 and if you still cant get the attachment please provide me with some more detail, such as data type, size and so on.

**Comment by mharjo** [comment]
yes. i use  1.0.2.5.1.
and use basic example in your documentation.
method getHTMLBody(true) and getAttachments() still return empty value.

i dump variable $oMessage
[http://prntscr.com/exthl6](http://prntscr.com/exthl6)

**Comment by mharjo** [comment]
i change :
$partNumber == null to $partNumber != null
$parameter->attribute == "FILENAME"
$parameter->attribute == "NAME"

in Message.php

now method getHTMLBody(true) and getAttachments() can return data.

**Comment by Webklex** [comment]
Hi mharjo,
thanks for the hint. Please take a look at the new version: https://github.com/Webklex/laravel-imap/releases/tag/1.0.2.7

Your Problem should be solved.
