### ISSUE TITLE
searchMessages in Folder is skipping messages due to put instead of push

### ISSUE THREAD

**Issue by mlands** [Webklex/laravel-imap#70]
When running this code:
```php
/** @var \Webklex\IMAP\Support\MessageCollection $aMessage */
$aMessage = $oFolder->getMessages('ALL', null, false);
```

SearchMessages in Folder Class is skipping messages that do not report back a correct id on `$message->getMessageId()` when fetching from a mailbox.  The put is replacing the same message in a messageCollection.  When this happens you will get one item in a collection even though there may be 300 messages in a mailbox.

I was able to resolve this so messages are not skipped by changing Folder.php#L287:
`$messages->put($message->getMessageId(), $message);` 
To:
 `$messages->push($message);`

https://github.com/Webklex/laravel-imap/blob/master/src/IMAP/Folder.php#L287

**Comment by Webklex** [comment]
Hi @mlands ,
I'm not sure if `push` would actually fix the problem since you have to fight an invalid `msgId` afterwards.

Do you have access to the mail server logs?

Best regards

**Comment by mlands** [comment]
Thanks for great project!
I don't have access to the mail server logs as I have only tested laravel-imap with popular free email providers.

**Comment by Webklex** [comment]
Hi @mlands ,
please update to the newest version and have a look at the new available config parameters. You can now choose between different message keys.

Best regrads
