### ISSUE TITLE
FT_PEEK config change gives error

### ISSUE THREAD

**Issue by atikrahman-ew** [Webklex/laravel-imap#71]
```php
   'options' => [
        'delimiter' => '/',
        'fetch' => FT_PEEK,
        'open' => [
            // 'DISABLE_AUTHENTICATOR' => 'GSSAPI'
        ]
    ]
```
As you suggest in the issue section I have to change this to peek from uid.

That gives error.
```php
  foreach($data['aMailboxes']->getMessages() as $oMessage){
                dd($oMessage->getHeaderInfo());
}
```
Error:
        
![save](https://user-images.githubusercontent.com/29091506/37872149-55eeadd0-3023-11e8-8b17-d688a8d72d78.PNG)

NB:Also tried `getMessages('ALL',FT_PEEK)`  .. Any solution guyz. Need help @Webklex

**Comment by atikrahman-ew** [comment]
Hey @Webklex  MY version is 1.0.4.1 i have checked you have changed many things from there .But cant install the later version ..BEcause it says

Problem 1
    - The requested package webklex/laravel-imap (locked at 1.0.4.1, required as 1.0.4.2) is satisfiable by webklex/laravel-imap[1.0.4.1] but these conflict with your requirements or minimum-stability.

Php 7,Laravel 5.4 .Can you tell the limitations here ?

**Comment by atikrahman-ew** [comment]
I am very much stucked here .I cant seems to change the flag that are automatically set to read.Also FT_PEEK Is giving error. @Webklex  :)

**Comment by Webklex** [comment]
Hi @atikrahman-ew ,
please don't write in caps lock and don't get me wrong but this is an open source project which means noone is getting paid. Things can take a while, testing and debugging yourself hoever is a good start.
You could try to narrow it further down to speed up things :)

However if you need commercial support, feel free to drop me a Mail ;)

Best regards
