### ISSUE TITLE
Clear error stack before imap_close

### ISSUE THREAD

**Issue by RpCoding** [Webklex/laravel-imap#72]
Since I experienced the same error with your package as described for other imap packages like this: 
https://github.com/natanfelles/codeigniter-imap/issues/5

Please consider replacing the follow code in https://github.com/Webklex/laravel-imap/blob/master/src/IMAP/Client.php

```
public function disconnect() {
    if ($this->isConnected()) {
        $this->connected = ! imap_close($this->connection, CL_EXPUNGE);
    }

    return $this;
}
```

with

```
public function disconnect() {
    if ($this->isConnected()) {
        $errs = imap_errors();
        $this->connected = ! imap_close($this->connection, CL_EXPUNGE);
    }

    return $this;
}
```

this fixed the error for me. Also see https://stackoverflow.com/questions/3378469/how-to-get-rid-of-error-messages-with-phps-imap-fetchstructure for more information.

**Comment by Webklex** [comment]
Hi @RpCoding ,
thanks for your suggestion. I just released an update containing your fix :)

Ref.: [v. 1.0.5.4](https://github.com/Webklex/laravel-imap/releases/tag/1.0.5.4)

**Comment by RpCoding** [comment]
Very nice, thanks!
