### ISSUE TITLE
imap_fetchstructure(): Bad message number

### ISSUE THREAD

**Issue by Wu4m4n** [Webklex/laravel-imap#73]
Hi,
First of all, thanks for this plugins!

When I am trying to fetch the body of a message I get this error.

`imap_fetchstructure(): Bad message number`

Code related.
` $html = $msg->parseBody()->bodies['html']->content;`

Also I try to use this function "getRawBody", but I get the same result.

I am trying to get emails from Gmail.

Regards.
Nelson.

**Comment by Wu4m4n** [comment]
I found this.
When I use this option  . getMessages('ALL', null, false); I get the error.
But if I use this.
getMessages('ALL');
Works like a charm ! 

The bad side is take too long to fetch all the emails.

**Comment by Webklex** [comment]
Hi @Wu4m4n ,
try using a limited request to reduce the amount you have to fetch:
```php
$messages = $oFolder->searchMessages([['SINCE', Carbon::now()->subMonths(1)->format('d M y')]]);
```
or
```php
$messages = $oFolder->searchMessages([['UNSEEN']]);
```

Hope that helps :)
