### ISSUE TITLE
Labels in Gmail

### ISSUE THREAD

**Issue by Wu4m4n** [Webklex/laravel-imap#74]
Hi,

When I trying to move email betweens labels, this function "moveToFolder " works really great. But for some reason still maintain the last label associated with the email.

For example I labeled an email with  "PROCESSING" and then I use moveToFolder to move the email to "DONE", in result the email have two label. "PROCESSING" and "DONE.

How I can avoid this? 

PS: also I use unsetFlag but I didn't see any change.
Thanks.

**Comment by Wu4m4n** [comment]
sorry, it was because the mails were shown nested. my bad.

**Comment by Webklex** [comment]
Hi @Wu4m4n ,
I'm glad to read it's not an actual existing bug. I just started to guess what could lead to such a "feature".

Thanks for updating and closing the issue :)
