### ISSUE TITLE
getMessage is not returning the body of the message

### ISSUE THREAD

**Issue by stefansidorovski** [Webklex/laravel-imap#75]
Hello Webklex,

First of all thanks for this plugin. It offers a lot of functionalities, and it is really helpful. We integrated your plugin within our project, and when using the getMessage function we encounter some difficulties. Please take in note the following:

$oMessage = $oFolder->getMessage(220);

The above code will get a message with UID 220(This is fine). The problem is that the getMessage function will not return the body of the message.

In Folder.php on line 158 instead of return new Message($uid, $msglist, $this->getClient()); we could call the function in the following way: return new Message($uid, $msglist, $this->getClient(), **true**);  In this way the function will also parse and return the body of the message.

**Comment by Webklex** [comment]
Hi @stefansidorovski ,
thanks for your kind words, its always nice to read :)

I just released a fix, resolving this issue. Thanks for pointing it out and reporting it as well.

Please change:
`$oMessage = $oFolder->getMessage(220); `
into
`$oMessage = $oFolder->getMessage(220, null, null, true);`

Ref.: [v. 1.0.5.6](https://github.com/Webklex/laravel-imap/releases/tag/1.0.5.6)

**Comment by stefansidorovski** [comment]
Hi Webklex,

Thanks for your quick response :).

Regards,
Stefan
