### ISSUE TITLE
Error In Fetch Attachments

### ISSUE THREAD

**Issue by mohamedothman91** [Webklex/laravel-imap#79]
version : "1.0.5.5"
Error 

> imap_fetchstructure(): No body information available {"exception":"[object] (Webklex\\IMAP\\Exceptions\\GetMessagesFailedException(code: 0): imap_fetchstructure(): No body information available at /var/www/testing/connex-cm/vendor/webklex/laravel-imap/src/IMAP/Folder.php:296

my fetching code
```php
$oMessage->getAttachments()->each(function ($oAttachment, $k) use ($oMessage) {

            $dir = storage_path('app/public/emails');
            if (!is_dir($dir)) {
                File::makeDirectory($dir, 0777, true);
            }
            $filename = date('Y_m_d_h_i_sa').'_'.str_replace(' ', '', $oAttachment->name);
            $filepath = 'public/emails/'.$filename;
            $pullfile = Storage::put($filepath, $oAttachment->content, 'public');
});
```

**Comment by Webklex** [comment]
Hi @mohamedothman91 ,
please do me a favor and try to open the attachment manually. If you can't open it, it might be corrupted, which means there isnt realy a way of fetching it.

If the attachment does open, please provide some more detail about the attachment itself - what has to be done to replicate this error?

Best regards
