### ISSUE TITLE
Create an option to avoid that the fetched messages marked as read 

### ISSUE THREAD

**Issue by alfonsobries** [Webklex/laravel-imap#8]
In the function "fetchStructure" in Message.php (line 308), especifically when you use the imap_fetchbody you have the fourth argument (options) with the value "FT_UID", that's the default option and works fine but mark the fetched messages as read, that in some cases (like me) it's not what you want.

According to the documentation if you instead use the flag FT_PEEK the message wasn't marked as read.

I think that will be great if you make this option configurable, in my case i need that the messages doesn't mark as read.

´´´
//imap_fetchbody($this->client->connection, $this->uid, $partNumber, FT_UID);
imap_fetchbody($this->client->connection, $this->uid, $partNumber, FT_PEEK);
´´´

http://php.net/manual/es/function.imap-fetchbody.php

**Comment by Webklex** [comment]
Hi alfonsobries,
thanks for your suggestion and yes you are right but I think it would be better to use a config parameter. I will release a new version in a few days.

**Comment by Webklex** [comment]
Hi,
I just released a new version. You can now set the default by adding this to your config file:
```
 'options' => [
        'fetch' => FT_PEEK,
]
```
