### ISSUE TITLE
Request: add getReferences method to Message class

### ISSUE THREAD

**Issue by robtesch** [Webklex/laravel-imap#83]
Firstly thank you for the amazing package, it's added some great features in the past couple of months that are particularly useful for my use case. I would like to request an addition of a getReferences method to the Message class. I use the references as well as the inReplyTo for threading purposes. Currently everything I need is there except this, so I have to manually parse the headers again and get the references from there.

Many thanks in advance.

**Comment by Webklex** [comment]
Hi @robtesch ,
please update to [v. 1.0.5.9](https://github.com/Webklex/laravel-imap/releases/tag/1.0.5.9)

**Comment by robtesch** [comment]
This used to work after update v. 1.0.5.9, however for a while now i have been getting the following error:

```php
getReferences() not supported
```

I switched to simply getting the references (and all the other properties of a message) by simply accessing them directly as follows:

```php
$references = $message->references;
$messageId = $message->message_id;
//etc etc.
```
