### ISSUE TITLE
Error when searching messages using the FT_PEEK fetch option

### ISSUE THREAD

**Issue by stephanecoinon** [Webklex/laravel-imap#84]
https://github.com/Webklex/laravel-imap#configuration states that setting the configuration item `imap.options.fetch` to `FT_PEEK` fetches the messages without setting the "read" flag

however, in this environment:

PHP version: 7.2.2-3+ubuntu16.04.1+deb.sury.org+1
IMAP c-Client version: 2007f
Laravel version: 5.6.15

the following code:

``` php
$where = [
    ['SINCE', \Carbon\Carbon::parse('1 week ago')],
    ['FROM', 'john@example.com'],
];
Client::getFolder('INBOX')->searchMessages($where, FT_PEEK)->dd();
```

produces the following error:

```
Error in src/IMAP/Folder.php:302 
imap_fetchheader(): invalid value for the options parameter
```

because `imap_fetchheader()` expects options to be either `FT_UID`, `FT_INTERNAL` or `FT_PREFETCHTEXT` (and not `FT_PEEK`)
see http://php.net/manual/en/function.imap-fetchheader.php

`FT_PEEK` is used in options bitmask of `imap_fetchbody()`
see http://php.net/manual/en/function.imap-fetchbody.php

**Proposed solution**: set `Webklex\IMAP\Message::$fetch_options` as a bitmask and use `FT_UID` for `imap_fetchheader()`

I suggest `Webklex\IMAP\Message::$fetch_options` always has the FT_UID bit at 1 and replace `$fetch_options` by `$markAsRead` in `Folder::searchMessages()`: 

``` php
public function searchMessages(array $where, $markAsRead = true, $fetch_body = true, $charset = "UTF-8", $fetch_attachment = true)
```

where `$markAsRead` would toggle the `FT_PEEK` bit in the options bitmask passed to `imap_fetchbody()`

therefore, the configuration key `imap.options.fetch`

``` php
'options' => [
    // ...
    'fetch' => FT_UID,
    // ...
]
```

could be replaced by `imap.options.mark_as_read`

``` php
'options' => [
    // ...
    'mark_as_read' => true,
    // ...
]
```

which I find more friendly than having to understand the `FT_UID` and `FT_PEEK` constants

I'm happy to work on a PR if you're OK with the proposed solution

**Comment by Webklex** [comment]
Hi @stephanecoinon ,
thanks for your previous contributions! It's always a joy receiving pull requests :)

I like your idea and think it would be a reasonable change, but I always try to prevent major version changes.
Therefore at least for now I would like to keep the `fetch` option active and working and depricate it with v. 2.

If you can think of a way to combine both, I would very welcome a pull request :)

Best regards

**Comment by stephanecoinon** [comment]
@Webklex you're very welcome, thank you for open sourcing and maintaining this useful package :)

I understand your point of view, I'll try to submit a PR this week to fix the `FT_PEEK` bug while maintaining the current API

I have the idea to add an intuitive fluent API to build the message search a bit like the Eloquent query builder. 

We could use a closure:

``` php
$folder->search(function ($search) {
    $search->to('john@example.com')
        ->since(Carbon::parse('1 month ago'))
        ->leaveUnread();
});
```

or not:

``` php
$folder->search()
    ->to('john@example.com')
    ->since(Carbon::parse('1 month ago'))
    ->markAsRead()
    ->get();
```

and use methods like `leaveUnread()` and `markAsRead()` to toggle the `SEEN` flag

I have a [branch](https://github.com/stephanecoinon/laravel-imap/tree/search-query) (still in progress) but you can have a look at it. I'm also adding PHPUnit tests in the process.

**Comment by Webklex** [comment]
@stephanecoinon you rock! Yeah that's a great idea - I'm in :)
..and perhaps:
```php
$search->where ('TO', 'john@example')->where ('UNSEEN')->markAsRead ()->get ();
```
...to allow even more flexibility.

**Comment by Webklex** [comment]
Hi @stephanecoinon ,
I just released a new version containing some of our ideas - however it can be easily extended :)

If you are still working on it, please reopen this issue.

Best regards
