### ISSUE TITLE
'UNSEEN' search not working with Gmail

### ISSUE THREAD

**Issue by lauspadafora** [Webklex/laravel-imap#85]
I've been trying to make my app read emails in a Gmail account inbox but I can't get it to work. The `imap_search` function returns all emails in the inbox when the default value `ALL` is set, but it doesn't work when I pass `UNSEEN` or any other search criteria. It always returns 0. Possibly a Gmail configuration I'm missing?

**Comment by lauspadafora** [comment]
UPDATE! I tried using the `searchMessages()` method with the `UNSEEN` search criteria and a Gmail account and it worked! 

`$oMailbox->searchMessages([['UNSEEN']]);`

But I'm still wondering why `getMessages()` and `getUnseenMessages()` don't work with a Gmail account.

**Comment by Webklex** [comment]
Hi @lauspadafora ,
please update to the latest version and give it another try. I could not reproduce this behavior.

Please reopen this issue if it still occures :)

Best regards

**Comment by joshcalloway** [comment]
I'm having the same issue with office 365.
