### ISSUE TITLE
moveToFolder does not move the message in case we provide uid

### ISSUE THREAD

**Issue by tanjapetrovska5** [Webklex/laravel-imap#86]
Hi Webklex,
First of all, thanks for this plugin!

When using the moveToFolder($mailbox = 'INBOX') function by uid I encounter some problems (the message wasn't move). 
```php
$oMessage->msglist = $oMessage->uid;
$status = $oMessage->moveToFolder($this->helpdesk);
```
The problem is that the moveToFolder function in Message.php on line 558 does not provide option to specify if the msglist is a sequence number or uid.
If we replace following code: 
```php
imap_mail_move($this->client->getConnection(), $this->msglist, $mailbox);
```
with 
```php
imap_mail_move($this->client->getConnection(), $this->msglist, $mailbox, CP_UID);
```
the message will be moved.

Regards,
Tanja

**Comment by dembee111** [comment]
HI Can you solve this issue ? how to move to inbox and what inbox URL ?

**Comment by Webklex** [comment]
Hi @tanjapetrovska5,
thanks for your sugestion :)

Please update to [v. 1.0.5.9](https://github.com/Webklex/laravel-imap/releases/tag/1.0.5.9) to work with it.

**Comment by tanjapetrovska5** [comment]
Hi Webklex,

I updated to v. 1.0.5.9 and now there is another issue. The attachments are missing and I cannot test moveToFolder functionality.

Regards,
Tanja Miloshevska

**Comment by tanjapetrovska5** [comment]
Hi Weblex,

Everything works as expected. I was fetching the message by uid and with the new update there is option fetch attachments default to false. I haven't seen that, that is way I didn't get the messages.  

Thanks,
Tanja Miloshevska
