### ISSUE TITLE
Multiple connections

### ISSUE THREAD

**Issue by cloudstudio** [Webklex/laravel-imap#87]
Hello ! thanks in advance.

I want foreach all $users in database

But something is wrong, only connect to one account, i don't know if we need disconnect before, something like this ?

`               $oClient->disconnect();
`

Thanks in advance !
![captura de pantalla 2018-04-11 a las 11 51 45](https://user-images.githubusercontent.com/3589377/38609618-d76be036-3d7e-11e8-8e56-1398fa2e991c.png)

**Comment by dembee111** [comment]
hello,  how to show  $oMessage read more detail

**Comment by cloudstudio** [comment]
Sure, this is all function 👍 

![captura de pantalla 2018-04-11 a las 12 04 54](https://user-images.githubusercontent.com/3589377/38610203-6d944692-3d80-11e8-96bb-39e51253f687.png)

**Comment by dembee111** [comment]
Thank you very much

**Comment by cloudstudio** [comment]
You welcome :)

**Comment by cloudstudio** [comment]
Is working with : 

`
$oClient = new Client([
                        'host' => 'imap.gmail.com',
                        'port' => 993,
                        'encryption' => 'ssl', // Supported: false, 'ssl', 'tls'
                        'validate_cert' => true,
                        'username' => $user->imap_user,
                        'password' => $user->imap_password
                ]);
`

Maybe is a bug ?

**Comment by stephanecoinon** [comment]
@cloudstudio this is not a bug, the connection configurations are cached when you use the facade, see [src/IMAP/ClientManager.php:53](https://github.com/Webklex/laravel-imap/blob/master/src/IMAP/ClientManager.php#L53)

in other words, no matter how many times you call `Gmail::account('gmail')`, even when you update `config('imap.accounts.gmail.*')`, you will always get the first configuration.

The workaround to new up a Client instance on each iteration is the correct way to go
But you could save a couple lines of code like this maybe:

``` php
// Grab the config template for GMail from the IMAP config
$gmailConfig = config('imap.accounts.gmail');

foreach ($users as $user) {
    // Only set the username and password in the config
    $gmailConfig['username'] = $user->username;
    $gmailConfig['password'] = $user->password;
    // Spin up a new IMAP client with the user config
    $oClient = new Client($gmailConfig);
    // ...
}
```

**Comment by cloudstudio** [comment]
Thanks @stephanecoinon  is working now, so all right.

Thanks man !
