### ISSUE TITLE
$message->getRawBody() throws Exception

### ISSUE THREAD

**Issue by patricks8** [Webklex/laravel-imap#88]
Hello, 

When I try to get the raw body of a message with the function getRawBody, it throws an Exception. 
I get the following error: imap_fetchbody(): Bad message number.

**Comment by Webklex** [comment]
Hi @patricks8 ,
please provide more information such as code samples etc. A bad message number error can be caused by a lot of things :)

**Comment by patricks8** [comment]
Hi,

What I do is the following.
// Connect to the mailbox
$this->client = new Client([
    'host' => **************,
    'port' => *************,
    'encryption' => false,
    'validate_cert' => false,
    'username' => ***************,
    'password' => ***************
])
// Get the folder
$this->folder = $this->client->getFolder('INBOX');

// Get the messages from the folder
$messages = $folder->getMessages();

// Loop over every message and process it
foreach ($messages as $message) {
     $this->processMessage($message);
}

function processMessage(Message $message) 
{
      $rawBody =  $message->getRawBody();
     // I do some other actions here to process the message.
}

What I want to do is check the raw body on some contents. But when I try to get the raw body it fails. Cause I am looking for some specific content in the raw body that is not available in the html or text body. When I don't try to get to raw body, the message will be fully processed.

**Comment by Webklex** [comment]
Hi @patricks8 @IFR001 ,
please update to [v. 1.0.5.9](https://github.com/Webklex/laravel-imap/releases/tag/1.0.5.9)
