### ISSUE TITLE
General usage question

### ISSUE THREAD

**Issue by MarcosBL** [Webklex/laravel-imap#90]
Hi there, I'm trying to automatically save messages sent trought Laravel to the IMAP sent folder of the account, any idea on how that could be achieved with your library (if even possible)?

**Comment by stephanecoinon** [comment]
It can be done using [Mail Events](https://laravel.com/docs/5.6/mail#events)

First create a listener for the `Illuminate\Mail\Events\MessageSent` event:

``` bash
php artisan make:listener SaveSentMessage
```

Declare it in `App\Providers\EventServiceProvider`:

``` php
    protected $listen = [
        'Illuminate\Mail\Events\MessageSent' => [
            'App\Listeners\SaveSentMessage',
        ],
    ];
```

Then edit `SaveSentMessage::handle()` method so it looks like this:

```php
    public function handle($event)
    {
        $client = new \Webklex\IMAP\Client;
        $folder = $client->getFolder('INBOX.Sent');

        $client->checkConnection();

        imap_append(
            $client->getConnection(),
            $folder->path,
            $event->message->toString()
        );
    }
```

now, every mailable you send will be saved in the sent folder automatically, for example:

```php
    Mail::to('joe@example.com')->send(new OrderShipped);
```

PS: I didn't test with attachments, let me know if you need that

**Comment by MarcosBL** [comment]
@stephanecoinon great idea ! Huge THANK YOU !
