### ISSUE TITLE
Empty Body

### ISSUE THREAD

**Issue by cloudstudio** [Webklex/laravel-imap#95]
Helo ! i don't know why, but normally i get all body empty ( 0 ), paypal, slack, apple...

![empty](https://user-images.githubusercontent.com/3589377/39565217-723518e6-4eb7-11e8-9029-84b906a5d0ff.png)

I try all body functions getTextBody, getHTMLBody...

Maybe is something wrong ?  ( i remove some code just for show it )

![code](https://user-images.githubusercontent.com/3589377/39565330-d2f0e660-4eb7-11e8-97bf-e70164e71f10.png)

Thanks in advance !

**Comment by cloudstudio** [comment]
Thanks @Webklex i check it ! 

Can i send some PR ? for example in save() function inside attachments, you can define $filename, but extension is missing.

![extension](https://user-images.githubusercontent.com/3589377/39617589-8f86bb1a-4f80-11e8-8ec0-cb197b31a45f.png)

Maybe we can add a new function ? 

![captura de pantalla 2018-05-04 a las 10 29 18](https://user-images.githubusercontent.com/3589377/39618900-06f82ae4-4f86-11e8-88f5-a0297f6ba99b.png)

**Comment by Webklex** [comment]
Hi @cloudstudio ,
please feel free to send as many pull requests as you like :)

I just added two new methods for archiving what you are looking for and released a new version [1.1.1](https://github.com/Webklex/laravel-imap/releases/tag/1.1.1).

Best regards
