### ISSUE TITLE
Attachment name displayed incorrectly

### ISSUE THREAD

**Issue by tanjapetrovska5** [Webklex/laravel-imap#97]
Hi Webklex,

First of all, thanks for this plugin.
While using this plugin we noticed that for some of the attachments the attachment name isn't displayed correctly. Attached is the original email, in this scenario for the first attachment we got the correct name, but for the second attachment instead  'inkooporder FT Networks 6180108.pdf' we got "=?UTF-8?b?aW5rb29wb3JkZXIgRlQgTmV0d29ya3MgNjE4MDEwOC5wZGY=?="y.
![image](https://user-images.githubusercontent.com/38242325/39697061-ef29ff5c-51ef-11e8-9d6c-ea31d496d783.png)
Below is a screenshot from the output of the getAttachments method.
$messageAttachments = $message->getAttachments();

![image](https://user-images.githubusercontent.com/38242325/39697135-36970772-51f0-11e8-8d60-872f967d4f4c.png)

Attached is one of the pdfs in order to reproduce the issue. 
[inkooporder FT Networks 6180108.pdf](https://github.com/Webklex/laravel-imap/files/1979667/inkooporder.FT.Networks.6180108.pdf)

Regards,
Tanja

**Comment by tayfunkayahan** [comment]
Hi Tanja (@tanjapetrovska5),

I just looked into it and send my dummy email-address an email with the file attached and did the same as you did (`$message->getAttachments();`) and I get the correct PDF name.. (See screenshot)

![schermafbeelding 2018-05-19 om 01 46 20](https://user-images.githubusercontent.com/10990971/40262275-76baa344-5b06-11e8-82e5-47b3eda7489b.png)


Could it be that your e-mail server is protecting the name? (What e-mail server are you testing on BTW?) I've tested it on the IMAP implementation of Outlook. I would suggest you to test it on another e-mail server you've tested on.

Cheers!

**Comment by MarouaneZizah** [comment]
Same problem here, for example if I use attachment name : presentation.pdf it works well, but when I use : présentation.pdf it returns : ?UTF-8?Q?Pre=CC=81sentation=2Epdf?=
Seems like there is a problem with accented characters.

**Comment by MarouaneZizah** [comment]
This solved it for me : 
```
foreach ($message->getAttachments() as $attachment)
{
    $attachment_name         = $attachment->getName();
    $attachment_encodage     = mb_detect_encoding($attachment->getName());

    if( $attachment_encodage != 'UTF-8')
    {
        $attachment_name = iconv_mime_decode($attachment_name, 0, "UTF-8");
    }

    echo 'Attachment Name :' . $attachment_name;
}
```

**Comment by Webklex** [comment]
Hi @tanjapetrovska5 @MarouaneZizah I just pushed a new commit which contains a fix for your described problem. If you wan't you can checkout the master branch and test it right away :)

This change will be part of the upcoming release.

Ref. commit: [47f6d8f6404f24a257cdde10a4d442352f237669](https://github.com/Webklex/laravel-imap/commit/47f6d8f6404f24a257cdde10a4d442352f237669)

Best regards

**Comment by freescout-helpdesk** [comment]
Thanks. When will the next release be published?

**Comment by Webklex** [comment]
Hi @freescout-helpdesk ,
this weekend :)

Best regards
